### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  id: ShutdownMode
  children:
  - Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  - Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  langs:
  - csharp
  name: ShutdownMode
  nameWithType: ShutdownMode
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  type: Enum
  summary: "Angir betingelsen som skal føre til en Windows Forms-program å avslutte."
  remarks: "Du kan angi avsluttet-modus for et program ved hjelp av <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.ShutdownStyle%2A>egenskapen.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.ShutdownStyle%2A> Som standard den <xref:System.Windows.Forms.ApplicationContext.OnMainFormClosed%2A>metoden kontrollerer verdien for den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.ShutdownStyle%2A>til å fastslå om programmet må avsluttes.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.ShutdownStyle%2A> </xref:System.Windows.Forms.ApplicationContext.OnMainFormClosed%2A>"
  syntax:
    content: public enum ShutdownMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  id: AfterAllFormsClose
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  langs:
  - csharp
  name: AfterAllFormsClose
  nameWithType: ShutdownMode.AfterAllFormsClose
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Lukk etter siste skjemaet lukkes."
  syntax:
    content: AfterAllFormsClose
    return:
      type: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  id: AfterMainFormCloses
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  langs:
  - csharp
  name: AfterMainFormCloses
  nameWithType: ShutdownMode.AfterMainFormCloses
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Lukk når primære skjemaet lukkes."
  syntax:
    content: AfterMainFormCloses
    return:
      type: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  isExternal: false
  name: AfterAllFormsClose
  nameWithType: ShutdownMode.AfterAllFormsClose
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: ShutdownMode
  nameWithType: ShutdownMode
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  isExternal: false
  name: AfterMainFormCloses
  nameWithType: ShutdownMode.AfterMainFormCloses
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
