### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  id: StartupNextInstanceEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  langs:
  - csharp
  name: StartupNextInstanceEventArgs
  nameWithType: StartupNextInstanceEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  type: Class
  summary: "Gir dataene for den <xref uid=&quot;langword_csharp_My.Application.StartupNextInstance&quot; name=&quot;My.Application.StartupNextInstance&quot; href=&quot;&quot;> </xref> hendelsen."
  remarks: "Den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>hendelsen oppstår når et etterfølgende forekomst av en enkel forekomst programmet starter, ved hjelp av Visual Basic applikasjons-modellen.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Hvis du vil ha mer informasjon, se [oversikt over Visual Basic programmet modellen](~/add/includes/ajax-current-ext-md.md).       StartupNextInstanceEventArgs inneholder kommandolinjeargumenter for etterfølgende programmet-forekomsten, og angir om den første forekomsten av programmet skal hentes til forgrunnen ved avslutningen behandlingsprogrammet unntak."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public class StartupNextInstanceEventArgs : EventArgs
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs&quot;> </xref> klasse."
  remarks: "Den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>hendelsen oppstår når et etterfølgende forekomst av en enkel forekomst programmet starter, ved hjelp av Visual Basic applikasjons-modellen.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Hvis du vil ha mer informasjon, se [oversikt over Visual Basic programmet modellen](~/add/includes/ajax-current-ext-md.md).       <xref:Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs>inneholder kommandolinjeargumenter for etterfølgende programmet-forekomsten, og angir om den første forekomsten av programmet skal hentes til forgrunnen ved avslutningen behandlingsprogrammet unntak.</xref:Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs>"
  syntax:
    content: public StartupNextInstanceEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args, bool bringToForegroundFlag);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "En &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; objekt som inneholder kommandolinjeargumenter for etterfølgende application-forekomst."
    - id: bringToForegroundFlag
      type: System.Boolean
      description: "En <xref:System.Boolean>som angir om den første forekomsten av programmet skal hentes til forgrunnen ved avslutningen unntak behandlingsprogrammet.</xref:System.Boolean>"
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  id: BringToForeground
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Angir om den første forekomsten av programmet skal hentes til forgrunnen ved avslutningen behandlingsprogrammet unntak."
  remarks: "Visual Basic programmet modellen kontrollerer verdien for denne egenskapen når du har kjørt behandlingsprogrammer for den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>hendelsen.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Hvis egenskapen BringToForeground er `True`, den første forekomsten av programmet er koblet til forgrunnen. Hvis ikke, forblir den første forekomsten av programmet der det var. Hvis du vil ha mer informasjon, se [oversikt over Visual Basic programmet modellen](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public bool BringToForeground { get; set; }
    return:
      type: System.Boolean
      description: "En <xref:System.Boolean>som angir om den første forekomsten av programmet skal hentes til forgrunnen ved avslutningen unntak behandlingsprogrammet.</xref:System.Boolean>"
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Henter kommandolinjeargumenter for etterfølgende application-forekomst."
  remarks: "Den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>hendelsen oppstår når et etterfølgende forekomst av en enkel forekomst programmet starter, ved hjelp av Visual Basic applikasjons-modellen.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Hvis du vil ha mer informasjon, se [oversikt over Visual Basic programmet modellen](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "En &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; objekt som inneholder kommandolinjeargumenter for etterfølgende application-forekomst."
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: StartupNextInstanceEventArgs
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
