### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  id: BuiltInRole
  children:
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  langs:
  - csharp
  name: BuiltInRole
  nameWithType: BuiltInRole
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  type: Enum
  summary: "Angir hvilken type rollen du vil se når du kaller den <xref:Microsoft.VisualBasic.ApplicationServices.User.IsInRole*>metoden.</xref:Microsoft.VisualBasic.ApplicationServices.User.IsInRole*>"
  remarks: "Denne opplisting gir funksjonalitet som er lik den <xref:System.Security.Principal.WindowsBuiltInRole>opplisting.</xref:System.Security.Principal.WindowsBuiltInRole>       Disse rollene representerer de lokale Windows-gruppene som er felles for de fleste installasjoner av Windows."
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(Microsoft.VisualBasic.ApplicationServices.BuiltInRoleConverter))]

      public enum BuiltInRole
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  id: AccountOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: AccountOperator
  nameWithType: BuiltInRole.AccountOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Kontoen operatorer Administrer brukerkontoer på en datamaskin eller domene."
  syntax:
    content: AccountOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  id: Administrator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Administrator
  nameWithType: BuiltInRole.Administrator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Administratorer har full og ubegrenset tilgang til datamaskinen eller domenet."
  syntax:
    content: Administrator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  id: BackupOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: BackupOperator
  nameWithType: BuiltInRole.BackupOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Sikkerhetskopiering operatorer kan overstyre sikkerhetsbegrensninger for å sikkerhetskopiere eller gjenopprette filer."
  syntax:
    content: BackupOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  id: Guest
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Guest
  nameWithType: BuiltInRole.Guest
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Gjester begrenses mer enn brukere."
  syntax:
    content: Guest
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  id: PowerUser
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: PowerUser
  nameWithType: BuiltInRole.PowerUser
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Privilegerte brukere har de fleste administratortillatelser med noen begrensninger. Erfarne brukere kan derfor kjøre eldre programmer, i tillegg til godkjente programmer."
  syntax:
    content: PowerUser
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  id: PrintOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: PrintOperator
  nameWithType: BuiltInRole.PrintOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Skriv ut operatorer kan ta kontroll over en skriver."
  syntax:
    content: PrintOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  id: Replicator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Replicator
  nameWithType: BuiltInRole.Replicator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Replikatorer støtter filen replikering i et domene."
  syntax:
    content: Replicator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  id: SystemOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: SystemOperator
  nameWithType: BuiltInRole.SystemOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Systemet operatorer administrere en bestemt datamaskin."
  syntax:
    content: SystemOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  id: User
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: User
  nameWithType: BuiltInRole.User
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Brukere ikke endringer tilsiktet eller utilsiktet systemomfattende. På denne måten kan brukere kjøre godkjente programmer, men ikke mange eldre programmer."
  syntax:
    content: User
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: AccountOperator
  nameWithType: BuiltInRole.AccountOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: BuiltInRole
  nameWithType: BuiltInRole
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Administrator
  nameWithType: BuiltInRole.Administrator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: BackupOperator
  nameWithType: BuiltInRole.BackupOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Guest
  nameWithType: BuiltInRole.Guest
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: PowerUser
  nameWithType: BuiltInRole.PowerUser
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: PrintOperator
  nameWithType: BuiltInRole.PrintOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Replicator
  nameWithType: BuiltInRole.Replicator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: SystemOperator
  nameWithType: BuiltInRole.SystemOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: User
  nameWithType: BuiltInRole.User
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
