### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser
  id: WebUser
  children:
  - Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  - Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  langs:
  - csharp
  name: WebUser
  nameWithType: WebUser
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser
  type: Class
  summary: "Gir tilgang til informasjon om den gjeldende brukeren."
  remarks: "Egenskaper og metoder som vises av den `My.User` objektet gir tilgang til informasjon om den gjeldende brukeren. Betydning &quot;gjeldende bruker&quot; varierer litt mellom Windows- og webprogrammer. Gjeldende bruker er brukeren som kjører programmet i Windows-program. Gjeldende bruker er brukeren som har tilgang til programmet i et webprogram.       Den `My.User` egenskapen gir deg også tilgang til den <xref:System.Security.Principal.IPrincipal>for gjeldende bruker.</xref:System.Security.Principal.IPrincipal> En standardobjektet representerer brukerens sikkerhetskontekst, inkludert brukerens identitet og alle roller som brukeren tilhører.       Denne egenskapen gir for Windows-programmer, på samme måte som den <xref:System.Threading.Thread.CurrentPrincipal%2A>egenskapen.</xref:System.Threading.Thread.CurrentPrincipal%2A> Denne egenskapen gir for webprogrammer, på samme måte som den <xref:System.Web.HttpContext.User%2A>for objektet som returneres av den <xref:System.Web.HttpContext.Current%2A>egenskapen.</xref:System.Web.HttpContext.Current%2A> </xref:System.Web.HttpContext.User%2A>      > [!NOTE] > For Windows-programmer, bare prosjekter som er bygget på den **Windows-program** malen initialisere den `My.User` objekt som standard. I alle andre Windows prosjekttyper, må du starte den `My.User` objektet ved å kalle den <xref:Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser%2A>metoden eksplisitt eller ved å tilordne en verdi til <xref:System.Threading.Thread.CurrentPrincipal%2A>.</xref:System.Threading.Thread.CurrentPrincipal%2A> </xref:Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser%2A>      > [!NOTE] > Den `My.User` objektet kan ikke rapportere informasjon om gjeldende Windows-bruker når kjører under Windows 95 og Windows 98 disse operativsystemene støtter ikke var en pålogget bruker. Du må implementere egendefinerte godkjenning for å bruke den `My.User` objekt på disse operativsystemene.."
  example:
  - "This example checks if the application is using Windows or custom authentication, and uses that information to parse the `My.User.Name` property.  \n  \n [!code-vb[VbVbalrMyUser#3](~/add/codesnippet/visualbasic/VbVbalrMyUser/Class1.vb#3)]"
  syntax:
    content: 'public class WebUser : Microsoft.VisualBasic.ApplicationServices.User'
  inheritance:
  - System.Object
  - Microsoft.VisualBasic.ApplicationServices.User
  implements: []
  inheritedMembers:
  - Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal
  - Microsoft.VisualBasic.ApplicationServices.User.InitializeWithWindowsUser
  - Microsoft.VisualBasic.ApplicationServices.User.IsAuthenticated
  - Microsoft.VisualBasic.ApplicationServices.User.IsInRole(Microsoft.VisualBasic.ApplicationServices.BuiltInRole)
  - Microsoft.VisualBasic.ApplicationServices.User.IsInRole(System.String)
  - Microsoft.VisualBasic.ApplicationServices.User.Name
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  langs:
  - csharp
  name: WebUser()
  nameWithType: WebUser.WebUser()
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.WebUser()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.WebUser&quot;> </xref> klasse."
  remarks: "Egenskaper og metoder som vises av den `My.User` objektet gir tilgang til informasjon om den gjeldende brukeren."
  syntax:
    content: public WebUser ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  id: InternalPrincipal
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  langs:
  - csharp
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Henter eller angir standardobjektet som representerer gjeldende bruker."
  remarks: "I den <xref:Microsoft.VisualBasic.ApplicationServices.WebUser>objekt egenskapen bryter det <xref:System.Web.HttpContext.User%2A>for den <xref:System.Web.HttpContext.Current%2A?displayProperty=fullName>egenskapen.</xref:System.Web.HttpContext.Current%2A?displayProperty=fullName> </xref:System.Web.HttpContext.User%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WebUser>       For mer informasjon, kan du se den <xref:Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal%2A>egenskapen.</xref:Microsoft.VisualBasic.ApplicationServices.User.CurrentPrincipal%2A>"
  syntax:
    content: protected override System.Security.Principal.IPrincipal InternalPrincipal { get; set; }
    return:
      type: System.Security.Principal.IPrincipal
      description: "En <xref:System.Security.Principal.IPrincipal>-objekt som representerer gjeldende bruker.</xref:System.Security.Principal.IPrincipal>"
  overload: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal*
  exceptions: []
  platform:
  - net462
references:
- uid: Microsoft.VisualBasic.ApplicationServices.User
  isExternal: false
  name: Microsoft.VisualBasic.ApplicationServices.User
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: WebUser()
  nameWithType: WebUser.WebUser()
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.WebUser()
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
  fullName: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal
- uid: System.Security.Principal.IPrincipal
  parent: System.Security.Principal
  isExternal: true
  name: IPrincipal
  nameWithType: IPrincipal
  fullName: System.Security.Principal.IPrincipal
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: WebUser
  nameWithType: WebUser.WebUser
- uid: Microsoft.VisualBasic.ApplicationServices.WebUser.InternalPrincipal*
  parent: Microsoft.VisualBasic.ApplicationServices.WebUser
  isExternal: false
  name: InternalPrincipal
  nameWithType: WebUser.InternalPrincipal
