### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.FindAppConfigFile
  id: FindAppConfigFile
  children:
  - Microsoft.Build.Tasks.FindAppConfigFile.#ctor
  - Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile
  - Microsoft.Build.Tasks.FindAppConfigFile.Execute
  - Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList
  - Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList
  - Microsoft.Build.Tasks.FindAppConfigFile.TargetPath
  langs:
  - csharp
  name: FindAppConfigFile
  nameWithType: FindAppConfigFile
  fullName: Microsoft.Build.Tasks.FindAppConfigFile
  type: Class
  summary: "Søker etter filen app.config eventuell i de angitte listene."
  remarks: "FindAppConfigFile også legger til den <xref:Microsoft.Build.Tasks.FindAppConfigFile.TargetPath%2A>metadata.</xref:Microsoft.Build.Tasks.FindAppConfigFile.TargetPath%2A>"
  syntax:
    content: 'public class FindAppConfigFile : Microsoft.Build.Tasks.TaskExtension'
  inheritance:
  - System.Object
  - Microsoft.Build.Utilities.Task
  - Microsoft.Build.Tasks.TaskExtension
  implements: []
  inheritedMembers:
  - Microsoft.Build.Tasks.TaskExtension.Log
  - Microsoft.Build.Utilities.Task.BuildEngine
  - Microsoft.Build.Utilities.Task.BuildEngine2
  - Microsoft.Build.Utilities.Task.BuildEngine3
  - Microsoft.Build.Utilities.Task.BuildEngine4
  - Microsoft.Build.Utilities.Task.HelpKeywordPrefix
  - Microsoft.Build.Utilities.Task.HostObject
  - Microsoft.Build.Utilities.Task.TaskResources
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: FindAppConfigFile()
  nameWithType: FindAppConfigFile.FindAppConfigFile()
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.FindAppConfigFile()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;Microsoft.Build.Tasks.FindAppConfigFile&quot;> </xref> klasse."
  syntax:
    content: public FindAppConfigFile ();
    parameters: []
  overload: Microsoft.Build.Tasks.FindAppConfigFile.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile
  id: AppConfigFile
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: AppConfigFile
  nameWithType: FindAppConfigFile.AppConfigFile
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Henter eller angir det første, samsvarende elementet finnes i listen, hvis noen."
  syntax:
    content: public Microsoft.Build.Framework.ITaskItem AppConfigFile { get; set; }
    return:
      type: Microsoft.Build.Framework.ITaskItem
      description: "Det første, samsvarende elementet finnes i listen, eller <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> Hvis ingen samsvarende elementer er funnet."
  overload: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.Execute
  id: Execute
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: Execute()
  nameWithType: FindAppConfigFile.Execute()
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.Execute()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Finner app config-filen."
  remarks: "Kjøre det ser ut til først i hele elementet-oppsett. Det vil si først søker app.config filer direkte i prosjektmappen. Hvis dette mislykkes, deretter går den tilbake til app.config filer hvor som helst i prosjektet."
  syntax:
    content: public override bool Execute ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>i alle tilfeller."
  overload: Microsoft.Build.Tasks.FindAppConfigFile.Execute*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList
  id: PrimaryList
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: PrimaryList
  nameWithType: FindAppConfigFile.PrimaryList
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Henter eller angir primære listen for å søke gjennom."
  syntax:
    content: public Microsoft.Build.Framework.ITaskItem[] PrimaryList { get; set; }
    return:
      type: Microsoft.Build.Framework.ITaskItem[]
      description: "Primær listen for å søke gjennom."
  overload: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList
  id: SecondaryList
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: SecondaryList
  nameWithType: FindAppConfigFile.SecondaryList
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Henter eller angir sekundær listen for å søke gjennom."
  syntax:
    content: public Microsoft.Build.Framework.ITaskItem[] SecondaryList { get; set; }
    return:
      type: Microsoft.Build.Framework.ITaskItem[]
      description: "Sekundær listen for å søke gjennom."
  overload: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath
  id: TargetPath
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  langs:
  - csharp
  name: TargetPath
  nameWithType: FindAppConfigFile.TargetPath
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks
  summary: "Henter eller angir verdien for å legge til som målbane metadata."
  syntax:
    content: public string TargetPath { get; set; }
    return:
      type: System.String
      description: "Målbane-metadata."
  overload: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath*
  exceptions: []
  platform:
  - net462
references:
- uid: Microsoft.Build.Tasks.TaskExtension
  isExternal: false
  name: Microsoft.Build.Tasks.TaskExtension
- uid: Microsoft.Build.Tasks.FindAppConfigFile.#ctor
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: FindAppConfigFile()
  nameWithType: FindAppConfigFile.FindAppConfigFile()
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.FindAppConfigFile()
- uid: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: AppConfigFile
  nameWithType: FindAppConfigFile.AppConfigFile
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile
- uid: Microsoft.Build.Framework.ITaskItem
  parent: Microsoft.Build.Framework
  isExternal: false
  name: ITaskItem
  nameWithType: ITaskItem
  fullName: Microsoft.Build.Framework.ITaskItem
- uid: Microsoft.Build.Tasks.FindAppConfigFile.Execute
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: Execute()
  nameWithType: FindAppConfigFile.Execute()
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.Execute()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: PrimaryList
  nameWithType: FindAppConfigFile.PrimaryList
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList
- uid: Microsoft.Build.Framework.ITaskItem[]
  parent: Microsoft.Build.Framework
  isExternal: false
  name: ITaskItem
  nameWithType: ITaskItem
  fullName: Microsoft.Build.Framework.ITaskItem[]
  spec.csharp:
  - uid: Microsoft.Build.Framework.ITaskItem
    name: ITaskItem
    nameWithType: ITaskItem
    fullName: ITaskItem[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: SecondaryList
  nameWithType: FindAppConfigFile.SecondaryList
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList
- uid: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: TargetPath
  nameWithType: FindAppConfigFile.TargetPath
  fullName: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.FindAppConfigFile.#ctor*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: FindAppConfigFile
  nameWithType: FindAppConfigFile.FindAppConfigFile
- uid: Microsoft.Build.Tasks.FindAppConfigFile.AppConfigFile*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: AppConfigFile
  nameWithType: FindAppConfigFile.AppConfigFile
- uid: Microsoft.Build.Tasks.FindAppConfigFile.Execute*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: Execute
  nameWithType: FindAppConfigFile.Execute
- uid: Microsoft.Build.Tasks.FindAppConfigFile.PrimaryList*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: PrimaryList
  nameWithType: FindAppConfigFile.PrimaryList
- uid: Microsoft.Build.Tasks.FindAppConfigFile.SecondaryList*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: SecondaryList
  nameWithType: FindAppConfigFile.SecondaryList
- uid: Microsoft.Build.Tasks.FindAppConfigFile.TargetPath*
  parent: Microsoft.Build.Tasks.FindAppConfigFile
  isExternal: false
  name: TargetPath
  nameWithType: FindAppConfigFile.TargetPath
