### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  id: AuthenticationMode
  children:
  - Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  - Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  langs:
  - csharp
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  type: Enum
  summary: "Angir hvordan et Visual Basic-program godkjenner brukeren om den <xref uid=&quot;langword_csharp_My.User&quot; name=&quot;My.User&quot; href=&quot;&quot;> </xref> objektet."
  remarks: "Du kan angi godkjenningsmodusen for et program ved å sende denne opplisting verdier til den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A>konstruktør.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A> Hvis du vil ha mer informasjon, se [utvider Visual Basic programmet modellen](~/add/includes/ajax-current-ext-md.md).       Et Visual Basic-program som bruker Visual Basic programmet modellen kan angi om den bruker Windows-godkjenning eller egendefinert godkjenning. Du kan også konfigurere godkjenningsmodusen i Visual Studio integrert utviklingsmiljøet. Hvis du vil ha mer informasjon, se [programmet siden prosjektet Designer (Visual Basic)](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public enum AuthenticationMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  id: ApplicationDefined
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  langs:
  - csharp
  name: ApplicationDefined
  nameWithType: AuthenticationMode.ApplicationDefined
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Den &lt;xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A&gt; konstruktøren ikke initialisere sikkerhetskontohaveren for programmets hovedtråden. Programmet må initialisere sikkerhetskontohaveren for programmets hovedtråden."
  syntax:
    content: ApplicationDefined
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  id: Windows
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  langs:
  - csharp
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Den &lt;xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A&gt; konstruktøren initialiserer sikkerhetskontohaveren for programmets hovedtråden med gjeldende bruker Windows-brukerinformasjon."
  syntax:
    content: Windows
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  isExternal: false
  name: ApplicationDefined
  nameWithType: AuthenticationMode.ApplicationDefined
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  isExternal: false
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
