### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  id: UnhandledExceptionEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  - Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  langs:
  - csharp
  name: UnhandledExceptionEventArgs
  nameWithType: UnhandledExceptionEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  type: Class
  summary: "Gir dataene for den <xref uid=&quot;langword_csharp_My.Application.UnhandledException&quot; name=&quot;My.Application.UnhandledException&quot; href=&quot;&quot;> </xref> hendelsen."
  remarks: "Den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException>hendelsen oppstår når det oppstår et ubehandlet unntak i en applikasjon som implementerer Visual Basic applikasjons-modellen.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException> Hvis du vil ha mer informasjon, se [oversikt over Visual Basic programmet modellen](~/add/includes/ajax-current-ext-md.md).       UnhandledExceptionEventArgs inneholder den <xref:System.Exception>som oppstod, og angir om programmet må avsluttes ved avslutningen unntak behandlingsprogrammet.</xref:System.Exception>"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public class UnhandledExceptionEventArgs : System.Threading.ThreadExceptionEventArgs
  inheritance:
  - System.EventArgs
  - System.Threading.ThreadExceptionEventArgs
  implements: []
  inheritedMembers:
  - System.Threading.ThreadExceptionEventArgs.Exception
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  id: '#ctor(System.Boolean,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  langs:
  - csharp
  name: UnhandledExceptionEventArgs(Boolean,Exception)
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs&quot;> </xref> klasse."
  remarks: "Den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException>hendelsen oppstår når det oppstår et ubehandlet unntak i en applikasjon som implementerer Visual Basic applikasjons-modellen.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException> Hvis du vil ha mer informasjon, se [oversikt over Visual Basic programmet modellen](~/add/includes/ajax-current-ext-md.md).       <xref:Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs>inneholder den <xref:System.Exception>som oppstod, og angir om programmet må avsluttes ved avslutningen unntak behandlingsprogrammet.</xref:System.Exception></xref:Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs>"
  syntax:
    content: public UnhandledExceptionEventArgs (bool exitApplication, Exception exception);
    parameters:
    - id: exitApplication
      type: System.Boolean
      description: "En <xref:System.Boolean>som angir om programmet må avsluttes ved avslutningen unntak behandlingsprogrammet.</xref:System.Boolean>"
    - id: exception
      type: System.Exception
      description: "Den <xref:System.Exception>som oppstod.</xref:System.Exception>"
  overload: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  id: ExitApplication
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  langs:
  - csharp
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Angir om programmet må avsluttes ved avslutningen behandlingsprogrammet unntak."
  remarks: "Visual Basic programmet modellen kontrollerer verdien for denne egenskapen når du har kjørt behandlingsprogrammer for den <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException>hendelsen.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException> Hvis ExitApplication `True`, og programmet avsluttes. Ellers fortsetter programmet å kjøre. Hvis du vil ha mer informasjon, se [oversikt over Visual Basic programmet modellen](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public bool ExitApplication { get; set; }
    return:
      type: System.Boolean
      description: "En <xref:System.Boolean>som angir om programmet må avsluttes ved avslutningen unntak behandlingsprogrammet.</xref:System.Boolean>"
  overload: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Threading.ThreadExceptionEventArgs
  isExternal: false
  name: System.Threading.ThreadExceptionEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: UnhandledExceptionEventArgs(Boolean,Exception)
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: UnhandledExceptionEventArgs
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication*
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
