### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ServerWebConfig
  id: ServerWebConfig
  children:
  - System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  - System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: ServerWebConfig
  nameWithType: ServerWebConfig
  fullName: System.EnterpriseServices.Internal.ServerWebConfig
  type: Class
  summary: "Oppretter en Web.config-filen for en SOAP-aktiverte COM +-programmet. Kan også legge til komponenten oppføringer filen for COM-grensesnitt som publiseres i applikasjonen."
  remarks: "Klassen ServerWebConfig brukes til å opprette en Web.config-filen under oppretting av en virtuell rotmappe i Internet Information Services (IIS) 6.0 for SOAP-aktiverte COM +-programmet. Det kan også legge til XML-elementer i Web.config-filen for komponentgrensesnitt som legges til programmet.       ServerWebConfig er brukt internt av .NET Framework. Du trenger ikke å bruke den direkte i koden."
  syntax:
    content: 'public class ServerWebConfig : System.EnterpriseServices.Internal.IServerWebConfig'
  inheritance:
  - System.Object
  implements:
  - System.EnterpriseServices.Internal.IServerWebConfig
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.EnterpriseServices.Internal.ServerWebConfig&quot;> </xref> klasse."
  syntax:
    content: public ServerWebConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Legger til XML-elementer i Web.config-filen for et COM-grensesnitt som er publisert i SOAP-aktiverte COM +-programmet."
  remarks: "For den angitte typen metoden AddElement legger til filen Web.config i `<wellknown>` og `<activated>` elementer som underordnede av den `<service>` element med følgende XPath: `/configuration/system.runtime.remoting/application/service` den `AssemblyName`, `TypeName`, `ProgId`, og `WkoMode` parametere er inkludert i attributtverdier for de to tillagte elementene.       AddElement skal ikke kalles direkte. I stedet kalle den <xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>metoden.</xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>"
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string WkoMode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Banen til den eksisterende Web.config-filen."
    - id: AssemblyName
      type: System.String
      description: "Navnet på samlingen som inneholder typen som legges til."
    - id: TypeName
      type: System.String
      description: "Navnet på typen som legges til."
    - id: ProgId
      type: System.String
      description: "Program-IDen for typen som legges til."
    - id: WkoMode
      type: System.String
      description: "En strengkonstant som tilsvarer navnet på et medlem fra den <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> opplisting som angir hvordan et kjent objekt er aktivert."
    - id: Error
      type: System.String
      description: "Du kan skrive en feilmelding som en streng."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Oppretter en Web.config-filen for en SOAP-aktiverte COM +-programmet slik at filen er klar til å ha XML-elementer som er lagt til for COM-grensesnitt publiseres."
  remarks: "Metoden Create oppretter en Web.config-fil som inneholder hierarkiet for et tomt element med følgende XPath: ```   /configuration/system.runtime.remoting/application/service   ``` i stedet for å starte en <xref:System.EnterpriseServices.Internal.ServerWebConfig>klasse objekt og kaller Opprett direkte, kall den <xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A>metoden.</xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A> </xref:System.EnterpriseServices.Internal.ServerWebConfig>"
  syntax:
    content: public void Create (string FilePath, string FilePrefix, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Mappen konfigurasjonsfilen skal opprettes."
    - id: FilePrefix
      type: System.String
      description: "Strengverdien &quot;Web&quot;, som en config-filtype er lagt til."
    - id: Error
      type: System.String
      description: "Du kan skrive en feilmelding som en streng."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig
  nameWithType: ServerWebConfig.ServerWebConfig
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: ServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create
  nameWithType: ServerWebConfig.Create
