### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebConfigurationFileMap
  id: WebConfigurationFileMap
  children:
  - System.Web.Configuration.WebConfigurationFileMap.#ctor
  - System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  - System.Web.Configuration.WebConfigurationFileMap.Clone
  - System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  langs:
  - csharp
  name: WebConfigurationFileMap
  nameWithType: WebConfigurationFileMap
  fullName: System.Web.Configuration.WebConfigurationFileMap
  type: Class
  summary: "Definerer tilordninger for filen for konfigurasjon for et webprogram. Denne klassen kan ikke arves."
  remarks: "Klassen WebConfigurationFileMap brukes til å angi Web konfigurasjonshierarkiet-filen. Som standard bruker Konfigurasjonssystemet IIS-metabasen for å avgjøre Web filen hierarkiet. Hvis IIS ikke er installert, eller hvis et program rettet mot en versjon av .NET Framework som ikke er den nyeste versjonen som er installert på serveren, gir WebConfigurationFileMap-klassen en metode til å definere en egendefinert hierarki.       Klassen WebConfigurationFileMap kan angi en enkelt bane eller flere baner som er relatert til konfigurasjonsfiler."
  syntax:
    content: 'public sealed class WebConfigurationFileMap : System.Configuration.ConfigurationFileMap'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationFileMap
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: WebConfigurationFileMap()
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap()
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Oppretter en ny forekomst av den <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klasse."
  syntax:
    content: public WebConfigurationFileMap ();
    parameters: []
  overload: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: WebConfigurationFileMap(String)
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap(String)
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klassen ved hjelp av angitte maskinen konfigurasjonsfilnavnet."
  remarks: "Du bruker denne konstruktøren når du bruker en versjon av den [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] som er eldre enn den siste som er installert på datamaskinen. Metoden, kan du angi en konfigurasjonsfil for maskinen som passer til versjon av den [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] som du bruker.      > [!NOTE] > Selv om konstruktøren aksepterer bare banen til filen Machine.config, Konfigurasjonssystemet også lese roten Web.config-filen i samme mappe der Machine.config-filen finnes."
  syntax:
    content: public WebConfigurationFileMap (string machineConfigFileName);
    parameters:
    - id: machineConfigFileName
      type: System.String
      description: "Maskinen konfigurasjonsfilnavnet med hele fysiske banen (for eksempel `c:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\CONFIG\\machine.config`)."
  overload: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone
  id: Clone
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: Clone()
  nameWithType: WebConfigurationFileMap.Clone()
  fullName: System.Web.Configuration.WebConfigurationFileMap.Clone()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Oppretter en ny forekomst av en <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klassen med samme verdi som den eksisterende forekomsten."
  syntax:
    content: public override object Clone ();
    parameters: []
    return:
      type: System.Object
      description: "En ny forekomst av en <xref href=&quot;System.Web.Configuration.WebConfigurationFileMap&quot;> </xref> klasse."
  overload: System.Web.Configuration.WebConfigurationFileMap.Clone*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  id: VirtualDirectories
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
  fullName: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter samlingen listen over virtuelle mapper for et webprogram."
  remarks: "De virtuelle mappene på et webprogram kan ikke nødvendigvis tilordne til de fysiske mappene på serveren. Den <xref:System.Web.Configuration.VirtualDirectoryMapping>klassen er uavhengig av IIS.</xref:System.Web.Configuration.VirtualDirectoryMapping>"
  syntax:
    content: public System.Web.Configuration.VirtualDirectoryMappingCollection VirtualDirectories { get; }
    return:
      type: System.Web.Configuration.VirtualDirectoryMappingCollection
      description: "En samling av <xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;> </xref> objekter."
  overload: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: System.Configuration.ConfigurationFileMap
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap()
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap()
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap()
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap(String)
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap(String)
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: Clone()
  nameWithType: WebConfigurationFileMap.Clone()
  fullName: System.Web.Configuration.WebConfigurationFileMap.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
  fullName: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
- uid: System.Web.Configuration.VirtualDirectoryMappingCollection
  parent: System.Web.Configuration
  isExternal: false
  name: VirtualDirectoryMappingCollection
  nameWithType: VirtualDirectoryMappingCollection
  fullName: System.Web.Configuration.VirtualDirectoryMappingCollection
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: Clone
  nameWithType: WebConfigurationFileMap.Clone
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
