### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs
  id: SelectingProviderEventArgs
  children:
  - System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  - System.Web.ApplicationServices.SelectingProviderEventArgs.User
  langs:
  - csharp
  name: SelectingProviderEventArgs
  nameWithType: SelectingProviderEventArgs
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs
  type: Class
  summary: "Gir dataene for den <xref href=&quot;System.Web.ApplicationServices.RoleService.SelectingProvider&quot;> </xref> hendelsen."
  remarks: "Klassen SelectingProviderEventArgs leverer verdier i <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>hendelsesbehandlingen.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider> Du oppretter en <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>hendelsesbehandlingen å velge rolleleverandør på kjøretidspunktet.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>       Den <xref:System.Web.ApplicationServices.RoleService>klasse hever den <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>hendelsen når enten den <xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A>metoden eller <xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A>-metoden for den <xref:System.Web.ApplicationServices.RoleService>klassen kalles.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A> </xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A> </xref:System.Web.ApplicationServices.RoleService.SelectingProvider> </xref:System.Web.ApplicationServices.RoleService>       Du bruker den <xref:System.Web.ApplicationServices.SelectingProviderEventArgs.User%2A>til å hente informasjon om den påloggede brukeren.</xref:System.Web.ApplicationServices.SelectingProviderEventArgs.User%2A> For å hente informasjon om via en ikke-standard rolleleverandør, kan du angi den <xref:System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName%2A>egenskapen til navnet på rolleleverandør du vil bruke den <xref:System.Web.ApplicationServices.RoleService>objekt som skal brukes.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the SelectingProviderEventArgs object to check the user name and to set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/t-system.web.application_0_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/t-system.web.application_0_1.asax)]"
  syntax:
    content: 'public class SelectingProviderEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  id: ProviderName
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  langs:
  - csharp
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter eller angir rolleleverandør skal brukes for å hente brukerens roller."
  remarks: "Du kan bruke egenskapen ProviderName angi rolleleverandør under den <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>hendelsen.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the <xref:System.Web.ApplicationServices.SelectingProviderEventArgs> object to check the user name and to set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/p-system.web.application_3_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/p-system.web.application_3_1.asax)]"
  syntax:
    content: public string ProviderName { get; set; }
    return:
      type: System.String
      description: "Navnet på rolleleverandør som brukes til å hente brukerens roller."
  overload: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  id: User
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  langs:
  - csharp
  name: User
  nameWithType: SelectingProviderEventArgs.User
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter den godkjente brukeren."
  remarks: "Du bruke egenskapen for bruker til å hente informasjon om brukeren under den <xref:System.Web.ApplicationServices.RoleService.SelectingProvider>hendelsen.</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the <xref:System.Web.ApplicationServices.SelectingProviderEventArgs> object to check the user name and set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/p-system.web.application_9_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/p-system.web.application_9_1.asax)]"
  syntax:
    content: public System.Security.Principal.IPrincipal User { get; }
    return:
      type: System.Security.Principal.IPrincipal
      description: "Et objekt som inneholder den godkjente brukeren."
  overload: System.Web.ApplicationServices.SelectingProviderEventArgs.User*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: User
  nameWithType: SelectingProviderEventArgs.User
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.User
- uid: System.Security.Principal.IPrincipal
  parent: System.Security.Principal
  isExternal: true
  name: IPrincipal
  nameWithType: IPrincipal
  fullName: System.Security.Principal.IPrincipal
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName*
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User*
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: User
  nameWithType: SelectingProviderEventArgs.User
