### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.IApplicationTrustManager
  id: IApplicationTrustManager
  children:
  - System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  langs:
  - csharp
  name: IApplicationTrustManager
  nameWithType: IApplicationTrustManager
  fullName: System.Security.Policy.IApplicationTrustManager
  type: Interface
  summary: "Bestemmer om et program skal kjøres, og hvilke sett med tillatelser bør gis til den."
  remarks: "Stoler lederne må implementere grensesnittet IApplicationTrustManager. Vert-kall i <xref:System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust%2A?displayProperty=fullName>metode for å finne ut om et program skal kjøres, og hvilke tillatelser bør gis til programmet.</xref:System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust%2A?displayProperty=fullName>       I de [!INCLUDE[net_v40_long](~/add/includes/net-v40-long-md.md)] og nyere, vises bare én klarering manager, som kan være en egendefinert implementering av grensesnittet IApplicationTrustManager. Standard klarering manager implementering ber brukeren om tillatelse til å installere programmet og utvide rettighetene til programmet. Andre klarering manager implementeringer kan angi opplevelser annen bruker. Implementering kan for eksempel se en liste over enterprise for klarerte programmer i stedet for ber brukeren om at informasjon."
  example:
  - "The following example shows a simple implementation of IApplicationTrustManager.  \n  \n [!code-cs[System.Security.Policy.IApplicationTrustManager#1](~/add/codesnippet/csharp/t-system.security.policy_3_1.cs)]\n [!code-vb[System.Security.Policy.IApplicationTrustManager#1](~/add/codesnippet/visualbasic/t-system.security.policy_3_1.vb)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public interface IApplicationTrustManager : System.Security.ISecurityEncodable
  implements:
  - System.Security.ISecurityEncodable
  platform:
  - net462
- uid: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  id: DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  parent: System.Security.Policy.IApplicationTrustManager
  langs:
  - csharp
  name: DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  nameWithType: IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  fullName: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Bestemmer om et program skal kjøres, og hvilke sett med tillatelser bør gis til den."
  remarks: "Metoden DetermineApplicationTrust kalles av verten som bestemmer om et program skal kjøres, og hvilket sett med tillatelser den bør gis. DetermineApplicationTrust returnerer en <xref:System.Security.Policy.ApplicationTrust>objekt med en <xref:System.Security.Policy.ApplicationTrust.DefaultGrantSet%2A>egenskapen som inneholder en tillatelse angis som representerer tillatelse til å gis til hver samlingen kjøres i konteksten for applikasjonen.</xref:System.Security.Policy.ApplicationTrust.DefaultGrantSet%2A> </xref:System.Security.Policy.ApplicationTrust> Tillatelsene som er gitt gjelder ikke for samlinger i den globale samlingsbufferen. Den <xref:System.Security.Policy.ApplicationTrust>objektet har også en <xref:System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun%2A>egenskapen transportbehandling klarering angir som viser om programmet skal være klarerte.</xref:System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun%2A> </xref:System.Security.Policy.ApplicationTrust> Hvis transportbehandling klarering indikerer at programmet er klarert, verten aktiverer programmet og gir samlingene sett med tillatelser som er angitt i den <xref:System.Security.Policy.ApplicationTrust>samlingen.</xref:System.Security.Policy.ApplicationTrust>"
  example:
  - "The following example shows an implementation of the DetermineApplicationTrust method for a custom trust manager. This code example is part of a larger example provided for the <xref:System.Security.Policy.IApplicationTrustManager> interface.  \n  \n [!code-cs[System.Security.Policy.IApplicationTrustManager#2](~/add/codesnippet/csharp/24b6db65-f82b-47e4-ac93-_1.cs)]\n [!code-vb[System.Security.Policy.IApplicationTrustManager#2](~/add/codesnippet/visualbasic/24b6db65-f82b-47e4-ac93-_1.vb)]"
  syntax:
    content: public System.Security.Policy.ApplicationTrust DetermineApplicationTrust (ActivationContext activationContext, System.Security.Policy.TrustManagerContext context);
    parameters:
    - id: activationContext
      type: System.ActivationContext
      description: "Aktiveringskonteksten for programmet."
    - id: context
      type: System.Security.Policy.TrustManagerContext
      description: "Stoler manager konteksten for programmet."
    return:
      type: System.Security.Policy.ApplicationTrust
      description: "Et objekt som inneholder sikkerhet beslutninger om applikasjonen."
  overload: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(System.ActivationContext,System.Security.Policy.TrustManagerContext)
  parent: System.Security.Policy.IApplicationTrustManager
  isExternal: false
  name: DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  nameWithType: IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
  fullName: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust(ActivationContext,TrustManagerContext)
- uid: System.Security.Policy.ApplicationTrust
  parent: System.Security.Policy
  isExternal: false
  name: ApplicationTrust
  nameWithType: ApplicationTrust
  fullName: System.Security.Policy.ApplicationTrust
- uid: System.ActivationContext
  parent: System
  isExternal: false
  name: ActivationContext
  nameWithType: ActivationContext
  fullName: System.ActivationContext
- uid: System.Security.Policy.TrustManagerContext
  parent: System.Security.Policy
  isExternal: false
  name: TrustManagerContext
  nameWithType: TrustManagerContext
  fullName: System.Security.Policy.TrustManagerContext
- uid: System.Security.Policy.IApplicationTrustManager.DetermineApplicationTrust*
  parent: System.Security.Policy.IApplicationTrustManager
  isExternal: false
  name: DetermineApplicationTrust
  nameWithType: IApplicationTrustManager.DetermineApplicationTrust
