### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  id: PartialTrustVisibleAssembliesSection
  children:
  - System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor
  - System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  - System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  langs:
  - csharp
  name: PartialTrustVisibleAssembliesSection
  nameWithType: PartialTrustVisibleAssembliesSection
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  type: Class
  summary: "Konfigurerer et sett med samlinger delvis klarering. Denne klassen kan ikke arves."
  remarks: "Som standard definerer ASP.NET internt kjente settet med samlinger som er merket med delvis klarert brukere attributtet (APTCA) for bruk i delvis klarert ASP.NET-applikasjoner. PartialTrustVisibleAssembliesSection kan du legge til APTCA merket samlinger i listen.       Hvis du vil konfigurere en samling, må du heksadesimale strengrepresentasjon av sin fellesnøkkel. Du åpner denne nøkkelen ved hjelp av verktøyet sterkt navn (Sn.exe). Dette verktøyet produserer den heksadesimale strengrepresentasjon med fellesnøkkel som du bruker for konfigurasjon og produserer også fellesnøkkel-token.       Du finner mer informasjon om verktøyet sterkt navn [Sn.exe (sterke navnet verktøyet)](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following example shows how to configure a partial trust assembly by using the `partialTrustVisibleAssemblies` section in a configuration file.  \n  \n```  \n<partialTrustVisibleAssemblies>  \n  <add assemblyName=\"MyAssembly\"   \n    publicKey=\"hex_key_representation\"/>  \n</partialTrustVisibleAssemblies>  \n```"
  syntax:
    content: 'public sealed class PartialTrustVisibleAssembliesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  langs:
  - csharp
  name: PartialTrustVisibleAssembliesSection()
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.PartialTrustVisibleAssembliesSection&quot;> </xref> klasse."
  syntax:
    content: public PartialTrustVisibleAssembliesSection ();
    parameters: []
  overload: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  id: PartialTrustVisibleAssemblies
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  langs:
  - csharp
  name: PartialTrustVisibleAssemblies
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter den <xref href=&quot;System.Web.Configuration.PartialTrustVisibleAssembliesSection&quot;> </xref> samling APTCA merket samlinger bruker i delvis klarert ASP.NET-applikasjoner."
  syntax:
    content: public System.Web.Configuration.PartialTrustVisibleAssemblyCollection PartialTrustVisibleAssemblies { get; }
    return:
      type: System.Web.Configuration.PartialTrustVisibleAssemblyCollection
      description: "En samling av samlingene APTCA merket for bruk i delvis klareringsnivå ASP.NET-applikasjoner."
  overload: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  id: Properties
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  langs:
  - csharp
  name: Properties
  nameWithType: PartialTrustVisibleAssembliesSection.Properties
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssembliesSection()
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection()
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssemblies
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
- uid: System.Web.Configuration.PartialTrustVisibleAssemblyCollection
  parent: System.Web.Configuration
  isExternal: false
  name: PartialTrustVisibleAssemblyCollection
  nameWithType: PartialTrustVisibleAssemblyCollection
  fullName: System.Web.Configuration.PartialTrustVisibleAssemblyCollection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: Properties
  nameWithType: PartialTrustVisibleAssembliesSection.Properties
  fullName: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.#ctor*
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssembliesSection
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssembliesSection
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies*
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: PartialTrustVisibleAssemblies
  nameWithType: PartialTrustVisibleAssembliesSection.PartialTrustVisibleAssemblies
- uid: System.Web.Configuration.PartialTrustVisibleAssembliesSection.Properties*
  parent: System.Web.Configuration.PartialTrustVisibleAssembliesSection
  isExternal: false
  name: Properties
  nameWithType: PartialTrustVisibleAssembliesSection.Properties
