### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentDownloadException
  id: DeploymentDownloadException
  children:
  - System.Deployment.Application.DeploymentDownloadException.#ctor
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: DeploymentDownloadException
  nameWithType: DeploymentDownloadException
  fullName: System.Deployment.Application.DeploymentDownloadException
  type: Class
  summary: "Indikerer at det oppstod en feil under nedlasting av enten den [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] programmanifest eller den distribusjonen filer til klientdatamaskinen."
  remarks: "En DeploymentDownloadException kan tyde på at en rekke problemer oppstod under brukeren prøvde å laste ned en [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] appoppdateringen:-klientens datamaskinens nettverksforbindelse er nede.      -Nettserveren FTP-server eller filressurs vert oppdateringen er utilgjengelig.      -En eller flere av filene i den [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] distribusjon ble ikke funnet.       Hvis du vil ha detaljert informasjon om feilen om et unntak, kan du se den [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] feilloggen. Hvis du vil ha mer informasjon, se [feilsøking ClickOnce distribusjoner](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following code example installs an application update synchronously, and reports to the user if there was a problem downloading either the manifests or the deployment's files.  \n  \n [!code-cs[ClickOnceAPI#5](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#5)]\n [!code-cpp[ClickOnceAPI#5](~/add/codesnippet/cpp/t-system.deployment.appl_2_1.cpp)]\n [!code-vb[ClickOnceAPI#5](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#5)]"
  syntax:
    content: 'public class DeploymentDownloadException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException()
  nameWithType: DeploymentDownloadException.DeploymentDownloadException()
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref> klasse."
  syntax:
    content: public DeploymentDownloadException ();
    parameters: []
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(String)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref> klassen med en melding som beskriver unntaket."
  syntax:
    content: public DeploymentDownloadException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Meldingen som beskriver unntaket. Oppkalleren for denne konstruktøren kreves for å sikre at denne strengen er lokalisert for den gjeldende kulturen i systemet."
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref> klasse."
  syntax:
    content: protected DeploymentDownloadException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "Objektet som har datatypen serialiserte objektet."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "Kontekstavhengig informasjon om kilden eller målet."
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(String,Exception)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref> klasse."
  syntax:
    content: public DeploymentDownloadException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Meldingen som beskriver unntaket. Oppkalleren for denne konstruktøren kreves for å sikre at denne strengen er lokalisert for den gjeldende kulturen i systemet."
    - id: innerException
      type: System.Exception
      description: "Unntaket er årsaken til den gjeldende unntaket. Hvis den `innerException` -parameteren er ikke <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, oppstår det gjeldende unntaket i en <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokken som behandler det interne unntaket."
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException()
  nameWithType: DeploymentDownloadException.DeploymentDownloadException()
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException()
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(String)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(String,Exception)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor*
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException
  nameWithType: DeploymentDownloadException.DeploymentDownloadException
