### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup
  id: CachingSectionGroup
  children:
  - System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  - System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  langs:
  - csharp
  name: CachingSectionGroup
  nameWithType: CachingSectionGroup
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup
  type: Class
  summary: "Definerer en konfigurasjonsdelen for.NET Framework hurtigbufring. Denne klassen kan ikke arves."
  remarks: "Klassen CachingSectionGroup definerer en hurtigbufring del (`system.runtime.caching`) for konfigurasjonsfiler. Denne delen inneholder elementer som brukes til å konfigurere forskjellige typer fullført. Bare elementet som er tilgjengelig i delen hurtigbufring er elementet i ASP.NET. Dette elementet konfigurerer hurtigbuffere som er basert på <xref:System.Runtime.Caching.MemoryCache>klasse.</xref:System.Runtime.Caching.MemoryCache>"
  syntax:
    content: 'public sealed class CachingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  langs:
  - csharp
  name: CachingSectionGroup()
  nameWithType: CachingSectionGroup.CachingSectionGroup()
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup()
  type: Constructor
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Runtime.Caching.Configuration.CachingSectionGroup&quot;> </xref> klasse."
  syntax:
    content: public CachingSectionGroup ();
    parameters: []
  overload: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  id: MemoryCaches
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  langs:
  - csharp
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  type: Property
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: "Henter samlingen av <xref href=&quot;System.Runtime.Caching.Configuration.MemoryCacheElement&quot;> </xref> objekter."
  remarks: "Egenskapen MemoryCaches returnerer samlingen av <xref:System.Runtime.Caching.Configuration.MemoryCacheSection>objekter fra overordnet hurtigbufring delen.</xref:System.Runtime.Caching.Configuration.MemoryCacheSection>"
  syntax:
    content: public System.Runtime.Caching.Configuration.MemoryCacheSection MemoryCaches { get; }
    return:
      type: System.Runtime.Caching.Configuration.MemoryCacheSection
      description: "Samling av cache-delen objekter."
  overload: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: CachingSectionGroup()
  nameWithType: CachingSectionGroup.CachingSectionGroup()
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup()
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection
  parent: System.Runtime.Caching.Configuration
  isExternal: false
  name: MemoryCacheSection
  nameWithType: MemoryCacheSection
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor*
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: CachingSectionGroup
  nameWithType: CachingSectionGroup.CachingSectionGroup
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches*
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
