### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProviderAttribute
  id: SettingsProviderAttribute
  children:
  - System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  - System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  - System.Configuration.SettingsProviderAttribute.ProviderTypeName
  langs:
  - csharp
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute
  fullName: System.Configuration.SettingsProviderAttribute
  type: Class
  summary: "Angir innstillingene for leverandøren som brukes til å angi lagring for den gjeldende klasse for programmet eller egenskapen. Denne klassen kan arves."
  remarks: "Klasse for hvert program definerer en gruppe i innstillinger-egenskapene for applikasjonen som representerer informasjon som vedvarer mellom kjøringer av programmet. Det er en Innstillingsleverandør, en klasse som er avledet fra <xref:System.Configuration.SettingsProvider>, som gir faktisk lagring mekanisme.</xref:System.Configuration.SettingsProvider>       SettingsProviderAttribute angir innstillinger leverandøren som brukes til å angi lagring for innstillinger for programmet. Dette attributtet kan brukes til klasse for hele programmet eller enkelt program-innstillinger. En SettingsProviderAttribute sett på nivå egenskapen overstyrer attributtet klassen nivå. Hvis innstillingene leverandør ikke eksplisitt er angitt, brukes standardleverandøren. For klientprogrammer er standardleverandøren <xref:System.Configuration.LocalFileSettingsProvider>.</xref:System.Configuration.LocalFileSettingsProvider>       Angi leverandører kan ikke fastslås på kjøretidspunktet. Noen kjøretid fastsettelse av lagring metoder må være kodet i innstillinger leverandøren selve klassen.      > [!CAUTION] > Ved hjelp av egendefinerte innstillinger leverandører fra tilfeldig tredjeparter er arvbart unsafe fordi disse leverandørene har full lese-/ skrivetilgang til programmets konfigurasjonsinformasjon. Leverandør innstillingene skal grundig vetted før den er tatt i bruk for generell bruk."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsProviderAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en forekomst av den <xref href=&quot;System.Configuration.SettingsProviderAttribute&quot;> </xref> klasse."
  remarks: "Typenavn er navnet på klassen som er avledet fra <xref:System.Configuration.SettingsProvider>, som er angitt som innstillingene for leverandøren.</xref:System.Configuration.SettingsProvider>      > [!CAUTION] > Ved hjelp av egendefinerte innstillinger leverandører fra tilfeldig tredjeparter er arvbart unsafe fordi disse leverandørene har full lese-/ skrivetilgang til programmets konfigurasjonsinformasjon. Leverandør innstillingene skal grundig vetted før den er tatt i bruk for generell bruk."
  syntax:
    content: public SettingsProviderAttribute (string providerTypeName);
    parameters:
    - id: providerTypeName
      type: System.String
      description: "En <xref:System.String>som inneholder navnet på innstillinger-leverandøren.</xref:System.String>"
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.SettingsProviderAttribute&quot;> </xref> klasse."
  syntax:
    content: public SettingsProviderAttribute (Type providerType);
    parameters:
    - id: providerType
      type: System.Type
      description: "En <xref:System.Type>som inneholder innstillinger for leverandørtypen.</xref:System.Type>"
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  id: ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Henter typenavnet på Innstillingsleverandør."
  remarks: "Egenskapen ProviderTypeName er angitt i det <xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A>for klassen.</xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A>"
  syntax:
    content: public string ProviderTypeName { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som inneholder navnet på innstillinger-leverandøren.</xref:System.String>"
  overload: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
- uid: System.Configuration.SettingsProviderAttribute.#ctor*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
