### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceElement
  id: ServiceElement
  children:
  - System.ServiceModel.Configuration.ServiceElement.#ctor
  - System.ServiceModel.Configuration.ServiceElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ServiceElement.BehaviorConfiguration
  - System.ServiceModel.Configuration.ServiceElement.Endpoints
  - System.ServiceModel.Configuration.ServiceElement.Host
  - System.ServiceModel.Configuration.ServiceElement.Name
  - System.ServiceModel.Configuration.ServiceElement.Properties
  - System.ServiceModel.Configuration.ServiceElement.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: ServiceElement
  nameWithType: ServiceElement
  fullName: System.ServiceModel.Configuration.ServiceElement
  type: Class
  summary: "Representerer et XML-element som inneholder innstillinger for en [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] tjenesten, i tillegg til endepunkt som eksponerer tjenesten. Denne klassen kan ikke arves."
  syntax:
    content: 'public sealed class ServiceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceElement
  langs:
  - csharp
  name: ServiceElement()
  nameWithType: ServiceElement.ServiceElement()
  fullName: System.ServiceModel.Configuration.ServiceElement.ServiceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.ServiceElement&quot;> </xref> klasse."
  syntax:
    content: public ServiceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ServiceElement
  langs:
  - csharp
  name: ServiceElement(String)
  nameWithType: ServiceElement.ServiceElement(String)
  fullName: System.ServiceModel.Configuration.ServiceElement.ServiceElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.ServiceElement&quot;> </xref> klasse tjenestetypen å brukes."
  syntax:
    content: public ServiceElement (string serviceName);
    parameters:
    - id: serviceName
      type: System.String
      description: "Typen for at tjenesten skal starte."
  overload: System.ServiceModel.Configuration.ServiceElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceElement.BehaviorConfiguration
  id: BehaviorConfiguration
  parent: System.ServiceModel.Configuration.ServiceElement
  langs:
  - csharp
  name: BehaviorConfiguration
  nameWithType: ServiceElement.BehaviorConfiguration
  fullName: System.ServiceModel.Configuration.ServiceElement.BehaviorConfiguration
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en streng som inneholder navnet på virkemåte for virkemåten som skal brukes til å starte tjenesten."
  syntax:
    content: public string BehaviorConfiguration { get; set; }
    return:
      type: System.String
      description: "Virkemåte navnet på virkemåten som skal brukes til å starte tjenesten. Navnet på virkemåte må være i området på punkt tjenesten er definert. Standardverdien er en tom streng."
  overload: System.ServiceModel.Configuration.ServiceElement.BehaviorConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceElement.Endpoints
  id: Endpoints
  parent: System.ServiceModel.Configuration.ServiceElement
  langs:
  - csharp
  name: Endpoints
  nameWithType: ServiceElement.Endpoints
  fullName: System.ServiceModel.Configuration.ServiceElement.Endpoints
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter en samling av endepunkt som vises av denne tjenesten."
  remarks: "Hvert endepunkt har sin egen adresse og bindingen. Alle bindinger brukes i konfigurasjonsfilen må være definert i omfanget av filen."
  syntax:
    content: public System.ServiceModel.Configuration.ServiceEndpointElementCollection Endpoints { get; }
    return:
      type: System.ServiceModel.Configuration.ServiceEndpointElementCollection
      description: "En <xref href=&quot;System.ServiceModel.Configuration.ServiceEndpointElementCollection&quot;> </xref> som inneholder ett eller flere sluttpunkter vises av denne tjenesten."
  overload: System.ServiceModel.Configuration.ServiceElement.Endpoints*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceElement.Host
  id: Host
  parent: System.ServiceModel.Configuration.ServiceElement
  langs:
  - csharp
  name: Host
  nameWithType: ServiceElement.Host
  fullName: System.ServiceModel.Configuration.ServiceElement.Host
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter en konfigurasjonselementet som angir verten for denne tjenesteforekomsten."
  syntax:
    content: public System.ServiceModel.Configuration.HostElement Host { get; }
    return:
      type: System.ServiceModel.Configuration.HostElement
      description: "En <xref href=&quot;System.ServiceModel.Configuration.HostElement&quot;> </xref> som angir verten for denne tjenesteforekomsten."
  overload: System.ServiceModel.Configuration.ServiceElement.Host*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.ServiceElement
  langs:
  - csharp
  name: Name
  nameWithType: ServiceElement.Name
  fullName: System.ServiceModel.Configuration.ServiceElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir det unike navnet på denne tjenesten."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Det unike navnet på denne tjenesten."
  overload: System.ServiceModel.Configuration.ServiceElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ServiceElement
  langs:
  - csharp
  name: Properties
  nameWithType: ServiceElement.Properties
  fullName: System.ServiceModel.Configuration.ServiceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.ServiceModel.Configuration.ServiceElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceElement.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ServiceElement
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: ServiceElement.Reset(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ServiceElement.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "Som skal legges til."
  overload: System.ServiceModel.Configuration.ServiceElement.Reset*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ServiceElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: ServiceElement()
  nameWithType: ServiceElement.ServiceElement()
  fullName: System.ServiceModel.Configuration.ServiceElement.ServiceElement()
- uid: System.ServiceModel.Configuration.ServiceElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: ServiceElement(String)
  nameWithType: ServiceElement.ServiceElement(String)
  fullName: System.ServiceModel.Configuration.ServiceElement.ServiceElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ServiceElement.BehaviorConfiguration
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: BehaviorConfiguration
  nameWithType: ServiceElement.BehaviorConfiguration
  fullName: System.ServiceModel.Configuration.ServiceElement.BehaviorConfiguration
- uid: System.ServiceModel.Configuration.ServiceElement.Endpoints
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: Endpoints
  nameWithType: ServiceElement.Endpoints
  fullName: System.ServiceModel.Configuration.ServiceElement.Endpoints
- uid: System.ServiceModel.Configuration.ServiceEndpointElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceEndpointElementCollection
  nameWithType: ServiceEndpointElementCollection
  fullName: System.ServiceModel.Configuration.ServiceEndpointElementCollection
- uid: System.ServiceModel.Configuration.ServiceElement.Host
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: Host
  nameWithType: ServiceElement.Host
  fullName: System.ServiceModel.Configuration.ServiceElement.Host
- uid: System.ServiceModel.Configuration.HostElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HostElement
  nameWithType: HostElement
  fullName: System.ServiceModel.Configuration.HostElement
- uid: System.ServiceModel.Configuration.ServiceElement.Name
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: Name
  nameWithType: ServiceElement.Name
  fullName: System.ServiceModel.Configuration.ServiceElement.Name
- uid: System.ServiceModel.Configuration.ServiceElement.Properties
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: Properties
  nameWithType: ServiceElement.Properties
  fullName: System.ServiceModel.Configuration.ServiceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ServiceElement.Reset(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: ServiceElement.Reset(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ServiceElement.Reset(ConfigurationElement)
- uid: System.ServiceModel.Configuration.ServiceElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: ServiceElement
  nameWithType: ServiceElement.ServiceElement
- uid: System.ServiceModel.Configuration.ServiceElement.BehaviorConfiguration*
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: BehaviorConfiguration
  nameWithType: ServiceElement.BehaviorConfiguration
- uid: System.ServiceModel.Configuration.ServiceElement.Endpoints*
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: Endpoints
  nameWithType: ServiceElement.Endpoints
- uid: System.ServiceModel.Configuration.ServiceElement.Host*
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: Host
  nameWithType: ServiceElement.Host
- uid: System.ServiceModel.Configuration.ServiceElement.Name*
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: Name
  nameWithType: ServiceElement.Name
- uid: System.ServiceModel.Configuration.ServiceElement.Properties*
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: Properties
  nameWithType: ServiceElement.Properties
- uid: System.ServiceModel.Configuration.ServiceElement.Reset*
  parent: System.ServiceModel.Configuration.ServiceElement
  isExternal: false
  name: Reset
  nameWithType: ServiceElement.Reset
