### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute
  id: ManagementConfigurationAttribute
  children:
  - System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor
  - System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  - System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  langs:
  - csharp
  name: ManagementConfigurationAttribute
  nameWithType: ManagementConfigurationAttribute
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute
  type: Class
  summary: "Attributtet ManagementConfiguration angir at en egenskap eller felt representerer en skrivebeskyttet WMI-egenskap.       Obs! regnes nå WMI .NET-bibliotekene i endelig status, og ingen ytterligere development, forbedringer, eller oppdateringer er tilgjengelige for ikke-relaterte sikkerhetsproblemer som påvirker disse bibliotekene. Den [MI APIer](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx) skal brukes for alle nye utvikling."
  remarks: "Egenskapen eller feltet må være felles. Klassen som inneholder egenskapen må være merket med den <xref:System.Management.Instrumentation.ManagementEntityAttribute>attributtet.</xref:System.Management.Instrumentation.ManagementEntityAttribute>       Alle felt eller egenskaper i klassen som ikke er merket med denne eller en annen WMI-leverandøren utvidelser-attributtet kan ikke brukes."
  example:
  - "The following example shows how to use the ManagementConfiguration attribute to mark a property. This property is exposed to WMI.  \n  \n [C#]  \n  \n```  \n// Use the ManagementConfiguration attribute to specify that a property  \n// is a read/write property in the provider. Consumers will be  \n// able to get and set this property value through WMI.  \n[ManagementConfiguration]  \npublic double ReadableWritableProperty  \n{  \n    get { return this.propertyValue; }  \n    set { this.propertyValue = value; }  \n}  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, AllowMultiple=false)]

      public sealed class ManagementConfigurationAttribute : System.Management.Instrumentation.ManagementMemberAttribute
  inheritance:
  - System.Attribute
  - System.Management.Instrumentation.ManagementMemberAttribute
  implements: []
  inheritedMembers:
  - System.Management.Instrumentation.ManagementMemberAttribute.Name
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor
  id: '#ctor'
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  langs:
  - csharp
  name: ManagementConfigurationAttribute()
  nameWithType: ManagementConfigurationAttribute.ManagementConfigurationAttribute()
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.ManagementConfigurationAttribute()
  type: Constructor
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Initialiserer en ny forekomst av <xref:System.Management.ManagementConfigurationAttribute>klassen.</xref:System.Management.ManagementConfigurationAttribute> Dette er Standardkonstruktøren."
  syntax:
    content: public ManagementConfigurationAttribute ();
    parameters: []
  overload: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  id: Mode
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  langs:
  - csharp
  name: Mode
  nameWithType: ManagementConfigurationAttribute.Mode
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Henter eller angir modus for egenskapen, som angir om endringer brukes så snart som mulig eller når en commit-metoden."
  remarks: "Hvis det er en commit-metoden som er definert, er ansvarlig for å oppdatere alle skrivetilgang WMI egenskaper som bruker den <xref:System.Management.Instrumentation.ManagementConfigurationType>modus.</xref:System.Management.Instrumentation.ManagementConfigurationType> Det er identifisert av <xref:System.Management.Instrumentation.ManagementCommitAttribute>.</xref:System.Management.Instrumentation.ManagementCommitAttribute>"
  syntax:
    content: public System.Management.Instrumentation.ManagementConfigurationType Mode { get; set; }
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "Returnerer en <xref href=&quot;System.Management.Instrumentation.ManagementConfigurationType&quot;> </xref> som indikerer om egenskapen WMI bruker <xref href=&quot;System.Management.Instrumentation.ManagementConfigurationType&quot;> </xref> eller <xref href=&quot;System.Management.Instrumentation.ManagementConfigurationType&quot;> </xref> modus."
  overload: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  id: Schema
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  langs:
  - csharp
  name: Schema
  nameWithType: ManagementConfigurationAttribute.Schema
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Henter eller angir en verdi som definerer utdatatypen egenskapen som er merket med attributtet ManagementConfiguration skal returnere."
  remarks: "Hvis returnerte typen <xref:System.Object?displayProperty=fullName>, deretter utdataene skal behandles som en verdi av typen <xref:System.Object?displayProperty=fullName>.</xref:System.Object?displayProperty=fullName> </xref:System.Object?displayProperty=fullName>"
  syntax:
    content: public Type Schema { get; set; }
    return:
      type: System.Type
      description: "En <xref:System.Type>verdien som representerer utdatatypen egenskapen merket med attributtet ManagementConfiguration tilbakestiller.</xref:System.Type>"
  overload: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Management.Instrumentation.ManagementMemberAttribute
  isExternal: false
  name: System.Management.Instrumentation.ManagementMemberAttribute
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: ManagementConfigurationAttribute()
  nameWithType: ManagementConfigurationAttribute.ManagementConfigurationAttribute()
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.ManagementConfigurationAttribute()
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Mode
  nameWithType: ManagementConfigurationAttribute.Mode
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
- uid: System.Management.Instrumentation.ManagementConfigurationType
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Schema
  nameWithType: ManagementConfigurationAttribute.Schema
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor*
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: ManagementConfigurationAttribute
  nameWithType: ManagementConfigurationAttribute.ManagementConfigurationAttribute
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode*
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Mode
  nameWithType: ManagementConfigurationAttribute.Mode
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema*
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Schema
  nameWithType: ManagementConfigurationAttribute.Schema
