### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  id: ConfigurationBasedIssuerNameRegistry
  children:
  - System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.#ctor
  - System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(System.String,System.String)
  - System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  - System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName(System.IdentityModel.Tokens.SecurityToken)
  - System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(System.Xml.XmlNodeList)
  langs:
  - csharp
  name: ConfigurationBasedIssuerNameRegistry
  nameWithType: ConfigurationBasedIssuerNameRegistry
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  type: Class
  summary: "Representerer en utsteder navnet registret som inneholder en liste over godkjente leverandører er lastet inn fra elementer i programmets konfigurasjonsfil som knytter hver utstedernavn X.509-sertifikatet som trengs for å verifisere filens signatur med token fra utstederen."
  remarks: "The ConfigurationBasedIssuerNameRegistry class maintains a dictionary of trusted issuers by mapping the certificate of each trusted issuer to a name that refers to that issuer. The certificates are specified using the ASN.1 encoded form of the thumbprint. The issuer name can be any string, as long as it is unique within the scope of the application. This dictionary can be accessed through the <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers%2A> property. The class can only resolve X.509 certificates.  \n  \n The map of trusted issuers is specified in a configuration file by adding entries under the [\\&lt;trustedIssuers\\&gt;](../Topic/%3CtrustedIssuers%3E.md) element. The `<trustedIssuers>` element is a child element of the [\\&lt;issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) element and it is valid when the ConfigurationBasedIssuerNameRegistry class is specified in the `type` attribute of that element. For more information, see the documentation for each of these elements in the [WIF Configuration Schema](~/add/includes/ajax-current-ext-md.md). For more information about issuer name registries, see the <xref:System.IdentityModel.Tokens.IssuerNameRegistry> class.  \n  \n You can derive from ConfigurationBasedIssuerNameRegistry to implement your own configuration based issuer name registry. Which methods you override will depend upon your implementation. For example, you can override the <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration%2A> method to load configuration from a custom configuration schema."
  example:
  - "The following XML shows configuration for a ConfigurationBasedIssuerNameRegistry added for a collection of security token handlers. The `<trustedIssuers>` element behaves like a classic .NET configuration collection, allowing the `<add>`, `<delete>` and `<clear>` elements as child elements.  \n  \n```  \n<system.identityModel>  \n  <identityConfiguration>  \n    <securityTokenHandlersCollection>  \n      <securityTokenHandlerConfiguration>  \n        <issuerNameRegistry type=\"System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry, System.IdentityModel\">  \n          <trustedIssuers>  \n             <add thumbprint=\"97249e … 158de\" name=\"contoso.com\" />  \n         </trustedIssuers>  \n        </issuerNameRegistry>  \n      </securityTokenHandlerConfiguration>  \n  </identityConfiguration>  \n</system.identityModel>  \n```"
  syntax:
    content: 'public class ConfigurationBasedIssuerNameRegistry : System.IdentityModel.Tokens.IssuerNameRegistry'
  inheritance:
  - System.Object
  - System.IdentityModel.Tokens.IssuerNameRegistry
  implements: []
  inheritedMembers:
  - System.IdentityModel.Tokens.IssuerNameRegistry.GetIssuerName(System.IdentityModel.Tokens.SecurityToken,System.String)
  - System.IdentityModel.Tokens.IssuerNameRegistry.GetWindowsIssuerName
  platform:
  - net462
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  langs:
  - csharp
  name: ConfigurationBasedIssuerNameRegistry()
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfigurationBasedIssuerNameRegistry()
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfigurationBasedIssuerNameRegistry()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Tokens
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry&quot;> </xref> klasse."
  syntax:
    content: public ConfigurationBasedIssuerNameRegistry ();
    parameters: []
  overload: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(System.String,System.String)
  id: AddTrustedIssuer(System.String,System.String)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  langs:
  - csharp
  name: AddTrustedIssuer(String,String)
  nameWithType: ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(String,String)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(String,String)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Tokens
  summary: "Legger til en utsteder liste over godkjente leverandører."
  remarks: "Du kan kalle denne metoden for å legge til malutstedere til den <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers%2A>ordlisten.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers%2A> I avledede klasser, kan du kalle denne metoden fra den <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration%2A>metode for å legge til malutstedere i ordlisten.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration%2A>"
  syntax:
    content: public void AddTrustedIssuer (string certificateThumbprint, string name);
    parameters:
    - id: certificateThumbprint
      type: System.String
      description: "ASN.1 kodet form av den utsteder sertifikatavtrykk."
    - id: name
      type: System.String
      description: "Navnet på utstederen."
  overload: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>certificateThumbprint</code>er <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> eller tom.       -or-       <code>name</code> is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref> or empty."
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "Utsteder angitt av <code> certificateThumbprint </code> er allerede konfigurert. (Utstederen finnes allerede i den <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*>ordlisten.)</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*>"
  platform:
  - net462
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  id: ConfiguredTrustedIssuers
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  langs:
  - csharp
  name: ConfiguredTrustedIssuers
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Tokens
  summary: "Henter liste over godkjente leverandører som er konfigurert for denne forekomsten."
  remarks: "Nøkkelen i ordlisten er ASN.1 kodet form av avtrykk for det klarerte utsteder sertifikatet og verdien er navnet på utsteder. Ordlisten inneholder malutstedere som ble angitt i konfigurasjonen og ekstra malutstedere som har blitt lagt til med den <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer%2A>metoden.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer%2A>"
  syntax:
    content: public System.Collections.Generic.IDictionary<string,string> ConfiguredTrustedIssuers { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.String}
      description: "En liste som inneholder de klarerte malutstedere."
  overload: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName(System.IdentityModel.Tokens.SecurityToken)
  id: GetIssuerName(System.IdentityModel.Tokens.SecurityToken)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  langs:
  - csharp
  name: GetIssuerName(SecurityToken)
  nameWithType: ConfigurationBasedIssuerNameRegistry.GetIssuerName(SecurityToken)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName(SecurityToken)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Tokens
  summary: "Returnerer utstedernavn som er knyttet til den angitte <xref href=&quot;System.IdentityModel.Tokens.X509SecurityToken&quot;> </xref> ved å tilordne sertifikatavtrykket navnet i ordlisten klarerte malutstedere."
  remarks: "Standard implementering Søk i <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers%2A>ordliste for avtrykk for det X.509-sertifikatet som er angitt i `securityToken`.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers%2A> Hvis en oppføring er funnet, returneres utstedernavn; Ellers `null` returneres. Hvis `securityToken` kan ikke tilordnes fra <xref:System.IdentityModel.Tokens.X509SecurityToken>, `null` returneres.</xref:System.IdentityModel.Tokens.X509SecurityToken>"
  syntax:
    content: public override string GetIssuerName (System.IdentityModel.Tokens.SecurityToken securityToken);
    parameters:
    - id: securityToken
      type: System.IdentityModel.Tokens.SecurityToken
      description: "Sikkerhetstokenet navnet utsteder forespørres. Skal tilordnes som <xref href=&quot;System.IdentityModel.Tokens.X509SecurityToken&quot;> </xref>."
    return:
      type: System.String
      description: "Utstedernavn Hvis en oppføring for sertifikatavtrykket for tokenet finnes i den <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*>ordlisten; ellers <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*>"
  overload: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>securityToken</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(System.Xml.XmlNodeList)
  id: LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  langs:
  - csharp
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(XmlNodeList)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Tokens
  summary: "Laster inn klarerte malutstedere fra konfigurasjonen."
  remarks: "The LoadCustomConfiguration method is called by the configuration infrastructure. When this method is called, the `nodelist` will contain the top-level child elements of the [\\&lt;issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) element from the configuration file. Each of these may, in turn, contain attributes or child elements depending on the configuration schema you define for your derived class.  \n  \n This method is called by the configuration infrastructure. The default implementation loads configuration from a [\\&lt;trustedIssuers\\&gt;](../Topic/%3CtrustedIssuers%3E.md) element (configured under the [\\&lt;issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) element). You can override this method to provide support for your own custom configuration elements in derived classes."
  syntax:
    content: public override void LoadCustomConfiguration (System.Xml.XmlNodeList customConfiguration);
    parameters:
    - id: customConfiguration
      type: System.Xml.XmlNodeList
      description: "XML-filen som representerer kartet over godkjente leverandører som er angitt i konfigurasjonsfilen."
  overload: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>customConfiguration</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "Konfigurasjonen inneholder ett eller flere elementer som ikke gjenkjennes."
  platform:
  - net462
references:
- uid: System.IdentityModel.Tokens.IssuerNameRegistry
  isExternal: false
  name: System.IdentityModel.Tokens.IssuerNameRegistry
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.InvalidOperationException
  isExternal: true
  name: System.InvalidOperationException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.#ctor
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: ConfigurationBasedIssuerNameRegistry()
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfigurationBasedIssuerNameRegistry()
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfigurationBasedIssuerNameRegistry()
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(System.String,System.String)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: AddTrustedIssuer(String,String)
  nameWithType: ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(String,String)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: ConfiguredTrustedIssuers
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
- uid: System.Collections.Generic.IDictionary{System.String,System.String}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<String,String>
  nameWithType: IDictionary<String,String>
  fullName: System.Collections.Generic.IDictionary<System.String,System.String>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary<System.String,System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName(System.IdentityModel.Tokens.SecurityToken)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: GetIssuerName(SecurityToken)
  nameWithType: ConfigurationBasedIssuerNameRegistry.GetIssuerName(SecurityToken)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName(SecurityToken)
- uid: System.IdentityModel.Tokens.SecurityToken
  parent: System.IdentityModel.Tokens
  isExternal: false
  name: SecurityToken
  nameWithType: SecurityToken
  fullName: System.IdentityModel.Tokens.SecurityToken
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration(XmlNodeList)
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.#ctor*
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: ConfigurationBasedIssuerNameRegistry
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfigurationBasedIssuerNameRegistry
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer*
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: AddTrustedIssuer
  nameWithType: ConfigurationBasedIssuerNameRegistry.AddTrustedIssuer
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers*
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: ConfiguredTrustedIssuers
  nameWithType: ConfigurationBasedIssuerNameRegistry.ConfiguredTrustedIssuers
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.GetIssuerName*
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: GetIssuerName
  nameWithType: ConfigurationBasedIssuerNameRegistry.GetIssuerName
- uid: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration*
  parent: System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry
  isExternal: false
  name: LoadCustomConfiguration
  nameWithType: ConfigurationBasedIssuerNameRegistry.LoadCustomConfiguration
