### YamlMime:ManagedReference
items:
- uid: System.Data.Services.IDataServiceConfiguration
  id: IDataServiceConfiguration
  children:
  - System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  - System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  - System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  - System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  - System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  - System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  - System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  - System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  - System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  - System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  langs:
  - csharp
  name: IDataServiceConfiguration
  nameWithType: IDataServiceConfiguration
  fullName: System.Data.Services.IDataServiceConfiguration
  type: Interface
  summary: "IDataServiceConfiguration brukes av [!INCLUDE[ssAstoria](~/add/includes/ssastoria-md.md)] å konfigurere virkemåten for tjenesten, inkludert rettigheter på enheten sett og operasjoner, begrenser for tillatte forespørsler, registrerer typer er ikke synlig som standard, og standard detaljnivået på feilbehandling."
  remarks: "Denne typen brukes av <xref:System.Data.Services.DataService%601>klasser til å konfigurere tjenesten ved å implementere en statisk metode navnet InitializeService, returnere void, og ta ett enkelt argument av typen IDataServiceConfiguration.</xref:System.Data.Services.DataService%601> Konfigurasjonsobjektet kan bare brukes under kall til initialisering av tjenesten."
  syntax:
    content: public interface IDataServiceConfiguration
  implements: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  id: MaxBatchCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Henter maksimalt antall forespørsler som kan behandles i en bunke."
  syntax:
    content: public int MaxBatchCount { get; set; }
    return:
      type: System.Int32
      description: "Heltallsverdi som angir maksimalt antall forespørsler som kan behandles i en bunke."
  overload: System.Data.Services.IDataServiceConfiguration.MaxBatchCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  id: MaxChangesetCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Henter maksimalt antall endringssettene som kan behandles i en bunke."
  syntax:
    content: public int MaxChangesetCount { get; set; }
    return:
      type: System.Int32
      description: "Heltallsverdi som angir det maksimale antallet endringssettene som kan behandles i en bunke."
  overload: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  id: MaxExpandCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Henter eller angir maksimalt antall segmenter som kan ekspanderes av $Vis spørre alternativet for alle forespørsler til vertstjenesten."
  remarks: "Hvis grensen overskrides, returneres en statuskode for 400 Ugyldig forespørsel. Den angitte verdien må være mellom 0 og `int.MaxValue`; ellers en `ArgumentOutOfRangeException` er et.       Følgende spørring streng eksemplet har to segmenter:"
  syntax:
    content: public int MaxExpandCount { get; set; }
    return:
      type: System.Int32
      description: "Maksimalt antall segmenter skal utvides."
  overload: System.Data.Services.IDataServiceConfiguration.MaxExpandCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  id: MaxExpandDepth
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Henter eller angir maksimalt antall segmenter som støttes i én `$expand` bane for alle forespørsler til vertstjenesten."
  remarks: "Hvis grensen overskrides, returneres en statuskode for 400 Ugyldig forespørsel. Den angitte verdien må være mellom 0 og `int.MaxValue`; ellers en `ArgumentOutOfRangeException` er et.       Følgende spørring strengen eksemplet har to segmenter i først `$expand` banen og én i andre `$expand` banen:"
  syntax:
    content: public int MaxExpandDepth { get; set; }
    return:
      type: System.Int32
      description: "Heltallet som representerer det maksimale antallet støttede segmenter i `$expand` banen."
  overload: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  id: MaxObjectCountOnInsert
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Henter eller angir maksimalt antall objekter som kan settes inn i en enkelt forespørsel."
  syntax:
    content: public int MaxObjectCountOnInsert { get; set; }
    return:
      type: System.Int32
      description: "Heltallsverdi som inneholder maksimalt antall objekter som kan settes inn i en enkelt forespørsel."
  overload: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  id: MaxResultsPerCollection
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Henter maksimalt antall resultater per samling."
  syntax:
    content: public int MaxResultsPerCollection { get; set; }
    return:
      type: System.Int32
      description: "Heltallsverdi som angir det maksimale antallet resultater per samling."
  overload: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  id: RegisterKnownType(System.Type)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: RegisterKnownType(Type)
  nameWithType: IDataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(Type)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Registrerer en ressurstype for bruk av datatjenesten."
  syntax:
    content: public void RegisterKnownType (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Ressurstypen for å registrere."
  overload: System.Data.Services.IDataServiceConfiguration.RegisterKnownType*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  id: SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Angir tilgangsregler for den angitte enheten angitt."
  remarks: "Standardkonfigurasjonen er å nekte tilgang til ressurser. Tilgangsrettighetene må aktiveres når en tjeneste er initialisert."
  syntax:
    content: public void SetEntitySetAccessRule (string name, System.Data.Services.EntitySetRights rights);
    parameters:
    - id: name
      type: System.String
      description: "Navnet på enheten som er angitt for konfigurerte tilgang."
    - id: rights
      type: System.Data.Services.EntitySetRights
      description: "Rettigheter som er tillatt for enheten definert."
  overload: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  id: SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Angir tilgangsregler for den angitte operasjonen."
  remarks: "Standardkonfigurasjonen er å nekte tilgang til ressurser. Når en tjeneste er initialisert, må være aktivert tilgangsrettigheter."
  syntax:
    content: public void SetServiceOperationAccessRule (string name, System.Data.Services.ServiceOperationRights rights);
    parameters:
    - id: name
      type: System.String
      description: "Navnet på tjenesteoperasjon som du vil angi tilgangsrettigheter."
    - id: rights
      type: System.Data.Services.ServiceOperationRights
      description: "Rettigheter som er tillatt i henhold til <xref href=&quot;System.Data.Services.ServiceOperationRights&quot;> </xref> opplisting."
  overload: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  id: UseVerboseErrors
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Henter eller angir om detaljert feil brukes som standard for alle svar fra vertstjenesten."
  remarks: "Ugyldig svar fra en angitt forespørsel kan overstyres av data service-utvikler ved å overstyre den `HandleException` metoden. Detaljert feil kan bare aktiveres under utvikling ikke i produksjonsmiljøer av sikkerhetsgrunner."
  syntax:
    content: public bool UseVerboseErrors { get; set; }
    return:
      type: System.Boolean
      description: "En boolsk verdi som angir om detaljert feil returneres."
  overload: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: RegisterKnownType(Type)
  nameWithType: IDataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Services.EntitySetRights
  parent: System.Data.Services
  isExternal: false
  name: EntitySetRights
  nameWithType: EntitySetRights
  fullName: System.Data.Services.EntitySetRights
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
- uid: System.Data.Services.ServiceOperationRights
  parent: System.Data.Services
  isExternal: false
  name: ServiceOperationRights
  nameWithType: ServiceOperationRights
  fullName: System.Data.Services.ServiceOperationRights
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: RegisterKnownType
  nameWithType: IDataServiceConfiguration.RegisterKnownType
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
