### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs
  id: DeploymentProgressChangedEventArgs
  children:
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  langs:
  - csharp
  name: DeploymentProgressChangedEventArgs
  nameWithType: DeploymentProgressChangedEventArgs
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs
  type: Class
  summary: "Representerer pågår data som er rapportert i en asynkron operasjon."
  remarks: "Denne klassen inneholder egenskaper som beskriver fremdrift for den <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, og <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>hendelser.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> Ikke alle egenskapene i denne klassen gjelder for hver hendelse.       <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted%2A>og <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal%2A>representerer Totalt antall byte ned til datoen og totalt antall byte i nedlastingen, henholdsvis; de gjelder for alle tre hendelser.</xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal%2A></xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted%2A> <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.Group%2A>navngir filgruppen som svarer til gjeldende <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>hendelse, og <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.State%2A>gjenspeiler gjeldende trinn i nedlastingen.</xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.State%2A> </xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged></xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.Group%2A>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/t-system.deployment.appl_5_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: 'public class DeploymentProgressChangedEventArgs : System.ComponentModel.ProgressChangedEventArgs'
  inheritance:
  - System.ComponentModel.ProgressChangedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  id: BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter antall byte som allerede har lastet ned i denne operasjonen."
  remarks: "For <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, egenskapen BytesCompleted refererer til nedlasting av distribusjon manifestet.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> For <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, egenskapen refererer til fremdrift for nedlasting av hele oppdateringen, inkludert filer programmanifest, samlinger og data.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> For <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, egenskapen refererer til fremdrift for nedlasting av hele settet med filer som er en del av gruppen navngitt.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/c5260b60-c259-429d-9763-_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public long BytesCompleted { get; }
    return:
      type: System.Int64
      description: "En <xref:System.Int64>som representerer dataene allerede overført, i byte.</xref:System.Int64>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  id: BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter Totalt antall byte i nedlastingen."
  remarks: "For <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, egenskapen BytesTotal refererer til nedlasting av distribusjon manifestet.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> For <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, egenskapen refererer til fremdrift for nedlasting av hele oppdateringen, inkludert filer programmanifest, samlinger og data.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> For <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, egenskapen refererer til fremdrift for nedlasting av hele settet med filer som er en del av gruppen navngitt.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_3_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public long BytesTotal { get; }
    return:
      type: System.Int64
      description: "En <xref:System.Int64>som representerer den totale størrelsen på nedlastingen, i byte.</xref:System.Int64>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  id: Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter navnet på filgruppen lastes ned."
  remarks: "Du kan starte flere kall til <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A>og Last ned flere filgrupper samtidig.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A> Bruk gruppen for å finne ut hvilke hendelsen tilbakeringinger samsvarer med hvilken gruppe."
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_4_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public string Group { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som inneholder navnet på filgruppen Hvis hendelsen oppstod som et resultat av et kall til <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync*>; Hvis ikke returneres en tom streng.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync*> </xref:System.String>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  id: State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter handlingen som utføres for øyeblikket prosessen."
  remarks: ''
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_11_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public System.Deployment.Application.DeploymentProgressState State { get; }
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "En <xref href=&quot;System.Deployment.Application.DeploymentProgressState&quot;> </xref> verdi som angir hvilken elementet eller elementer operasjonen laster ned."
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.State*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.ProgressChangedEventArgs
  isExternal: false
  name: System.ComponentModel.ProgressChangedEventArgs
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
