### YamlMime:ManagedReference
items:
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute
  id: SettingsAllowAnonymousAttribute
  children:
  - System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  - System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  - System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  langs:
  - csharp
  name: SettingsAllowAnonymousAttribute
  nameWithType: SettingsAllowAnonymousAttribute
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute
  type: Class
  summary: "Angir om en profilegenskap kan angis eller tilgang til for en anonym bruker."
  remarks: "Klassen SettingsAllowAnonymousAttribute brukes til å finne ut om du kan få tilgang til en egenskap for en egendefinert profil implementering Hvis brukeren er en anonym bruker. Se dokumentasjonen for konfigurasjonselementet for informasjon om hvordan du aktiverer anonym identifisering.       Hvis ingen SettingsAllowAnonymousAttribute er angitt for en profilegenskap, tillates ikke anonym tilgang for profilegenskapen.       En egendefinert profil implementering er klassen som arver fra den <xref:System.Web.Profile.ProfileBase>abstrakt klasse og definerer egenskaper for brukerprofilen som ikke er angitt i konfigurasjonselementet.</xref:System.Web.Profile.ProfileBase> Du kan angi en egendefinert brukerprofil type i programmets Web.config-filen med det `inherits` for konfigurasjonselementet som vist i eksemplet nedenfor.       `<configuration>`       `<connectionStrings>`       `<add`       `name=&quot;SqlServices&quot;`       `connectionString=&quot;Data Source=localhost;Integrated Security=SSPI;Initial Catalog=aspnetdb;&quot; />`       `</connectionStrings>`       `<system.web>`       `<authentication mode=&quot;Forms&quot; >`       `<forms`       `loginUrl=&quot;login.aspx&quot;`       `name=&quot;.ASPXFORMSAUTH&quot; />`       `</authentication>`       `<authorization>`       `<deny users=&quot;?&quot; />`       `</authorization>`       `<profile inherits=&quot;Samples.AspNet.Profile.EmployeeProfile&quot;`       `defaultProvider=&quot;SqlProvider&quot;>`       `<providers>`       `<clear />`       `<add`       `name=&quot;SqlProvider&quot;`       `type=&quot;System.Web.Profile.SqlProfileProvider&quot;`       `connectionStringName=&quot;SqlServices&quot;`       `description=&quot;SQL Profile Provider for Sample&quot;/>`       `<add`       `name=&quot;EmployeeInfoProvider&quot;`       `type=&quot;System.Web.Profile.SqlProfileProvider&quot;`       `connectionStringName=&quot;SqlServices&quot;`       `description=&quot;SQL Profile Provider for Employee Info&quot;/>`       `</providers>`       `<properties>`       `<add name=&quot;GarmentSize&quot; />`       `</properties>`       `</profile>`       `</system.web>`       `</configuration>`"
  example:
  - "The following code example defines a class that inherits from the <xref:System.Web.Profile.ProfileBase> to create a custom profile. The type of the custom profile is specified in the `inherits` attribute of the  configuration element in the Web.config file for an application.  \n  \n [!code-cs[System.Web.Profile.ProfileBase#1](~/add/codesnippet/csharp/t-system.web.profile.set_1.cs)]\n [!code-vb[System.Web.Profile.ProfileBase#1](~/add/codesnippet/visualbasic/t-system.web.profile.set_1.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsAllowAnonymousAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: SettingsAllowAnonymousAttribute(Boolean)
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "Oppretter en ny forekomst av den <xref href=&quot;System.Web.Profile.SettingsAllowAnonymousAttribute&quot;> </xref> klasse og angir om anonym tilgang til den tilknyttede profilegenskapen."
  remarks: "Den <xref:System.Web.Profile.SettingsAllowAnonymousAttribute>klassen brukes til å finne ut om du kan få tilgang til en egenskap for en egendefinert profil implementering Hvis brukeren er en anonym bruker.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute> For informasjon om hvordan du aktiverer anonym identifisering, kan du se konfigurasjonselementet.       Hvis ingen <xref:System.Web.Profile.SettingsAllowAnonymousAttribute>er angitt for en profilegenskap, anonym tilgang til profilegenskapen ikke er tillatt.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute>       En egendefinert profil implementering er klassen som arver fra den <xref:System.Web.Profile.ProfileBase>abstrakt klasse og definerer egenskaper for brukerprofilen som ikke er angitt i konfigurasjonselementet.</xref:System.Web.Profile.ProfileBase>"
  example:
  - "The following example defines a class that inherits from the <xref:System.Web.Profile.ProfileBase> class to create a custom profile. The type of the custom profile is specified in the `inherits` attribute of the  configuration element in the Web.config file for an application. For an example of a configuration file that specifies a custom profile implementation, see the <xref:System.Web.Profile.SettingsAllowAnonymousAttribute> class overview.  \n  \n [!code-cs[System.Web.Profile.ProfileBase#1](~/add/codesnippet/csharp/m-system.web.profile.set_1.cs)]\n [!code-vb[System.Web.Profile.ProfileBase#1](~/add/codesnippet/visualbasic/m-system.web.profile.set_1.vb)]"
  syntax:
    content: public SettingsAllowAnonymousAttribute (bool allow);
    parameters:
    - id: allow
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis anonyme brukere får tilgang til den tilknyttede profilegenskapen; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  id: Allow
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "Henter en verdi som angir om den tilknyttede egenskapen for en egendefinert profil implementering kan åpnes hvis brukeren er en anonym bruker."
  syntax:
    content: public bool Allow { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis anonyme brukere får tilgang til den tilknyttede profilegenskapen; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  id: IsDefaultAttribute
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: IsDefaultAttribute()
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "Henter en verdi som angir om den <xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>egenskapen er satt til standardverdien.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>"
  syntax:
    content: public override bool IsDefaultAttribute ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis den <xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>egenskapen er satt til standardverdi; ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>"
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: SettingsAllowAnonymousAttribute(Boolean)
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: IsDefaultAttribute()
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute()
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: SettingsAllowAnonymousAttribute
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: IsDefaultAttribute
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute
