### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs
  id: CreatingCookieEventArgs
  children:
  - System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  - System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  - System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  - System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  - System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  langs:
  - csharp
  name: CreatingCookieEventArgs
  nameWithType: CreatingCookieEventArgs
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs
  type: Class
  summary: "Gir dataene for den <xref href=&quot;System.Web.ApplicationServices.AuthenticationService.CreatingCookie&quot;> </xref> hendelsen."
  remarks: "Klassen CreatingCookieEventArgs leverer verdier noen <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>hendelsesbehandlingen.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> Ved hjelp av egenskapene for denne klassen, kan du hente brukerlegitimasjon når du oppretter en egendefinert godkjenning informasjonskapsel.       Den <xref:System.Web.ApplicationServices.AuthenticationService>klasse hever den <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>-hendelse når den angir informasjonskapselen for godkjenning etter brukerlegitimasjonen som er godkjent.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService> Den <xref:System.Web.ApplicationServices.AuthenticationService>bygger et CreatingCookieEventArgs objekt og sendes til noen <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>hendelsesbehandlingen.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService>       Du hente brukerlegitimasjonen via <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.UserName%2A> <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.Password%2A>, og <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A>Egenskaper.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> </xref:System.Web.ApplicationServices.CreatingCookieEventArgs.Password%2A></xref:System.Web.ApplicationServices.CreatingCookieEventArgs.UserName%2A> Den <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A>egenskapen kan inneholde egendefinerte verdier du trenger for å godkjenne, for eksempel en ID-nummer.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> Den <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent%2A>egenskapen angir om informasjonskapsler for godkjenning skal beholdes forbi gjeldende økt.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent%2A> Angi den <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A>egenskapen `true` Hvis du oppretter informasjonskapselen for godkjenning slik at den <xref:System.Web.ApplicationServices.AuthenticationService>klassen ikke opprette informasjonskapselen.</xref:System.Web.ApplicationServices.AuthenticationService> </xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the CreatingCookieEventArgs object to customize the authentication cookie. The handler saves the value from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> property in the authentication ticket and sets the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A> property to `true` to indicate that the authentication cookie has been created.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/t-system.web.application_1_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/t-system.web.application_1_1.asax)]"
  syntax:
    content: 'public class CreatingCookieEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  id: CookieIsSet
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter eller angir en verdi som angir om informasjonskapsler for godkjenning har blitt opprettet."
  remarks: "Den <xref:System.Web.ApplicationServices.AuthenticationService>klassen kontrollerer CookieIsSet-egenskapen for å fastslå om informasjonskapselen for godkjenning har blitt opprettet.</xref:System.Web.ApplicationServices.AuthenticationService> Du setter denne verdien til `true` Hvis du oppretter en informasjonskapsel for godkjenning i hendelsesbehandling for den <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>hendelsen.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> Hvis CookieIsSet er satt til `false` (standardverdien) i <xref:System.Web.ApplicationServices.AuthenticationService>klassen oppretter en informasjonskapsel for godkjenning, dette overskriver informasjonskapsel som du har opprettet i et behandlingsprogram for den <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>hendelsen.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object to customize the authentication cookie. The CookieIsSet property is set to `true` after the authentication ticket is created.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_11_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_11_1.asax)]"
  syntax:
    content: public bool CookieIsSet { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis godkjenning informasjonskapselen ble opprettet. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  id: CustomCredential
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter godkjenning med flere verdier som er oppgitt av brukeren."
  remarks: "Du kan bruke egenskapen CustomCredential ikke hente egendefinerte verdier i godkjenningsbillett. Egenskapen CustomCredential inneholder verdien som er sendt til den <xref:System.Web.ApplicationServices.AuthenticationService.Login%2A>metoden.</xref:System.Web.ApplicationServices.AuthenticationService.Login%2A> Denne egenskapen brukes til å sende tilpassede verdier må valideres med brukernavn og passord, for eksempel en ID-nummer. Hvis mer enn én verdi er lagret i egenskapen, må du analysere CustomCredential-egenskapen for å hente verdier."
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object in order to customize the authentication cookie. The value passed in the CustomCredential property is stored in the <xref:System.Web.Security.FormsAuthenticationTicket.UserData%2A> property of the forms authentication ticket.  \n  \n> [!NOTE]\n>  Store the CustomCredential property in a cookie only when you know that the data in the property is not sensitive. Malicious users can access the values in the cookie.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_2_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_2_1.asax)]"
  syntax:
    content: public string CustomCredential { get; }
    return:
      type: System.String
      description: "De egendefinerte verdiene som kreves for godkjenning enn brukernavn og passord."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  id: IsPersistent
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter en verdi som angir om informasjonskapsler for godkjenning skal beholdes utenfor økten."
  remarks: "Når du oppretter en <xref:System.Web.Security.FormsAuthenticationTicket>objektet, kan du bruke egenskapen IsPersistent til å angi om godkjenning informasjonskapselen er beholdt utenfor økten.</xref:System.Web.Security.FormsAuthenticationTicket>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object in order to customize the authentication cookie. The <xref:System.Web.Security.FormsAuthenticationTicket.IsPersistent%2A> property of the <xref:System.Web.Security.FormsAuthenticationTicket> object is set to the value in the IsPersistent property.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_0_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_0_1.asax)]"
  syntax:
    content: public bool IsPersistent { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis informasjonskapselen skal beholdes utover den gjeldende økten; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  id: Password
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter passordet for brukeren."
  remarks: "Du kan bruke passordegenskapen til å hente passordet når du angir egendefinerte verdier i godkjenningsbillett.      > [!NOTE] > Ikke lagre verdien for egenskapen passord i godkjenningsbillett. En bruker med onde hensikter kan få tilgang til informasjonskapselen og hente passordet selv om informasjonskapselen er kryptert."
  syntax:
    content: public string Password { get; }
    return:
      type: System.String
      description: "Passordet som er oppgitt av brukeren for godkjenning."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.Password*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  id: UserName
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter navnet for brukeren."
  remarks: "Du kan bruke UserName-egenskapen til å hente navnet på godkjenning når du angir egendefinerte verdier i godkjenningsbillett. Vanligvis angir du den <xref:System.Web.Security.FormsAuthenticationTicket.Name%2A>for den <xref:System.Web.Security.FormsAuthenticationTicket>objekt verdien brukernavn.</xref:System.Web.Security.FormsAuthenticationTicket> </xref:System.Web.Security.FormsAuthenticationTicket.Name%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object to customize the authentication cookie. The <xref:System.Web.Security.FormsAuthenticationTicket.Name%2A> property is set to the values of the UserName property.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_6_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_6_1.asax)]"
  syntax:
    content: public string UserName { get; }
    return:
      type: System.String
      description: "Navnet som er oppgitt av brukeren for godkjenning."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
