### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.OutputCacheSettingsSection
  id: OutputCacheSettingsSection
  children:
  - System.Web.Configuration.OutputCacheSettingsSection.#ctor
  - System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  - System.Web.Configuration.OutputCacheSettingsSection.Properties
  langs:
  - csharp
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection
  fullName: System.Web.Configuration.OutputCacheSettingsSection
  type: Class
  summary: "Konfigurerer du innstillinger for utdatabuffer for programsider. Denne klassen kan ikke arves."
  remarks: "Klassen OutputCacheSettingsSection gjør det mulig å programmatisk tilgang til og endre den `outputCacheSettings` element av den `caching` delen i en konfigurasjonsfil. Innstillingene for utdatabuffer definerer avhengighetene (relasjoner mellom elementer som er lagret i hurtigbufferen og filer, hurtigbufferen nøkler, eller <xref:System.Web.Caching.CacheDependency>objekter) som er brukt i bufring av utdata for forekomsten av den [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) direktivet eller <xref:System.Web.Configuration.OutputCacheProfile>.</xref:System.Web.Configuration.OutputCacheProfile> </xref:System.Web.Caching.CacheDependency>      > [!NOTE] > For OutputCacheSettingsSection kan skrive informasjon til delen relaterte konfigurasjonsfilen i henhold til begrensningene som er definert av den delen egenskapen <xref:System.Configuration.SectionInformation.AllowDefinition%2A>der verdien er <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A> Forsøk på å skrive til konfigurasjonsfilen på et nivå ikke tillatt i hierarkiet vil føre til en feilmelding som er generert av parseren. Du kan imidlertid bruke denne klassen kan lese konfigurasjonsinformasjon under noen nivå i hierarkiet."
  example:
  - "The following code example shows how to obtain the OutputCacheSettingsSection object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.OutputCacheSettingsSection#1](~/add/codesnippet/csharp/t-system.web.configurati_9_1.cs)]\n [!code-vb[System.Web.Configuration.OutputCacheSettingsSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_9_1.vb)]"
  syntax:
    content: 'public sealed class OutputCacheSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: OutputCacheSettingsSection()
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection()
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheSettingsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.OutputCacheSettingsSection&quot;> </xref> klasse."
  remarks: "Konstruktøren OutputCacheSettingsSection skal ikke brukes direkte fra koden. Kalles av ASP.NET Konfigurasjonssystemet. Du hente en forekomst av den <xref:System.Web.Configuration.OutputCacheSettingsSection>klassen ved hjelp av den <xref:System.Configuration.Configuration.GetSection%2A>metoden.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.OutputCacheSettingsSection>"
  syntax:
    content: public OutputCacheSettingsSection ();
    parameters: []
  overload: System.Web.Configuration.OutputCacheSettingsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  id: OutputCacheProfiles
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a <xref href=&quot;System.Web.Configuration.OutputCacheProfileCollection&quot;></xref>."
  remarks: "Egenskapen OutputCacheProfiles gjør at du programmatisk tilgang av `outputCacheProfiles` element i en konfigurasjonsfil. Du kan bruke OutputCacheProfiles-egenskapen til å endre den `outputCacheProfiles` elementet programmatisk.       Den `outputCacheProfiles` delen inneholder <xref:System.Web.Configuration.OutputCacheProfile>innstillinger som kan brukes av sider i programmet for objekter som representerer output-hurtigbuffer.</xref:System.Web.Configuration.OutputCacheProfile>  Disse innstillingene kan brukes på en side ved å angi den `CacheProfile` for den [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) direktivet. Bruke profilen på kontroll hurtigbufring attributter som avhengigheter, hurtigbufferplasseringen og hurtigbufferen tidspunktet for utløp.       Den [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) direktivet kan overstyre alle innstillingene som inneholder en <xref:System.Web.Configuration.OutputCacheProfile>bortsett fra de <xref:System.Web.Configuration.OutputCacheProfile.Enabled%2A>egenskapen.</xref:System.Web.Configuration.OutputCacheProfile.Enabled%2A> </xref:System.Web.Configuration.OutputCacheProfile> Dette er at du kan aktivere eller deaktivere den <xref:System.Web.Configuration.OutputCacheProfile>uten å endre instruksjonene for alle sidene som har overstyrt det.</xref:System.Web.Configuration.OutputCacheProfile>"
  example:
  - "The following code example shows how to use the OutputCacheProfiles property.  \n  \n [!code-cs[System.Web.Configuration.OutputCacheSettingsSection#3](~/add/codesnippet/csharp/p-system.web.configurati_105_1.cs)]\n [!code-vb[System.Web.Configuration.OutputCacheSettingsSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_105_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheProfileCollection OutputCacheProfiles { get; }
    return:
      type: System.Web.Configuration.OutputCacheProfileCollection
      description: "A <xref href=&quot;System.Web.Configuration.OutputCacheProfileCollection&quot;></xref> of <xref href=&quot;System.Web.Configuration.OutputCacheProfile&quot;></xref> objects"
  overload: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties
  id: Properties
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
  fullName: System.Web.Configuration.OutputCacheSettingsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Web.Configuration.OutputCacheSettingsSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheSettingsSection()
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection()
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheSettingsSection()
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
- uid: System.Web.Configuration.OutputCacheProfileCollection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheProfileCollection
  nameWithType: OutputCacheProfileCollection
  fullName: System.Web.Configuration.OutputCacheProfileCollection
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
  fullName: System.Web.Configuration.OutputCacheSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
