### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  id: BrowserCapabilitiesCodeGenerator
  children:
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  langs:
  - csharp
  name: BrowserCapabilitiesCodeGenerator
  nameWithType: BrowserCapabilitiesCodeGenerator
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  type: Class
  summary: "Klassen BrowserCapabilitiesCodeGenerator er brukt internt av den <xref uid=&quot;langword_csharp_aspnet_regbrowsers&quot; name=&quot;aspnet_regbrowsers&quot; href=&quot;&quot;> </xref> verktøyet til å analysere .browser leser filer, og Legg til nettlesere kjøretid-samlingen i kjente nettlesere som finnes i den <xref href=&quot;System.Web.Configuration.BrowserCapabilitiesFactory&quot;> </xref> objektet."
  remarks: "Denne klassen genererer kildekoden for en samling for den <xref:System.Web.Configuration.BrowserCapabilitiesFactory>klassen som produserer forespørsel-spesifikke ved kjøretid, <xref:System.Web.Configuration.HttpCapabilitiesBase>objekter på offentlig tilgang via ASP.NET indre `Request.Browser` egenskapen.</xref:System.Web.Configuration.HttpCapabilitiesBase> </xref:System.Web.Configuration.BrowserCapabilitiesFactory>"
  syntax:
    content: public class BrowserCapabilitiesCodeGenerator
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: BrowserCapabilitiesCodeGenerator()
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Internt brukes til å opprette en ny forekomst av <xref href=&quot;System.Web.Configuration.BrowserCapabilitiesCodeGenerator&quot;> </xref>."
  syntax:
    content: public BrowserCapabilitiesCodeGenerator ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  id: Create
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: Create()
  nameWithType: BrowserCapabilitiesCodeGenerator.Create()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Brukt internt koordinere virkemåten til denne klassen."
  remarks: "Denne metoden først går gjennom mappen &quot;Nettlesere&quot;. Kaller deretter <xref:System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles%2A>, som laster inn analyserer XML i en samling av nettleseren definisjon filer og setter inn informasjon der. i en intern samling med klientlesere.</xref:System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles%2A> Deretter kaller en intern metoden som genererer kilde kode kompilerer, og registrerer den som en samling i den globale samlingsbufferen bufre i den <xref:System.Web.Configuration.BrowserCapabilitiesFactory>objektet.</xref:System.Web.Configuration.BrowserCapabilitiesFactory> Hvis det er nødvendig, kaller denne metoden deretter en intern metode som starter nettserveren."
  syntax:
    content: public virtual void Create ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  id: ProcessBrowserFiles(System.Boolean,System.String)
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: ProcessBrowserFiles(Boolean,String)
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Laster inn og analyserer XML i en samling av nettleseren definisjon filer og setter inn informasjon der. i en intern samling med klientlesere."
  syntax:
    content: protected void ProcessBrowserFiles (bool useVirtualPath, string virtualDir);
    parameters:
    - id: useVirtualPath
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>du bruker en virtuell bane; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standard <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    - id: virtualDir
      type: System.String
      description: "Banen til den virtuelle mappen som inneholder filene nettleseren definisjonen. Standard er <xref:System.String>.</xref:System.String>"
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles*
  exceptions:
  - type: System.Web.HttpParseException
    commentId: T:System.Web.HttpParseException
    description: "One of the browser-definition files does not have a root element named \"browsers\".  \n  \n \\- or -  \n  \n One of the browser-definition files fails to load."
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  id: Uninstall
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: Uninstall()
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Fjerner nettleseren funksjoner fabrikken fra den globale samlingsbufferen og sletter den sterkt navn offentlige token nøkkelfilen."
  remarks: "Denne metoden starter webtjenesten. Nettleseren funksjoner fabrikken fjernes deretter fra den globale samlingsbufferen, og det sterkt navn offentlig key token fil er slettet. Webtjenesten deretter startes på nytt hvis avinstallere lykkes."
  syntax:
    content: public bool Uninstall ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis nettleseren funksjoner fabrikken er avinstallert fra den globale samlingsbufferen; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.HttpParseException
  parent: System.Web
  isExternal: false
  name: HttpParseException
  nameWithType: HttpParseException
  fullName: System.Web.HttpParseException
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: BrowserCapabilitiesCodeGenerator()
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Create()
  nameWithType: BrowserCapabilitiesCodeGenerator.Create()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: ProcessBrowserFiles(Boolean,String)
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Uninstall()
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: BrowserCapabilitiesCodeGenerator
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Create
  nameWithType: BrowserCapabilitiesCodeGenerator.Create
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: ProcessBrowserFiles
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Uninstall
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall
