### YamlMime:ManagedReference
items:
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  id: ConfigErrorGlyph
  children:
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.#ctor
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds(System.Workflow.ComponentModel.Design.ActivityDesigner,System.Boolean)
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate(System.Workflow.ComponentModel.Design.ActivityDesigner)
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint(System.Drawing.Graphics,System.Boolean,System.Workflow.ComponentModel.Design.AmbientTheme,System.Workflow.ComponentModel.Design.ActivityDesigner)
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority
  langs:
  - csharp
  name: ConfigErrorGlyph
  nameWithType: ConfigErrorGlyph
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  type: Class
  summary: "Gir et symbol for en <xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;> </xref> skal vises når en bruker ikke har utført nødvendig designer handlinger under utformingen."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]Aktiviteten utviklere Bruk ConfigErrorGlyph til å vise handlinger som er knyttet til smartkortet koder på utformingsoverflaten. Hvis en aktivitet krever brukere å angi en egenskap, viser Aktivitetsdesigner ConfigErrorGlyph for å varsle dem at de er påkrevd for å angi egenskapen."
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public class ConfigErrorGlyph : System.Workflow.ComponentModel.Design.DesignerGlyph
  inheritance:
  - System.Object
  - System.Workflow.ComponentModel.Design.DesignerGlyph
  implements: []
  inheritedMembers:
  - System.Workflow.ComponentModel.Design.DesignerGlyph.HighestPriority
  - System.Workflow.ComponentModel.Design.DesignerGlyph.LowestPriority
  - System.Workflow.ComponentModel.Design.DesignerGlyph.NormalPriority
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.#ctor
  id: '#ctor'
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: ConfigErrorGlyph()
  nameWithType: ConfigErrorGlyph.ConfigErrorGlyph()
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.ConfigErrorGlyph()
  type: Constructor
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Workflow.ComponentModel.Design.ConfigErrorGlyph&quot;> </xref> klasse."
  syntax:
    content: public ConfigErrorGlyph ();
    parameters: []
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated
  id: CanBeActivated
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: CanBeActivated
  nameWithType: ConfigErrorGlyph.CanBeActivated
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated
  type: Property
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "Henter en verdi som angir om den <xref href=&quot;System.Workflow.ComponentModel.Design.ConfigErrorGlyph&quot;> </xref> kan få fokus på den <xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;> </xref> med som den er tilknyttet."
  syntax:
    content: public override bool CanBeActivated { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis designer tegnet kan aktiveres; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standard <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds(System.Workflow.ComponentModel.Design.ActivityDesigner,System.Boolean)
  id: GetBounds(System.Workflow.ComponentModel.Design.ActivityDesigner,System.Boolean)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: GetBounds(ActivityDesigner,Boolean)
  nameWithType: ConfigErrorGlyph.GetBounds(ActivityDesigner,Boolean)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds(ActivityDesigner,Boolean)
  type: Method
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "Returnerer grensene for tegnet på den angitte <xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;> </xref>."
  syntax:
    content: public override System.Drawing.Rectangle GetBounds (System.Workflow.ComponentModel.Design.ActivityDesigner designer, bool activated);
    parameters:
    - id: designer
      type: System.Workflow.ComponentModel.Design.ActivityDesigner
      description: "Den <xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;> </xref> med som tegnet er knyttet til."
    - id: activated
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>som viser om tegnet vises på utformingsoverflaten aktiviteten; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    return:
      type: System.Drawing.Rectangle
      description: "En <xref href=&quot;System.Drawing.Rectangle&quot;> </xref> som representerer grensene for tegnet."
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>designer</code>inneholder en nullreferanse (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> i Visual Basic)."
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate(System.Workflow.ComponentModel.Design.ActivityDesigner)
  id: OnActivate(System.Workflow.ComponentModel.Design.ActivityDesigner)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: OnActivate(ActivityDesigner)
  nameWithType: ConfigErrorGlyph.OnActivate(ActivityDesigner)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate(ActivityDesigner)
  type: Method
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "Varsler tegn som er en handling utføres som har aktivert tegnet."
  remarks: "Når VedAktivering kalles, vises designer verb som er forbundet med tegnet på aktiviteten utformingsoverflaten."
  syntax:
    content: protected override void OnActivate (System.Workflow.ComponentModel.Design.ActivityDesigner designer);
    parameters:
    - id: designer
      type: System.Workflow.ComponentModel.Design.ActivityDesigner
      description: "Den <xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;> </xref> på tegnet tegnes."
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint(System.Drawing.Graphics,System.Boolean,System.Workflow.ComponentModel.Design.AmbientTheme,System.Workflow.ComponentModel.Design.ActivityDesigner)
  id: OnPaint(System.Drawing.Graphics,System.Boolean,System.Workflow.ComponentModel.Design.AmbientTheme,System.Workflow.ComponentModel.Design.ActivityDesigner)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
  nameWithType: ConfigErrorGlyph.OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
  type: Method
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "Utfører en oppgaver som kreves for å vise tegnet på aktiviteten utformingsoverflaten."
  syntax:
    content: protected override void OnPaint (System.Drawing.Graphics graphics, bool activated, System.Workflow.ComponentModel.Design.AmbientTheme ambientTheme, System.Workflow.ComponentModel.Design.ActivityDesigner designer);
    parameters:
    - id: graphics
      type: System.Drawing.Graphics
      description: "Den <xref href=&quot;System.Drawing.Graphics&quot;> </xref> til å utføre fyll og tegning oppgaver."
    - id: activated
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>for å angi at tegnet vises på utformingsoverflaten; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
    - id: ambientTheme
      type: System.Workflow.ComponentModel.Design.AmbientTheme
      description: "Den <xref href=&quot;System.Workflow.ComponentModel.Design.AmbientTheme&quot;> </xref> skal brukes til å få tilgang til omkringliggende egenskapsinnstillingene."
    - id: designer
      type: System.Workflow.ComponentModel.Design.ActivityDesigner
      description: "Den <xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;> </xref> som å få informasjon om brukerhandlinger."
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority
  id: Priority
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: Priority
  nameWithType: ConfigErrorGlyph.Priority
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority
  type: Property
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "Henter prioritetsinnstillingen for tegnet på aktiviteten utformingsoverflaten."
  syntax:
    content: public override int Priority { get; }
    return:
      type: System.Int32
      description: "En heltallsverdi som representerer prioritetsinnstillingen for den <xref href=&quot;System.Workflow.ComponentModel.Design.ConfigErrorGlyph&quot;> </xref> på aktiviteten utformingsoverflaten."
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Workflow.ComponentModel.Design.DesignerGlyph
  isExternal: false
  name: System.Workflow.ComponentModel.Design.DesignerGlyph
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.#ctor
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: ConfigErrorGlyph()
  nameWithType: ConfigErrorGlyph.ConfigErrorGlyph()
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.ConfigErrorGlyph()
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: CanBeActivated
  nameWithType: ConfigErrorGlyph.CanBeActivated
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds(System.Workflow.ComponentModel.Design.ActivityDesigner,System.Boolean)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: GetBounds(ActivityDesigner,Boolean)
  nameWithType: ConfigErrorGlyph.GetBounds(ActivityDesigner,Boolean)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds(ActivityDesigner,Boolean)
- uid: System.Drawing.Rectangle
  parent: System.Drawing
  isExternal: false
  name: Rectangle
  nameWithType: Rectangle
  fullName: System.Drawing.Rectangle
- uid: System.Workflow.ComponentModel.Design.ActivityDesigner
  parent: System.Workflow.ComponentModel.Design
  isExternal: false
  name: ActivityDesigner
  nameWithType: ActivityDesigner
  fullName: System.Workflow.ComponentModel.Design.ActivityDesigner
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate(System.Workflow.ComponentModel.Design.ActivityDesigner)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: OnActivate(ActivityDesigner)
  nameWithType: ConfigErrorGlyph.OnActivate(ActivityDesigner)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate(ActivityDesigner)
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint(System.Drawing.Graphics,System.Boolean,System.Workflow.ComponentModel.Design.AmbientTheme,System.Workflow.ComponentModel.Design.ActivityDesigner)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
  nameWithType: ConfigErrorGlyph.OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
- uid: System.Drawing.Graphics
  parent: System.Drawing
  isExternal: false
  name: Graphics
  nameWithType: Graphics
  fullName: System.Drawing.Graphics
- uid: System.Workflow.ComponentModel.Design.AmbientTheme
  parent: System.Workflow.ComponentModel.Design
  isExternal: false
  name: AmbientTheme
  nameWithType: AmbientTheme
  fullName: System.Workflow.ComponentModel.Design.AmbientTheme
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: Priority
  nameWithType: ConfigErrorGlyph.Priority
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.#ctor*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: ConfigErrorGlyph
  nameWithType: ConfigErrorGlyph.ConfigErrorGlyph
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: CanBeActivated
  nameWithType: ConfigErrorGlyph.CanBeActivated
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: GetBounds
  nameWithType: ConfigErrorGlyph.GetBounds
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: OnActivate
  nameWithType: ConfigErrorGlyph.OnActivate
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: OnPaint
  nameWithType: ConfigErrorGlyph.OnPaint
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: Priority
  nameWithType: ConfigErrorGlyph.Priority
