### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.ApplicationContainerSettings
  id: ApplicationContainerSettings
  children:
  - System.ServiceModel.Channels.ApplicationContainerSettings.CurrentSession
  - System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName
  - System.ServiceModel.Channels.ApplicationContainerSettings.ServiceSession
  - System.ServiceModel.Channels.ApplicationContainerSettings.SessionId
  langs:
  - csharp
  name: ApplicationContainerSettings
  nameWithType: ApplicationContainerSettings
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings
  type: Class
  summary: "Angir innstillingene for programmet beholderen."
  syntax:
    content: public sealed class ApplicationContainerSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.CurrentSession
  id: CurrentSession
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  langs:
  - csharp
  name: CurrentSession
  nameWithType: ApplicationContainerSettings.CurrentSession
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.CurrentSession
  type: Field
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Innstillinger for gjeldende økt."
  syntax:
    content: public const int CurrentSession = -1;
    return:
      type: System.Int32
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName
  id: PackageFullName
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  langs:
  - csharp
  name: PackageFullName
  nameWithType: ApplicationContainerSettings.PackageFullName
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Henter fullname av pakken."
  syntax:
    content: public string PackageFullName { get; set; }
    return:
      type: System.String
      description: "Fullname av pakken."
  overload: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.ServiceSession
  id: ServiceSession
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  langs:
  - csharp
  name: ServiceSession
  nameWithType: ApplicationContainerSettings.ServiceSession
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.ServiceSession
  type: Field
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Økten tjenesteinnstillingene."
  syntax:
    content: public const int ServiceSession = 0;
    return:
      type: System.Int32
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId
  id: SessionId
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  langs:
  - csharp
  name: SessionId
  nameWithType: ApplicationContainerSettings.SessionId
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Henter eller angir øktidentifikatoren for beholder applikasjonsinnstillingene."
  syntax:
    content: public int SessionId { get; set; }
    return:
      type: System.Int32
      description: "Økt-IDen for beholder applikasjonsinnstillingene."
  overload: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.CurrentSession
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: CurrentSession
  nameWithType: ApplicationContainerSettings.CurrentSession
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.CurrentSession
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: PackageFullName
  nameWithType: ApplicationContainerSettings.PackageFullName
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.ServiceSession
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: ServiceSession
  nameWithType: ApplicationContainerSettings.ServiceSession
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.ServiceSession
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: SessionId
  nameWithType: ApplicationContainerSettings.SessionId
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.PackageFullName*
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: PackageFullName
  nameWithType: ApplicationContainerSettings.PackageFullName
- uid: System.ServiceModel.Channels.ApplicationContainerSettings.SessionId*
  parent: System.ServiceModel.Channels.ApplicationContainerSettings
  isExternal: false
  name: SessionId
  nameWithType: ApplicationContainerSettings.SessionId
