### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.UpdateCheckInfo
  id: UpdateCheckInfo
  children:
  - System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  - System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  - System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  - System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  - System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  langs:
  - csharp
  name: UpdateCheckInfo
  nameWithType: UpdateCheckInfo
  fullName: System.Deployment.Application.UpdateCheckInfo
  type: Class
  summary: "Representerer detaljert informasjon om fra et kall til <xref:System.Deployment.Application.ApplicationDeployment.CheckForDetailedUpdate*>.</xref:System.Deployment.Application.ApplicationDeployment.CheckForDetailedUpdate*>"
  remarks: "Med UpdateCheckInfo, kan du bestemme om oppgradere ClickOnce applikasjonen basert på om den nyeste versjonen. <xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A>Returnerer en boolsk verdi som angir om det er en ny oppdatering i det hele tatt.</xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A> Den <xref:System.Deployment.Application.UpdateCheckInfo.AvailableVersion%2A>egenskapen gir versjonsnummeret for den nye versjonen, mens <xref:System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion%2A>inneholder den tidligste versjonen som brukeren skal ha installert.</xref:System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion%2A> </xref:System.Deployment.Application.UpdateCheckInfo.AvailableVersion%2A> <xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A>uttrykker om den nyeste oppdateringen som kreves for brukeren.</xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A> Til slutt <xref:System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes%2A>uttrykker den totale størrelsen av oppdateringen.</xref:System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes%2A>      > [!NOTE] > Visual Studio legger til den `<deploymentProvider>` elementet som manifestfilen Hvis programmet er satt til å søke etter oppdateringer, slik at du enten har til å kontrollere **programmet skal se etter oppdateringer** eller angi en URL-adresse for oppdatering i **installere** i den [dialogboksen for programvareoppdateringer](http://msdn.microsoft.com/en-us/8eca8743-8e68-4d04-bfd5-4dc0a9b2934f)."
  example:
  - "The following code example uses <xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A> to determine if there is a new application update, and <xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A> to determine whether to ask the user to install the update.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/t-system.deployment.appl_8_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public class UpdateCheckInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  id: AvailableVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter versjonsnummeret for den nyeste versjonen på avinstallert."
  remarks: "Du kan bruke AvailableVersion til å bestemme om du vil installere oppdateringen basert på alvorsgrad av oppdateringen. Hvis det er bare for eksempel den <xref:System.Version.Build%2A>eller <xref:System.Version.Revision%2A>versjon egenskapene har blitt endret må programmet kan ikke oppdatere til enten den <xref:System.Version.Minor%2A>eller <xref:System.Version.Major%2A>endring av egenskap.</xref:System.Version.Major%2A> </xref:System.Version.Minor%2A> </xref:System.Version.Revision%2A> </xref:System.Version.Build%2A>"
  syntax:
    content: public Version AvailableVersion { get; }
    return:
      type: System.Version
      description: "Den <xref:System.Version>uttrykkes overordnede og underordnede kompilering og revisjon tall i den nyeste versjonen.</xref:System.Version>"
  overload: System.Deployment.Application.UpdateCheckInfo.AvailableVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  id: IsUpdateRequired
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
  fullName: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter en verdi som angir om oppdateringen må installeres."
  remarks: "Når du distribuerer en oppdatering til ClickOnce-programmet, kan du merke den som en nødvendig oppdatering signaliserer til programmet at det bør oppgradere umiddelbart. Vil du merke programmet hvis den nyeste versjonen inneholder en kritisk oppdatering, eller hvis det er ikke kompatibelt med filformater eller bakenforliggende datakildene som brukes av den forrige versjonen."
  example:
  - "The following code example uses IsUpdateRequired to determine whether to ask the user to install the update, or to install it without prompting.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_6_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public bool IsUpdateRequired { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis oppdateringen er påkrevd. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  id: MinimumRequiredVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter minimumsversjonen som brukeren må ha installert på datamaskinen."
  remarks: "Programmer kan har gått glipp av obligatoriske oppdateringer når brukeren tar for en bestemt tildeling eller er bort fra datamaskinen for uker eller måneder. Bruk MinimumRequiredVersion til å bestemme om brukeren ikke er oppgradert programmet på en stund, har gått glipp av én eller flere obligatoriske oppdateringer."
  example:
  - "The following code example demonstrates displaying the MinimumRequiredVersion property to the user when there is a required update available.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_1_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public Version MinimumRequiredVersion { get; }
    return:
      type: System.Version
      description: "En <xref:System.Version>uttrykkes minst versjon som brukeren må installere.</xref:System.Version>"
  overload: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion*
  exceptions:
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "Det er ingen nye versjonen som er tilgjengelig for installasjon."
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  id: UpdateAvailable
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter om en avinstallert oppdatering er tilgjengelig."
  remarks: ''
  example:
  - "The following code example inspects UpdateAvailable to determine whether there is an update to install.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_10_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public bool UpdateAvailable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis ny versjon av programmet er tilgjengelig. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  id: UpdateSizeBytes
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter størrelsen på den tilgjengelige oppdateringen."
  syntax:
    content: public long UpdateSizeBytes { get; }
    return:
      type: System.Int64
      description: "En <xref:System.Int64>som beskriver størrelsen, i byte for oppdateringen.</xref:System.Int64> Hvis ingen oppdatering er tilgjengelig, returnerer 0."
  overload: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.InvalidOperationException
  isExternal: true
  name: System.InvalidOperationException
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
  fullName: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
