### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationInstance
  id: WorkflowApplicationInstance
  children:
  - System.Activities.WorkflowApplicationInstance.Abandon
  - System.Activities.WorkflowApplicationInstance.Abandon(System.TimeSpan)
  - System.Activities.WorkflowApplicationInstance.BeginAbandon(System.AsyncCallback,System.Object)
  - System.Activities.WorkflowApplicationInstance.BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  - System.Activities.WorkflowApplicationInstance.CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  - System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  - System.Activities.WorkflowApplicationInstance.EndAbandon(System.IAsyncResult)
  - System.Activities.WorkflowApplicationInstance.InstanceId
  - System.Activities.WorkflowApplicationInstance.InstanceStore
  langs:
  - csharp
  name: WorkflowApplicationInstance
  nameWithType: WorkflowApplicationInstance
  fullName: System.Activities.WorkflowApplicationInstance
  type: Class
  summary: "Angir informasjon om en arbeidsflytforekomst for programmet."
  remarks: "Denne klassen støtter versjonskontroll og dynamisk oppdateringsfunksjonaliteten til Windows-arbeidsflyten Foundation. [!INCLUDE[crabout](~/add/includes/ajax-current-ext-md.md)]arbeidsflyten versjonskontroll, arbeidsflyt-ID og dynamisk oppdatering, kan du se følgende emner.       [Arbeidsflyten versjonskontroll](http://go.microsoft.com/fwlink/?LinkID=271561) beskriver arbeidsflyten versjonskontroll funksjonaliteten introdusert i [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)].       [Dynamisk oppdatering](http://go.microsoft.com/fwlink/?LinkId=271563) beskriver hvordan du oppdaterer Arbeidsflytdefinisjonen for en arbeidsflytforekomst som er faste ved hjelp av dynamisk oppdatering.       [Ved hjelp av WorkflowApplication Identity og versjonskontroll](http://go.microsoft.com/fwlink/?LinkId=271564) beskriver hvordan du bruker <xref:System.Activities.WorkflowIdentity>som vert for flere versjoner av en arbeidsflyt side-ved-side.</xref:System.Activities.WorkflowIdentity>       [Side ved Side versjonskontroll i WorkflowServiceHost](http://go.microsoft.com/fwlink/?LinkId=271565) beskriver hvordan du vert flere versjoner av en arbeidsflyt på et enkelt endepunkt.       [Slik: verten flere versjoner av en arbeidsflyt Side-ved-Side](http://go.microsoft.com/fwlink/?LinkId=271566) dette trinnet i den [Opplæringen Komme i gang](http://go.microsoft.com/fwlink/?LinkId=271570) demonstrerer oppdatering av en arbeidsflytdefinisjon og er vert for arbeidsflyter med både gammel og ny definition samtidig.       [Slik: oppdatere definisjonen av en arbeidsflytforekomst som kjører](http://go.microsoft.com/fwlink/?LinkId=271567) dette trinnet i den [Opplæringen Komme i gang](http://go.microsoft.com/fwlink/?LinkId=271570) demonstrerer oppdatering faste arbeidsflytforekomster Hvis du vil bruke en ny arbeidsflytdefinisjonen."
  syntax:
    content: public class WorkflowApplicationInstance
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.Abandon
  id: Abandon
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: Abandon()
  nameWithType: WorkflowApplicationInstance.Abandon()
  fullName: System.Activities.WorkflowApplicationInstance.Abandon()
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Gjør maskin for tilstand for å bytte til tilstanden ble ignorert."
  syntax:
    content: public void Abandon ();
    parameters: []
  overload: System.Activities.WorkflowApplicationInstance.Abandon*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.Abandon(System.TimeSpan)
  id: Abandon(System.TimeSpan)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: Abandon(TimeSpan)
  nameWithType: WorkflowApplicationInstance.Abandon(TimeSpan)
  fullName: System.Activities.WorkflowApplicationInstance.Abandon(TimeSpan)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Gjør maskin for tilstand for å bytte til tilstanden ble ignorert med angitt tidsavbruddsverdi."
  syntax:
    content: public void Abandon (TimeSpan timeout);
    parameters:
    - id: timeout
      type: System.TimeSpan
      description: "Tidsavbrudd for abandon-operasjonen er fullført."
  overload: System.Activities.WorkflowApplicationInstance.Abandon*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.AsyncCallback,System.Object)
  id: BeginAbandon(System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: BeginAbandon(AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Starter en asynkron abandon-operasjon."
  syntax:
    content: public IAsyncResult BeginAbandon (AsyncCallback callback, object state);
    parameters:
    - id: callback
      type: System.AsyncCallback
      description: "Asynkron tilbakeringing representanten som får beskjed om asynkrone operasjonen er fullført."
    - id: state
      type: System.Object
      description: "Brukerdefinerte tilstand-data."
    return:
      type: System.IAsyncResult
      description: "En asynkron abandon-operasjon."
  overload: System.Activities.WorkflowApplicationInstance.BeginAbandon*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  id: BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: BeginAbandon(TimeSpan,AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Starter en asynkron abandon-operasjon."
  syntax:
    content: public IAsyncResult BeginAbandon (TimeSpan timeout, AsyncCallback callback, object state);
    parameters:
    - id: timeout
      type: System.TimeSpan
      description: "Tidsavbruddet som inneholder årsaken til abandon-operasjonen."
    - id: callback
      type: System.AsyncCallback
      description: "Asynkron tilbakeringing representanten som får beskjed om asynkrone operasjonen er fullført."
    - id: state
      type: System.Object
      description: "Brukerdefinerte tilstand-data."
    return:
      type: System.IAsyncResult
      description: "En asynkron abandon-operasjon."
  overload: System.Activities.WorkflowApplicationInstance.BeginAbandon*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  id: CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  nameWithType: WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  fullName: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Returnerer en verdi som angir om WorkflowApplicationInstance kan oppdatere."
  syntax:
    content: public bool CanApplyUpdate (System.Activities.DynamicUpdate.DynamicUpdateMap updateMap, out System.Collections.Generic.IList<System.Activities.DynamicUpdate.ActivityBlockingUpdate> activitiesBlockingUpdate);
    parameters:
    - id: updateMap
      type: System.Activities.DynamicUpdate.DynamicUpdateMap
      description: "Oppdaterer et kart."
    - id: activitiesBlockingUpdate
      type: System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}
      description: "Aktivitetene blokkering av oppdateringen."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>Hvis WorkflowApplicationInstance kan bruke oppdateringen. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.WorkflowApplicationInstance.CanApplyUpdate*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  id: DefinitionIdentity
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: DefinitionIdentity
  nameWithType: WorkflowApplicationInstance.DefinitionIdentity
  fullName: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Henter eller angir identiteten definisjonen av arbeidsflyten."
  syntax:
    content: public System.Activities.WorkflowIdentity DefinitionIdentity { get; }
    return:
      type: System.Activities.WorkflowIdentity
      description: "Identiteten definisjonen av arbeidsflyten."
  overload: System.Activities.WorkflowApplicationInstance.DefinitionIdentity*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.EndAbandon(System.IAsyncResult)
  id: EndAbandon(System.IAsyncResult)
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: EndAbandon(IAsyncResult)
  nameWithType: WorkflowApplicationInstance.EndAbandon(IAsyncResult)
  fullName: System.Activities.WorkflowApplicationInstance.EndAbandon(IAsyncResult)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Fullfører en asynkron abandon-operasjon."
  syntax:
    content: public void EndAbandon (IAsyncResult asyncResult);
    parameters:
    - id: asyncResult
      type: System.IAsyncResult
      description: "IAsyncResult som ble returnert av et kall til én av metodene BeginAbandon."
  overload: System.Activities.WorkflowApplicationInstance.EndAbandon*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.InstanceId
  id: InstanceId
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: InstanceId
  nameWithType: WorkflowApplicationInstance.InstanceId
  fullName: System.Activities.WorkflowApplicationInstance.InstanceId
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Henter den unike identifikatoren til arbeidsflytforekomsten."
  syntax:
    content: public Guid InstanceId { get; }
    return:
      type: System.Guid
      description: "Den unike identifikatoren til arbeidsflytforekomsten."
  overload: System.Activities.WorkflowApplicationInstance.InstanceId*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationInstance.InstanceStore
  id: InstanceStore
  parent: System.Activities.WorkflowApplicationInstance
  langs:
  - csharp
  name: InstanceStore
  nameWithType: WorkflowApplicationInstance.InstanceStore
  fullName: System.Activities.WorkflowApplicationInstance.InstanceStore
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Henter eller angir et objekt som gir tilgang til den lagrede tilstanden til gjeldende forekomst av arbeidsflyten-programmet."
  syntax:
    content: public System.Runtime.DurableInstancing.InstanceStore InstanceStore { get; }
    return:
      type: System.Runtime.DurableInstancing.InstanceStore
      description: "Et objekt som gir tilgang til den lagrede tilstanden til gjeldende forekomst av arbeidsflyten-programmet."
  overload: System.Activities.WorkflowApplicationInstance.InstanceStore*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.WorkflowApplicationInstance.Abandon
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: Abandon()
  nameWithType: WorkflowApplicationInstance.Abandon()
  fullName: System.Activities.WorkflowApplicationInstance.Abandon()
- uid: System.Activities.WorkflowApplicationInstance.Abandon(System.TimeSpan)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: Abandon(TimeSpan)
  nameWithType: WorkflowApplicationInstance.Abandon(TimeSpan)
  fullName: System.Activities.WorkflowApplicationInstance.Abandon(TimeSpan)
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: BeginAbandon(AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(AsyncCallback,Object)
- uid: System.IAsyncResult
  parent: System
  isExternal: true
  name: IAsyncResult
  nameWithType: IAsyncResult
  fullName: System.IAsyncResult
- uid: System.AsyncCallback
  parent: System
  isExternal: true
  name: AsyncCallback
  nameWithType: AsyncCallback
  fullName: System.AsyncCallback
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon(System.TimeSpan,System.AsyncCallback,System.Object)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: BeginAbandon(TimeSpan,AsyncCallback,Object)
  nameWithType: WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
  fullName: System.Activities.WorkflowApplicationInstance.BeginAbandon(TimeSpan,AsyncCallback,Object)
- uid: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(System.Activities.DynamicUpdate.DynamicUpdateMap,System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}@)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  nameWithType: WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
  fullName: System.Activities.WorkflowApplicationInstance.CanApplyUpdate(DynamicUpdateMap,IList<ActivityBlockingUpdate>)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.DynamicUpdate.DynamicUpdateMap
  parent: System.Activities.DynamicUpdate
  isExternal: false
  name: DynamicUpdateMap
  nameWithType: DynamicUpdateMap
  fullName: System.Activities.DynamicUpdate.DynamicUpdateMap
- uid: System.Collections.Generic.IList{System.Activities.DynamicUpdate.ActivityBlockingUpdate}
  parent: System.Collections.Generic
  isExternal: true
  name: IList<ActivityBlockingUpdate>
  nameWithType: IList<ActivityBlockingUpdate>
  fullName: System.Collections.Generic.IList<System.Activities.DynamicUpdate.ActivityBlockingUpdate>
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: IList<System.Activities.DynamicUpdate.ActivityBlockingUpdate>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Activities.DynamicUpdate.ActivityBlockingUpdate
    name: ActivityBlockingUpdate
    nameWithType: ActivityBlockingUpdate
    fullName: ActivityBlockingUpdate
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: DefinitionIdentity
  nameWithType: WorkflowApplicationInstance.DefinitionIdentity
  fullName: System.Activities.WorkflowApplicationInstance.DefinitionIdentity
- uid: System.Activities.WorkflowIdentity
  parent: System.Activities
  isExternal: false
  name: WorkflowIdentity
  nameWithType: WorkflowIdentity
  fullName: System.Activities.WorkflowIdentity
- uid: System.Activities.WorkflowApplicationInstance.EndAbandon(System.IAsyncResult)
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: EndAbandon(IAsyncResult)
  nameWithType: WorkflowApplicationInstance.EndAbandon(IAsyncResult)
  fullName: System.Activities.WorkflowApplicationInstance.EndAbandon(IAsyncResult)
- uid: System.Activities.WorkflowApplicationInstance.InstanceId
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationInstance.InstanceId
  fullName: System.Activities.WorkflowApplicationInstance.InstanceId
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationInstance.InstanceStore
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: InstanceStore
  nameWithType: WorkflowApplicationInstance.InstanceStore
  fullName: System.Activities.WorkflowApplicationInstance.InstanceStore
- uid: System.Runtime.DurableInstancing.InstanceStore
  parent: System.Runtime.DurableInstancing
  isExternal: false
  name: InstanceStore
  nameWithType: InstanceStore
  fullName: System.Runtime.DurableInstancing.InstanceStore
- uid: System.Activities.WorkflowApplicationInstance.Abandon*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: Abandon
  nameWithType: WorkflowApplicationInstance.Abandon
- uid: System.Activities.WorkflowApplicationInstance.BeginAbandon*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: BeginAbandon
  nameWithType: WorkflowApplicationInstance.BeginAbandon
- uid: System.Activities.WorkflowApplicationInstance.CanApplyUpdate*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: CanApplyUpdate
  nameWithType: WorkflowApplicationInstance.CanApplyUpdate
- uid: System.Activities.WorkflowApplicationInstance.DefinitionIdentity*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: DefinitionIdentity
  nameWithType: WorkflowApplicationInstance.DefinitionIdentity
- uid: System.Activities.WorkflowApplicationInstance.EndAbandon*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: EndAbandon
  nameWithType: WorkflowApplicationInstance.EndAbandon
- uid: System.Activities.WorkflowApplicationInstance.InstanceId*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationInstance.InstanceId
- uid: System.Activities.WorkflowApplicationInstance.InstanceStore*
  parent: System.Activities.WorkflowApplicationInstance
  isExternal: false
  name: InstanceStore
  nameWithType: WorkflowApplicationInstance.InstanceStore
