### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  id: ValidatingPropertiesEventArgs
  children:
  - System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties
  - System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties
  langs:
  - csharp
  name: ValidatingPropertiesEventArgs
  nameWithType: ValidatingPropertiesEventArgs
  fullName: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  type: Class
  summary: "Gir dataene for den <xref href=&quot;System.Web.ApplicationServices.ProfileService.ValidatingProperties&quot;> </xref> hendelsen."
  remarks: "Du oppretter en hendelsesbehandling for den <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties>-hendelsen for å tilpasse hvordan profilegenskapsverdier valideres.</xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> Den <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties>denne hendelsen oppstår når profilegenskaper er angitt for en bruker.</xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> Hvis alle egenskapsverdiene ikke validering, legger du dem til samlingen i den <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A>egenskapen.</xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> Den <xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>metoden returnerer samlingen i den <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A>egenskapen slik at du kan finne ut hvilke egenskaper ikke kan validere.</xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> </xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> event. When the value passed for `FirstName` property is empty or `null`, the `FirstName` property is added to the <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> collection.  \n  \n [!code-vb[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/visualbasic/t-system.web.application_2_1.asax)]\n [!code-cs[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/csharp/t-system.web.application_2_1.asax)]"
  syntax:
    content: 'public class ValidatingPropertiesEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties
  id: FailedProperties
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  langs:
  - csharp
  name: FailedProperties
  nameWithType: ValidatingPropertiesEventArgs.FailedProperties
  fullName: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter samlingen som inneholder profilegenskaper som har ikke bestått valideringen."
  remarks: "Egenskapen FailedProperties inneholder en samling av navn på Egenskaper som har ikke bestått valideringen. Hvis du oppretter en hendelsesbehandling for den <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties>hendelsen du legger til navn på Egenskaper som ikke kan valideres til samlingen i egenskapen FailedProperties.</xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> Den <xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>metoden returnerer samlingen i egenskapen FailedProperties slik at du kan finne ut hvilke egenskaper ikke kan validere.</xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> event. When the value passed for `FirstName` property is empty or `null`, the `FirstName` property is added to the FailedProperties collection.  \n  \n [!code-vb[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/visualbasic/p-system.web.application_7_1.asax)]\n [!code-cs[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/csharp/p-system.web.application_7_1.asax)]"
  syntax:
    content: public System.Collections.ObjectModel.Collection<string> FailedProperties { get; }
    return:
      type: System.Collections.ObjectModel.Collection{System.String}
      description: "Profilegenskaper som har ikke bestått valideringen."
  overload: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties
  id: Properties
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  langs:
  - csharp
  name: Properties
  nameWithType: ValidatingPropertiesEventArgs.Properties
  fullName: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter verdier profilegenskaper til å validere og samlingen av navn."
  remarks: "Returnerer egenskaper for en <xref:System.Collections.IDictionary>objekt som inneholder navn og verdier av profilegenskaper angi for brukeren.</xref:System.Collections.IDictionary> Hvis du oppretter en hendelsesbehandling for den <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties>hendelse, kan du hente egenskaper for å validere fra egenskapen egenskaper.</xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> Hvis ingen verdier ikke validering, kan du legge dem til i <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A>egenskapen.</xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> Den <xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>metoden returnerer samlingen i den <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A>egenskapen slik at du kan finne ut hvilke egenskaper ikke kan validere.</xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> </xref:System.Web.ApplicationServices.ProfileService.SetPropertiesForCurrentUser%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.ProfileService.ValidatingProperties> event. When the value passed for `FirstName` property is empty or `null`, the `FirstName` property is added to the <xref:System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties%2A> collection.  \n  \n [!code-vb[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/visualbasic/p-system.web.application_8_1.asax)]\n [!code-cs[System.Web.ApplicationServices.ProfileService#1](~/add/codesnippet/csharp/p-system.web.application_8_1.asax)]"
  syntax:
    content: public System.Collections.Generic.IDictionary<string,object> Properties { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
      description: "Navn og verdier av profilegenskaper til å validere."
  overload: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  isExternal: false
  name: FailedProperties
  nameWithType: ValidatingPropertiesEventArgs.FailedProperties
  fullName: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties
- uid: System.Collections.ObjectModel.Collection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: Collection<String>
  nameWithType: Collection<String>
  fullName: System.Collections.ObjectModel.Collection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.Collection`1
    name: Collection
    nameWithType: Collection
    fullName: Collection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  isExternal: false
  name: Properties
  nameWithType: ValidatingPropertiesEventArgs.Properties
  fullName: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties
- uid: System.Collections.Generic.IDictionary{System.String,System.Object}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<String,Object>
  nameWithType: IDictionary<String,Object>
  fullName: System.Collections.Generic.IDictionary<System.String,System.Object>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary<System.String,System.Object>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: Object
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.FailedProperties*
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  isExternal: false
  name: FailedProperties
  nameWithType: ValidatingPropertiesEventArgs.FailedProperties
- uid: System.Web.ApplicationServices.ValidatingPropertiesEventArgs.Properties*
  parent: System.Web.ApplicationServices.ValidatingPropertiesEventArgs
  isExternal: false
  name: Properties
  nameWithType: ValidatingPropertiesEventArgs.Properties
