### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SecurityPolicySection
  id: SecurityPolicySection
  children:
  - System.Web.Configuration.SecurityPolicySection.#ctor
  - System.Web.Configuration.SecurityPolicySection.Properties
  - System.Web.Configuration.SecurityPolicySection.TrustLevels
  langs:
  - csharp
  name: SecurityPolicySection
  nameWithType: SecurityPolicySection
  fullName: System.Web.Configuration.SecurityPolicySection
  type: Class
  summary: "Definerer konfigurasjonsinnstillinger som brukes til å støtte infrastruktur for sikkerhet for et webprogram. Denne klassen kan arves."
  remarks: "Klassen SecurityPolicySection gjør det mulig å programmatisk tilgang til og endre innholdet i den `securityPolicy` delen av konfigurasjonsfilen."
  example:
  - "This example demonstrates how to specify values declaratively within the `securityPolicy` section, which can also be accessed as members of the SecurityPolicySection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `securityPolicy` section.  \n  \n```  \n<system.web>  \n  <securityPolicy>  \n    <trustLevel name=\"Full\" policyFile=\"internal\" />  \n    <trustLevel name=\"High\" policyFile=\"web_hightrust.config\" />  \n    <trustLevel name=\"Medium\" policyFile=\"web_mediumtrust.config\" />  \n    <trustLevel name=\"Low\" policyFile=\"web_lowtrust.config\" />  \n    <trustLevel name=\"Minimal\" policyFile=\"web_minimaltrust.config\" />  \n  </securityPolicy>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the SecurityPolicySection class.  \n  \n [!code-cs[System.Web.Configuration.SecurityPolicySection#1](~/add/codesnippet/csharp/t-system.web.configurati_26_1.cs)]\n [!code-vb[System.Web.Configuration.SecurityPolicySection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_26_1.vb)]"
  syntax:
    content: 'public sealed class SecurityPolicySection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.SecurityPolicySection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SecurityPolicySection
  langs:
  - csharp
  name: SecurityPolicySection()
  nameWithType: SecurityPolicySection.SecurityPolicySection()
  fullName: System.Web.Configuration.SecurityPolicySection.SecurityPolicySection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.SecurityPolicySection&quot;> </xref> klassen ved hjelp av standardinnstillingene."
  remarks: "Konstruktøren SecurityPolicySection skal ikke brukes direkte fra koden. Kalles av ASP.NET Konfigurasjonssystemet. Du hente en forekomst av den <xref:System.Web.Configuration.SecurityPolicySection>klassen ved hjelp av den <xref:System.Configuration.Configuration.GetSection%2A>metoden.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.SecurityPolicySection>"
  syntax:
    content: public SecurityPolicySection ();
    parameters: []
  overload: System.Web.Configuration.SecurityPolicySection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SecurityPolicySection.Properties
  id: Properties
  parent: System.Web.Configuration.SecurityPolicySection
  langs:
  - csharp
  name: Properties
  nameWithType: SecurityPolicySection.Properties
  fullName: System.Web.Configuration.SecurityPolicySection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Web.Configuration.SecurityPolicySection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SecurityPolicySection.TrustLevels
  id: TrustLevels
  parent: System.Web.Configuration.SecurityPolicySection
  langs:
  - csharp
  name: TrustLevels
  nameWithType: SecurityPolicySection.TrustLevels
  fullName: System.Web.Configuration.SecurityPolicySection.TrustLevels
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter TrustLevels-samlingen."
  remarks: "Standardverdier for egenskapen TrustLevels er `Full`, `High`, `Medium`, `Low`, og `Minimal`. Elementer av TrustLevels samlingen hver angi et nivå for nettverkssikkerhet navn og en tilhørende policyfil. Du kan utvide sikkerhetssystemet ved å gi din egen navngitt klareringsnivå-elementet er tilordnet til en fil som er angitt av den `policyFile` attributtet. Hvis du vil ha informasjon om hvordan du oppretter klareringsnivå elementer, se [trustLevel elementet for securityPolicy (ASP.NET innstillingsskjemaet)](http://msdn.microsoft.com/en-us/729ab04c-03da-4ee5-86b1-be9d08a09369)."
  example:
  - "The following code example demonstrates how to use the TrustLevels property, add a trust-level element to the configuration file, and update the configuration file. This code example is part of a larger example provided for the <xref:System.Web.Configuration.SecurityPolicySection> class.  \n  \n [!code-cs[System.Web.Configuration.SecurityPolicySection#2](~/add/codesnippet/csharp/p-system.web.configurati_203_1.cs)]\n [!code-vb[System.Web.Configuration.SecurityPolicySection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_203_1.vb)]"
  syntax:
    content: public System.Web.Configuration.TrustLevelCollection TrustLevels { get; }
    return:
      type: System.Web.Configuration.TrustLevelCollection
      description: "En samling av TrustLevels objekter."
  overload: System.Web.Configuration.SecurityPolicySection.TrustLevels*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.SecurityPolicySection.#ctor
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: SecurityPolicySection()
  nameWithType: SecurityPolicySection.SecurityPolicySection()
  fullName: System.Web.Configuration.SecurityPolicySection.SecurityPolicySection()
- uid: System.Web.Configuration.SecurityPolicySection.Properties
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: Properties
  nameWithType: SecurityPolicySection.Properties
  fullName: System.Web.Configuration.SecurityPolicySection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.SecurityPolicySection.TrustLevels
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: TrustLevels
  nameWithType: SecurityPolicySection.TrustLevels
  fullName: System.Web.Configuration.SecurityPolicySection.TrustLevels
- uid: System.Web.Configuration.TrustLevelCollection
  parent: System.Web.Configuration
  isExternal: false
  name: TrustLevelCollection
  nameWithType: TrustLevelCollection
  fullName: System.Web.Configuration.TrustLevelCollection
- uid: System.Web.Configuration.SecurityPolicySection.#ctor*
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: SecurityPolicySection
  nameWithType: SecurityPolicySection.SecurityPolicySection
- uid: System.Web.Configuration.SecurityPolicySection.Properties*
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: Properties
  nameWithType: SecurityPolicySection.Properties
- uid: System.Web.Configuration.SecurityPolicySection.TrustLevels*
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: TrustLevels
  nameWithType: SecurityPolicySection.TrustLevels
