### YamlMime:ManagedReference
items:
- uid: System.Configuration.InfiniteTimeSpanConverter
  id: InfiniteTimeSpanConverter
  children:
  - System.Configuration.InfiniteTimeSpanConverter.#ctor
  - System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: InfiniteTimeSpanConverter
  nameWithType: InfiniteTimeSpanConverter
  fullName: System.Configuration.InfiniteTimeSpanConverter
  type: Class
  summary: "Konverterer mellom en streng og standard uendelig <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  remarks: "Denne typen som alle de andre konfigurasjon konverteringsprogram typene, konverterer strenger i konfigurasjonsfilen til og fra de forespørselsparameter av sterk type egenskapene.       Spesielt InfiniteTimeSpanConverter konverterer den <xref:System.String>verdien &quot;uendelige&quot; tilordnet et configuration-egenskapen til standard uendelige <xref:System.TimeSpan>og omvendt.</xref:System.TimeSpan> </xref:System.String> Uendelige <xref:System.TimeSpan>verdien som er representert av den <xref:System.TimeSpan>opplistingsverdien.</xref:System.TimeSpan> </xref:System.TimeSpan>       Denne konverteringsprogram brukes med <xref:System.TimeSpan>Egenskaper.</xref:System.TimeSpan> En uendelig verdien er fast som &quot;uendelig&quot; streng."
  example:
  - "The following code example shows how to define a custom section property that uses the InfiniteTimeSpanConverter class.  \n  \n For the complete example code that implements the custom section, refer to the <xref:System.Configuration.ConfigurationConverterBase> class.  \n  \n [!code-cs[System.Configuration.ConfigurationConvertersCustomSection#3](~/add/codesnippet/csharp/t-system.configuration.i_6_1.cs)]\n [!code-vb[System.Configuration.ConfigurationConvertersCustomSection#3](~/add/codesnippet/visualbasic/t-system.configuration.i_6_1.vb)]  \n  \n The following example code shows how to access the previous custom section property.  \n  \n [!code-cs[System.Configuration.InfiniteTimeSpanConverter#1](~/add/codesnippet/csharp/t-system.configuration.i_6_2.cs)]\n [!code-vb[System.Configuration.InfiniteTimeSpanConverter#1](~/add/codesnippet/visualbasic/t-system.configuration.i_6_2.vb)]  \n  \n The following is a configuration excerpt as used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <configSections>  \n    <section name=\"CustomSection\"   \n      type=\"Samples.AspNet.CustomSection,   \n      ConfigurationConverters,   \n      Version=1.0.0.0, Culture=neutral,   \n      PublicKeyToken=null\"   \n      allowDefinition=\"Everywhere\"   \n      allowExeDefinition=\"MachineToApplication\"   \n      restartOnExternalChanges=\"true\" />  \n    </configSections>  \n    <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\" timeDelay=\"infinite\"/>  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class InfiniteTimeSpanConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: InfiniteTimeSpanConverter()
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  fullName: System.Configuration.InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.InfiniteTimeSpanConverter&quot;> </xref> klasse."
  remarks: "Vanligvis bruker konverteringsprogram typene som er angitt av systemet. Den eneste gangen du må bruke InfiniteTimeSpanConverter konstruktøren er når du oppretter en konverteringstype."
  syntax:
    content: public InfiniteTimeSpanConverter ();
    parameters: []
  overload: System.Configuration.InfiniteTimeSpanConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konverterer en <xref:System.String>til <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  remarks: "Systemet bruker metoden ConvertFrom ved lesing fra en konfigurasjonsfil til å konvertere en <xref:System.String>verdi eller <xref:System.TimeSpan>den <xref:System.String>&quot;uendelig&quot; til <xref:System.TimeSpan.MaxValue>.</xref:System.TimeSpan.MaxValue> </xref:System.String> </xref:System.TimeSpan> </xref:System.String>"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Den <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> objekt som brukes for konverteringer av datatyper."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Den <xref:System.Globalization.CultureInfo>objektet som ble brukt under konvertering.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "Den <xref:System.String>objekt for å konvertere.</xref:System.String>"
    return:
      type: System.Object
      description: "Den <xref:System.TimeSpan.MaxValue>, hvis den <code> data </code> parameteren er den <xref:System.String>uendelig; motsatt fall, av <xref:System.TimeSpan>som representerer den <code> data </code> parameter i minutter.</xref:System.TimeSpan> </xref:System.String> </xref:System.TimeSpan.MaxValue>"
  overload: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konverterer en <xref:System.TimeSpan>til <xref:System.String>.</xref:System.String> </xref:System.TimeSpan>"
  remarks: "Systemet bruker metoden ConvertTo under skriving av et attributt til en konfigurasjonsfil til å konvertere en <xref:System.TimeSpan>objekt en <xref:System.String>objektet.</xref:System.String> </xref:System.TimeSpan>       Systemet bruker metoden ConvertTo under skriving til en konfigurasjonsfil til å konvertere en <xref:System.TimeSpan>verdi eller <xref:System.TimeSpan.MaxValue>til en <xref:System.String>.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.TimeSpan>"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Den <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> objekt som brukes for konverteringer av datatyper."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Den <xref:System.Globalization.CultureInfo>brukes under konvertering av objektet.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "Verdien som skal konverteres."
    - id: type
      type: System.Type
      description: "Konverteringstype."
    return:
      type: System.Object
      description: "Den <xref:System.String>&quot;uendelig&quot;, hvis den <code> value </code> parameteren er <xref:System.TimeSpan.MaxValue>; ellers den <xref:System.String>som representerer den <code> value </code> parameter i minutter.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.String>"
  overload: System.Configuration.InfiniteTimeSpanConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: InfiniteTimeSpanConverter()
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  fullName: System.Configuration.InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: InfiniteTimeSpanConverter
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertTo
  nameWithType: InfiniteTimeSpanConverter.ConvertTo
