### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsContext
  id: SettingsContext
  children:
  - System.Configuration.SettingsContext.#ctor
  langs:
  - csharp
  name: SettingsContext
  nameWithType: SettingsContext
  fullName: System.Configuration.SettingsContext
  type: Class
  summary: "Gir kontekstavhengig informasjon leverandøren kan bruke når vedvarende innstillinger."
  remarks: "Klassen SettingsContext er basisklasse brukes av programmer for å gi kontekstavhengig informasjon til Innstillingsleverandør. Selv om klassen er abstrakt, kan et program velge å opprette en spesialiserte klassen som arver fra SettingsContext klassen og gir ekstra informasjon til bestemte typer leverandører. Leverandøren kan deretter undersøke kontekstavhengig innstillinger under skriving av egenskaper.       Hovedformål av klassen SettingsContext er å gi funksjoner som bruker den <xref:System.Configuration.SettingsBase>klassen og relaterte infrastruktur.</xref:System.Configuration.SettingsBase> Klassen SettingsContext inneholder funksjonen-spesifikke kontekstavhengig tilleggsinformasjon om egenskapsdata som er lagret i <xref:System.Configuration.SettingsBase>forekomsten.</xref:System.Configuration.SettingsBase> Derfor er det svært enkelt å lagre tilleggsinformasjon i en SettingsContext klasse uten avledes fra den (eller andre innstillinger * klasser) for å støtte flere funksjonen-spesifikke kontekstinformasjon.       For eksempel ASP.NET bruker klassen SettingsContext skal sendes langs brukernavnet tilknyttet dataene administreres av en <xref:System.Configuration.SettingsBase>forekomsten, i tillegg til en egenskap som angir om brukeren anses som godkjennes.</xref:System.Configuration.SettingsBase> På denne måten bruker ASP.NET klassen SettingsContext for å identifisere godkjent sammenlignet anonym profildata."
  syntax:
    content: 'public class SettingsContext : System.Collections.Hashtable'
  inheritance:
  - System.Object
  - System.Collections.Hashtable
  implements: []
  inheritedMembers:
  - System.Collections.Hashtable.Add(System.Object,System.Object)
  - System.Collections.Hashtable.Clear
  - System.Collections.Hashtable.Clone
  - System.Collections.Hashtable.comparer
  - System.Collections.Hashtable.Contains(System.Object)
  - System.Collections.Hashtable.ContainsKey(System.Object)
  - System.Collections.Hashtable.ContainsValue(System.Object)
  - System.Collections.Hashtable.CopyTo(System.Array,System.Int32)
  - System.Collections.Hashtable.Count
  - System.Collections.Hashtable.EqualityComparer
  - System.Collections.Hashtable.GetEnumerator
  - System.Collections.Hashtable.GetHash(System.Object)
  - System.Collections.Hashtable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Collections.Hashtable.hcp
  - System.Collections.Hashtable.IsFixedSize
  - System.Collections.Hashtable.IsReadOnly
  - System.Collections.Hashtable.IsSynchronized
  - System.Collections.Hashtable.Item(System.Object)
  - System.Collections.Hashtable.KeyEquals(System.Object,System.Object)
  - System.Collections.Hashtable.Keys
  - System.Collections.Hashtable.OnDeserialization(System.Object)
  - System.Collections.Hashtable.Remove(System.Object)
  - System.Collections.Hashtable.Synchronized(System.Collections.Hashtable)
  - System.Collections.Hashtable.SyncRoot
  - System.Collections.Hashtable.System#Collections#IEnumerable#GetEnumerator
  - System.Collections.Hashtable.Values
  platform:
  - net462
- uid: System.Configuration.SettingsContext.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsContext
  langs:
  - csharp
  name: SettingsContext()
  nameWithType: SettingsContext.SettingsContext()
  fullName: System.Configuration.SettingsContext.SettingsContext()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> klasse."
  syntax:
    content: public SettingsContext ();
    parameters: []
  overload: System.Configuration.SettingsContext.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.Hashtable
  isExternal: false
  name: System.Collections.Hashtable
- uid: System.Configuration.SettingsContext.#ctor
  parent: System.Configuration.SettingsContext
  isExternal: false
  name: SettingsContext()
  nameWithType: SettingsContext.SettingsContext()
  fullName: System.Configuration.SettingsContext.SettingsContext()
- uid: System.Configuration.SettingsContext.#ctor*
  parent: System.Configuration.SettingsContext
  isExternal: false
  name: SettingsContext
  nameWithType: SettingsContext.SettingsContext
