### YamlMime:ManagedReference
items:
- uid: System.Windows.BaseValueSource
  id: BaseValueSource
  children:
  - System.Windows.BaseValueSource.Default
  - System.Windows.BaseValueSource.DefaultStyle
  - System.Windows.BaseValueSource.DefaultStyleTrigger
  - System.Windows.BaseValueSource.ImplicitStyleReference
  - System.Windows.BaseValueSource.Inherited
  - System.Windows.BaseValueSource.Local
  - System.Windows.BaseValueSource.ParentTemplate
  - System.Windows.BaseValueSource.ParentTemplateTrigger
  - System.Windows.BaseValueSource.Style
  - System.Windows.BaseValueSource.StyleTrigger
  - System.Windows.BaseValueSource.TemplateTrigger
  - System.Windows.BaseValueSource.Unknown
  langs:
  - csharp
  name: BaseValueSource
  nameWithType: BaseValueSource
  fullName: System.Windows.BaseValueSource
  type: Enum
  summary: "Identifiserer egenskapen system kilden for en bestemt avhengighet egenskapsverdi."
  remarks: "Denne opplisting er brukt av en egenskap i den <xref:System.Windows.ValueSource>-struktur som er anskaffet ved å kalle en <xref:System.Windows.DependencyPropertyHelper.GetValueSource%2A>metoden mot en bestemt avhengighetsegenskapen.</xref:System.Windows.DependencyPropertyHelper.GetValueSource%2A> </xref:System.Windows.ValueSource>       Hver verdi i denne opplisting angir at en spesiell del av samlede [!INCLUDE[TLA2#tla_winclient](~/add/includes/tla2sharptla-winclient-md.md)] egenskapen systemet er ansvarlig for fastsettelse gjeldende verdi for en bestemt avhengighet egenskapsverdi på et bestemt avhengighetsobjekt. Å lære mer om den [!INCLUDE[TLA2#tla_winclient](~/add/includes/tla2sharptla-winclient-md.md)] egenskapen systemet og prioriteten på som hver størrelsesforholdet for egenskapen system fungerer, kan du se [avhengighet egenskapen verdien prioriteten](~/add/includes/ajax-current-ext-md.md).       Verdien som standard er standardverdien for opplistingen."
  syntax:
    content: public enum BaseValueSource
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Windows.BaseValueSource.Default
  id: Default
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Default
  nameWithType: BaseValueSource.Default
  fullName: System.Windows.BaseValueSource.Default
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Kilden er standardverdien som er angitt av egenskapmetadata."
  syntax:
    content: Default
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.DefaultStyle
  id: DefaultStyle
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: DefaultStyle
  nameWithType: BaseValueSource.DefaultStyle
  fullName: System.Windows.BaseValueSource.DefaultStyle
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Datakilden er fra en aksesamlingen i standardstilen. Standardstilen kommer fra gjeldende tema."
  syntax:
    content: DefaultStyle
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.DefaultStyleTrigger
  id: DefaultStyleTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: DefaultStyleTrigger
  nameWithType: BaseValueSource.DefaultStyleTrigger
  fullName: System.Windows.BaseValueSource.DefaultStyleTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Kilden er fra en utløser i standardstilen. Standardstilen kommer fra gjeldende tema."
  syntax:
    content: DefaultStyleTrigger
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.ImplicitStyleReference
  id: ImplicitStyleReference
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: ImplicitStyleReference
  nameWithType: BaseValueSource.ImplicitStyleReference
  fullName: System.Windows.BaseValueSource.ImplicitStyleReference
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Source er en implisitt referanse (stil er basert på registrerte typen eller basert på type). Denne verdien, returneres bare for seg selv, stilegenskapen ikke for egenskaper som er angitt i setters eller utløsere på slike en stil."
  syntax:
    content: ImplicitStyleReference
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.Inherited
  id: Inherited
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Inherited
  nameWithType: BaseValueSource.Inherited
  fullName: System.Windows.BaseValueSource.Inherited
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Datakilden er en verdi gjennom egenskapen verdien arv."
  syntax:
    content: Inherited
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.Local
  id: Local
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Local
  nameWithType: BaseValueSource.Local
  fullName: System.Windows.BaseValueSource.Local
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Source er en lokalt angitt verdi."
  syntax:
    content: Local
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.ParentTemplate
  id: ParentTemplate
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: ParentTemplate
  nameWithType: BaseValueSource.ParentTemplate
  fullName: System.Windows.BaseValueSource.ParentTemplate
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Datakilden er basert på en mal for overordnede brukes av et element."
  syntax:
    content: ParentTemplate
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.ParentTemplateTrigger
  id: ParentTemplateTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: ParentTemplateTrigger
  nameWithType: BaseValueSource.ParentTemplateTrigger
  fullName: System.Windows.BaseValueSource.ParentTemplateTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Datakilden er en utløser kodebasert verdi fra en mal for overordnede som opprettet elementet."
  syntax:
    content: ParentTemplateTrigger
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.Style
  id: Style
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Style
  nameWithType: BaseValueSource.Style
  fullName: System.Windows.BaseValueSource.Style
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Datakilden er fra en stil for aksesamlingen for en ikke-tema-stil."
  syntax:
    content: Style
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.StyleTrigger
  id: StyleTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: StyleTrigger
  nameWithType: BaseValueSource.StyleTrigger
  fullName: System.Windows.BaseValueSource.StyleTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Datakilden er en utløser kodebasert verdi for en ikke-tema-stil."
  syntax:
    content: StyleTrigger
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.TemplateTrigger
  id: TemplateTrigger
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: TemplateTrigger
  nameWithType: BaseValueSource.TemplateTrigger
  fullName: System.Windows.BaseValueSource.TemplateTrigger
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Datakilden er en utløser kodebasert verdi i en mal som kommer fra en ikke-tema-stil."
  syntax:
    content: TemplateTrigger
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.BaseValueSource.Unknown
  id: Unknown
  parent: System.Windows.BaseValueSource
  langs:
  - csharp
  name: Unknown
  nameWithType: BaseValueSource.Unknown
  fullName: System.Windows.BaseValueSource.Unknown
  type: Field
  assemblies:
  - PresentationFramework
  namespace: System.Windows
  summary: "Datakilden er ukjent. Dette er standardverdien."
  syntax:
    content: Unknown
    return:
      type: System.Windows.BaseValueSource
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Windows.BaseValueSource.Default
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Default
  nameWithType: BaseValueSource.Default
  fullName: System.Windows.BaseValueSource.Default
- uid: System.Windows.BaseValueSource
  parent: System.Windows
  isExternal: false
  name: BaseValueSource
  nameWithType: BaseValueSource
  fullName: System.Windows.BaseValueSource
- uid: System.Windows.BaseValueSource.DefaultStyle
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: DefaultStyle
  nameWithType: BaseValueSource.DefaultStyle
  fullName: System.Windows.BaseValueSource.DefaultStyle
- uid: System.Windows.BaseValueSource.DefaultStyleTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: DefaultStyleTrigger
  nameWithType: BaseValueSource.DefaultStyleTrigger
  fullName: System.Windows.BaseValueSource.DefaultStyleTrigger
- uid: System.Windows.BaseValueSource.ImplicitStyleReference
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: ImplicitStyleReference
  nameWithType: BaseValueSource.ImplicitStyleReference
  fullName: System.Windows.BaseValueSource.ImplicitStyleReference
- uid: System.Windows.BaseValueSource.Inherited
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Inherited
  nameWithType: BaseValueSource.Inherited
  fullName: System.Windows.BaseValueSource.Inherited
- uid: System.Windows.BaseValueSource.Local
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Local
  nameWithType: BaseValueSource.Local
  fullName: System.Windows.BaseValueSource.Local
- uid: System.Windows.BaseValueSource.ParentTemplate
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: ParentTemplate
  nameWithType: BaseValueSource.ParentTemplate
  fullName: System.Windows.BaseValueSource.ParentTemplate
- uid: System.Windows.BaseValueSource.ParentTemplateTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: ParentTemplateTrigger
  nameWithType: BaseValueSource.ParentTemplateTrigger
  fullName: System.Windows.BaseValueSource.ParentTemplateTrigger
- uid: System.Windows.BaseValueSource.Style
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Style
  nameWithType: BaseValueSource.Style
  fullName: System.Windows.BaseValueSource.Style
- uid: System.Windows.BaseValueSource.StyleTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: StyleTrigger
  nameWithType: BaseValueSource.StyleTrigger
  fullName: System.Windows.BaseValueSource.StyleTrigger
- uid: System.Windows.BaseValueSource.TemplateTrigger
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: TemplateTrigger
  nameWithType: BaseValueSource.TemplateTrigger
  fullName: System.Windows.BaseValueSource.TemplateTrigger
- uid: System.Windows.BaseValueSource.Unknown
  parent: System.Windows.BaseValueSource
  isExternal: false
  name: Unknown
  nameWithType: BaseValueSource.Unknown
  fullName: System.Windows.BaseValueSource.Unknown
