### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.ApplicationHost
  id: ApplicationHost
  children:
  - System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  langs:
  - csharp
  name: ApplicationHost
  nameWithType: ApplicationHost
  fullName: System.Web.Hosting.ApplicationHost
  type: Class
  summary: "Aktiverer verter for ASP.NET-sider utenfor webprogrammet Internet Information Services (IIS). Denne klassen gjør det mulig å opprette programdomener for behandling av ASP.NET-forespørsler."
  remarks: "ApplicationHost introduseres i .NET Framework, versjon 3.5.  Hvis du vil ha mer informasjon, se [versjoner og avhengigheter](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public sealed class ApplicationHost
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  id: CreateApplicationHost(System.Type,System.String,System.String)
  parent: System.Web.Hosting.ApplicationHost
  langs:
  - csharp
  name: CreateApplicationHost(Type,String,String)
  nameWithType: ApplicationHost.CreateApplicationHost(Type,String,String)
  fullName: System.Web.Hosting.ApplicationHost.CreateApplicationHost(Type,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Oppretter og konfigurerer et programdomene som vert for ASP.NET."
  syntax:
    content: public static object CreateApplicationHost (Type hostType, string virtualDir, string physicalDir);
    parameters:
    - id: hostType
      type: System.Type
      description: "Navnet på en brukerangitte klasse skal opprettes i det nye domenet for programmet."
    - id: virtualDir
      type: System.String
      description: "Den virtuelle mappen for programdomenet; for eksempel/MyApp."
    - id: physicalDir
      type: System.String
      description: "Den fysiske katalogen for programdomenet der ASP.NET-sider finnes; for eksempel c:\\mypages."
    return:
      type: System.Object
      description: "En forekomst av den brukerangitte klassen som er brukt til å formidle kall til nyopprettede programdomenet."
  overload: System.Web.Hosting.ApplicationHost.CreateApplicationHost*
  exceptions:
  - type: System.PlatformNotSupportedException
    commentId: T:System.PlatformNotSupportedException
    description: "Web vertsdatamaskinen kjører ikke Windows NT-plattformen eller et Coriolis miljø."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.PlatformNotSupportedException
  isExternal: true
  name: System.PlatformNotSupportedException
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  parent: System.Web.Hosting.ApplicationHost
  isExternal: false
  name: CreateApplicationHost(Type,String,String)
  nameWithType: ApplicationHost.CreateApplicationHost(Type,String,String)
  fullName: System.Web.Hosting.ApplicationHost.CreateApplicationHost(Type,String,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost*
  parent: System.Web.Hosting.ApplicationHost
  isExternal: false
  name: CreateApplicationHost
  nameWithType: ApplicationHost.CreateApplicationHost
