### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComUdtElement
  id: ComUdtElement
  children:
  - System.ServiceModel.Configuration.ComUdtElement.#ctor
  - System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ComUdtElement.Name
  - System.ServiceModel.Configuration.ComUdtElement.Properties
  - System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  - System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  - System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  langs:
  - csharp
  name: ComUdtElement
  nameWithType: ComUdtElement
  fullName: System.ServiceModel.Configuration.ComUdtElement
  type: Class
  summary: "Representerer en bruker angitt Type (UDT) som skal inkluderes i servicekontrakten. Denne klassen kan ikke arves."
  remarks: "Kjøretiden for COM +-integrering oppretter services ved å undersøke typebiblioteket. Når en COM +-komponent inneholder metoder som sendes en `VARIANT`, systemet kan ikke fastslå de faktiske typene som skal sendes før kjøring. Derfor når du prøver å sende en bruker angitt Type (UDT) i en `VARIANT`, den ikke fordi den ikke er en kjent type for serialisering.       Hvis du vil omgå problemet, kan du legge UDTs konfigurasjonsfilen slik at de kan bli inkludert som kjente typer i riktig servicekontrakten. For å gjøre dette, må du gi en unik identifikasjon av UDT og kontrakten, som er den opprinnelige COM grensesnitt som bruker den.       Eksemplet nedenfor viser legger til to bestemte UDTs til den `userDefinedTypes`> delen av konfigurasjonsfilen for dette formålet.       [!code-cs[XpsCreate #XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent) ] attributtene for den `userDefinedType`> elementet er definert som følger:- `typeName`: et valgfritt attributt som inneholder navnet på lesbar. Dette brukes ikke av kjøretiden, men hjelper leseren til å skille mellom typene.      - `typeLibID`: en GUID-streng som angir registrerte typebiblioteket som definerer typen.      - `typeLibVersion`: en streng som angir typen bibliotek-versjonen som definerer typen.      - `typeDefID`: en GUID-streng som angir bestemte UDT i registrerte typebiblioteket.       Når tjenesten er initialisert, kjøretiden for COM +-integrering søker etter de angitte typene og legger dem til samlingen kjente typer for de angitte avtaler."
  example:
  - "The following example demonstrates adding two specific UDTs to the <`userDefinedTypes`> section of the configuration file for this purpose.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: 'public sealed class ComUdtElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: ComUdtElement()
  nameWithType: ComUdtElement.ComUdtElement()
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.ComUdtElement&quot;> </xref> klasse."
  syntax:
    content: public ComUdtElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: ComUdtElement(String)
  nameWithType: ComUdtElement.ComUdtElement(String)
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.ComUdtElement&quot;> </xref> klassen med angitt GUID-strengen."
  syntax:
    content: public ComUdtElement (string typeDefID);
    parameters:
    - id: typeDefID
      type: System.String
      description: "En streng med GUID som identifiserer bestemte UDT i registrerte typebiblioteket."
  overload: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: Name
  nameWithType: ComUdtElement.Name
  fullName: System.ServiceModel.Configuration.ComUdtElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir navnet på lesbar."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Lesbar Typenavnet."
  overload: System.ServiceModel.Configuration.ComUdtElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: Properties
  nameWithType: ComUdtElement.Properties
  fullName: System.ServiceModel.Configuration.ComUdtElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.ServiceModel.Configuration.ComUdtElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  id: TypeDefID
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en GUID-streng som identifiserer bestemte UDT i registrerte typebiblioteket."
  syntax:
    content: public string TypeDefID { get; set; }
    return:
      type: System.String
      description: "Bestemte UDT typen i registrerte typebiblioteket."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeDefID*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  id: TypeLibID
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en GUID-streng som identifiserer registrerte typebiblioteket som definerer typen."
  syntax:
    content: public string TypeLibID { get; set; }
    return:
      type: System.String
      description: "Registrerte typebiblioteket som definerer typen."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeLibID*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  id: TypeLibVersion
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en streng som identifiserer typen biblioteket versjonen som definerer typen."
  syntax:
    content: public string TypeLibVersion { get; set; }
    return:
      type: System.String
      description: "Den type biblioteket versjonen som definerer typen."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement()
  nameWithType: ComUdtElement.ComUdtElement()
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement()
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement(String)
  nameWithType: ComUdtElement.ComUdtElement(String)
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ComUdtElement.Name
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Name
  nameWithType: ComUdtElement.Name
  fullName: System.ServiceModel.Configuration.ComUdtElement.Name
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Properties
  nameWithType: ComUdtElement.Properties
  fullName: System.ServiceModel.Configuration.ComUdtElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement
  nameWithType: ComUdtElement.ComUdtElement
- uid: System.ServiceModel.Configuration.ComUdtElement.Name*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Name
  nameWithType: ComUdtElement.Name
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Properties
  nameWithType: ComUdtElement.Properties
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
