### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  id: NamedPipeConnectionPoolSettingsElement
  children:
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  langs:
  - csharp
  name: NamedPipeConnectionPoolSettingsElement
  nameWithType: NamedPipeConnectionPoolSettingsElement
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  type: Class
  summary: "Representerer en konfigurasjonselementet som angir ekstra tilkobling applikasjonsutvalget innstillingene for en navngitt datakanal transport. Denne klassen kan ikke arves."
  syntax:
    content: 'public sealed class NamedPipeConnectionPoolSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: NamedPipeConnectionPoolSettingsElement()
  nameWithType: NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement&quot;> </xref> klasse."
  syntax:
    content: public NamedPipeConnectionPoolSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  id: GroupName
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en streng som definerer navnet på tilkoblingskøen brukes for utgående kanaler"
  remarks: "I flyt modus er tilkoblinger ikke delt, noe som betyr at tilkoblingsutvalg er deaktivert. Standard er en &quot;standard&quot;-streng. Du kan endre verdien for å isolere tilkoblinger for en bestemt client i egen grupper."
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "En streng som definerer navnet på tilkoblingskøen brukes for utgående kanaler"
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir den maksimale tiden tilkoblingen kan være inaktiv før den kobles fra."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Et positivt <xref:System.TimeSpan>som angir den maksimale tiden tilkoblingen kan være inaktiv før den kobles fra.</xref:System.TimeSpan> Standarden er 02:00:00."
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir maksimalt antall tilkoblinger til en ekstern endepunktet startet av tjenesten."
  remarks: "Tilkoblinger ved overskrider grensen er i kø før et mellomrom under grensen er tilgjengelig. Denne egenskapen begrenser hvor lenge der tilkoblinger bli værende i kø før et unntak.       Denne egenskapen begrenser antall samtidig aktive tilkoblinger fra klienten til en bestemt serviceendepunktet. Hvis denne verdien er overskredet ved at flere aktive klienttilkoblinger, kan tjenesten vises ikke svarer til klienten. I dette tilfellet skal denne verdien justeres til å overskride det maksimale antallet forventet samtidige klienttilkoblinger til et bestemt endepunkt."
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "Et positivt heltall som angir maksimalt antall tilkoblinger til eksterne endepunktet til en startet av tjenesten. Standard er 10."
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: NamedPipeConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: NamedPipeConnectionPoolSettingsElement()
  nameWithType: NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: NamedPipeConnectionPoolSettingsElement
  nameWithType: NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettingsElement.GroupName
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettingsElement.IdleTimeout
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeConnectionPoolSettingsElement.Properties
