### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CustomError
  id: CustomError
  children:
  - System.Web.Configuration.CustomError.#ctor(System.Int32,System.String)
  - System.Web.Configuration.CustomError.Equals(System.Object)
  - System.Web.Configuration.CustomError.GetHashCode
  - System.Web.Configuration.CustomError.Properties
  - System.Web.Configuration.CustomError.Redirect
  - System.Web.Configuration.CustomError.StatusCode
  langs:
  - csharp
  name: CustomError
  nameWithType: CustomError
  fullName: System.Web.Configuration.CustomError
  type: Class
  summary: "Konfigurerer en CustomError del for å tilordne en ASP.NET-feilkode til en egendefinert side. Denne klassen kan arves."
  remarks: "Klassen CustomError gjør det mulig å programmatisk tilgang til og endre den `error` delen av konfigurasjonsfilen. Denne typen er en del av en gruppe som inneholder den <xref:System.Web.Configuration.CustomErrorCollection>, <xref:System.Web.Configuration.CustomErrorsMode>, og <xref:System.Web.Configuration.CustomErrorsSection>.</xref:System.Web.Configuration.CustomErrorsSection> </xref:System.Web.Configuration.CustomErrorsMode> </xref:System.Web.Configuration.CustomErrorCollection>      > [!NOTE] > Når du definerer en egendefinert feilmelding, ASP.NET tilordnes den standard feilen vanligvis utstedt av den underliggende tjenesten, for eksempel IIS. For eksempel hvis du definerer en egendefinert feilmelding for statuskoden 404, får ASP.NET den hver gang du referere til en ikke-eksisterende .aspx-siden. Egendefinerte feilmeldinger utstedes bare for disse elementene som behandles av ASP.NET. Hvis du refererer til en ikke-eksisterende htm-side, utsteder for eksempel IIS standard 404 feilen."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `customErrors` section, which can also be accessed as members of the CustomError class.  \n  \n The following configuration file example shows how to specify values declaratively for the `customErrors` section.  \n  \n```  \n<customErrors mode=\"RemoteOnly\"  \n  defaultRedirect=\"customerror.htm\">  \n    <error statusCode=\"404\" redirect=\"customerror404.htm\"/>  \n</customErrors>  \n```  \n  \n The following code example demonstrates how to use the CustomError class.  \n  \n [!code-vb[System.Web.Configuration.CustomError#1](~/add/codesnippet/visualbasic/t-system.web.configurati_47_1.vb)]\n [!code-cs[System.Web.Configuration.CustomError#1](~/add/codesnippet/csharp/t-system.web.configurati_47_1.cs)]"
  syntax:
    content: 'public sealed class CustomError : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.CustomError.#ctor(System.Int32,System.String)
  id: '#ctor(System.Int32,System.String)'
  parent: System.Web.Configuration.CustomError
  langs:
  - csharp
  name: CustomError(Int32,String)
  nameWithType: CustomError.CustomError(Int32,String)
  fullName: System.Web.Configuration.CustomError.CustomError(Int32,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.CustomError&quot;> </xref> klasse."
  remarks: "Konstruktøren CustomError skal ikke brukes direkte fra koden. Kalles av ASP.NET Konfigurasjonssystemet. Du hente en forekomst av den <xref:System.Web.Configuration.CustomError>klassen ved hjelp av den <xref:System.Configuration.Configuration.GetSection%2A>metoden.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.CustomError>"
  syntax:
    content: public CustomError (int statusCode, string redirect);
    parameters:
    - id: statusCode
      type: System.Int32
      description: "HTTP-statuskoden som fører til omadressering til feilmeldingssiden."
    - id: redirect
      type: System.String
      description: "URL-adressen for den egendefinerte siden tilordnet feilkoden."
  overload: System.Web.Configuration.CustomError.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomError.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.CustomError
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: CustomError.Equals(Object)
  fullName: System.Web.Configuration.CustomError.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Sammenligner <xref href=&quot;System.Web.Configuration.CustomError&quot;> </xref> feil."
  remarks: "Metoden er lik sammenligner alle feil objektene som er sendt til metoden."
  syntax:
    content: public override bool Equals (object customError);
    parameters:
    - id: customError
      type: System.Object
      description: "Feil skal sammenlignes med."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis feilene er like. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.CustomError.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomError.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.CustomError
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: CustomError.GetHashCode()
  fullName: System.Web.Configuration.CustomError.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter den <xref href=&quot;System.Web.Configuration.CustomError&quot;> </xref> objekt hash-kode."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Den <xref href=&quot;System.Web.Configuration.CustomError&quot;> </xref> objekt hash-kode."
  overload: System.Web.Configuration.CustomError.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomError.Properties
  id: Properties
  parent: System.Web.Configuration.CustomError
  langs:
  - csharp
  name: Properties
  nameWithType: CustomError.Properties
  fullName: System.Web.Configuration.CustomError.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Web.Configuration.CustomError.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomError.Redirect
  id: Redirect
  parent: System.Web.Configuration.CustomError
  langs:
  - csharp
  name: Redirect
  nameWithType: CustomError.Redirect
  fullName: System.Web.Configuration.CustomError.Redirect
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir URL-adressen for omadressering."
  remarks: "Egenskapen omadressering identifiserer URL-adressen for den egendefinerte siden som er forbundet med en bestemt feil."
  example:
  - "The following code example shows how to use the redirection URL. Refer to the code example in the <xref:System.Web.Configuration.CustomError> class topic to learn how to get the collection.  \n  \n [!code-vb[System.Web.Configuration.CustomError#4](~/add/codesnippet/visualbasic/p-system.web.configurati_297_1.vb)]\n [!code-cs[System.Web.Configuration.CustomError#4](~/add/codesnippet/csharp/p-system.web.configurati_297_1.cs)]"
  syntax:
    content: public string Redirect { get; set; }
    return:
      type: System.String
      description: "URL-adressen som programmet omdirigeres når det oppstår en feil."
  overload: System.Web.Configuration.CustomError.Redirect*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomError.StatusCode
  id: StatusCode
  parent: System.Web.Configuration.CustomError
  langs:
  - csharp
  name: StatusCode
  nameWithType: CustomError.StatusCode
  fullName: System.Web.Configuration.CustomError.StatusCode
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir statuskoden for HTTP-feil."
  remarks: "HTTP-statuskode brukes av ASP.NET-infrastruktur for å omdirigere programmet til feilmeldingssiden når det oppstår en feil.      > [!NOTE] > Den egendefinerte feilmeldingen utstedes bare hvis det er et resultat av en enhet som behandles av ASP.NET; ellers en standard feil er utstedt."
  example:
  - "The following code example shows how to use the status code. Refer to the code example in the <xref:System.Web.Configuration.CustomError> class topic to learn how to get the collection.  \n  \n [!code-vb[System.Web.Configuration.CustomError#5](~/add/codesnippet/visualbasic/p-system.web.configurati_351_1.vb)]\n [!code-cs[System.Web.Configuration.CustomError#5](~/add/codesnippet/csharp/p-system.web.configurati_351_1.cs)]"
  syntax:
    content: public int StatusCode { get; set; }
    return:
      type: System.Int32
      description: "HTTP feilstatuskode som fører til at omadressering til den egendefinerte feilmeldingssiden."
  overload: System.Web.Configuration.CustomError.StatusCode*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.CustomError.#ctor(System.Int32,System.String)
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: CustomError(Int32,String)
  nameWithType: CustomError.CustomError(Int32,String)
  fullName: System.Web.Configuration.CustomError.CustomError(Int32,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.CustomError.Equals(System.Object)
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: Equals(Object)
  nameWithType: CustomError.Equals(Object)
  fullName: System.Web.Configuration.CustomError.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.CustomError.GetHashCode
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: GetHashCode()
  nameWithType: CustomError.GetHashCode()
  fullName: System.Web.Configuration.CustomError.GetHashCode()
- uid: System.Web.Configuration.CustomError.Properties
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: Properties
  nameWithType: CustomError.Properties
  fullName: System.Web.Configuration.CustomError.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.CustomError.Redirect
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: Redirect
  nameWithType: CustomError.Redirect
  fullName: System.Web.Configuration.CustomError.Redirect
- uid: System.Web.Configuration.CustomError.StatusCode
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: StatusCode
  nameWithType: CustomError.StatusCode
  fullName: System.Web.Configuration.CustomError.StatusCode
- uid: System.Web.Configuration.CustomError.#ctor*
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: CustomError
  nameWithType: CustomError.CustomError
- uid: System.Web.Configuration.CustomError.Equals*
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: Equals
  nameWithType: CustomError.Equals
- uid: System.Web.Configuration.CustomError.GetHashCode*
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: GetHashCode
  nameWithType: CustomError.GetHashCode
- uid: System.Web.Configuration.CustomError.Properties*
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: Properties
  nameWithType: CustomError.Properties
- uid: System.Web.Configuration.CustomError.Redirect*
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: Redirect
  nameWithType: CustomError.Redirect
- uid: System.Web.Configuration.CustomError.StatusCode*
  parent: System.Web.Configuration.CustomError
  isExternal: false
  name: StatusCode
  nameWithType: CustomError.StatusCode
