### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.ChannelPoolSettings
  id: ChannelPoolSettings
  children:
  - System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  - System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  - System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  - System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  langs:
  - csharp
  name: ChannelPoolSettings
  nameWithType: ChannelPoolSettings
  fullName: System.ServiceModel.Channels.ChannelPoolSettings
  type: Class
  summary: "Angir opp for kanaler som hører til et utvalg av kanaler som brukes av endepunktet til en tjeneste."
  remarks: "Opp brukes som en policy mekanisme for å hindre at forbruket av mye ressurser. De forhindre avslått for Service (DOS) angrep som skadelig eller tilsiktet. Bruk denne klassen ved angivelse av kanalen opp på en egendefinert kanal.       ChannelPoolSettings angir tre opp:- <xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>til å angi maksimalt antall tidsintervallet som kanaler for i programutvalget kan være inaktiv før blir lukket.</xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>til å angi tidsintervallet før en kanal når returneres til utvalget, er lukket.</xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>til å angi maksimalt antall kanaler som kan lagres i programutvalget for hver eksterne endepunktet.</xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>"
  syntax:
    content: public class ChannelPoolSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: ChannelPoolSettings()
  nameWithType: ChannelPoolSettings.ChannelPoolSettings()
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.ChannelPoolSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Channels.ChannelPoolSettings&quot;> </xref> klasse."
  remarks: "Settet med standard verdier er:- <xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>: 2 minutter.</xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>: 10 minutter.</xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>      - <xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>: 10 kanaler.</xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>       Disse standardverdiene kvoten er basert på en skje beskjeden tildeling av ressurser som passer for utviklingsmiljøer og lavt installasjonsscenarier. Tjenesteadministratorer må gå gjennom kanal opp og justere individuelle kvoteverdier Hvis en installasjon som kjører tom for ressurser eller tilkoblinger begrenses tross tilgjengeligheten av flere ressurser."
  syntax:
    content: public ChannelPoolSettings ();
    parameters: []
  overload: System.ServiceModel.Channels.ChannelPoolSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Får eller angir det maksimale tidsintervallet som kanaler for i programutvalget kan være inaktiv før blir lukket."
  remarks: "Kvoten IdleTimeout brukes til å begrense avslått for Service (DOS) angrep på serveren som avhenger av binde opp ressurser i lengre tid. På klienten, kan angi den riktige verdien øke påliteligheten til å koble til tjenesten. Standardverdien er basert på en skje beskjeden tildeling av ressurser. Det passer for et utviklingsmiljø og lavt installasjonsscenarier. Tjenesteadministratorer bør se verdien hvis en installasjon som kjører tom for ressurser eller tilkoblinger begrenses tross tilgjengeligheten av flere ressurser."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Den <xref:System.TimeSpan>som angir det maksimale tidsintervallet som kanaler for i programutvalget kan være inaktiv før blir lukket.</xref:System.TimeSpan> Standardverdien er 2 minutter."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Verdien er mindre enn null eller større enn T:System.Int32.MaxValue i millisekunder."
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Henter eller angir levetiden for en kanal, før den er lukket."
  remarks: "Kvoten LeaseTimeout brukes til å for integrering med belastningsfordeling og for å forbedre påliteligheten. Standardverdien er basert på en konservativ tildeling av ressurser. Det passer for et utviklingsmiljø og lavt installasjonsscenarier. Tjenesteadministratorer bør se verdien hvis en installasjon som kjører tom for ressurser eller tilkoblinger begrenses tross tilgjengeligheten av flere ressurser."
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "En <xref:System.TimeSpan>som angir levetiden for en kanal, før den er lukket.</xref:System.TimeSpan> Standardverdien er 10 minutter."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Verdien er mindre enn null."
  platform:
  - net462
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  id: MaxOutboundChannelsPerEndpoint
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Henter eller angir det maksimale antallet kanaler tilkobling til eksterne endepunktene kan startes med tjenesten."
  remarks: "Kvoten MaxOutboundChannelsPerEndpoint angir hurtigbufferen begrenser på klienten og serveren, og brukes til å forbedre påliteligheten. Standardverdien er basert på en skje beskjeden tildeling av ressurser som passer for et utviklingsmiljø og lavt installasjonsscenarier. Tjenesteadministratorer bør se verdien hvis en installasjon som kjører tom for ressurser eller tilkoblinger begrenses tross tilgjengeligheten av flere ressurser."
  syntax:
    content: public int MaxOutboundChannelsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "Et positivt heltall som angir det maksimale antallet kanaler til eksterne endepunktet i programutvalget kan startes med tjenesten. Standardverdien er 10 kanaler."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Verdien er mindre enn null."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: ChannelPoolSettings()
  nameWithType: ChannelPoolSettings.ChannelPoolSettings()
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.ChannelPoolSettings()
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: ChannelPoolSettings
  nameWithType: ChannelPoolSettings.ChannelPoolSettings
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
