### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  id: X509DefaultServiceCertificateElement
  children:
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.#ctor
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy(System.ServiceModel.Configuration.X509DefaultServiceCertificateElement)
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType
  langs:
  - csharp
  name: X509DefaultServiceCertificateElement
  nameWithType: X509DefaultServiceCertificateElement
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  type: Class
  summary: "Representerer en konfigurasjonselementet som angir en standard sertifikatet som brukes av en tjeneste. Denne klassen kan ikke arves."
  syntax:
    content: 'public sealed class X509DefaultServiceCertificateElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: X509DefaultServiceCertificateElement()
  nameWithType: X509DefaultServiceCertificateElement.X509DefaultServiceCertificateElement()
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509DefaultServiceCertificateElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.X509DefaultServiceCertificateElement&quot;> </xref> klasse."
  syntax:
    content: public X509DefaultServiceCertificateElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy(System.ServiceModel.Configuration.X509DefaultServiceCertificateElement)
  id: Copy(System.ServiceModel.Configuration.X509DefaultServiceCertificateElement)
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: Copy(X509DefaultServiceCertificateElement)
  nameWithType: X509DefaultServiceCertificateElement.Copy(X509DefaultServiceCertificateElement)
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy(X509DefaultServiceCertificateElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Kopierer innholdet i den angitte konfigurasjonselementet til dette konfigurasjonselementet."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509DefaultServiceCertificateElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
      description: "Konfigurasjonselementet som skal kopieres."
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Konfigurasjonsfilen er skrivebeskyttet."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: FindValue
  nameWithType: X509DefaultServiceCertificateElement.FindValue
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en streng som angir verdien til å søke etter i X.509 sertifikatlageret."
  remarks: "Typen som finnes i denne egenskapen må oppfylle kravene til den angitte <xref:System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType%2A>verdi.</xref:System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType%2A> Standarden er en tom streng."
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "Verdien til å søke etter i X.509 sertifikatlageret."
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509DefaultServiceCertificateElement.Properties
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: X509DefaultServiceCertificateElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en verdi som angir plasseringen av sertifikatlageret klienten kan bruke til å validere serversertifikatet."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "En <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref> som angir plasseringen til sertifikatlageret klienten kan bruke til å validere serversertifikatet. Standardverdien er <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>."
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: StoreName
  nameWithType: X509DefaultServiceCertificateElement.StoreName
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir navnet på X.509 sertifikatlageret til å åpne."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "En <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref> som inneholder navnet på X.509 sertifikatlageret til å åpne."
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: X509DefaultServiceCertificateElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir typen X.509 søk kjøres."
  remarks: "Hvilken <xref:System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue%2A>må oppfylle kravene for denne egenskapen.</xref:System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue%2A>"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "En <xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref> som angir typen X.509 søk kjøres."
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.#ctor
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: X509DefaultServiceCertificateElement()
  nameWithType: X509DefaultServiceCertificateElement.X509DefaultServiceCertificateElement()
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509DefaultServiceCertificateElement()
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy(System.ServiceModel.Configuration.X509DefaultServiceCertificateElement)
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: Copy(X509DefaultServiceCertificateElement)
  nameWithType: X509DefaultServiceCertificateElement.Copy(X509DefaultServiceCertificateElement)
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy(X509DefaultServiceCertificateElement)
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509DefaultServiceCertificateElement
  nameWithType: X509DefaultServiceCertificateElement
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: FindValue
  nameWithType: X509DefaultServiceCertificateElement.FindValue
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: Properties
  nameWithType: X509DefaultServiceCertificateElement.Properties
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509DefaultServiceCertificateElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: StoreName
  nameWithType: X509DefaultServiceCertificateElement.StoreName
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: X509FindType
  nameWithType: X509DefaultServiceCertificateElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.#ctor*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: X509DefaultServiceCertificateElement
  nameWithType: X509DefaultServiceCertificateElement.X509DefaultServiceCertificateElement
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: Copy
  nameWithType: X509DefaultServiceCertificateElement.Copy
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: FindValue
  nameWithType: X509DefaultServiceCertificateElement.FindValue
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: Properties
  nameWithType: X509DefaultServiceCertificateElement.Properties
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509DefaultServiceCertificateElement.StoreLocation
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: StoreName
  nameWithType: X509DefaultServiceCertificateElement.StoreName
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: X509FindType
  nameWithType: X509DefaultServiceCertificateElement.X509FindType
