### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.NetMsmqSecurity
  id: NetMsmqSecurity
  children:
  - System.ServiceModel.NetMsmqSecurity.#ctor
  - System.ServiceModel.NetMsmqSecurity.Message
  - System.ServiceModel.NetMsmqSecurity.Mode
  - System.ServiceModel.NetMsmqSecurity.Transport
  langs:
  - csharp
  name: NetMsmqSecurity
  nameWithType: NetMsmqSecurity
  fullName: System.ServiceModel.NetMsmqSecurity
  type: Class
  summary: "Klassen NetMsmqSecurity innkapsler MSMQ-sikkerhet-funksjonene som er tilgjengelige når du bruker den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> binding."
  remarks: "Objekter av denne typen er opprettet ved å opprette en forekomst av den <xref:System.ServiceModel.NetMsmqBinding>binding.</xref:System.ServiceModel.NetMsmqBinding> Du kan deretter bruke dette objektet for å referere til alle ulike innstillinger som er knyttet til den <xref:System.ServiceModel.NetMsmqBinding>binding.</xref:System.ServiceModel.NetMsmqBinding>"
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#1](~/add/codesnippet/csharp/t-system.servicemodel.ne_3_1.cs)]
     [!code-vb[UENetMsmqSecurity#1](~/add/codesnippet/visualbasic/t-system.servicemodel.ne_3_1.vb)]
  syntax:
    content: public sealed class NetMsmqSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: NetMsmqSecurity()
  nameWithType: NetMsmqSecurity.NetMsmqSecurity()
  fullName: System.ServiceModel.NetMsmqSecurity.NetMsmqSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.NetMsmqSecurity&quot;> </xref> klasse."
  syntax:
    content: public NetMsmqSecurity ();
    parameters: []
  overload: System.ServiceModel.NetMsmqSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Message
  id: Message
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Message
  nameWithType: NetMsmqSecurity.Message
  fullName: System.ServiceModel.NetMsmqSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Henter eller angir den <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> som er knyttet til den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> binding."
  remarks: "Den <xref:System.ServiceModel.MessageSecurityOverMsmq>innkapsler sikkerhetsinnstillinger for SOAP-melding.</xref:System.ServiceModel.MessageSecurityOverMsmq>"
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#2](~/add/codesnippet/csharp/p-system.servicemodel.ne_11_1.cs)]
     [!code-vb[UENetMsmqSecurity#2](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_11_1.vb)]
  syntax:
    content: public System.ServiceModel.MessageSecurityOverMsmq Message { get; set; }
    return:
      type: System.ServiceModel.MessageSecurityOverMsmq
      description: "Den <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> som er knyttet til den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> binding."
  overload: System.ServiceModel.NetMsmqSecurity.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Mode
  id: Mode
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
  fullName: System.ServiceModel.NetMsmqSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Henter eller angir den <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> som er knyttet til den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> binding."
  remarks: "Angir hvilken type sikkerhet som brukes av den tilknyttede NetMsmqBinding for denne egenskapen. Listen nedenfor beskriver akseptable verdier:- **ingen** – ingen sikkerhet brukes.      - **Transport** -transportsikkerhet brukes.      - **Meldingen** -melding kodebasert sikkerhet brukes.      - **Begge** -begge meldingen kodebasert sikkerhet og transport sikkerhet brukes."
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#3](~/add/codesnippet/csharp/p-system.servicemodel.ne_13_1.cs)]
     [!code-vb[UENetMsmqSecurity#3](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_13_1.vb)]
  syntax:
    content: public System.ServiceModel.NetMsmqSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetMsmqSecurityMode
      description: "Den <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> som er knyttet til den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> binding."
  overload: System.ServiceModel.NetMsmqSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Verdien er ikke én av <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> verdier."
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Transport
  id: Transport
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
  fullName: System.ServiceModel.NetMsmqSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Henter eller angir den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> som er knyttet til den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> binding."
  remarks: "Denne egenskapen gir tilgang til MSMQ-Transport sikkerhetsinnstillinger."
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#4](~/add/codesnippet/csharp/p-system.servicemodel.ne_19_1.cs)]
     [!code-vb[UENetMsmqSecurity#4](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_19_1.vb)]
  syntax:
    content: public System.ServiceModel.MsmqTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.MsmqTransportSecurity
      description: "Den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> som er knyttet til den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> binding."
  overload: System.ServiceModel.NetMsmqSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.NetMsmqSecurity.#ctor
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: NetMsmqSecurity()
  nameWithType: NetMsmqSecurity.NetMsmqSecurity()
  fullName: System.ServiceModel.NetMsmqSecurity.NetMsmqSecurity()
- uid: System.ServiceModel.NetMsmqSecurity.Message
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurity.Message
  fullName: System.ServiceModel.NetMsmqSecurity.Message
- uid: System.ServiceModel.MessageSecurityOverMsmq
  parent: System.ServiceModel
  isExternal: false
  name: MessageSecurityOverMsmq
  nameWithType: MessageSecurityOverMsmq
  fullName: System.ServiceModel.MessageSecurityOverMsmq
- uid: System.ServiceModel.NetMsmqSecurity.Mode
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
  fullName: System.ServiceModel.NetMsmqSecurity.Mode
- uid: System.ServiceModel.NetMsmqSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetMsmqSecurityMode
  nameWithType: NetMsmqSecurityMode
  fullName: System.ServiceModel.NetMsmqSecurityMode
- uid: System.ServiceModel.NetMsmqSecurity.Transport
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
  fullName: System.ServiceModel.NetMsmqSecurity.Transport
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.NetMsmqSecurity.#ctor*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: NetMsmqSecurity
  nameWithType: NetMsmqSecurity.NetMsmqSecurity
- uid: System.ServiceModel.NetMsmqSecurity.Message*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurity.Message
- uid: System.ServiceModel.NetMsmqSecurity.Mode*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
- uid: System.ServiceModel.NetMsmqSecurity.Transport*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
