### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement
  id: IssuerNameRegistryElement
  children:
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  langs:
  - csharp
  name: IssuerNameRegistryElement
  nameWithType: IssuerNameRegistryElement
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement
  type: Class
  summary: "Representerer en <xref uid=&quot;langword_csharp_&lt;issuerNameRegistry&gt;&quot; name=&quot;&lt;issuerNameRegistry&gt;&quot; href=&quot;&quot;> </xref> element i en konfigurasjonsfil. Denne klassen kan ikke arves."
  remarks: "Den `<issuerNameRegistry>` elementet konfigurerer utsteder navnet registeret. Utsteder navnet registeret tilordner utsteder-token til et navn på tilkoblingsstrengen. Den <xref:System.IdentityModel.Configuration.IssuerNameRegistryElement.Type%2A>egenskapen (som representerer den `type` -attributtet for elementet) kan angis for å registrere en egendefinert.</xref:System.IdentityModel.Configuration.IssuerNameRegistryElement.Type%2A> Som standard en type <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>antas.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>       Den `<issuerNameRegistry>` -element kan angis på tjenestenivå under den `<identityConfiguration>` element eller på en sikkerhet token behandlingsprogrammet samling under den `<securityTokenHandlerConfiguration>` elementet. Den `IssuerNameRegistry` -egenskapen for den <xref:System.IdentityModel.Configuration.IdentityConfigurationElement>klassen av den <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement>klassen er en forekomst av IssuerNameRegistryElement.</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement> </xref:System.IdentityModel.Configuration.IdentityConfigurationElement>"
  syntax:
    content: 'public sealed class IssuerNameRegistryElement : System.IdentityModel.Configuration.ConfigurationElementInterceptor'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: IssuerNameRegistryElement()
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement()
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.IssuerNameRegistryElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.IdentityModel.Configuration.IssuerNameRegistryElement&quot;> </xref> klasse."
  syntax:
    content: public IssuerNameRegistryElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  id: Type
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Henter eller angir en strengrepresentasjon av den <xref:System.Type>av utsteder navnet registeret.</xref:System.Type>"
  remarks: "Denne egenskapen er valgfrie. Det samsvarer med den `type` for den `<issuerNameRegistry>` elementet. Hvis den ikke er angitt i egenskapen er `null`, en type <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>antas.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Strengrepresentasjon av den <xref:System.Type>av utsteder navnet registeret.</xref:System.Type> Typen må være utledet fra den <xref href=&quot;System.IdentityModel.Tokens.IssuerNameRegistry&quot;> </xref> klasse."
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: System.IdentityModel.Configuration.ConfigurationElementInterceptor
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: IssuerNameRegistryElement()
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement()
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.IssuerNameRegistryElement()
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: IssuerNameRegistryElement
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
