### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.NetNamedPipeSecurity
  id: NetNamedPipeSecurity
  children:
  - System.ServiceModel.NetNamedPipeSecurity.#ctor
  - System.ServiceModel.NetNamedPipeSecurity.Mode
  - System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport
  - System.ServiceModel.NetNamedPipeSecurity.Transport
  langs:
  - csharp
  name: NetNamedPipeSecurity
  nameWithType: NetNamedPipeSecurity
  fullName: System.ServiceModel.NetNamedPipeSecurity
  type: Class
  summary: "Gir tilgang til sikkerhetsinnstillingene for endepunkt som er konfigurert med bindingen for navngitte datakanalen."
  remarks: ''
  example:
  - "The following code shows how to add a NetNamedPipeSecurity object to a <xref:System.ServiceModel.NetNamedPipeBinding> instance.  \n  \n [!code-cs[S_UENetNamedPipeSecurity#1](~/add/codesnippet/csharp/t-system.servicemodel.ne_2_1.cs)]"
  syntax:
    content: public sealed class NetNamedPipeSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: NetNamedPipeSecurity()
  nameWithType: NetNamedPipeSecurity.NetNamedPipeSecurity()
  fullName: System.ServiceModel.NetNamedPipeSecurity.NetNamedPipeSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.NetNamedPipeSecurity&quot;> </xref> klasse."
  syntax:
    content: public NetNamedPipeSecurity ();
    parameters: []
  overload: System.ServiceModel.NetNamedPipeSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.Mode
  id: Mode
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: NetNamedPipeSecurity.Mode
  fullName: System.ServiceModel.NetNamedPipeSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Henter eller angir sikkerhetsmodus for den navngitte datakanal bindingen."
  remarks: "Gyldige verdier for denne egenskapen er: - Transport - Bruk transport kodebasert sikkerhet. Standardinnstillingen bruker NTLM som ikke inneholder servergodkjenning.      -Ingen - Bruk ingen sikkerhet."
  example:
  - "The following code shows how to set the Mode property:  \n  \n [!code-cs[S_UENetNamedPipeSecurity#2](~/add/codesnippet/csharp/p-system.servicemodel.ne_3_1.cs)]"
  syntax:
    content: public System.ServiceModel.NetNamedPipeSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetNamedPipeSecurityMode
      description: "Verdien for den <xref href=&quot;System.ServiceModel.NetNamedPipeSecurityMode&quot;> </xref> for den navngitte datakanal bindingen. Standardverdien er <xref href=&quot;System.ServiceModel.NetNamedPipeSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.NetNamedPipeSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: NetNamedPipeSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Returnerer en verdi som angir om den <xref:System.ServiceModel.NetNamedPipeSecurity.Transport*>egenskapen er endret fra standardverdien og skal serialiseres.</xref:System.ServiceModel.NetNamedPipeSecurity.Transport*> Dette brukes av WCF for XAML integrering."
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis den <xref:System.ServiceModel.NetNamedPipeSecurity.Transport*>egenskapsverdi må være serialiserte; ellers, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.NetNamedPipeSecurity.Transport*>"
  overload: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.Transport
  id: Transport
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: NetNamedPipeSecurity.Transport
  fullName: System.ServiceModel.NetNamedPipeSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Henter transport sikkerheten for den navngitte datakanal bindingen."
  remarks: "Denne metoden gir tilgang til den <xref:System.Net.Security.ProtectionLevel>for den navngitte datakanalen transporten via <xref:System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel%2A>.</xref:System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel%2A> </xref:System.Net.Security.ProtectionLevel>"
  example:
  - "The following code shows how to access the Transport property:  \n  \n [!code-cs[S_UENetNamedPipeSecurity#3](~/add/codesnippet/csharp/p-system.servicemodel.ne_21_1.cs)]"
  syntax:
    content: public System.ServiceModel.NamedPipeTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.NamedPipeTransportSecurity
      description: "Verdien for den <xref href=&quot;System.ServiceModel.NamedPipeTransportSecurity&quot;> </xref> for den navngitte datakanal bindingen."
  overload: System.ServiceModel.NetNamedPipeSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.NetNamedPipeSecurity.#ctor
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: NetNamedPipeSecurity()
  nameWithType: NetNamedPipeSecurity.NetNamedPipeSecurity()
  fullName: System.ServiceModel.NetNamedPipeSecurity.NetNamedPipeSecurity()
- uid: System.ServiceModel.NetNamedPipeSecurity.Mode
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Mode
  nameWithType: NetNamedPipeSecurity.Mode
  fullName: System.ServiceModel.NetNamedPipeSecurity.Mode
- uid: System.ServiceModel.NetNamedPipeSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetNamedPipeSecurityMode
  nameWithType: NetNamedPipeSecurityMode
  fullName: System.ServiceModel.NetNamedPipeSecurityMode
- uid: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: NetNamedPipeSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.NetNamedPipeSecurity.Transport
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Transport
  nameWithType: NetNamedPipeSecurity.Transport
  fullName: System.ServiceModel.NetNamedPipeSecurity.Transport
- uid: System.ServiceModel.NamedPipeTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: NamedPipeTransportSecurity
  nameWithType: NamedPipeTransportSecurity
  fullName: System.ServiceModel.NamedPipeTransportSecurity
- uid: System.ServiceModel.NetNamedPipeSecurity.#ctor*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: NetNamedPipeSecurity
  nameWithType: NetNamedPipeSecurity.NetNamedPipeSecurity
- uid: System.ServiceModel.NetNamedPipeSecurity.Mode*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Mode
  nameWithType: NetNamedPipeSecurity.Mode
- uid: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: NetNamedPipeSecurity.ShouldSerializeTransport
- uid: System.ServiceModel.NetNamedPipeSecurity.Transport*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Transport
  nameWithType: NetNamedPipeSecurity.Transport
