### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSettings
  id: ConfigurationSettings
  children:
  - System.Configuration.ConfigurationSettings.AppSettings
  - System.Configuration.ConfigurationSettings.GetConfig(System.String)
  langs:
  - csharp
  name: ConfigurationSettings
  nameWithType: ConfigurationSettings
  fullName: System.Configuration.ConfigurationSettings
  type: Class
  summary: "Gir runtime versjon 1.0 og 1.1 støtte for lesing konfigurasjonsdeler og vanlige konfigurasjonsinnstillingene."
  remarks: "Ved hjelp av statiske metoder og egenskaper av typen ConfigurationSettings er den anbefalte metoden for lesing av konfigurasjonsinformasjon under kjøring for versjon 1.0 og 1.1 programmer.      > [!NOTE] > For ConfigurationSettings klassen gir bare bakoverkompatibilitet. For nye apper må du bruke den <xref:System.Configuration.ConfigurationManager>klassen eller <xref:System.Web.Configuration.WebConfigurationManager>klasse i stedet.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager> Hvis du vil bruke disse to klasser, må du legge til en referanse i prosjektet eller programmet navneområdet System.Configuration."
  syntax:
    content: public sealed class ConfigurationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.AppSettings
  id: AppSettings
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Henter en skrivebeskyttet <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> for innstillinger applikasjonsdelen i konfigurasjonsfilen."
  remarks: "Den `appSettings` delelementet i konfigurasjonsfilen inneholder en serie med navn/verdi-parene som programmet kan bruke en.       Denne metoden er avskrevet og opprettholdes for bakoverkompatibilitet. Bruk GetSection-metoden i stedet.      > [!NOTE] > Den <xref:System.Configuration.ConfigurationSettings>klassen gir bare bakoverkompatibilitet.</xref:System.Configuration.ConfigurationSettings> Du må bruke den <xref:System.Configuration.ConfigurationManager>klassen eller <xref:System.Web.Configuration.WebConfigurationManager>klasse i stedet.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager>"
  syntax:
    content: public static System.Collections.Specialized.NameValueCollection AppSettings { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "En skrivebeskyttet <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> for innstillinger applikasjonsdelen i konfigurasjonsfilen."
  overload: System.Configuration.ConfigurationSettings.AppSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  id: GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Returnerer den <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> objekt for overførte delen navn og bane."
  remarks: "Denne metoden er avskrevet og opprettholdes for bakoverkompatibilitet. Bruk GetSection-metoden i stedet."
  syntax:
    content: public static object GetConfig (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "Et navn og bane, for eksempel &quot;system.net/settings&quot;."
    return:
      type: System.Object
      description: "Den <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> objekt for overførte delen navn og bane.       <div class=&quot;alert NOTE&quot;>    Den <xref href=&quot;System.Configuration.ConfigurationSettings&quot;> </xref> klassen gir bare bakoverkompatibilitet. Du må bruke den <xref href=&quot;System.Configuration.ConfigurationManager&quot;> </xref> klassen eller <xref href=&quot;System.Web.Configuration.WebConfigurationManager&quot;> </xref> klasse i stedet.      </div>"
  overload: System.Configuration.ConfigurationSettings.GetConfig*
  exceptions:
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "Kan ikke hente den forespurte delen."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationException
  nameWithType: ConfigurationException
  fullName: System.Configuration.ConfigurationException
- uid: System.Configuration.ConfigurationSettings.AppSettings
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSettings.AppSettings*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
- uid: System.Configuration.ConfigurationSettings.GetConfig*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig
  nameWithType: ConfigurationSettings.GetConfig
