### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentException
  id: DeploymentException
  children:
  - System.Deployment.Application.DeploymentException.#ctor
  - System.Deployment.Application.DeploymentException.#ctor(System.String)
  - System.Deployment.Application.DeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DeploymentException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  langs:
  - csharp
  name: DeploymentException
  nameWithType: DeploymentException
  fullName: System.Deployment.Application.DeploymentException
  type: Class
  summary: "Definerer en basisklasse for alle-distribusjonsrelatert unntak."
  remarks: "DeploymentException er basisklasse for alle-distribusjonsrelatert unntak fra <xref:System.Deployment.Application.ApplicationDeployment>klasse.</xref:System.Deployment.Application.ApplicationDeployment>"
  syntax:
    content: 'public class DeploymentException : SystemException'
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException()
  nameWithType: DeploymentException.DeploymentException()
  fullName: System.Deployment.Application.DeploymentException.DeploymentException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Deployment.Application.DeploymentException&quot;> </xref> klasse."
  syntax:
    content: public DeploymentException ();
    parameters: []
  overload: System.Deployment.Application.DeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException(String)
  nameWithType: DeploymentException.DeploymentException(String)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Deployment.Application.DeploymentException&quot;> </xref> klasse."
  syntax:
    content: public DeploymentException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Representerer tekst som en rekke Unicode-tegn."
  overload: System.Deployment.Application.DeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Deployment.Application.DeploymentException&quot;> </xref> klasse."
  syntax:
    content: protected DeploymentException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "Lagrer alle data som er nødvendig for å serialisere eller deserialisering av et objekt. Denne klassen kan ikke arves."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "Beskriver kilde og mål for en gitt serialisert dataflyt, og gir et ekstra oppkaller brukerdefinert kontekst."
  overload: System.Deployment.Application.DeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException(String,Exception)
  nameWithType: DeploymentException.DeploymentException(String,Exception)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Deployment.Application.DeploymentException&quot;> </xref> klasse."
  syntax:
    content: public DeploymentException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Representerer tekst som en rekke Unicode-tegn."
    - id: innerException
      type: System.Exception
      description: "Representerer feil som oppstår under kjøring av programmet."
  overload: System.Deployment.Application.DeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Angir den <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> med informasjon om unntaket."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Den <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> som inneholder den serialiserte objektdata om som oppstod et unntak."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Den <xref:System.Runtime.Serialization.StreamingContext>som inneholder kontekstavhengig informasjon om kilden eller målet.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Deployment.Application.DeploymentException.GetObjectData*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.Deployment.Application.DeploymentException.#ctor
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException()
  nameWithType: DeploymentException.DeploymentException()
  fullName: System.Deployment.Application.DeploymentException.DeploymentException()
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException(String)
  nameWithType: DeploymentException.DeploymentException(String)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException(String,Exception)
  nameWithType: DeploymentException.DeploymentException(String,Exception)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.DeploymentException.#ctor*
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException
  nameWithType: DeploymentException.DeploymentException
- uid: System.Deployment.Application.DeploymentException.GetObjectData*
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: GetObjectData
  nameWithType: DeploymentException.GetObjectData
