### YamlMime:ManagedReference
items:
- uid: System.Deployment.Internal.InternalApplicationIdentityHelper
  id: InternalApplicationIdentityHelper
  children:
  - System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(System.ApplicationIdentity)
  langs:
  - csharp
  name: InternalApplicationIdentityHelper
  nameWithType: InternalApplicationIdentityHelper
  fullName: System.Deployment.Internal.InternalApplicationIdentityHelper
  type: Class
  summary: "Gir tilgang til interne egenskaper for en <xref href=&quot;System.ApplicationIdentity&quot;> </xref> objektet."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public static class InternalApplicationIdentityHelper
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(System.ApplicationIdentity)
  id: GetInternalAppId(System.ApplicationIdentity)
  parent: System.Deployment.Internal.InternalApplicationIdentityHelper
  langs:
  - csharp
  name: GetInternalAppId(ApplicationIdentity)
  nameWithType: InternalApplicationIdentityHelper.GetInternalAppId(ApplicationIdentity)
  fullName: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(ApplicationIdentity)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Deployment.Internal
  summary: "Henter en [IDefinitionAppId grensesnittet](~/add/includes/ajax-current-ext-md.md) som representerer den unike identifikatoren for en <xref href=&quot;System.ApplicationIdentity&quot;> </xref> objektet."
  syntax:
    content: public static object GetInternalAppId (ApplicationIdentity id);
    parameters:
    - id: id
      type: System.ApplicationIdentity
      description: "Objektet som skal hente identifikatoren."
    return:
      type: System.Object
      description: "Den unike identifikatoren holdes av den <xref href=&quot;System.ApplicationIdentity&quot;> </xref> objektet."
  overload: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(System.ApplicationIdentity)
  parent: System.Deployment.Internal.InternalApplicationIdentityHelper
  isExternal: false
  name: GetInternalAppId(ApplicationIdentity)
  nameWithType: InternalApplicationIdentityHelper.GetInternalAppId(ApplicationIdentity)
  fullName: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(ApplicationIdentity)
- uid: System.ApplicationIdentity
  parent: System
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity
  fullName: System.ApplicationIdentity
- uid: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId*
  parent: System.Deployment.Internal.InternalApplicationIdentityHelper
  isExternal: false
  name: GetInternalAppId
  nameWithType: InternalApplicationIdentityHelper.GetInternalAppId
