### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.WmiConfigurationAttribute
  id: WmiConfigurationAttribute
  children:
  - System.Management.Instrumentation.WmiConfigurationAttribute.#ctor(System.String)
  - System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup
  - System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel
  - System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel
  - System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity
  - System.Management.Instrumentation.WmiConfigurationAttribute.Scope
  - System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction
  langs:
  - csharp
  name: WmiConfigurationAttribute
  nameWithType: WmiConfigurationAttribute
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute
  type: Class
  summary: "Attributtet WmiConfiguration angir at en samling inneholder kode som implementerer WMI-tjenesten ved hjelp av WMI.NET leverandøren utvidelser modellen. Attributtet godtar parametere som oppretter på høyt nivå konfigurasjonen av implementert WMI-leverandøren.       Obs! regnes nå WMI .NET-bibliotekene i endelig status, og ingen ytterligere development, forbedringer, eller oppdateringer er tilgjengelige for ikke-relaterte sikkerhetsproblemer som påvirker disse bibliotekene. Den [MI APIer](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx) skal brukes for alle nye utvikling."
  remarks: "Tabellen nedenfor viser parameterne godtatt av dette attributtet sammen med hvilken del av leverandørkonfigurasjonen av det gjør det mulig å kontrollere.      | Parameteren | Konfigurerer |   |---------------|----------------|   | [Scope](~/add/includes/ajax-current-ext-md.md)| Navneområdet som viser leverandøren klasser. |   | [NamespaceSecurity](~/add/includes/ajax-current-ext-md.md)|-sikkerheten (DACL) på navneområdet som brukes. |   | [HostingModel](~/add/includes/ajax-current-ext-md.md)|-verts modellen som skal brukes av leverandøren. |   | [IdentifyLevel](~/add/includes/ajax-current-ext-md.md)|-modus for representasjon av leverandøren. |   | [HostingGroup](~/add/includes/ajax-current-ext-md.md)| Verts gruppen leverandøren tilhører. Denne parameteren brukes bare for å behandle leverandører. |   | [SecurityRestriction](~/add/includes/ajax-current-ext-md.md)| Sikkerhet (DACL) på WMI-leverandøren. |"
  example:
  - "```  \n// Specify that this assembly contains code that implements a WMI  \n// Provider. Use the assembly:WmiConfiguration attribute to define  \n// the WMI namespace, the hosting model, and the impersonation mode  \n// of the WMI provider.  \n// The attribute below specifies that the class this provider  \n// exposes to WMI will be in the root/MortgageCalc namespace, will  \n// use the decoupled hosting model and will not allow the provider  \n// to impersonate its callers.  \n  \n[assembly: WmiConfiguration(\"root/MortgageCalc\",HostingModel = ManagementHostingModel.Decoupled, IdentifyLevel = false)]  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly)]

      public sealed class WmiConfigurationAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: WmiConfigurationAttribute(String)
  nameWithType: WmiConfigurationAttribute.WmiConfigurationAttribute(String)
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.WmiConfigurationAttribute(String)
  type: Constructor
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Initialiserer en ny forekomst av den <xref:System.Management.WmiConfigurationAttribute>klasse som angir WMI-navneområde som WMI-leverandøren skal vise klasser.</xref:System.Management.WmiConfigurationAttribute>"
  remarks: "En WMI-leverandør må utsette klassene i et navneområde. Det er derfor konstruktøren krever omfanget som en parameter."
  syntax:
    content: public WmiConfigurationAttribute (string scope);
    parameters:
    - id: scope
      type: System.String
      description: "WMI-navneområdet som leverandøren skal vise klasser. For eksempel &quot;root\\MyProviderNamespace&quot;."
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup
  id: HostingGroup
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: HostingGroup
  nameWithType: WmiConfigurationAttribute.HostingGroup
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Henter eller angir gruppen verts for WMI-leverandøren."
  remarks: "Verts grupper gjelder bare for leverandører som er lagret i arbeid. Verdien ignoreres for avparet leverandører.       En verts gruppe er et sett med kjørende leverandører som alle tildelte samme verts gruppenavnet. Verts gruppenavnet er en streng som du definerer til å gruppere logisk leverandørene. Alle kjørende leverandørene i samme verts-gruppen kjører under den samme sikkerhetskonteksten lagres i en enkelt forekomst av Wmiprvse.exe prosessen. Dette er tilfellet, leverandører som deler samme verts-gruppen og sikkerhet kontekst dele samme vertsprosessen for tjenesten."
  example:
  - "In the following example, the <xref:System.Management.Instrumentation.WmiConfigurationAttribute> is used to indicate that the assembly it is contained in implements an in-process provider that runs under the NetworkService security context and is hosted in a instance of the Wmiprvse.exe process that also hosts any other in-process providers in the same hosting group that also run within the NetworkService security context.  \n  \n```  \n[assembly: WmiConfiguration(\"root\\\\NVPair\", HostingModel = ManagementHostingModel.NetworkService), HostingGroup = \"MyProviders\"]  \n```"
  syntax:
    content: public string HostingGroup { get; set; }
    return:
      type: System.String
      description: "En <xref:System.String>verdi som angir gruppen verts for WMI-leverandøren.</xref:System.String>"
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel
  id: HostingModel
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: HostingModel
  nameWithType: WmiConfigurationAttribute.HostingModel
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Henter eller angir verts modellen for WMI-leverandøren."
  remarks: "WMI-leverandører kan ligge av et program eller WMI-tjenesten. WMI-leverandører ved et program kalles avparet leverandører. De vert WMI-tjenesten kalles kjørende leverandører. Verdien for verts modellen bestemmer begge være vert modellen og, hvis det kjørende leverandører, kontoen (sikkerhetskontekst) som tjenesten kjører under. For mer informasjon om mulige verdier for HostingModel, kan du se <xref:System.Management.Instrumentation.ManagementHostingModel>.</xref:System.Management.Instrumentation.ManagementHostingModel>       Hvis du vil ha mer informasjon om hvordan du drifter modeller, kan du se den [leverandøren vert og sikkerhet](http://go.microsoft.com/fwlink/?LinkId=100075) emnet i WMI-SDK på MSDN."
  example:
  - "In the following example, the <xref:System.Management.Instrumentation.WmiConfigurationAttribute> is used to indicate that the assembly it is contained in implements a provider that is exposed through the root\\NVPair namespace. Because the hosting model is not <xref:System.Management.Instrumentation.ManagementHostingModel>, it is an in-process provider. The value <xref:System.Management.Instrumentation.ManagementHostingModel> indicates that the in-process provider runs under the NetworkService security context.  \n  \n```  \n[assembly: WmiConfiguration(\"root\\\\NVPair\", HostingModel = ManagementHostingModel.NetworkService)]  \n```  \n  \n In the next example, the <xref:System.Management.Instrumentation.WmiConfigurationAttribute> is used to indicate that the assembly it is contained in implements a provider that is exposed through the root\\NVPair namespace. The value <xref:System.Management.Instrumentation.ManagementHostingModel> indicates that it is a decoupled provider.  \n  \n```  \n[assembly: WmiConfiguration(\"root\\\\NVPair\", HostingModel = ManagementHostingModel.Decoupled)]  \n```"
  syntax:
    content: public System.Management.Instrumentation.ManagementHostingModel HostingModel { get; set; }
    return:
      type: System.Management.Instrumentation.ManagementHostingModel
      description: "En <xref href=&quot;System.Management.Instrumentation.ManagementHostingModel&quot;> </xref> verdi som angir verts modellen av WMI-leverandøren."
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel
  id: IdentifyLevel
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: IdentifyLevel
  nameWithType: WmiConfigurationAttribute.IdentifyLevel
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Henter eller angir en verdi som angir om WMI-leverandøren kan representere brukere. Hvis verdien er USANN, leverandøren ikke kan representere, og hvis verdien er SANN, leverandøren kan representere."
  remarks: "Du finner mer informasjon, se emnet &quot;Leverandøren vert og sikkerhet&quot; i MSDN-biblioteket online på [http://www.msdn.com](http://www.msdn.com/)."
  example:
  - "The following example demonstrates how to use the IdentifyLevel parameter to indicate that the provider can impersonate its callers.  \n  \n```  \n[assembly: WmiConfiguration(\"root/MyProv\", HostingModel = ManagementHostingModel.Decoupled, IdentifyLevel = true]  \n```"
  syntax:
    content: public bool IdentifyLevel { get; set; }
    return:
      type: System.Boolean
      description: "En boolsk verdi som angir om en leverandør kan eller ikke kan representere brukere. Hvis verdien er USANN, leverandøren ikke kan representere, og hvis verdien er SANN, leverandøren kan representere."
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity
  id: NamespaceSecurity
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: NamespaceSecurity
  nameWithType: WmiConfigurationAttribute.NamespaceSecurity
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Henter eller angir en streng i sikkerhet sikkerhetsbeskrivelse Definition Language (SDDL) som angir sikkerhetsbeskrivelsen i navneområdet som viser leverandøren management objects."
  remarks: "Hvis du vil ha mer informasjon om hvordan du representere Sikkerhetsbeskrivelsene i SDDL-format, se den [sikkerhet sikkerhetsbeskrivelse strengformat](http://go.microsoft.com/fwlink/?LinkId=100763) emnet i MSDN-biblioteket online."
  example:
  - "The following example demonstrates how to use the NamespaceSecurity parameter to set the security descriptor on the root/SDTest namespace in which the provider implemented in this assembly exposes WMI classes.  \n  \n```  \n[assembly: WmiConfiguration(\"root/SDTest\", HostingModel = ManagementHostingModel.Decoupled, IdentifyLevel = false, NamespaceSecurity = \"O:BAG:BAD:(A;CI;0x60003;;;WD)\")]  \n```"
  syntax:
    content: public string NamespaceSecurity { get; set; }
    return:
      type: System.String
      description: "SDDL-streng som representerer sikkerhetsbeskrivelsen i navneområdet som viser leverandøren management objects."
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.Scope
  id: Scope
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: Scope
  nameWithType: WmiConfigurationAttribute.Scope
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.Scope
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Henter eller angir WMI-navneområdet som viser WMI-leverandøren klasser."
  remarks: "Et WMI-navneområde er en kategori i WMI-lageret. Navneområdet som ofte brukes roten/cimv2 huser klasser som beskriver vanlige informasjon modellen versjon 2, som er definert av Desktop Management Task Force DMTF ()-consortium. Du bør bare eksponerer din leverandører i som navneområdet Hvis du utvide når standand CIM-modellen. Hvis ikke, må du opprette et riktig navneområde som gjør klar for brukere av WMI-klasser som de kan forvente å finne i navneområdet."
  syntax:
    content: public string Scope { get; }
    return:
      type: System.String
      description: "En <xref:System.String>verdi som angir navneområdet som viser WMI-leverandøren klasser.</xref:System.String>"
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.Scope*
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction
  id: SecurityRestriction
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  langs:
  - csharp
  name: SecurityRestriction
  nameWithType: WmiConfigurationAttribute.SecurityRestriction
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Henter eller angir en sikkerhetsbeskrivelse for WMI-leverandøren. For mer informasjon, kan du se SecurityDescriptor egenskapen informasjonen i emnet &quot;__Win32Provider&quot; i det elektroniske MSDN-biblioteket på [http://www.msdn.com](http://www.msdn.com/)."
  syntax:
    content: public string SecurityRestriction { get; set; }
    return:
      type: System.String
      description: "En <xref:System.String>verdi som inneholder sikkerhetsbeskrivelsen for WMI-leverandøren.</xref:System.String>"
  overload: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.#ctor(System.String)
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: WmiConfigurationAttribute(String)
  nameWithType: WmiConfigurationAttribute.WmiConfigurationAttribute(String)
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.WmiConfigurationAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: HostingGroup
  nameWithType: WmiConfigurationAttribute.HostingGroup
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: HostingModel
  nameWithType: WmiConfigurationAttribute.HostingModel
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel
- uid: System.Management.Instrumentation.ManagementHostingModel
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementHostingModel
  nameWithType: ManagementHostingModel
  fullName: System.Management.Instrumentation.ManagementHostingModel
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: IdentifyLevel
  nameWithType: WmiConfigurationAttribute.IdentifyLevel
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: NamespaceSecurity
  nameWithType: WmiConfigurationAttribute.NamespaceSecurity
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.Scope
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: Scope
  nameWithType: WmiConfigurationAttribute.Scope
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.Scope
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: SecurityRestriction
  nameWithType: WmiConfigurationAttribute.SecurityRestriction
  fullName: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.#ctor*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: WmiConfigurationAttribute
  nameWithType: WmiConfigurationAttribute.WmiConfigurationAttribute
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingGroup*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: HostingGroup
  nameWithType: WmiConfigurationAttribute.HostingGroup
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.HostingModel*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: HostingModel
  nameWithType: WmiConfigurationAttribute.HostingModel
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.IdentifyLevel*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: IdentifyLevel
  nameWithType: WmiConfigurationAttribute.IdentifyLevel
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.NamespaceSecurity*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: NamespaceSecurity
  nameWithType: WmiConfigurationAttribute.NamespaceSecurity
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.Scope*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: Scope
  nameWithType: WmiConfigurationAttribute.Scope
- uid: System.Management.Instrumentation.WmiConfigurationAttribute.SecurityRestriction*
  parent: System.Management.Instrumentation.WmiConfigurationAttribute
  isExternal: false
  name: SecurityRestriction
  nameWithType: WmiConfigurationAttribute.SecurityRestriction
