### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFramework
  id: CompatibleFramework
  children:
  - System.Deployment.Application.CompatibleFramework.Profile
  - System.Deployment.Application.CompatibleFramework.SupportedRuntime
  - System.Deployment.Application.CompatibleFramework.TargetVersion
  langs:
  - csharp
  name: CompatibleFramework
  nameWithType: CompatibleFramework
  fullName: System.Deployment.Application.CompatibleFramework
  type: Class
  summary: "Representerer en versjon av .NET Framework der et program kan installere og kjøre."
  syntax:
    content: public class CompatibleFramework
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFramework.Profile
  id: Profile
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: System.Deployment.Application.CompatibleFramework.Profile
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Angir profilen til .NET Framework-versjonen der et program kan installere og kjøre."
  remarks: "Hvis .NET Framework-versjonen er [!INCLUDE[net_client_v40_long](~/add/includes/net-client-v40-long-md.md)], profilegenskapen returnerer &quot;Klienten&quot;. Hvis .NET Framework-versjonen er [!INCLUDE[net_v40_long](~/add/includes/net-v40-long-md.md)], profilegenskapen returnerer &quot;Fullstendig&quot;."
  syntax:
    content: public string Profile { get; }
    return:
      type: System.String
      description: "En streng som representerer profilen."
  overload: System.Deployment.Application.CompatibleFramework.Profile*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  id: SupportedRuntime
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Angir hvor runtime versjon av .NET Framework der et program kan installere og kjøre."
  remarks: "Nye versjoner av .NET Framework kan fungere utgitt tidligere versjoner av kjøretiden."
  syntax:
    content: public string SupportedRuntime { get; }
    return:
      type: System.String
      description: "En streng som representerer runtime-versjonen."
  overload: System.Deployment.Application.CompatibleFramework.SupportedRuntime*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion
  id: TargetVersion
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
  fullName: System.Deployment.Application.CompatibleFramework.TargetVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Angir hvilken versjon av .NET Framework der et program kan installere og kjøre."
  syntax:
    content: public string TargetVersion { get; }
    return:
      type: System.String
      description: "En streng som representerer versjonen."
  overload: System.Deployment.Application.CompatibleFramework.TargetVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Application.CompatibleFramework.Profile
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: System.Deployment.Application.CompatibleFramework.Profile
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: System.Deployment.Application.CompatibleFramework.SupportedRuntime
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
  fullName: System.Deployment.Application.CompatibleFramework.TargetVersion
- uid: System.Deployment.Application.CompatibleFramework.Profile*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
