### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Converter
  id: Converter
  children:
  - System.Web.Configuration.Converter.#ctor
  - System.Web.Configuration.Converter.Name
  - System.Web.Configuration.Converter.Properties
  - System.Web.Configuration.Converter.Type
  langs:
  - csharp
  name: Converter
  nameWithType: Converter
  fullName: System.Web.Configuration.Converter
  type: Class
  summary: "Representerer en konfigurasjonselementet i en konfigurasjonsfil."
  remarks: "Klassen konverteringsprogram kan du programmatisk tilgang til og endre konfigurasjonsinnstillingene som er relatert til konverteringsprogrammer som brukes av ASP.NET AJAX-aktiverte programmer.       Hvis du vil opprette egendefinert konvertering funksjonalitet, kan du opprette en klassen som arver fra <xref:System.Web.Script.Serialization.JavaScriptConverter>klasse.</xref:System.Web.Script.Serialization.JavaScriptConverter> Etter konverteringen er opprettet, kan du registrere den for bruk i konfigurasjonsfilen for webprogrammet."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for properties of the Converter class.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <jsonSerialization>  \n        <converters>  \n          <add name=\"ConvertMe\" type=\"Acme.SubAcme.ConvertMeTypeConverter\" />  \n        </converters>  \n      </jsonSerialization>  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example demonstrates how to access Converter programmatically.  \n  \n [!code-cs[System.Web.Configuration#3](~/add/codesnippet/csharp/t-system.web.configurati_34_1.cs)]\n [!code-vb[System.Web.Configuration#3](~/add/codesnippet/visualbasic/t-system.web.configurati_34_1.vb)]"
  syntax:
    content: 'public class Converter : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.Converter.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Converter()
  nameWithType: Converter.Converter()
  fullName: System.Web.Configuration.Converter.Converter()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.Converter&quot;> </xref> klasse."
  syntax:
    content: public Converter ();
    parameters: []
  overload: System.Web.Configuration.Converter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Converter.Name
  id: Name
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Name
  nameWithType: Converter.Name
  fullName: System.Web.Configuration.Converter.Name
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Henter eller angir den unike identifikatoren for konvertering."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Den unike identifikatoren for konvertering."
  overload: System.Web.Configuration.Converter.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Converter.Properties
  id: Properties
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Properties
  nameWithType: Converter.Properties
  fullName: System.Web.Configuration.Converter.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Henter en samling av konfigurasjonselementet egenskaper."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;></xref> object."
  overload: System.Web.Configuration.Converter.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Converter.Type
  id: Type
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Type
  nameWithType: Converter.Type
  fullName: System.Web.Configuration.Converter.Type
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Henter eller angir fullstendige typenavnet på den <xref href=&quot;System.Web.Script.Serialization.JavaScriptConverter&quot;> </xref> objektet."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "Fullstendige typenavnet på den <xref href=&quot;System.Web.Script.Serialization.JavaScriptConverter&quot;> </xref> objektet."
  overload: System.Web.Configuration.Converter.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.Converter.#ctor
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Converter()
  nameWithType: Converter.Converter()
  fullName: System.Web.Configuration.Converter.Converter()
- uid: System.Web.Configuration.Converter.Name
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Name
  nameWithType: Converter.Name
  fullName: System.Web.Configuration.Converter.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.Converter.Properties
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Properties
  nameWithType: Converter.Properties
  fullName: System.Web.Configuration.Converter.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.Converter.Type
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Type
  nameWithType: Converter.Type
  fullName: System.Web.Configuration.Converter.Type
- uid: System.Web.Configuration.Converter.#ctor*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Converter
  nameWithType: Converter.Converter
- uid: System.Web.Configuration.Converter.Name*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Name
  nameWithType: Converter.Name
- uid: System.Web.Configuration.Converter.Properties*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Properties
  nameWithType: Converter.Properties
- uid: System.Web.Configuration.Converter.Type*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Type
  nameWithType: Converter.Type
