### YamlMime:ManagedReference
items:
- uid: System.Configuration.UserScopedSettingAttribute
  id: UserScopedSettingAttribute
  children:
  - System.Configuration.UserScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute
  fullName: System.Configuration.UserScopedSettingAttribute
  type: Class
  summary: "Angir at en applikasjon innstillinger for gruppe eller egenskap inneholder distinkte verdier for hver bruker med en applikasjon. Denne klassen kan ikke arves."
  remarks: "Egenskapene for applikasjonen innstillinger har et omfang som er basert enten på programmet eller brukernivå. Som kategoriene angir, presentere Programdefinert egenskaper uniform verdier for alle brukere av programmet, mens område bruker egenskapene har dedikerte verdier for hver bruker for applikasjonen.       UserScopedSettingAttribute angir at en egenskap anses som en innstilling for brukeren, og at riktig lagring avgjørelsene må gjøres tilsvarende av innstillingene for leverandøren.       Et område-attributtet er nødvendig for hver egenskap for innstillinger av programmet. Hvis en egenskap ikke brukes med enten en <xref:System.Configuration.ApplicationScopedSettingAttribute>eller UserScopedSettingAttribute, egenskapen ignoreres av leverandøren innstillinger, ikke serialiseres.</xref:System.Configuration.ApplicationScopedSettingAttribute> Det er imidlertid ugyldig, gjelder begge attributtene for den samme egenskapen innstillingene. Slik forsøk vil føre til at en <xref:System.Configuration.ConfigurationErrorsException>til å bli utløst.</xref:System.Configuration.ConfigurationErrorsException>"
  example:
  - "The following code example demonstrates the use of the UserScopedSettingAttribute applied to all four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.u_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.u_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class UserScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.UserScopedSettingAttribute
  langs:
  - csharp
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.UserScopedSettingAttribute&quot;> </xref> klasse."
  remarks: "Egenskapen hver programmet innstillingene må brukes med et enkelt omfanget attributt for at den skal gjenkjennes og serialisert av innstillingene for leverandøren."
  syntax:
    content: public UserScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.UserScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
- uid: System.Configuration.UserScopedSettingAttribute.#ctor*
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute
