### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata
  id: ProfilePropertyMetadata
  children:
  - System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  - System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  - System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  - System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  - System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  - System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  - System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  - System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  langs:
  - csharp
  name: ProfilePropertyMetadata
  nameWithType: ProfilePropertyMetadata
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata
  type: Class
  summary: "Inneholder en samling av verdiene som beskriver en profilegenskap."
  remarks: "Du bruker klassen ProfilePropertyMetadata til å hente informasjon om en profilegenskap når du åpner profiler via <xref:System.Web.ApplicationServices.ProfileService>klasse.</xref:System.Web.ApplicationServices.ProfileService> Du kan hente navnet og typen for egenskapen om den er skrivebeskyttet, om det kan åpnes av brukere som ikke er godkjent, og standardverdien. Et program kan ta de nødvendige handlingene som er basert på disse verdiene, for eksempel ikke forsøk på å angi en skrivebeskyttet egenskap.       For å få tilgang til ProfilePropertyMetadata-objektet fra et program som er kompatibel med Windows Communication Framework (WCF), bruker du <xref:System.Web.ApplicationServices.ProfileService.GetPropertiesMetadata%2A>metode for <xref:System.Web.ApplicationServices.ProfileService>klasse.</xref:System.Web.ApplicationServices.ProfileService> </xref:System.Web.ApplicationServices.ProfileService.GetPropertiesMetadata%2A> Brukeren har ikke er logget på å hente objektet ProfilePropertyMetadata fordi metadataene for profilegenskaper ikke gjelder brukerens profilegenskapsverdier.       Verdiene i klassen ProfilePropertyMetadata er angitt i Web.config-filen i elementet i delen når egenskapen er definert."
  syntax:
    content: >-
      [System.Runtime.Serialization.DataContract]

      public class ProfilePropertyMetadata : System.Runtime.Serialization.IExtensibleDataObject
  inheritance:
  - System.Object
  implements:
  - System.Runtime.Serialization.IExtensibleDataObject
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  id: '#ctor'
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: ProfilePropertyMetadata()
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata()
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ProfilePropertyMetadata()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.ApplicationServices.ProfilePropertyMetadata&quot;> </xref> klasse."
  syntax:
    content: public ProfilePropertyMetadata ();
    parameters: []
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  id: AllowAnonymousAccess
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter eller angir en verdi som angir om egenskapen er tilgjengelig for ikke-godkjente brukere."
  remarks: "Når du aktiverer anonym identifisering med innstillingene i elementet, kan du angi hvilken profilegenskaper er tilgjengelige for anonyme brukere. Du kan angi egenskapen AllowAnonymousAccess i elementet i delen i Web.config-filen når egenskapen er definert. Fra et klientprogram, kan du bruke egenskapen AllowAnonymousAccess å finne ut om en profilegenskap kan angis for en anonym bruker."
  syntax:
    content: public bool AllowAnonymousAccess { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis egenskapen er tilgjengelig for brukere som ikke godkjent. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  id: DefaultValue
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter eller angir standardverdien for egenskapen."
  remarks: "Egenskapen DefaultValue serialiserte formatet bestemmes av <xref:System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs%2A>egenskapen for <xref:System.Web.ApplicationServices.ProfilePropertyMetadata>klassen.</xref:System.Web.ApplicationServices.ProfilePropertyMetadata> </xref:System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs%2A>"
  syntax:
    content: public string DefaultValue { get; set; }
    return:
      type: System.String
      description: "En serialisert representasjon av verdien for egenskapen, hvis en standardverdi er definert i Web.config-filen. Hvis strengen &quot;(null)&quot;."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  id: ExtensionData
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter eller angir en referanse til en <xref href=&quot;System.Runtime.Serialization.ExtensionDataObject&quot;> </xref> forekomsten."
  syntax:
    content: public System.Runtime.Serialization.ExtensionDataObject ExtensionData { get; set; }
    return:
      type: System.Runtime.Serialization.ExtensionDataObject
      description: "En referanse til et objekt som lagrer utvidede data under deserialisering operasjoner."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  id: IsReadOnly
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter eller angir en verdi som angir om en profilegenskap er skrivebeskyttet."
  remarks: "Du kan angi egenskapen IsReadOnly i elementet i delen i Web.config-filen når egenskapen er definert."
  syntax:
    content: public bool IsReadOnly { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis profilegenskapen er skrivebeskyttet. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  id: PropertyName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter eller angir navnet på profilegenskapen."
  remarks: "Du kan angi egenskapen PropertyName i elementet i delen i Web.config-filen når egenskapen er definert."
  syntax:
    content: public string PropertyName { get; set; }
    return:
      type: System.String
      description: "Navnet på profilegenskapen som er definert i Web.config-filen."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  id: SerializeAs
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter eller angir en verdi som angir hvordan du serialisere egenskapsverdien."
  remarks: "Du kan angi egenskapen SerializeAs i elementet i delen i Web.config-filen når egenskapen er definert."
  syntax:
    content: public int SerializeAs { get; set; }
    return:
      type: System.Int32
      description: "Opplistingsverdien."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  id: TypeName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Henter eller angir samlingen kvalifisert egenskapstypen profilen."
  remarks: "Du kan angi egenskapen TypeName i elementet i delen i Web.config-filen når egenskapen er definert."
  syntax:
    content: public string TypeName { get; set; }
    return:
      type: System.String
      description: "Samlingen kvalifiserte navnet på egenskapstypen profilen."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ProfilePropertyMetadata()
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata()
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ProfilePropertyMetadata()
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
- uid: System.Runtime.Serialization.ExtensionDataObject
  parent: System.Runtime.Serialization
  isExternal: false
  name: ExtensionDataObject
  nameWithType: ExtensionDataObject
  fullName: System.Runtime.Serialization.ExtensionDataObject
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ProfilePropertyMetadata
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
