### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.ApplicationVersionMatch
  id: ApplicationVersionMatch
  children:
  - System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  - System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  langs:
  - csharp
  name: ApplicationVersionMatch
  nameWithType: ApplicationVersionMatch
  fullName: System.Security.Policy.ApplicationVersionMatch
  type: Enum
  summary: "Angir hvordan som samsvarer med versjoner når finne programmet klareringer i en samling."
  remarks: "Den <xref:System.Security.Policy.ApplicationTrustCollection.Remove%2A>og <xref:System.Security.Policy.ApplicationTrustCollection.Find%2A>metoder for en <xref:System.Security.Policy.ApplicationTrustCollection>kan brukes på alle versjoner av et program eller på den nøyaktige versjonen.</xref:System.Security.Policy.ApplicationTrustCollection> </xref:System.Security.Policy.ApplicationTrustCollection.Find%2A> </xref:System.Security.Policy.ApplicationTrustCollection.Remove%2A> Opplistingen ApplicationVersionMatch tillater oppkalleren Slik angir du ønsket virkemåte."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum ApplicationVersionMatch
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  id: MatchAllVersions
  parent: System.Security.Policy.ApplicationVersionMatch
  langs:
  - csharp
  name: MatchAllVersions
  nameWithType: ApplicationVersionMatch.MatchAllVersions
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Treff på alle versjoner."
  syntax:
    content: MatchAllVersions
    return:
      type: System.Security.Policy.ApplicationVersionMatch
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  id: MatchExactVersion
  parent: System.Security.Policy.ApplicationVersionMatch
  langs:
  - csharp
  name: MatchExactVersion
  nameWithType: ApplicationVersionMatch.MatchExactVersion
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Samsvare med nøyaktig versjon."
  syntax:
    content: MatchExactVersion
    return:
      type: System.Security.Policy.ApplicationVersionMatch
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  parent: System.Security.Policy.ApplicationVersionMatch
  isExternal: false
  name: MatchAllVersions
  nameWithType: ApplicationVersionMatch.MatchAllVersions
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
- uid: System.Security.Policy.ApplicationVersionMatch
  parent: System.Security.Policy
  isExternal: false
  name: ApplicationVersionMatch
  nameWithType: ApplicationVersionMatch
  fullName: System.Security.Policy.ApplicationVersionMatch
- uid: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  parent: System.Security.Policy.ApplicationVersionMatch
  isExternal: false
  name: MatchExactVersion
  nameWithType: ApplicationVersionMatch.MatchExactVersion
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
