### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  id: DownloadApplicationCompletedEventArgs
  children:
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  langs:
  - csharp
  name: DownloadApplicationCompletedEventArgs
  nameWithType: DownloadApplicationCompletedEventArgs
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  type: Class
  summary: "Gir dataene for den <xref href=&quot;System.Deployment.Application.InPlaceHostingManager.DownloadApplicationCompleted&quot;> </xref> hendelsen."
  syntax:
    content: 'public class DownloadApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  id: LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter banen til ClickOnce-loggfilen."
  syntax:
    content: public string LogFilePath { get; }
    return:
      type: System.String
      description: "Banen til ClickOnce-loggfilen."
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  id: ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter innholdet i en .appref-ms-fil som kan starte denne ClickOnce-programmet."
  remarks: 'Denne egenskapen inneholder et tilpasset installasjonsprogram kan skrive til en .appref-ms-fil for 책 starte dette ClickOnce-programmet. ClickOnce oppretter Start filen for deg n책r du installerer en ClickOnce-program som er tilgjengelig frakoblet, bortsett fra programmer som inneholder den `<customUX>` elementet. En egendefinert installasjonsprogrammet kan opprette en snarvei for 책 starte en ClickOnce-programmet som inneholder en `<customUX>` elementet ved 책 skrive inn i denne egenskapen til en ny .appref-ms-fil i Unicode-format. Hvis du vil ha mer informasjon, se [ \&lt; entryPoint\&gt; Elementet](../Topic/%3CentryPoint%3E%20Element%20\(ClickOnce%20Application\).md) og [gjennomgang: opprette en egendefinert installasjonsprogrammet for en ClickOnce-programmet](~/add/includes/ajax-current-ext-md.md).'
  syntax:
    content: public string ShortcutAppId { get; }
    return:
      type: System.String
      description: "Innholdet i en .appref-ms-fil."
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
