### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationScopedSettingAttribute
  id: ApplicationScopedSettingAttribute
  children:
  - System.Configuration.ApplicationScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute
  fullName: System.Configuration.ApplicationScopedSettingAttribute
  type: Class
  summary: "Angir at en egenskap for innstillinger av programmet har en felles verdi for alle brukere med en applikasjon. Denne klassen kan ikke arves."
  remarks: "Egenskapene for applikasjonen innstillinger har et omfang som er basert enten på programmet eller brukernivå. Som kategoriene angir, presentere Programdefinert innstillinger uniform verdier for alle brukere av programmet, mens område bruker egenskapene har dedikerte verdier for hver bruker for applikasjonen.       ApplicationScopedSettingAttribute angir at en egenskap anses som en programnivå innstilling, og at riktig lagring avgjørelsene må gjøres tilsvarende av innstillingene for leverandøren.       Scope-attributtet er nødvendig for hver egenskap for innstillinger. Hvis en egenskap ikke brukes med enten ApplicationScopedSettingAttribute eller <xref:System.Configuration.UserScopedSettingAttribute>, egenskapen gjenkjennes ikke av leverandøren innstillinger, ikke serialiseres.</xref:System.Configuration.UserScopedSettingAttribute> Det er imidlertid ugyldig, gjelder begge attributtene for samme egenskap. Slik forsøk vil føre til at en <xref:System.Configuration.ConfigurationErrorsException>til å bli utløst.</xref:System.Configuration.ConfigurationErrorsException>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class ApplicationScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationScopedSettingAttribute
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.ApplicationScopedSettingAttribute&quot;> </xref> klasse."
  remarks: "Egenskapen hver programmet innstillingene må brukes med et enkelt omfanget attributt for at den skal gjenkjennes og serialisert av innstillingene for leverandøren."
  syntax:
    content: public ApplicationScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute
