### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  id: NamedPipeConnectionPoolSettings
  children:
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  langs:
  - csharp
  name: NamedPipeConnectionPoolSettings
  nameWithType: NamedPipeConnectionPoolSettings
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  type: Class
  summary: "Representerer innstillinger som kontrollerer virkemåten for tilkoblingsutvalget navngitt datakanal."
  syntax:
    content: public sealed class NamedPipeConnectionPoolSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  id: GroupName
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Henter eller angir gruppenavnet på programutvalget tilkoblingsgruppe på klienten."
  remarks: "Standardverdien kan endres for å isolere tilkoblinger for en bestemt klient i egen grupper."
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "Navnet på applikasjonsutvalget tilkoblingsgruppe på klienten. Navnet på standardserveren er &quot;standard&quot;."
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "Verdien er <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  platform:
  - net462
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Henter eller angir den maksimale tiden tilkoblingen kan være inaktiv i tilkoblingsutvalget før den kobles fra."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Returnerer en <xref:System.TimeSpan>-strukturen som angir den maksimale tiden tilkoblingen kan være inaktiv i tilkoblingsutvalget før den kobles fra.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Verdien er mindre enn null."
  platform:
  - net462
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Henter eller angir maksimalt antall utgående tilkoblinger for hvert endepunkt som er bufret i tilkoblingsutvalget."
  remarks: "Dette begrenser antall tilkoblinger som er hurtigbufret for hver unike sluttpunktet. Hvis denne verdien er overskredet ved at flere aktive klienttilkoblinger, deretter tjenesten kan vises ikke svarer til klienten denne verdien skal justeres til å overskrider det maksimale antallet forventede tilkoblinger som er hurtigbufret for hver unike endepunkt"
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "Maksimalt antall tillatte utgående tilkoblinger for hvert endepunkt som er bufret i tilkoblingsutvalget. Standardverdien er 10."
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Verdien er mindre enn eller lik null."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
