### YamlMime:ManagedReference
items:
- uid: System.Configuration.PropertyValueOrigin
  id: PropertyValueOrigin
  children:
  - System.Configuration.PropertyValueOrigin.Default
  - System.Configuration.PropertyValueOrigin.Inherited
  - System.Configuration.PropertyValueOrigin.SetHere
  langs:
  - csharp
  name: PropertyValueOrigin
  nameWithType: PropertyValueOrigin
  fullName: System.Configuration.PropertyValueOrigin
  type: Enum
  summary: "Angir niv책et i konfigurasjonshierarkiet der en egenskapsverdi for konfigurasjon stammer fra."
  syntax:
    content: public enum PropertyValueOrigin
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.PropertyValueOrigin.Default
  id: Default
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: Default
  nameWithType: PropertyValueOrigin.Default
  fullName: System.Configuration.PropertyValueOrigin.Default
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egenskapen konfigurasjonsverdien stammer fra den <xref:System.Configuration.ConfigurationProperty.DefaultValue*>egenskapen.</xref:System.Configuration.ConfigurationProperty.DefaultValue*>"
  syntax:
    content: Default
    return:
      type: System.Configuration.PropertyValueOrigin
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PropertyValueOrigin.Inherited
  id: Inherited
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: Inherited
  nameWithType: PropertyValueOrigin.Inherited
  fullName: System.Configuration.PropertyValueOrigin.Inherited
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egenskapsverdien konfigurasjonen er arvet fra et overordnet niv책 i konfigurasjonen."
  syntax:
    content: Inherited
    return:
      type: System.Configuration.PropertyValueOrigin
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PropertyValueOrigin.SetHere
  id: SetHere
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: SetHere
  nameWithType: PropertyValueOrigin.SetHere
  fullName: System.Configuration.PropertyValueOrigin.SetHere
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egenskapsverdien konfigurasjonen er definert p책 dette niv책et i hierarkiet."
  syntax:
    content: SetHere
    return:
      type: System.Configuration.PropertyValueOrigin
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.PropertyValueOrigin.Default
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: Default
  nameWithType: PropertyValueOrigin.Default
  fullName: System.Configuration.PropertyValueOrigin.Default
- uid: System.Configuration.PropertyValueOrigin
  parent: System.Configuration
  isExternal: false
  name: PropertyValueOrigin
  nameWithType: PropertyValueOrigin
  fullName: System.Configuration.PropertyValueOrigin
- uid: System.Configuration.PropertyValueOrigin.Inherited
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: Inherited
  nameWithType: PropertyValueOrigin.Inherited
  fullName: System.Configuration.PropertyValueOrigin.Inherited
- uid: System.Configuration.PropertyValueOrigin.SetHere
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: SetHere
  nameWithType: PropertyValueOrigin.SetHere
  fullName: System.Configuration.PropertyValueOrigin.SetHere
