### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.PagesEnableSessionState
  id: PagesEnableSessionState
  children:
  - System.Web.Configuration.PagesEnableSessionState.False
  - System.Web.Configuration.PagesEnableSessionState.ReadOnly
  - System.Web.Configuration.PagesEnableSessionState.True
  langs:
  - csharp
  name: PagesEnableSessionState
  nameWithType: PagesEnableSessionState
  fullName: System.Web.Configuration.PagesEnableSessionState
  type: Enum
  summary: "Brukes til å avgjøre status for økten aktivering for en enkelt nettside eller et hele webprogram."
  remarks: "Denne opplisting bestemmer status for økten aktivering for en hele webprogrammet. Denne verdien kan brukes i den `pages` konfigurasjonsfilen delen vil påvirke alle aspx-sider i webprogrammet for området i konfigurasjonsfilen. Den <xref:System.Web.Configuration.PagesSection>tillater programmatisk tilgang til den `pages` konfigurasjonsdelen.</xref:System.Web.Configuration.PagesSection>"
  example:
  - "The following configuration file excerpt shows how to declaratively use values of the PagesEnableSessionState enumeration to specify whether the session state is enabled.  \n  \n```  \n<system.web>  \n  <pages enableSessionState=\"true\" />  \n</system.web>  \n  \n```  \n  \n The following code example shows how to use the PagesEnableSessionState enumeration with the <xref:System.Web.Configuration.PagesSection> type.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#14](~/add/codesnippet/csharp/t-system.web.configurati_56_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#14](~/add/codesnippet/visualbasic/t-system.web.configurati_56_1.vb)]"
  syntax:
    content: public enum PagesEnableSessionState
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.PagesEnableSessionState.False
  id: "False"
  parent: System.Web.Configuration.PagesEnableSessionState
  langs:
  - csharp
  name: "False"
  nameWithType: PagesEnableSessionState.False
  fullName: System.Web.Configuration.PagesEnableSessionState.False
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Status for økten er deaktivert."
  syntax:
    content: "False"
    return:
      type: System.Web.Configuration.PagesEnableSessionState
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PagesEnableSessionState.ReadOnly
  id: ReadOnly
  parent: System.Web.Configuration.PagesEnableSessionState
  langs:
  - csharp
  name: ReadOnly
  nameWithType: PagesEnableSessionState.ReadOnly
  fullName: System.Web.Configuration.PagesEnableSessionState.ReadOnly
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Økttilstand er aktivert, men ikke skrivbar."
  syntax:
    content: ReadOnly
    return:
      type: System.Web.Configuration.PagesEnableSessionState
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PagesEnableSessionState.True
  id: "True"
  parent: System.Web.Configuration.PagesEnableSessionState
  langs:
  - csharp
  name: "True"
  nameWithType: PagesEnableSessionState.True
  fullName: System.Web.Configuration.PagesEnableSessionState.True
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Økttilstand er aktivert."
  syntax:
    content: "True"
    return:
      type: System.Web.Configuration.PagesEnableSessionState
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.PagesEnableSessionState.False
  parent: System.Web.Configuration.PagesEnableSessionState
  isExternal: false
  name: "False"
  nameWithType: PagesEnableSessionState.False
  fullName: System.Web.Configuration.PagesEnableSessionState.False
- uid: System.Web.Configuration.PagesEnableSessionState
  parent: System.Web.Configuration
  isExternal: false
  name: PagesEnableSessionState
  nameWithType: PagesEnableSessionState
  fullName: System.Web.Configuration.PagesEnableSessionState
- uid: System.Web.Configuration.PagesEnableSessionState.ReadOnly
  parent: System.Web.Configuration.PagesEnableSessionState
  isExternal: false
  name: ReadOnly
  nameWithType: PagesEnableSessionState.ReadOnly
  fullName: System.Web.Configuration.PagesEnableSessionState.ReadOnly
- uid: System.Web.Configuration.PagesEnableSessionState.True
  parent: System.Web.Configuration.PagesEnableSessionState
  isExternal: false
  name: "True"
  nameWithType: PagesEnableSessionState.True
  fullName: System.Web.Configuration.PagesEnableSessionState.True
