### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.WebRequestModuleElement
  id: WebRequestModuleElement
  children:
  - System.Net.Configuration.WebRequestModuleElement.#ctor
  - System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  - System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  - System.Net.Configuration.WebRequestModuleElement.Prefix
  - System.Net.Configuration.WebRequestModuleElement.Properties
  - System.Net.Configuration.WebRequestModuleElement.Type
  langs:
  - csharp
  name: WebRequestModuleElement
  nameWithType: WebRequestModuleElement
  fullName: System.Net.Configuration.WebRequestModuleElement
  type: Class
  summary: "Representerer et URI-prefiks og tilknyttede klassen som behandler oppretter webforespørsler for prefikset. Denne klassen kan ikke arves."
  remarks: "Using the <xref:System.Net.WebRequest> and <xref:System.Net.WebResponse> classes, applications can request resources for any valid <xref:System.Uri>. Use this configuration element to specify a module that is registered to work with the <xref:System.Net.WebRequest.Create%2A> overloads to create new requests.  \n  \n This class corresponds to the [\\&lt;add\\&gt; Element for webRequestModules (Network Settings)](../Topic/%3Cadd%3E%20Element%20for%20webRequestModules%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify modules registered to authenticate requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files.  \n  \n The .NET Framework version 2.0 provides Web request modules that create requests for resources with the following prefixes:  \n  \n-   HTTP  \n  \n-   HTTPS  \n  \n-   FTP  \n  \n-   FILE"
  syntax:
    content: 'public sealed class WebRequestModuleElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement()
  nameWithType: WebRequestModuleElement.WebRequestModuleElement()
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Net.Configuration.WebRequestModuleElement&quot;> </xref> klasse."
  syntax:
    content: public WebRequestModuleElement ();
    parameters: []
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement(String,String)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,String)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Net.Configuration.WebRequestModuleElement&quot;> </xref> klasse ved hjelp av den angitte URI prefikset og type informasjonen."
  remarks: "Den `type` parameteren inneholder fullstendige typenavn fulgt av et komma (,) og samlingsinformasjon. Elementene i samlingsinformasjon atskilt med komma, for eksempel &quot;`System.Net.DigestClient, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;`.       Den <xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>er satt til `prefix` og <xref:System.Net.Configuration.WebRequestModuleElement.Type%2A>er satt til `type`.</xref:System.Net.Configuration.WebRequestModuleElement.Type%2A> </xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>"
  syntax:
    content: public WebRequestModuleElement (string prefix, string type);
    parameters:
    - id: prefix
      type: System.String
      description: "En streng med prefikset URI."
    - id: type
      type: System.String
      description: "En streng som inneholder informasjon og samlingsnavn for klassen som behandler oppretting av forespørsler for ressurser som bruker den `prefix` URI prefiks. For mer informasjon, kan du se kommentarer."
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  id: '#ctor(System.String,System.Type)'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement(String,Type)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,Type)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,Type)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Net.Configuration.WebRequestModuleElement&quot;> </xref> klasse ved hjelp av det angitte URIEN prefikset og Skriv inn identifikator."
  remarks: "Den <xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>er satt til `prefix` og <xref:System.Net.Configuration.WebRequestModuleElement.Type%2A>er satt til `type`.</xref:System.Net.Configuration.WebRequestModuleElement.Type%2A> </xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A>"
  syntax:
    content: public WebRequestModuleElement (string prefix, Type type);
    parameters:
    - id: prefix
      type: System.String
      description: "En streng med prefikset URI."
    - id: type
      type: System.Type
      description: "En <xref:System.Type>som identifiserer klassen som behandler oppretting forespørsler om ressurser som bruker den `prefix` URI prefiks.</xref:System.Type>"
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix
  id: Prefix
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
  fullName: System.Net.Configuration.WebRequestModuleElement.Prefix
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Henter eller angir URI-prefiks for den gjeldende forespørselen-modulen."
  remarks: ".NET Framework, versjon 2.0 gir forespørsel-moduler oppretter forespørsler om ressurser med følgende prefiks: – HTTP - HTTPS - FTP - fil"
  syntax:
    content: public string Prefix { get; set; }
    return:
      type: System.String
      description: "En streng som inneholder et URI-prefiks."
  overload: System.Net.Configuration.WebRequestModuleElement.Prefix*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.Properties
  id: Properties
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
  fullName: System.Net.Configuration.WebRequestModuleElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Net.Configuration.WebRequestModuleElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.WebRequestModuleElement.Type
  id: Type
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Type
  nameWithType: WebRequestModuleElement.Type
  fullName: System.Net.Configuration.WebRequestModuleElement.Type
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Henter eller angir en klasse som oppretter webforespørsler."
  remarks: "Ved hjelp av <xref:System.Net.WebRequest>og <xref:System.Net.WebResponse>klasser, programmer kan be om ressurser for en gyldig <xref:System.Uri>.</xref:System.Uri> </xref:System.Net.WebResponse> </xref:System.Net.WebRequest> Bruk denne egenskapen til å angi en type som er registrert til å fungere med den <xref:System.Net.WebRequest.Create%2A>metode for å opprette nye forespørsler.</xref:System.Net.WebRequest.Create%2A>       .NET Framework, versjon 2.0 gir forespørsel-moduler oppretter forespørsler om ressurser med følgende prefiks: – HTTP - HTTPS - FTP - fil"
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "En <xref:System.Type>-forekomst som identifiserer en forespørsel-modul.</xref:System.Type>"
  overload: System.Net.Configuration.WebRequestModuleElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement()
  nameWithType: WebRequestModuleElement.WebRequestModuleElement()
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement()
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement(String,String)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,String)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement(String,Type)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,Type)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
  fullName: System.Net.Configuration.WebRequestModuleElement.Prefix
- uid: System.Net.Configuration.WebRequestModuleElement.Properties
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
  fullName: System.Net.Configuration.WebRequestModuleElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.WebRequestModuleElement.Type
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Type
  nameWithType: WebRequestModuleElement.Type
  fullName: System.Net.Configuration.WebRequestModuleElement.Type
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement
  nameWithType: WebRequestModuleElement.WebRequestModuleElement
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
- uid: System.Net.Configuration.WebRequestModuleElement.Properties*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
- uid: System.Net.Configuration.WebRequestModuleElement.Type*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Type
  nameWithType: WebRequestModuleElement.Type
