### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  id: ServiceSettingsResponseInfo
  children:
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  langs:
  - csharp
  name: ServiceSettingsResponseInfo
  nameWithType: ServiceSettingsResponseInfo
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  type: Class
  summary: "Inneholder informasjonen som ble returnert når en node-forespørsler innstillingene for en node Løsningsprogrammet tjeneste."
  remarks: "Forekomster av denne klassen brukes primært til å sende tjenesten innstillinger svar informasjon fra tjenesten Løsningsprogrammet til en nettverksklient til denne tjenesten."
  syntax:
    content: >-
      [System.ServiceModel.MessageContract(IsWrapped=false)]

      public class ServiceSettingsResponseInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ServiceSettingsResponseInfo()
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Initialiserer en ny standardforekomst av den <xref href=&quot;System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo&quot;> </xref> klasse."
  remarks: "Standardverdien for `control` er satt til sann."
  syntax:
    content: public ServiceSettingsResponseInfo ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ServiceSettingsResponseInfo(Boolean)
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo&quot;> </xref> klassen med den angitte henvisning policy-verdien."
  syntax:
    content: public ServiceSettingsResponseInfo (bool control);
    parameters:
    - id: control
      type: System.Boolean
      description: "<xref:System.Boolean>som angir om referanser er sendt av Løsningsprogrammet-tjenesten.</xref:System.Boolean>"
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  id: ControlMeshShape
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Henter eller angir om referanser er sendt av Løsningsprogrammet-tjenesten."
  syntax:
    content: public bool ControlMeshShape { get; set; }
    return:
      type: System.Boolean
      description: "SANN hvis referanser fra motpartene deltar i nettet sendes; USANN hvis de ignoreres."
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  id: HasBody
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: HasBody()
  nameWithType: ServiceSettingsResponseInfo.HasBody()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Angir om meldingsteksten som inneholder en serialisert forekomst av denne typen er riktig utformet."
  syntax:
    content: public bool HasBody ();
    parameters: []
    return:
      type: System.Boolean
      description: "SANN hvis tjenesten innstillinger svartekst-informasjonen er riktig utformet av avsenderen; FALSE hvis den ikke."
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo()
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo(Boolean)
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: HasBody()
  nameWithType: ServiceSettingsResponseInfo.HasBody()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody()
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: HasBody
  nameWithType: ServiceSettingsResponseInfo.HasBody
