### YamlMime:ManagedReference
items:
- uid: System.Configuration.IConfigurationSectionHandler
  id: IConfigurationSectionHandler
  children:
  - System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: IConfigurationSectionHandler
  nameWithType: IConfigurationSectionHandler
  fullName: System.Configuration.IConfigurationSectionHandler
  type: Interface
  summary: "Behandler tilgang til bestemte konfigurasjonsdeler."
  remarks: "**Viktig** IConfigurationSectionHandler er avskrevet i .NET Framework 2.0 og nyere. Men fordi den brukes internt, den er beholdt. Du finner et eksempel på [slik: opprette egendefinert konfigurasjon deler ved hjelp av IConfigurationSectionHandler](~/add/includes/ajax-current-ext-md.md). Hvis du bruker det forrige eksemplet, bygger du den med .NET Framework, versjon 1.0 eller 1.1.       I .NET Framework, versjon 2.0 eller senere, du må i stedet avledes fra de <xref:System.Configuration.ConfigurationSection>klassen for å implementere relaterte for konfigurasjonsdelen.</xref:System.Configuration.ConfigurationSection> Du finner et eksempel på [slik: opprette egendefinert konfigurasjon deler ved hjelp av ConfigurationSection](~/add/includes/ajax-current-ext-md.md).       Forekomster av klassen IConfigurationSectionHandler må være tråd trygt og uten status. Den <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>metoden må kalles opp fra flere tråder samtidig.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A>       I tillegg konfigurasjonsobjektet generert av den <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>metoden må være tråd trygt og uforanderlig.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A> Fordi configuration-objekter hurtigbufres av Konfigurasjonssystemet, er det viktig ikke å endre argumentet overordnede til den <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>metoden.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A> For eksempel hvis returverdien for <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>er bare en liten endring av overordnet faktiske endringer må gjøres på en kopi av overordnet, ikke opprinnelig.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A>"
  syntax:
    content: public interface IConfigurationSectionHandler
  implements: []
  platform:
  - net462
- uid: System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IConfigurationSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Oppretter en konfigurasjonsdelen."
  remarks: "Forekomster av den <xref:System.Configuration.IConfigurationSectionHandler>klassen må være tråd trygt og uten status.</xref:System.Configuration.IConfigurationSectionHandler> Create-metoden må kalles opp fra flere tråder samtidig.       I tillegg må konfigurasjonsobjektet generert av en Create-metoden være tråd trygt og uforanderlig. Fordi configuration-objekter hurtigbufres av Konfigurasjonssystemet, er det viktig ikke å endre det overordnede argumentet for Create. For eksempel hvis returverdien opprette er bare en liten endring av overordnet, faktisk endringer må gjøres på en kopi av overordnet, ikke opprinnelig."
  syntax:
    content: public object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Overordnet objekt."
    - id: configContext
      type: System.Object
      description: "Konfigurasjonen context-objektet."
    - id: section
      type: System.Xml.XmlNode
      description: "Delen XML-node."
    return:
      type: System.Object
      description: "Objektet som opprettet delen behandlingsprogram."
  overload: System.Configuration.IConfigurationSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IConfigurationSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IConfigurationSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.IConfigurationSectionHandler.Create*
  parent: System.Configuration.IConfigurationSectionHandler
  isExternal: false
  name: Create
  nameWithType: IConfigurationSectionHandler.Create
