### YamlMime:ManagedReference
items:
- uid: System.Management.ComparisonSettings
  id: ComparisonSettings
  children:
  - System.Management.ComparisonSettings.IgnoreCase
  - System.Management.ComparisonSettings.IgnoreClass
  - System.Management.ComparisonSettings.IgnoreDefaultValues
  - System.Management.ComparisonSettings.IgnoreFlavor
  - System.Management.ComparisonSettings.IgnoreObjectSource
  - System.Management.ComparisonSettings.IgnoreQualifiers
  - System.Management.ComparisonSettings.IncludeAll
  langs:
  - csharp
  name: ComparisonSettings
  nameWithType: ComparisonSettings
  fullName: System.Management.ComparisonSettings
  type: Enum
  summary: "Beskriver objektet sammenligningen modi som kan brukes med <xref:System.Management.ManagementBaseObject.CompareTo*>.</xref:System.Management.ManagementBaseObject.CompareTo*> Vær oppmerksom på at disse verdiene kan kombineres."
  syntax:
    content: >-
      [System.Flags]

      public enum ComparisonSettings
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreCase
  id: IgnoreCase
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreCase
  nameWithType: ComparisonSettings.IgnoreCase
  fullName: System.Management.ComparisonSettings.IgnoreCase
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'En modus som sammenligner strengverdier på en samlingstype måte. Dette gjelder for strenger og kvalifikatoren verdier. Egenskapen og kvalifikatoren sammenlignes alltid på en samlingstype måte om dette flagget er angitt eller ikke. Verdi: 16.'
  syntax:
    content: IgnoreCase
    return:
      type: System.Management.ComparisonSettings
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreClass
  id: IgnoreClass
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreClass
  nameWithType: ComparisonSettings.IgnoreClass
  fullName: System.Management.ComparisonSettings.IgnoreClass
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'En modus som er basert på objekter som sammenlignes er forekomster av den samme klassen. Denne verdien gjør derfor sammenligning av bare forekomsten relatert informasjon. Bruk dette flagget for å optimalisere ytelsen. Hvis objektene ikke er av den samme klassen, er resultatet definert. Verdi: 8.'
  syntax:
    content: IgnoreClass
    return:
      type: System.Management.ComparisonSettings
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreDefaultValues
  id: IgnoreDefaultValues
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreDefaultValues
  nameWithType: ComparisonSettings.IgnoreDefaultValues
  fullName: System.Management.ComparisonSettings.IgnoreDefaultValues
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'En modus som ignorerer standardverdiene for egenskaper. Denne verdien har bare betydning når sammenligning klasser. Verdi: 4.'
  syntax:
    content: IgnoreDefaultValues
    return:
      type: System.Management.ComparisonSettings
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreFlavor
  id: IgnoreFlavor
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreFlavor
  nameWithType: ComparisonSettings.IgnoreFlavor
  fullName: System.Management.ComparisonSettings.IgnoreFlavor
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'En modus som ignorerer kvalifikatoren *utgaver*. Dette flagget fremdeles tar kvalifikatoren verdier til kontoen, ignorerer versjon forskjeller som overføring regler og overstyre begrensninger. Verdi: 32.'
  syntax:
    content: IgnoreFlavor
    return:
      type: System.Management.ComparisonSettings
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreObjectSource
  id: IgnoreObjectSource
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreObjectSource
  nameWithType: ComparisonSettings.IgnoreObjectSource
  fullName: System.Management.ComparisonSettings.IgnoreObjectSource
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'En modus som ignorerer kilden for objekter som serveren og navneområdet de kom fra i sammenligning til andre objekter. Verdi: 2.'
  syntax:
    content: IgnoreObjectSource
    return:
      type: System.Management.ComparisonSettings
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IgnoreQualifiers
  id: IgnoreQualifiers
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreQualifiers
  nameWithType: ComparisonSettings.IgnoreQualifiers
  fullName: System.Management.ComparisonSettings.IgnoreQualifiers
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'En modus som sammenligner objekter, ignorerer *kvalifikatorer*. Verdi: 1.'
  syntax:
    content: IgnoreQualifiers
    return:
      type: System.Management.ComparisonSettings
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Management.ComparisonSettings.IncludeAll
  id: IncludeAll
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IncludeAll
  nameWithType: ComparisonSettings.IncludeAll
  fullName: System.Management.ComparisonSettings.IncludeAll
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'En modus som sammenligner alle elementer i sammenlignede objekter. Verdi: 0.'
  syntax:
    content: IncludeAll
    return:
      type: System.Management.ComparisonSettings
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Management.ComparisonSettings.IgnoreCase
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreCase
  nameWithType: ComparisonSettings.IgnoreCase
  fullName: System.Management.ComparisonSettings.IgnoreCase
- uid: System.Management.ComparisonSettings
  parent: System.Management
  isExternal: false
  name: ComparisonSettings
  nameWithType: ComparisonSettings
  fullName: System.Management.ComparisonSettings
- uid: System.Management.ComparisonSettings.IgnoreClass
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreClass
  nameWithType: ComparisonSettings.IgnoreClass
  fullName: System.Management.ComparisonSettings.IgnoreClass
- uid: System.Management.ComparisonSettings.IgnoreDefaultValues
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreDefaultValues
  nameWithType: ComparisonSettings.IgnoreDefaultValues
  fullName: System.Management.ComparisonSettings.IgnoreDefaultValues
- uid: System.Management.ComparisonSettings.IgnoreFlavor
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreFlavor
  nameWithType: ComparisonSettings.IgnoreFlavor
  fullName: System.Management.ComparisonSettings.IgnoreFlavor
- uid: System.Management.ComparisonSettings.IgnoreObjectSource
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreObjectSource
  nameWithType: ComparisonSettings.IgnoreObjectSource
  fullName: System.Management.ComparisonSettings.IgnoreObjectSource
- uid: System.Management.ComparisonSettings.IgnoreQualifiers
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreQualifiers
  nameWithType: ComparisonSettings.IgnoreQualifiers
  fullName: System.Management.ComparisonSettings.IgnoreQualifiers
- uid: System.Management.ComparisonSettings.IncludeAll
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IncludeAll
  nameWithType: ComparisonSettings.IncludeAll
  fullName: System.Management.ComparisonSettings.IncludeAll
