### YamlMime:ManagedReference
items:
- uid: System.Configuration.NameValueFileSectionHandler
  id: NameValueFileSectionHandler
  children:
  - System.Configuration.NameValueFileSectionHandler.#ctor
  - System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: NameValueFileSectionHandler
  nameWithType: NameValueFileSectionHandler
  fullName: System.Configuration.NameValueFileSectionHandler
  type: Class
  summary: "Gir tilgang til en konfigurasjonsfil. Denne typen støtter infrastrukturen i .NET Framework-konfigurasjon og skal ikke brukes direkte fra koden."
  remarks: "Den `file` for den `<appSettings>` delen angir en relativ bane til en ekstern fil som inneholder innstillinger for egendefinert konfigurasjon av program. Informasjonen som er angitt i filen fungere som en `<appSettings>` delen i konfigurasjonsfilen. Den er tilgang til filen ved hjelp av NameValueFileSectionHandler-klassen. Filen rotelementet må samsvare med delen refererer til den."
  syntax:
    content: 'public class NameValueFileSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NameValueFileSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.NameValueFileSectionHandler
  langs:
  - csharp
  name: NameValueFileSectionHandler()
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler()
  fullName: System.Configuration.NameValueFileSectionHandler.NameValueFileSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.NameValueFileSectionHandler&quot;> </xref> klasse."
  syntax:
    content: public NameValueFileSectionHandler ();
    parameters: []
  overload: System.Configuration.NameValueFileSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.NameValueFileSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Oppretter en ny konfigurasjon-behandling og legger det til samlingen delen behandlingsprogrammet basert på de angitte parameterne."
  remarks: "Den `parent` objektet parameteren fungerer som konfigurasjonsinnstillingene under tilsvarende overordnede konfigurasjon. Den `configContext` objekt-parameteren er den virtuelle banen som beregner i konfigurasjonsdelen konfigurasjonsverdier. Vanligvis denne parameteren er reservert og `null`. Den `section` parameteren er av <xref:System.Xml.XmlNode>som inneholder konfigurasjonsinformasjonen som skal behandles.</xref:System.Xml.XmlNode> Den `section` parameteren gir direkte tilgang til XML-innholdet i konfigurasjonsdelen."
  syntax:
    content: public object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Det overordnede objektet."
    - id: configContext
      type: System.Object
      description: "Konfigurasjonsobjektet kontekst."
    - id: section
      type: System.Xml.XmlNode
      description: "Delen XML-node."
    return:
      type: System.Object
      description: "Konfigurasjonsobjektet."
  overload: System.Configuration.NameValueFileSectionHandler.Create*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The file specified in the <xref uid=\"langword_csharp_file\" name=\"file\" href=\"\"></xref> attribute of <code>section</code> exists but cannot be loaded.  \n  \n \\- or -  \n  \n The <xref uid=\"langword_csharp_name\" name=\"name\" href=\"\"></xref> attribute of <code>section</code> does not match the root element of the file specified in the <xref uid=\"langword_csharp_file\" name=\"file\" href=\"\"></xref> attribute."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Configuration.NameValueFileSectionHandler.#ctor
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: NameValueFileSectionHandler()
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler()
  fullName: System.Configuration.NameValueFileSectionHandler.NameValueFileSectionHandler()
- uid: System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.NameValueFileSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.NameValueFileSectionHandler.#ctor*
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: NameValueFileSectionHandler
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler
- uid: System.Configuration.NameValueFileSectionHandler.Create*
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: Create
  nameWithType: NameValueFileSectionHandler.Create
