### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ModuleElement
  id: ModuleElement
  children:
  - System.Net.Configuration.ModuleElement.#ctor
  - System.Net.Configuration.ModuleElement.Properties
  - System.Net.Configuration.ModuleElement.Type
  langs:
  - csharp
  name: ModuleElement
  nameWithType: ModuleElement
  fullName: System.Net.Configuration.ModuleElement
  type: Class
  summary: "Representerer typeinformasjonen for en egendefinert <xref:System.Net.IWebProxy>modulen.</xref:System.Net.IWebProxy> Denne klassen kan arves."
  remarks: "This class corresponds to the `type` attribute of the [\\&lt;module\\&gt; Element (Network Settings)](../Topic/%3Cmodule%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify a Web proxy that handles requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ModuleElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.ModuleElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ModuleElement
  langs:
  - csharp
  name: ModuleElement()
  nameWithType: ModuleElement.ModuleElement()
  fullName: System.Net.Configuration.ModuleElement.ModuleElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Net.Configuration.ModuleElement&quot;> </xref> klasse."
  remarks: "Denne konstruktøren legger til en <xref:System.Configuration.ConfigurationProperty>objekt den <xref:System.Net.Configuration.ModuleElement.Type%2A>egenskapen den <xref:System.Configuration.ConfigurationElement.Properties%2A>samlingen.</xref:System.Configuration.ConfigurationElement.Properties%2A> </xref:System.Net.Configuration.ModuleElement.Type%2A> </xref:System.Configuration.ConfigurationProperty>"
  syntax:
    content: public ModuleElement ();
    parameters: []
  overload: System.Net.Configuration.ModuleElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ModuleElement.Properties
  id: Properties
  parent: System.Net.Configuration.ModuleElement
  langs:
  - csharp
  name: Properties
  nameWithType: ModuleElement.Properties
  fullName: System.Net.Configuration.ModuleElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Net.Configuration.ModuleElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ModuleElement.Type
  id: Type
  parent: System.Net.Configuration.ModuleElement
  langs:
  - csharp
  name: Type
  nameWithType: ModuleElement.Type
  fullName: System.Net.Configuration.ModuleElement.Type
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Henter eller angir og samlingsnavn informasjonen for den gjeldende forekomsten."
  remarks: "Denne egenskapen inneholder fullstendige typenavn fulgt av et komma (,) og samlingsinformasjon. Elementene i samlingsinformasjon atskilt med komma, for eksempel `Corp.Net.CustomWebProxy, CorpLibrary, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=&quot;00000000000000000&quot;`."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "En streng som identifiserer en type som implementerer den <xref:System.Net.IWebProxy>grensesnittet eller <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> Hvis ingen verdi er angitt.</xref:System.Net.IWebProxy>"
  overload: System.Net.Configuration.ModuleElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ModuleElement.#ctor
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: ModuleElement()
  nameWithType: ModuleElement.ModuleElement()
  fullName: System.Net.Configuration.ModuleElement.ModuleElement()
- uid: System.Net.Configuration.ModuleElement.Properties
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Properties
  nameWithType: ModuleElement.Properties
  fullName: System.Net.Configuration.ModuleElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ModuleElement.Type
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Type
  nameWithType: ModuleElement.Type
  fullName: System.Net.Configuration.ModuleElement.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.ModuleElement.#ctor*
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: ModuleElement
  nameWithType: ModuleElement.ModuleElement
- uid: System.Net.Configuration.ModuleElement.Properties*
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Properties
  nameWithType: ModuleElement.Properties
- uid: System.Net.Configuration.ModuleElement.Type*
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Type
  nameWithType: ModuleElement.Type
