### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.ManagementConfigurationType
  id: ManagementConfigurationType
  children:
  - System.Management.Instrumentation.ManagementConfigurationType.Apply
  - System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  langs:
  - csharp
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
  type: Enum
  summary: "Representerer mulige commit-virkemåter i en egenskap med lese-og skrivetilgang. Den brukes som verdien for en parameter for de <xref href=&quot;System.Management.Instrumentation.ManagementConfigurationAttribute&quot;> </xref> attributtet.       Obs! regnes nå WMI .NET-bibliotekene i endelig status, og ingen ytterligere development, forbedringer, eller oppdateringer er tilgjengelige for ikke-relaterte sikkerhetsproblemer som påvirker disse bibliotekene. Den [MI APIer](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx) skal brukes for alle nye utvikling."
  remarks: "Dette attributtet brukes som en parameterverdi for den <xref:System.Management.Instrumentation.ManagementConfigurationAttribute>attributtet bare hvis det <xref:System.Management.Instrumentation.ManagementCommitAttribute>attributtet brukes til å identifisere en metode til å kjøre hvis du vil utføre verdier.</xref:System.Management.Instrumentation.ManagementCommitAttribute> </xref:System.Management.Instrumentation.ManagementConfigurationAttribute> Ellers brukt skrivetilgang egenskapsverdier automatisk."
  syntax:
    content: public enum ManagementConfigurationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  id: Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Angi verdier tre i kraft når Commit kalles."
  syntax:
    content: Apply
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  id: OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Angi verdiene brukes umiddelbart."
  syntax:
    content: OnCommit
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
- uid: System.Management.Instrumentation.ManagementConfigurationType
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
