### YamlMime:ManagedReference
items:
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  id: ChartHttpHandlerSettings
  children:
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(System.String)
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  - System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  langs:
  - csharp
  name: ChartHttpHandlerSettings
  nameWithType: ChartHttpHandlerSettings
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  type: Class
  summary: "Gir attributter som kan brukes til å skrive en egendefinert HTTP-behandlingsprogram for lagring av midlertidige bildefiler."
  syntax:
    content: public class ChartHttpHandlerSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  id: CustomHandlerName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: CustomHandlerName
  nameWithType: ChartHttpHandlerSettings.CustomHandlerName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Henter eller angir navnet på egendefinert behandlingsprogram."
  syntax:
    content: public string CustomHandlerName { get; set; }
    return:
      type: System.String
      description: "En <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> verdi som representerer navnet på egendefinert behandlingsprogram."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  id: Directory
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Directory
  nameWithType: ChartHttpHandlerSettings.Directory
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Henter eller angir til egendefinert behandlingsprogram mappe der de midlertidige bildefilene skal lagres."
  syntax:
    content: public string Directory { get; set; }
    return:
      type: System.String
      description: "En <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> verdi som representerer mappen."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  id: FolderName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: FolderName
  nameWithType: ChartHttpHandlerSettings.FolderName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Henter eller angir mappen som skal brukes for lagring av bilder i den angitte mappen."
  syntax:
    content: public string FolderName { get; set; }
    return:
      type: System.String
      description: "En <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> som representerer navnet på mappen."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  id: HandlerType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: HandlerType
  nameWithType: ChartHttpHandlerSettings.HandlerType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Henter behandlingsprogrammet typen egendefinert behandlingsprogram."
  syntax:
    content: public Type HandlerType { get; }
    return:
      type: System.Type
      description: "Den <xref:System.Type>for egendefinert behandlingsprogram.</xref:System.Type>"
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(System.String)
  id: Item(System.String)
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Item(String)
  nameWithType: ChartHttpHandlerSettings.Item(String)
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(String)
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Henter innstillinger for parameter med det angitte navnet som er registrert i Web.config-filen med det `ChartHttpHandler` nøkkel."
  remarks: "Bruk denne metoden til å få tilgang til en parameter i Web.config-filen med det `ChartHttpHandler` nøkkel."
  syntax:
    content: public string this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "Navnet på parameteren til å hente."
    return:
      type: System.String
      description: "Verdien for parameteren."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  id: PrivateImages
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: PrivateImages
  nameWithType: ChartHttpHandlerSettings.PrivateImages
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Henter et flagg som indikerer om behandlingsprogrammet benytte private bilder."
  remarks: "Når egenskapen PrivateImages er angitt, returnerer ikke et behandlingsprogram bilder utenfor økten. I tillegg vil klienten ikke kunne laste ned en annen bruker bilder. Dette er standard virkemåte."
  syntax:
    content: public bool PrivateImages { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>Hvis et behandlingsprogram benytte private bilder, ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  id: StorageType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: StorageType
  nameWithType: ChartHttpHandlerSettings.StorageType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Henter eller angir bildelagringstypen for diagrammet."
  remarks: "Diagrammet bilder kan lagres som filer eller i minnet."
  syntax:
    content: public System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType StorageType { get; set; }
    return:
      type: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType
      description: "En <xref href=&quot;System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType&quot;> </xref> opplistingsverdien som representerer bildelagringstypen for diagrammet."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  id: Timeout
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Timeout
  nameWithType: ChartHttpHandlerSettings.Timeout
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Henter eller angir tidsavbruddet for egendefinert behandlingsprogram."
  remarks: "Når tidsavbruddet er utløpt, lagrede diagrambildet overstyres av en ny diagrambildet eller forkastet."
  syntax:
    content: public TimeSpan Timeout { get; set; }
    return:
      type: System.TimeSpan
      description: "En <xref:System.TimeSpan>opplistingsverdien som representerer levetiden for diagrammet bilder.</xref:System.TimeSpan>"
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  id: Url
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  langs:
  - csharp
  name: Url
  nameWithType: ChartHttpHandlerSettings.Url
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  type: Property
  assemblies:
  - System.Web.DataVisualization
  namespace: System.Web.UI.DataVisualization.Charting
  summary: "Henter eller angir URL-adressen som samsvarer med HTTP-banen der midlertidige bildefiler er lagret."
  syntax:
    content: public string Url { get; set; }
    return:
      type: System.String
      description: "En <xref uid=&quot;langword_csharp_string&quot; name=&quot;string&quot; href=&quot;&quot;> </xref> verdi som representerer URL-adressen."
  overload: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: CustomHandlerName
  nameWithType: ChartHttpHandlerSettings.CustomHandlerName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Directory
  nameWithType: ChartHttpHandlerSettings.Directory
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: FolderName
  nameWithType: ChartHttpHandlerSettings.FolderName
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: HandlerType
  nameWithType: ChartHttpHandlerSettings.HandlerType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(System.String)
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Item(String)
  nameWithType: ChartHttpHandlerSettings.Item(String)
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item(String)
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: PrivateImages
  nameWithType: ChartHttpHandlerSettings.PrivateImages
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: StorageType
  nameWithType: ChartHttpHandlerSettings.StorageType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType
  parent: System.Web.UI.DataVisualization.Charting
  isExternal: false
  name: ChartHttpHandlerStorageType
  nameWithType: ChartHttpHandlerStorageType
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerStorageType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Timeout
  nameWithType: ChartHttpHandlerSettings.Timeout
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Url
  nameWithType: ChartHttpHandlerSettings.Url
  fullName: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.CustomHandlerName*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: CustomHandlerName
  nameWithType: ChartHttpHandlerSettings.CustomHandlerName
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Directory*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Directory
  nameWithType: ChartHttpHandlerSettings.Directory
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.FolderName*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: FolderName
  nameWithType: ChartHttpHandlerSettings.FolderName
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.HandlerType*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: HandlerType
  nameWithType: ChartHttpHandlerSettings.HandlerType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Item*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Item
  nameWithType: ChartHttpHandlerSettings.Item
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.PrivateImages*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: PrivateImages
  nameWithType: ChartHttpHandlerSettings.PrivateImages
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.StorageType*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: StorageType
  nameWithType: ChartHttpHandlerSettings.StorageType
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Timeout*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Timeout
  nameWithType: ChartHttpHandlerSettings.Timeout
- uid: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings.Url*
  parent: System.Web.UI.DataVisualization.Charting.ChartHttpHandlerSettings
  isExternal: false
  name: Url
  nameWithType: ChartHttpHandlerSettings.Url
