### YamlMime:ManagedReference
items:
- uid: System.Drawing.Printing.QueryPageSettingsEventHandler
  id: QueryPageSettingsEventHandler
  langs:
  - csharp
  name: QueryPageSettingsEventHandler
  nameWithType: QueryPageSettingsEventHandler
  fullName: System.Drawing.Printing.QueryPageSettingsEventHandler
  type: Delegate
  summary: "Representerer metoden som behandler den <xref href=&quot;System.Drawing.Printing.PrintDocument.QueryPageSettings&quot;> </xref> hendelse for en <xref href=&quot;System.Drawing.Printing.PrintDocument&quot;> </xref>."
  remarks: "Når du oppretter en QueryPageSettingsEventHandler representant, må du identifisere metoden som håndterer hendelsen. Hvis du vil knytte hendelsen til hendelsesbehandlingen, må du legge til en forekomst av representanten i hendelsen. Hendelsesbehandlingen kalles når det oppstår hendelsen, med mindre du fjerner representanten. Du finner mer informasjon om hendelsesbehandlingen representanter [hendelser](~/add/includes/ajax-current-ext-md.md).       Du finner mer informasjon om utskrift av <xref:System.Drawing.Printing>Oversikt over navneområde.</xref:System.Drawing.Printing>"
  syntax:
    content: public delegate void QueryPageSettingsEventHandler(object sender, QueryPageSettingsEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
