### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationCompletedException
  id: WorkflowApplicationCompletedException
  children:
  - System.Activities.WorkflowApplicationCompletedException.#ctor
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Exception)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid,System.Exception)
  langs:
  - csharp
  name: WorkflowApplicationCompletedException
  nameWithType: WorkflowApplicationCompletedException
  fullName: System.Activities.WorkflowApplicationCompletedException
  type: Class
  summary: "Representerer unntak forårsakes når en operasjon på en arbeidsflytforekomst ikke er gyldig fordi forekomsten er fullført."
  syntax:
    content: 'public class WorkflowApplicationCompletedException : System.Activities.WorkflowApplicationException'
  inheritance:
  - System.Exception
  - System.Activities.WorkflowApplicationException
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.InstanceId
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor
  id: '#ctor'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException()
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Oppretter en ny forekomst av den <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> klasse."
  syntax:
    content: public WorkflowApplicationCompletedException ();
    parameters: []
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Oppretter en ny forekomst av den <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> klassen med en beskrivelse av unntaket streng."
  syntax:
    content: public WorkflowApplicationCompletedException (string message);
    parameters:
    - id: message
      type: System.String
      description: "En beskrivelse av programmet fullført unntak."
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Oppretter en ny forekomst av den <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> klasse sammenheng og serialisering informasjonen som kreves for å hente data om dette unntaket fra en serialisert dataflyt."
  syntax:
    content: protected WorkflowApplicationCompletedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "All informasjon som er nødvendig for å serialisere eller deserialisere fullført unntak applikasjonsobjektet."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Kilde og mål for en gitt serialisert dataflyt og en ekstra oppkaller brukerdefinert kontekst."
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Oppretter en ny forekomst av den <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> klassen med en beskrivelse av unntaket streng og med et ekstra unntak som er årsaken til programmet er fullført-unntak."
  syntax:
    content: public WorkflowApplicationCompletedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "En beskrivelse av programmet fullført unntak."
    - id: innerException
      type: System.Exception
      description: "Et unntak som har en causal relasjon til programmet fullført unntak. Programmet er fullført unntaket er et svar på det interne unntaket og kan bruke informasjon fra det interne unntaket til å håndtere feilen mer på riktig måte."
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String,Guid)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Oppretter en ny forekomst av den <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> klassen med en beskrivelse av unntaket streng og en unik identifikator for unntaket."
  syntax:
    content: public WorkflowApplicationCompletedException (string message, Guid instanceId);
    parameters:
    - id: message
      type: System.String
      description: "En beskrivelse av programmet fullført unntak."
    - id: instanceId
      type: System.Guid
      description: "En globalt unik identifikator."
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid,System.Exception)
  id: '#ctor(System.String,System.Guid,System.Exception)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Oppretter en ny forekomst av den <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref> type med en beskrivelse for streng unntaket, en unik identifikator for den og et ekstra unntak som er årsaken til programmet er fullført-unntak."
  syntax:
    content: public WorkflowApplicationCompletedException (string message, Guid instanceId, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "En beskrivelse av programmet fullført unntak."
    - id: instanceId
      type: System.Guid
      description: "En globalt unik identifikator."
    - id: innerException
      type: System.Exception
      description: "Et unntak som har en causal relasjon til programmet fullført unntak. Programmet er fullført unntaket er et svar på det interne unntaket og kan bruke informasjon fra det interne unntaket til å håndtere feilen mer på riktig måte."
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.WorkflowApplicationException
  isExternal: false
  name: System.Activities.WorkflowApplicationException
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException()
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Exception)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String,Guid)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid,System.Exception)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor*
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException
