### YamlMime:ManagedReference
items:
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  id: EnvironmentPermissionAccess
  children:
  - System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  - System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  - System.Security.Permissions.EnvironmentPermissionAccess.Read
  - System.Security.Permissions.EnvironmentPermissionAccess.Write
  langs:
  - csharp
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
  type: Enum
  summary: "Angir tilgang til miljøvariabler."
  remarks: "Denne nummerering brukes av <xref:System.Security.Permissions.EnvironmentPermission>.</xref:System.Security.Permissions.EnvironmentPermission>      > [!NOTE] > Selv om NoAccess og AllAccess vises i EnvironmentPermissionAccess, de ikke er gyldig for bruk som parameter for <xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A>fordi de beskrive ingen miljøet variabelen tilgangstyper eller alle miljøet variabelen tilgangstyper, henholdsvis og <xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A>forventer variabelen tilgang av typen én-miljøet.</xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A> </xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A>"
  syntax:
    content: >-
      [System.Flags]

      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentPermissionAccess
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  id: AllAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: AllAccess
  nameWithType: EnvironmentPermissionAccess.AllAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Lese- og skrivetilgang til miljøvariabler. AllAccess representerer flere EnvironmentPermissionAccess og fører til en <xref:System.ArgumentException>når den brukes som den <code> flag </code> parameteren for den <xref:System.Security.Permissions.EnvironmentPermission.GetPathList*>metoden som forventer en enkeltverdi.</xref:System.Security.Permissions.EnvironmentPermission.GetPathList*> </xref:System.ArgumentException>"
  syntax:
    content: AllAccess
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  id: NoAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: NoAccess
  nameWithType: EnvironmentPermissionAccess.NoAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Ingen tilgang til miljøvariabler. NoAccess representerer ingen gyldig EnvironmentPermissionAccess og fører til en <xref:System.ArgumentException>når den brukes som parameteren for <xref:System.Security.Permissions.EnvironmentPermission.GetPathList*>, som forventer en enkeltverdi.</xref:System.Security.Permissions.EnvironmentPermission.GetPathList*> </xref:System.ArgumentException>"
  syntax:
    content: NoAccess
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Read
  id: Read
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: Read
  nameWithType: EnvironmentPermissionAccess.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Read
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Bare lesetilgang til miljøvariabler er angitt. Endre, slette og opprette miljøvariabler er ikke inkludert i dette tilgangsnivået."
  syntax:
    content: Read
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Write
  id: Write
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: Write
  nameWithType: EnvironmentPermissionAccess.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Write
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "Bare skrivetilgang til miljøvariabler er angitt. Skrivetilgang omfatter oppretting og sletting av miljøvariabler i tillegg endre eksisterende verdier. Lesing miljøvariabler er ikke inkludert i dette tilgangsnivået."
  syntax:
    content: Write
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: AllAccess
  nameWithType: EnvironmentPermissionAccess.AllAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: NoAccess
  nameWithType: EnvironmentPermissionAccess.NoAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Read
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAccess.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Read
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Write
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAccess.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Write
