### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.PriorityGroup
  id: PriorityGroup
  children:
  - System.Web.Services.Configuration.PriorityGroup.High
  - System.Web.Services.Configuration.PriorityGroup.Low
  langs:
  - csharp
  name: PriorityGroup
  nameWithType: PriorityGroup
  fullName: System.Web.Services.Configuration.PriorityGroup
  type: Enum
  summary: "Angir verdiene som kan brukes til å angi prioritet og gruppen attributter for en SOAP-filtype i konfigurasjonsfilen Web Services."
  syntax:
    content: public enum PriorityGroup
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Services.Configuration.PriorityGroup.High
  id: High
  parent: System.Web.Services.Configuration.PriorityGroup
  langs:
  - csharp
  name: High
  nameWithType: PriorityGroup.High
  fullName: System.Web.Services.Configuration.PriorityGroup.High
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Representerer verdien 1. Angir at SOAP-filtypen kjøres i gruppen i SOAP-utvidelser med høyest prioritet."
  syntax:
    content: High
    return:
      type: System.Web.Services.Configuration.PriorityGroup
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.PriorityGroup.Low
  id: Low
  parent: System.Web.Services.Configuration.PriorityGroup
  langs:
  - csharp
  name: Low
  nameWithType: PriorityGroup.Low
  fullName: System.Web.Services.Configuration.PriorityGroup.Low
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Representerer verdien 0. Angir at SOAP-filtypen kjøres i gruppen i SOAP-utvidelser med laveste prioritet."
  syntax:
    content: Low
    return:
      type: System.Web.Services.Configuration.PriorityGroup
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Services.Configuration.PriorityGroup.High
  parent: System.Web.Services.Configuration.PriorityGroup
  isExternal: false
  name: High
  nameWithType: PriorityGroup.High
  fullName: System.Web.Services.Configuration.PriorityGroup.High
- uid: System.Web.Services.Configuration.PriorityGroup
  parent: System.Web.Services.Configuration
  isExternal: false
  name: PriorityGroup
  nameWithType: PriorityGroup
  fullName: System.Web.Services.Configuration.PriorityGroup
- uid: System.Web.Services.Configuration.PriorityGroup.Low
  parent: System.Web.Services.Configuration.PriorityGroup
  isExternal: false
  name: Low
  nameWithType: PriorityGroup.Low
  fullName: System.Web.Services.Configuration.PriorityGroup.Low
