### YamlMime:ManagedReference
items:
- uid: System.Web.PreApplicationStartMethodAttribute
  id: PreApplicationStartMethodAttribute
  children:
  - System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  - System.Web.PreApplicationStartMethodAttribute.MethodName
  - System.Web.PreApplicationStartMethodAttribute.Type
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute
  fullName: System.Web.PreApplicationStartMethodAttribute
  type: Class
  summary: "Gir utvidet støtte for oppstart av programmet."
  remarks: "-Det er ingen garantier i rekkefølgen som kalles samlingen brukerdefinert programmet start-metoder. Resultatet hver registrerte start-metoden må være kodet for å kjøre i isolasjon og bør ikke avhengige bivirkninger fra andre registrerte start-metoder.       Du finner mer informasjon om hvordan du bruker attributter [attributter](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple=true)]

      public sealed class PreApplicationStartMethodAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  id: '#ctor(System.Type,System.String)'
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute(Type,String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.PreApplicationStartMethodAttribute&quot;> </xref> klasse."
  remarks: "Metoden refererer til den `methodName` parameteren må være felles og kan være en forekomst metoden eller statisk metode."
  syntax:
    content: public PreApplicationStartMethodAttribute (Type type, string methodName);
    parameters:
    - id: type
      type: System.Type
      description: "Et objekt som beskriver metoden startet..."
    - id: methodName
      type: System.String
      description: "En tom parameteren signatur som har ingen returverdi."
  overload: System.Web.PreApplicationStartMethodAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  id: MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Henter den tilknyttede startet-metoden."
  syntax:
    content: public string MethodName { get; }
    return:
      type: System.String
      description: "En streng som inneholder navnet på den tilknyttede startet-metoden."
  overload: System.Web.PreApplicationStartMethodAttribute.MethodName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  id: Type
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Henter typen som er returnert av metoden tilknyttede startet."
  syntax:
    content: public Type Type { get; }
    return:
      type: System.Type
      description: "Et objekt som beskriver metoden startet."
  overload: System.Web.PreApplicationStartMethodAttribute.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute(Type,String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
