### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProfileGroupSettings
  id: ProfileGroupSettings
  children:
  - System.Web.Configuration.ProfileGroupSettings.#ctor(System.String)
  - System.Web.Configuration.ProfileGroupSettings.Equals(System.Object)
  - System.Web.Configuration.ProfileGroupSettings.GetHashCode
  - System.Web.Configuration.ProfileGroupSettings.Name
  - System.Web.Configuration.ProfileGroupSettings.Properties
  - System.Web.Configuration.ProfileGroupSettings.PropertySettings
  langs:
  - csharp
  name: ProfileGroupSettings
  nameWithType: ProfileGroupSettings
  fullName: System.Web.Configuration.ProfileGroupSettings
  type: Class
  summary: "Gir programmatisk tilgang til den <xref uid=&quot;langword_csharp_group&quot; name=&quot;group&quot; href=&quot;&quot;> </xref> spørsmål for den <xref uid=&quot;langword_csharp_profiles&quot; name=&quot;profiles&quot; href=&quot;&quot;> </xref> konfigurasjonsdelen filen."
  remarks: "Klassen ProfileGroupSettings gjør det mulig å programmatisk opprette tilgang til og endre grupper med egenskaper som er lagt til i `group` spørsmål for den `profile` delen av konfigurasjonsfilen.       Den `profile` delen av konfigurasjonsfilen angir et skjema for brukerprofiler. Ved kjøretid, bruker systemet ASP.NET kompilering informasjon som er angitt i den `profile` delen til å generere en klasse med navnet `ProfileCommon`, som er avledet fra <xref:System.Web.Profile.ProfileBase>.</xref:System.Web.Profile.ProfileBase> Den `ProfileCommon` definisjon av klasse er basert på egenskapene som er definert i den `properties` spørsmål for den `profile` delen av konfigurasjonsfilen. En forekomst av denne klassen er opprettet for hver brukerprofil, og du har tilgang til de individuelle profil verdiene i koden via den <xref:System.Web.HttpContext.Profile%2A?displayProperty=fullName>egenskapen.</xref:System.Web.HttpContext.Profile%2A?displayProperty=fullName> For mer informasjon om profilen-funksjoner som er lagt til [!INCLUDE[vstecasplong](~/add/includes/vstecasplong-md.md)], se [ASP.NET profilen egenskaper oversikt over](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following code example shows how to use the ProfileGroupSettings type. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#13](~/add/codesnippet/csharp/t-system.web.configurati_94_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#13](~/add/codesnippet/visualbasic/t-system.web.configurati_94_1.vb)]"
  syntax:
    content: 'public sealed class ProfileGroupSettings : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: ProfileGroupSettings(String)
  nameWithType: ProfileGroupSettings.ProfileGroupSettings(String)
  fullName: System.Web.Configuration.ProfileGroupSettings.ProfileGroupSettings(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.ProfileGroupSettings&quot;> </xref> klasse med standardinnstillinger."
  remarks: "Konstruktøren ProfileGroupSettings skal ikke brukes direkte fra koden. Kalles av ASP.NET Konfigurasjonssystemet. Du hente en forekomst av den <xref:System.Web.Configuration.ProfileGroupSettings>klassen ved hjelp av den <xref:System.Configuration.Configuration.GetSection%2A>metoden.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.ProfileGroupSettings>"
  syntax:
    content: public ProfileGroupSettings (string name);
    parameters:
    - id: name
      type: System.String
      description: "Navnet på den nye gruppen."
  overload: System.Web.Configuration.ProfileGroupSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: ProfileGroupSettings.Equals(Object)
  fullName: System.Web.Configuration.ProfileGroupSettings.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Bestemmer om den angitte <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;> </xref> er lik gjeldende <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;> </xref>."
  syntax:
    content: public override bool Equals (object obj);
    parameters:
    - id: obj
      type: System.Object
      description: "Den <xref:System.Object>skal sammenlignes med gjeldende <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;> </xref>.</xref:System.Object>"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis den angitte <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;> </xref> er lik gjeldende <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;> </xref>; ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.ProfileGroupSettings.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: ProfileGroupSettings.GetHashCode()
  fullName: System.Web.Configuration.ProfileGroupSettings.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter en unik verdi som representerer gjeldende <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> forekomsten."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "En unik verdi som representerer gjeldende <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> forekomsten."
  overload: System.Web.Configuration.ProfileGroupSettings.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.Name
  id: Name
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: Name
  nameWithType: ProfileGroupSettings.Name
  fullName: System.Web.Configuration.ProfileGroupSettings.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir navnet på gruppen for <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objekter som inneholder dette objektet."
  remarks: "Gruppenavnet må være unike i en <xref:System.Web.Configuration.ProfileGroupSettingsCollection>samlingen; ellers oppstår et unntak når konfigurasjonsfilen er lagret.</xref:System.Web.Configuration.ProfileGroupSettingsCollection>"
  example:
  - "The following code example shows how to use the Name property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/csharp/p-system.web.configurati_232_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/visualbasic/p-system.web.configurati_232_1.vb)]"
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "En streng som inneholder navnet på gruppen med <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objekter som inneholder dette objektet. Standardverdien er en tom streng (&quot;&quot;)."
  overload: System.Web.Configuration.ProfileGroupSettings.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.Properties
  id: Properties
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: Properties
  nameWithType: ProfileGroupSettings.Properties
  fullName: System.Web.Configuration.ProfileGroupSettings.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Web.Configuration.ProfileGroupSettings.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGroupSettings.PropertySettings
  id: PropertySettings
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: PropertySettings
  nameWithType: ProfileGroupSettings.PropertySettings
  fullName: System.Web.Configuration.ProfileGroupSettings.PropertySettings
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter samlingen av profilen innstillingene for dette objektet inneholder."
  remarks: ''
  example:
  - "The following code example shows how to use the PropertySettings property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/csharp/p-system.web.configurati_256_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/visualbasic/p-system.web.configurati_256_1.vb)]"
  syntax:
    content: public System.Web.Configuration.ProfilePropertySettingsCollection PropertySettings { get; }
    return:
      type: System.Web.Configuration.ProfilePropertySettingsCollection
      description: "En <xref href=&quot;System.Web.Configuration.ProfilePropertySettingsCollection&quot;> </xref> samling som inneholder alle de <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objekter i denne gruppen."
  overload: System.Web.Configuration.ProfileGroupSettings.PropertySettings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.ProfileGroupSettings.#ctor(System.String)
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: ProfileGroupSettings(String)
  nameWithType: ProfileGroupSettings.ProfileGroupSettings(String)
  fullName: System.Web.Configuration.ProfileGroupSettings.ProfileGroupSettings(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.ProfileGroupSettings.Equals(System.Object)
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Equals(Object)
  nameWithType: ProfileGroupSettings.Equals(Object)
  fullName: System.Web.Configuration.ProfileGroupSettings.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.ProfileGroupSettings.GetHashCode
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: GetHashCode()
  nameWithType: ProfileGroupSettings.GetHashCode()
  fullName: System.Web.Configuration.ProfileGroupSettings.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.ProfileGroupSettings.Name
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Name
  nameWithType: ProfileGroupSettings.Name
  fullName: System.Web.Configuration.ProfileGroupSettings.Name
- uid: System.Web.Configuration.ProfileGroupSettings.Properties
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Properties
  nameWithType: ProfileGroupSettings.Properties
  fullName: System.Web.Configuration.ProfileGroupSettings.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ProfileGroupSettings.PropertySettings
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: PropertySettings
  nameWithType: ProfileGroupSettings.PropertySettings
  fullName: System.Web.Configuration.ProfileGroupSettings.PropertySettings
- uid: System.Web.Configuration.ProfilePropertySettingsCollection
  parent: System.Web.Configuration
  isExternal: false
  name: ProfilePropertySettingsCollection
  nameWithType: ProfilePropertySettingsCollection
  fullName: System.Web.Configuration.ProfilePropertySettingsCollection
- uid: System.Web.Configuration.ProfileGroupSettings.#ctor*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: ProfileGroupSettings
  nameWithType: ProfileGroupSettings.ProfileGroupSettings
- uid: System.Web.Configuration.ProfileGroupSettings.Equals*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Equals
  nameWithType: ProfileGroupSettings.Equals
- uid: System.Web.Configuration.ProfileGroupSettings.GetHashCode*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: GetHashCode
  nameWithType: ProfileGroupSettings.GetHashCode
- uid: System.Web.Configuration.ProfileGroupSettings.Name*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Name
  nameWithType: ProfileGroupSettings.Name
- uid: System.Web.Configuration.ProfileGroupSettings.Properties*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Properties
  nameWithType: ProfileGroupSettings.Properties
- uid: System.Web.Configuration.ProfileGroupSettings.PropertySettings*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: PropertySettings
  nameWithType: ProfileGroupSettings.PropertySettings
