### YamlMime:ManagedReference
items:
- uid: System.Activities.Validation.ValidationSettings
  id: ValidationSettings
  children:
  - System.Activities.Validation.ValidationSettings.#ctor
  - System.Activities.Validation.ValidationSettings.AdditionalConstraints
  - System.Activities.Validation.ValidationSettings.CancellationToken
  - System.Activities.Validation.ValidationSettings.Environment
  - System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  - System.Activities.Validation.ValidationSettings.PrepareForRuntime
  - System.Activities.Validation.ValidationSettings.SingleLevel
  - System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  langs:
  - csharp
  name: ValidationSettings
  nameWithType: ValidationSettings
  fullName: System.Activities.Validation.ValidationSettings
  type: Class
  summary: "Representerer en samling med innstillinger som tilpasser virkemåten som <xref:System.Activities.Validation.ActivityValidationServices.Validate*>vil ha.</xref:System.Activities.Validation.ActivityValidationServices.Validate*> Det gjør også at brukeren aktiviteten gjelder Policybegrensninger for en arbeidsflyt."
  syntax:
    content: public class ValidationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.#ctor
  id: '#ctor'
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: ValidationSettings()
  nameWithType: ValidationSettings.ValidationSettings()
  fullName: System.Activities.Validation.ValidationSettings.ValidationSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Oppretter en ny forekomst av den <xref href=&quot;System.Activities.Validation.ValidationSettings&quot;> </xref> klasse."
  syntax:
    content: public ValidationSettings ();
    parameters: []
  overload: System.Activities.Validation.ValidationSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  id: AdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Henter en ordliste for typebegrensning par. Hver ekstra betingelse legges til i ordlisten vil gjelde for alle aktiviteter av typen angi i arbeidsflyten til å validere."
  syntax:
    content: public System.Collections.Generic.IDictionary<Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>> AdditionalConstraints { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.Type,System.Collections.Generic.IList{System.Activities.Validation.Constraint}}
      description: "Ordliste typen listen over begrensninger og typer."
  overload: System.Activities.Validation.ValidationSettings.AdditionalConstraints*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.CancellationToken
  id: CancellationToken
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
  fullName: System.Activities.Validation.ValidationSettings.CancellationToken
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Henter eller angir avbryte tokenet brukes til å varsle skal aktiviteten avbrytes."
  syntax:
    content: public System.Threading.CancellationToken CancellationToken { get; set; }
    return:
      type: System.Threading.CancellationToken
      description: "Avbryte-token som brukes til å varsle skal aktiviteten avbrytes."
  overload: System.Activities.Validation.ValidationSettings.CancellationToken*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.Environment
  id: Environment
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: Environment
  nameWithType: ValidationSettings.Environment
  fullName: System.Activities.Validation.ValidationSettings.Environment
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Henter eller angir miljøet med variabler og argumenter som er forbundet med denne validering-innstillinger."
  syntax:
    content: public System.Activities.LocationReferenceEnvironment Environment { get; set; }
    return:
      type: System.Activities.LocationReferenceEnvironment
      description: "Miljøet med variabler og argumenter som er forbundet med denne validering-innstillinger."
  overload: System.Activities.Validation.ValidationSettings.Environment*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  id: OnlyUseAdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Henter eller angir en verdi som angir om tilleggsgodkjenning-begrensninger som brukes utelukkende til å validere arbeidsflyten. Hvis satt til <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>, ignoreres alle valideringen finnes i aktiviteten seg selv."
  remarks: "<xref:System.Activities.Validation.ActivityValidationServices.Validate%2A>kalles når en arbeidsflyt kjøres, og og resulterende feil vil forårsake en <xref:System.Activities.InvalidWorkflowException>til å bli utløst.</xref:System.Activities.InvalidWorkflowException></xref:System.Activities.Validation.ActivityValidationServices.Validate%2A>"
  syntax:
    content: public bool OnlyUseAdditionalConstraints { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis flere betingelser som skal brukes eksklusivt; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  id: PrepareForRuntime
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
  fullName: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Henter eller angir en verdi som angir om denne forekomsten er klargjort for kjøring."
  syntax:
    content: public bool PrepareForRuntime { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>Hvis denne forekomsten er klargjort for kjøring; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.Validation.ValidationSettings.PrepareForRuntime*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.SingleLevel
  id: SingleLevel
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
  fullName: System.Activities.Validation.ValidationSettings.SingleLevel
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Henter eller angir en verdi som angir om den angitte aktiviteten og alle underordnede og undertype underordnede av den angitte aktiviteten er godkjent, eller hvis validereren må validere bare for den angitte aktiviteten."
  syntax:
    content: public bool SingleLevel { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis et element valideres uten å validere de underordnede elementene. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> Hvis elementet og underordnede og undertype underordnede blir validert."
  overload: System.Activities.Validation.ValidationSettings.SingleLevel*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  id: SkipValidatingRootConfiguration
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
  fullName: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "Henter eller angir en verdi som angir om root-konfigurasjon ikke er emnet for validering."
  syntax:
    content: public bool SkipValidatingRootConfiguration { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis den opprinnelige konfigurasjonen ikke emne for validering; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Validation.ValidationSettings.#ctor
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: ValidationSettings()
  nameWithType: ValidationSettings.ValidationSettings()
  fullName: System.Activities.Validation.ValidationSettings.ValidationSettings()
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.AdditionalConstraints
- uid: System.Collections.Generic.IDictionary{System.Type,System.Collections.Generic.IList{System.Activities.Validation.Constraint}}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<Type,IList<Constraint>>
  nameWithType: IDictionary<Type,IList<Constraint>>
  fullName: System.Collections.Generic.IDictionary<System.Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary<System.Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: Type
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: IList<System.Activities.Validation.Constraint>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Activities.Validation.Constraint
    name: Constraint
    nameWithType: Constraint
    fullName: Constraint
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.Validation.ValidationSettings.CancellationToken
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
  fullName: System.Activities.Validation.ValidationSettings.CancellationToken
- uid: System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  name: CancellationToken
  nameWithType: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Activities.Validation.ValidationSettings.Environment
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: Environment
  nameWithType: ValidationSettings.Environment
  fullName: System.Activities.Validation.ValidationSettings.Environment
- uid: System.Activities.LocationReferenceEnvironment
  parent: System.Activities
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: LocationReferenceEnvironment
  fullName: System.Activities.LocationReferenceEnvironment
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
  fullName: System.Activities.Validation.ValidationSettings.PrepareForRuntime
- uid: System.Activities.Validation.ValidationSettings.SingleLevel
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
  fullName: System.Activities.Validation.ValidationSettings.SingleLevel
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
  fullName: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
- uid: System.Activities.Validation.ValidationSettings.#ctor*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: ValidationSettings
  nameWithType: ValidationSettings.ValidationSettings
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
- uid: System.Activities.Validation.ValidationSettings.CancellationToken*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
- uid: System.Activities.Validation.ValidationSettings.Environment*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: Environment
  nameWithType: ValidationSettings.Environment
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
- uid: System.Activities.Validation.ValidationSettings.SingleLevel*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
