### YamlMime:ManagedReference
items:
- uid: System.Windows.Converters.SizeValueSerializer
  id: SizeValueSerializer
  children:
  - System.Windows.Converters.SizeValueSerializer.#ctor
  - System.Windows.Converters.SizeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Converters.SizeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Converters.SizeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Converters.SizeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: SizeValueSerializer
  nameWithType: SizeValueSerializer
  fullName: System.Windows.Converters.SizeValueSerializer
  type: Class
  summary: "Konverterer forekomster av <xref:System.String>til og fra forekomster av <xref href=&quot;System.Windows.Size&quot;> </xref>.</xref:System.String>"
  remarks: "Denne klassen vanligvis bare brukes av den <xref:System.Windows.Markup.Primitives.MarkupWriter>serialisering formålene.</xref:System.Windows.Markup.Primitives.MarkupWriter>      <a name=&quot;xamlTextUsage_Int32RectValueSerializer&quot;></a>## XAML teksten Bruk"
  syntax:
    content: 'public class SizeValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Converters.SizeValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Converters.SizeValueSerializer
  langs:
  - csharp
  name: SizeValueSerializer()
  nameWithType: SizeValueSerializer.SizeValueSerializer()
  fullName: System.Windows.Converters.SizeValueSerializer.SizeValueSerializer()
  type: Constructor
  assemblies:
  - WindowsBase
  namespace: System.Windows.Converters
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Windows.Converters.SizeValueSerializer&quot;> </xref> klasse."
  syntax:
    content: public SizeValueSerializer ();
    parameters: []
  overload: System.Windows.Converters.SizeValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Converters.SizeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.SizeValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: SizeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Converters.SizeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  namespace: System.Windows.Converters
  summary: "Bestemmer om den angitte <xref:System.String>kan konverteres til en forekomst av <xref href=&quot;System.Windows.Size&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Strengen som skal evalueres for konvertering."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informasjon om sikkerhetskontekst som brukes til konvertering."
    return:
      type: System.Boolean
      description: "Returnerer alltid <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Converters.SizeValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Converters.SizeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.SizeValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: SizeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Converters.SizeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  namespace: System.Windows.Converters
  summary: "Bestemmer om den angitte <xref href=&quot;System.Windows.Size&quot;> </xref> kan konverteres til en <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Objektet som skal evalueres for konvertering."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informasjon om sikkerhetskontekst som brukes til konvertering."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis <code> value </code> kan konverteres til en <xref:System.String>; ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Windows.Converters.SizeValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Converters.SizeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.SizeValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: SizeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Converters.SizeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  namespace: System.Windows.Converters
  summary: "Konverterer en <xref:System.String>til en <xref href=&quot;System.Windows.Size&quot;> </xref>.</xref:System.String>"
  remarks: "Bruker implementeringen <xref:System.Windows.Size.Parse%2A?displayProperty=fullName>internt.</xref:System.Windows.Size.Parse%2A?displayProperty=fullName>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Strengen som skal endres."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informasjon om sikkerhetskontekst som brukes til konvertering."
    return:
      type: System.Object
      description: "En ny forekomst av <xref href=&quot;System.Windows.Size&quot;> </xref> basert på den angitte <code> value </code>."
  overload: System.Windows.Converters.SizeValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Converters.SizeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.SizeValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: SizeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Converters.SizeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  namespace: System.Windows.Converters
  summary: "Konverterer en forekomst av <xref href=&quot;System.Windows.Size&quot;> </xref> til <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Objektet som skal konverteres til en streng."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Informasjon om sikkerhetskontekst som brukes til konvertering."
    return:
      type: System.String
      description: "En strengrepresentasjon av den angitte <xref href=&quot;System.Windows.Size&quot;> </xref>."
  overload: System.Windows.Converters.SizeValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Converters.SizeValueSerializer.#ctor
  parent: System.Windows.Converters.SizeValueSerializer
  isExternal: false
  name: SizeValueSerializer()
  nameWithType: SizeValueSerializer.SizeValueSerializer()
  fullName: System.Windows.Converters.SizeValueSerializer.SizeValueSerializer()
- uid: System.Windows.Converters.SizeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.SizeValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: SizeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Converters.SizeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Converters.SizeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.SizeValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: SizeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Converters.SizeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Converters.SizeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.SizeValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: SizeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Converters.SizeValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Converters.SizeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.SizeValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: SizeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Converters.SizeValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Converters.SizeValueSerializer.#ctor*
  parent: System.Windows.Converters.SizeValueSerializer
  isExternal: false
  name: SizeValueSerializer
  nameWithType: SizeValueSerializer.SizeValueSerializer
- uid: System.Windows.Converters.SizeValueSerializer.CanConvertFromString*
  parent: System.Windows.Converters.SizeValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: SizeValueSerializer.CanConvertFromString
- uid: System.Windows.Converters.SizeValueSerializer.CanConvertToString*
  parent: System.Windows.Converters.SizeValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: SizeValueSerializer.CanConvertToString
- uid: System.Windows.Converters.SizeValueSerializer.ConvertFromString*
  parent: System.Windows.Converters.SizeValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: SizeValueSerializer.ConvertFromString
- uid: System.Windows.Converters.SizeValueSerializer.ConvertToString*
  parent: System.Windows.Converters.SizeValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: SizeValueSerializer.ConvertToString
