### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.XhtmlConformanceSection
  id: XhtmlConformanceSection
  children:
  - System.Web.Configuration.XhtmlConformanceSection.#ctor
  - System.Web.Configuration.XhtmlConformanceSection.Mode
  - System.Web.Configuration.XhtmlConformanceSection.Properties
  langs:
  - csharp
  name: XhtmlConformanceSection
  nameWithType: XhtmlConformanceSection
  fullName: System.Web.Configuration.XhtmlConformanceSection
  type: Class
  summary: "Konfigurerer den <xref uid=&quot;langword_csharp_xhtmlConformance&quot; name=&quot;xhtmlConformance&quot; href=&quot;&quot;> </xref> delen. Denne klassen kan ikke arves."
  remarks: "Klassen XhtmlConformanceSection gjør det mulig å programmatisk tilgang til og endre den `xhtmlConformance` delen av konfigurasjonsfilen.      > [!NOTE] > ASP.NET lar deg opprette nettsider som er kompatible med XHTML 1.1 standarder. For mer informasjon om XHTML 1.1 standard, kan du se W3C-området. Som standard når du arbeider med nettlesere som støtter HTML 4.0 eller senere, gjengi ASP.NET-sider og kontroller koder som er kompatibel med XHTML 1.0 overgang standard. Imidlertid i noen tilfeller kanskje vil du ikke ASP.NET til å gjengi XHTML markup. Dette er vanligvis SANN når du har eksisterende sider som avhenger av koder eller attributter som vanligvis ville være forbudt av XHTML."
  syntax:
    content: 'public sealed class XhtmlConformanceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: XhtmlConformanceSection()
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection()
  fullName: System.Web.Configuration.XhtmlConformanceSection.XhtmlConformanceSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.XhtmlConformanceSection&quot;> </xref> klasse ved hjelp av standardparametere."
  remarks: "Konstruktøren XhtmlConformanceSection skal ikke brukes direkte fra koden. Kalles av ASP.NET Konfigurasjonssystemet. Du hente en forekomst av den <xref:System.Web.Configuration.XhtmlConformanceSection>klassen ved hjelp av den <xref:System.Configuration.Configuration.GetSection%2A>metoden.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.XhtmlConformanceSection>"
  syntax:
    content: public XhtmlConformanceSection ();
    parameters: []
  overload: System.Web.Configuration.XhtmlConformanceSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode
  id: Mode
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: System.Web.Configuration.XhtmlConformanceSection.Mode
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir egenskapen."
  remarks: "Som standard når du arbeider med nettlesere som støtter HTML 4.0 eller senere, gjengi ASP.NET-sider og kontroller koder som er kompatibel med XHTML 1.0 overgang standard. Imidlertid i noen tilfeller kanskje vil du ikke ASP.NET til å gjengi XHTML markup. Dette er vanligvis SANN når du har eksisterende sider som avhenger av koder eller attributter som vanligvis ville være forbudt av XHTML."
  syntax:
    content: public System.Web.Configuration.XhtmlConformanceMode Mode { get; set; }
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "Én av de <xref href=&quot;System.Web.Configuration.XhtmlConformanceMode&quot;> </xref> verdier. Standard <xref href=&quot;System.Web.Configuration.XhtmlConformanceMode&quot;> </xref>."
  overload: System.Web.Configuration.XhtmlConformanceSection.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties
  id: Properties
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: System.Web.Configuration.XhtmlConformanceSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Web.Configuration.XhtmlConformanceSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: XhtmlConformanceSection()
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection()
  fullName: System.Web.Configuration.XhtmlConformanceSection.XhtmlConformanceSection()
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: System.Web.Configuration.XhtmlConformanceSection.Mode
- uid: System.Web.Configuration.XhtmlConformanceMode
  parent: System.Web.Configuration
  isExternal: false
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: System.Web.Configuration.XhtmlConformanceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: XhtmlConformanceSection
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
