### YamlMime:ManagedReference
items:
- uid: System.Web.UI.Design.AppSettingsExpressionEditor
  id: AppSettingsExpressionEditor
  children:
  - System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  - System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  - System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  langs:
  - csharp
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor
  type: Class
  summary: "Inneholder egenskaper og metoder for å evaluere og redigere programmet innstillingen uttrykk i en konfigurasjonsfil under utformingen."
  remarks: "AppSettingsExpressionEditor klassen hentes fra det <xref:System.Web.UI.Design.ExpressionEditor>klasse og inneholder en implementering for evaluering og knytte en programmet innstillingen referanse til en kontrollegenskap under utformingen.</xref:System.Web.UI.Design.ExpressionEditor> Du kan for eksempel binde verdien for en kontrollegenskapen til programmet innstillingen uttrykket `AppSettings:mySettingKeyName`, som angir at egenskapsverdien kontrollen angis ved hjelp av den `mySettingKeyName` verdi i den `appSettings` delen av Webkonfigurasjonsfilen.       Visuelle utformeren vert, for eksempel [!INCLUDE[vsprvslong](~/add/includes/ajax-current-ext-md.md)], bruker AppSettingsExpressionEditor klassen for å velge en applikasjonsinnstilling fra den `appSettings` konfigurasjonsdelen, og returnerer uttrykket som er valgt for utforming gjengivelse.       Når du går til det <xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A>-egenskapen for en kontroll i rutenettet utformingen egenskaper den visuelle utformeren vises en dialogboks til et angitt uttrykk som yter kjøretid for en kontrollegenskap.</xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A> Du kan velge uttrykkstypen basert på en liste over uttrykk prefikser. Når du merker av **AppSettings** uttrykksprefiks fra listen visual designer verten bruker den tilknyttede <xref:System.Web.UI.Design.ExpressionEditorSheet>objektet til å gi utformingen funksjonaliteten for redigering av `appSettings` uttrykk og bruker AppSettingsExpressionEditor metoder for å evaluere og konvertere Uttrykksstrengen basert på syntaksen for et program innstillingsuttrykk.</xref:System.Web.UI.Design.ExpressionEditorSheet> Visuelle designer verten bruker resultatet evaluerte uttrykket til å tilordne kontrollen egenskapsverdiene som gjengis på utformingsoverflaten.       Den <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>for et objekt for AppSettingsExpressionEditor returnerer strengen `AppSettings`.</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> Den <xref:System.Web.Compilation.AppSettingsExpressionBuilder>klassen som er knyttet til uttrykket prefikset `AppSettings` og AppSettingsExpressionEditor implementeringen.</xref:System.Web.Compilation.AppSettingsExpressionBuilder>       Den <xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A>metoden evaluerer en inndata programmet innstillingen uttrykk-strengen.</xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A> Den <xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>metoden returnerer den <xref:System.Web.UI.Design.ExpressionEditorSheet>implementering som brukes til å registrere og redigere programmet innstillingen uttrykk.</xref:System.Web.UI.Design.ExpressionEditorSheet> </xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>"
  example:
  - "The following code example demonstrates how to bind the <xref:System.Web.UI.WebControls.HyperLink.NavigateUrl%2A> property of a <xref:System.Web.UI.WebControls.HyperLink> control to an application setting expression using the AppSettingsExpressionEditor object.  \n  \n1.  In a Web Forms project, add `MyHyperLinkSetting` to the `<appSettings>` section of the web.config file.  \n  \n     [!code-xml[ControlsUsingExpressions#5](~/add/codesnippet/xml/t-system.web.ui.design.a_1.xml)]  \n  \n2.  On a Web Forms page, add a <xref:System.Web.UI.WebControls.HyperLink> control.  \n  \n3.  For the `Hyperlink` control, in Properties, click **Expressions**, and then click the ellipsis button (**...**).  \n  \n     The `<Hyperlinkname>`**Expression** dialog box appears.  \n  \n4.  Under **Bindable properties**, click **NavigateUrl**, in the **Expression type** list, click **AppSettings**, and then under **Expression properties**, in the **AppSetting** box, type **MyHyperLinkSetting**.  \n  \n The visual designer uses the AppSettingsExpressionEditor to assign the expression for the `NavigateUrl` property.  \n  \n The following aspx source shows an example of a property value set using an application setting expression.  \n  \n [!code-vb[ControlsUsingExpressions#2](~/add/codesnippet/visualbasic/t-system.web.ui.design.a_2.aspx)]\n [!code-cs[ControlsUsingExpressions#2](~/add/codesnippet/csharp/t-system.web.ui.design.a_2.aspx)]\n [!code-xml[ControlsUsingExpressions#2](~/add/codesnippet/xml/t-system.web.ui.design.a_2.xml)]"
  syntax:
    content: 'public class AppSettingsExpressionEditor : System.Web.UI.Design.ExpressionEditor'
  inheritance:
  - System.Object
  - System.Web.UI.Design.ExpressionEditor
  implements: []
  inheritedMembers:
  - System.Web.UI.Design.ExpressionEditor.ExpressionPrefix
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.String,System.IServiceProvider)
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.Type,System.IServiceProvider)
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  id: '#ctor'
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  type: Constructor
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.UI.Design.AppSettingsExpressionEditor&quot;> </xref> klasse."
  remarks: "En forekomst av den <xref:System.Web.UI.Design.AppSettingsExpressionEditor>klassen er konfigurert av basisklassen sammen med den <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>-egenskapen satt til `AppSettings`.</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> </xref:System.Web.UI.Design.AppSettingsExpressionEditor>"
  syntax:
    content: public AppSettingsExpressionEditor ();
    parameters: []
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  id: EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Evaluerer en programmet innstillingen uttrykksstreng og inneholder verdien for utforming for en kontrollegenskap."
  remarks: "Metoden EvaluateExpression slår opp applikasjonsinnstilling som er angitt av `expression`, og returnerer verdien for innstillingen programmet.       Den visuelle utformeren bruker EvaluateExpression-metoden til å evaluere programmet innstillingsuttrykk og angi verdien for utforming for en egenskap for tilknyttede kontrollen. Den visuelle utformeren kaller metoden EvaluateExpression med uttrykk-strengen og bruker resultatet evaluerte uttrykket til å tilordne kontrollen egenskapsverdiene som gjengis på utformingsoverflaten.       Siden parseren bruker under kjøring av <xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>og <xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A>metoder for den tilsvarende <xref:System.Web.Compilation.AppSettingsExpressionBuilder>implementering evaluere et uttrykk for å angi verdien kjøretid for en egenskap for tilknyttede kontrollen.</xref:System.Web.Compilation.AppSettingsExpressionBuilder> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>"
  syntax:
    content: public override object EvaluateExpression (string expression, object parseTimeData, Type propertyType, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "En programmet innstillingen uttrykket strengen som skal evalueres. `expression`inneholder ikke den <xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;> </xref> uttrykksprefiks."
    - id: parseTimeData
      type: System.Object
      description: "Et objekt som inneholder analyse av tilleggsinformasjon for å evaluere `expression`."
    - id: propertyType
      type: System.Type
      description: "Egenskapen kontrolltypen."
    - id: serviceProvider
      type: System.IServiceProvider
      description: "En tjenesten leverandøren implementering angitt av designer verten, brukes til å hente utformingen tilleggstjenester."
    return:
      type: System.Object
      description: "Objektet som refererer til <code> expression </code>, hvis uttrykket evalueringen lyktes; ellers <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  id: GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Returnerer et uttrykk redigeringsprogrammet ark for et program innstillingsuttrykk."
  remarks: "Metoden GetExpressionEditorSheet returnerer et enkelt redigeringsprogram arket implementering, som bruker en enkelt Inndatastrengen for å utgjøre uttrykket."
  syntax:
    content: public override System.Web.UI.Design.ExpressionEditorSheet GetExpressionEditorSheet (string expression, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "Uttrykk-strengen er angitt for en kontrollegenskap som brukes til å starte uttrykket redigeringsprogrammet arket. `expression`inneholder ikke den <xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;> </xref> uttrykksprefiks."
    - id: serviceProvider
      type: System.IServiceProvider
      description: "En tjenesten leverandøren implementering angitt av designer verten, brukes til å hente utformingen tilleggstjenester."
    return:
      type: System.Web.UI.Design.ExpressionEditorSheet
      description: "En <xref href=&quot;System.Web.UI.Design.ExpressionEditorSheet&quot;> </xref> implementering som definerer egenskapene for applikasjonen innstillingen uttrykk."
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.Design.ExpressionEditor
  isExternal: false
  name: System.Web.UI.Design.ExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.IServiceProvider
  parent: System
  isExternal: true
  name: IServiceProvider
  nameWithType: IServiceProvider
  fullName: System.IServiceProvider
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
- uid: System.Web.UI.Design.ExpressionEditorSheet
  parent: System.Web.UI.Design
  isExternal: false
  name: ExpressionEditorSheet
  nameWithType: ExpressionEditorSheet
  fullName: System.Web.UI.Design.ExpressionEditorSheet
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet
