### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlObjectReaderSettings
  id: XamlObjectReaderSettings
  children:
  - System.Xaml.XamlObjectReaderSettings.#ctor
  - System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  langs:
  - csharp
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings
  fullName: System.Xaml.XamlObjectReaderSettings
  type: Class
  summary: "Angir behandlingen av regler eller innstillingene for en <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref>."
  syntax:
    content: 'public class XamlObjectReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Xaml.XamlObjectReaderSettings&quot;> </xref> klasse."
  syntax:
    content: public XamlObjectReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlObjectReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  id: RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Henter eller angir en verdi som bestemmer om forfattere som bruker den tilknyttede <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref> for konteksten må bruke designer innstillinger for skriving innhold eksplisitt."
  remarks: "Denne innstillingen forespørres internt. Den påvirker følgende virkemåte for konteksten som en <xref:System.Xaml.XamlObjectReader>går til noen <xref:System.Xaml.XamlWriter>:-egenskapen RequireExplicitContentVisibility virkemåten gjelder bare for egenskaper der <xref:System.Xaml.XamlMember.IsWritePublic%2A>er `false`, og når en `ShouldSerialize` mønsteret er ikke tilgjengelig for egenskapsverdien.</xref:System.Xaml.XamlMember.IsWritePublic%2A> </xref:System.Xaml.XamlWriter> </xref:System.Xaml.XamlObjectReader>      -Hvis uttrykket i det første punktet er true, og RequireExplicitContentVisibility `true`, og deretter designer innstillingene bestemmer om egenskapen skriver utdataene som innhold eller egenskapen anses implisitt. Tilgang til designer innstillinger er intern APIer i .NET Framework XAML Services og er basert på lesing <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>fra sikkerhetskopiering samlinger.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute> I dette tilfellet den interne koden søker etter verdien <xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName>og skriver utdataene til egenskapen.</xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName> Ellers anses innholdet implisitt.      -Hvis uttrykket i det første punktet `true`, og RequireExplicitContentVisibility er `false`, egenskapen skriver alltid utdataene, og <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>fra sikkerhetskopiering samlinger er relevant.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>"
  syntax:
    content: public bool RequireExplicitContentVisibility { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>noen sender innhold i tilfeller der <xref:System.Xaml.XamlMember.IsWritePublic*>rapporter til å angi at forfattere som bruker denne sammenhengen skal bruke designer innstillinger for skriving <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> Hvis designer innstillingene skal ignoreres.</xref:System.Xaml.XamlMember.IsWritePublic*>"
  overload: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlObjectReaderSettings.#ctor*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
