### YamlMime:ManagedReference
items:
- uid: System.Configuration.PositiveTimeSpanValidator
  id: PositiveTimeSpanValidator
  children:
  - System.Configuration.PositiveTimeSpanValidator.#ctor
  - System.Configuration.PositiveTimeSpanValidator.CanValidate(System.Type)
  - System.Configuration.PositiveTimeSpanValidator.Validate(System.Object)
  langs:
  - csharp
  name: PositiveTimeSpanValidator
  nameWithType: PositiveTimeSpanValidator
  fullName: System.Configuration.PositiveTimeSpanValidator
  type: Class
  summary: "Gir validering av en <xref:System.TimeSpan>objektet.</xref:System.TimeSpan> Denne klassen kan ikke arves."
  remarks: "PositiveTimeSpanValidator brukes til å sikre en <xref:System.TimeSpan>objektet oppfyller bestemte kriterier.</xref:System.TimeSpan> Den <xref:System.Configuration.PositiveTimeSpanValidator.CanValidate%2A>metoden bestemmer om objekttypen valideres samsvarer med den forventede typen.</xref:System.Configuration.PositiveTimeSpanValidator.CanValidate%2A> Objektet valideres sendes som en parameter for den <xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A>metoden.</xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A> Valideringen skal være bestått objektet valideres må være et positivt <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  example:
  - "The following code example demonstrates how to use the PositiveTimeSpanValidator type.  \n  \n [!code-cs[System.Configuration.PositiveTimeSpanValidator#1](~/add/codesnippet/csharp/t-system.configuration.p_2_1.cs)]\n [!code-vb[System.Configuration.PositiveTimeSpanValidator#1](~/add/codesnippet/visualbasic/t-system.configuration.p_2_1.vb)]"
  syntax:
    content: 'public class PositiveTimeSpanValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidator.#ctor
  id: '#ctor'
  parent: System.Configuration.PositiveTimeSpanValidator
  langs:
  - csharp
  name: PositiveTimeSpanValidator()
  nameWithType: PositiveTimeSpanValidator.PositiveTimeSpanValidator()
  fullName: System.Configuration.PositiveTimeSpanValidator.PositiveTimeSpanValidator()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.PositiveTimeSpanValidator&quot;> </xref> klasse."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the PositiveTimeSpanValidator constructor. This code example is part of a larger example provided for the <xref:System.Configuration.PositiveTimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.PositiveTimeSpanValidator#2](~/add/codesnippet/csharp/m-system.configuration.p_1_1.cs)]\n [!code-vb[System.Configuration.PositiveTimeSpanValidator#2](~/add/codesnippet/visualbasic/m-system.configuration.p_1_1.vb)]"
  syntax:
    content: public PositiveTimeSpanValidator ();
    parameters: []
  overload: System.Configuration.PositiveTimeSpanValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.PositiveTimeSpanValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: PositiveTimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.PositiveTimeSpanValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Bestemmer om objekttypen kan valideres."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the CanValidate method. This code example is part of a larger example provided for the <xref:System.Configuration.PositiveTimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.PositiveTimeSpanValidator#3](~/add/codesnippet/csharp/m-system.configuration.p_2_1.cs)]\n [!code-vb[System.Configuration.PositiveTimeSpanValidator#3](~/add/codesnippet/visualbasic/m-system.configuration.p_2_1.vb)]"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Objekttypen."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis den <code> type </code> parameteren samsvarer med en <xref:System.TimeSpan>objekt; ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.TimeSpan>"
  overload: System.Configuration.PositiveTimeSpanValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.PositiveTimeSpanValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: PositiveTimeSpanValidator.Validate(Object)
  fullName: System.Configuration.PositiveTimeSpanValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Bestemmer om verdien av et objekt er ugyldig."
  remarks: "Objektet for å validere sendes som en parameter for metoden Valider. Valideringen skal være bestått objektet valideres må være et positivt <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  example:
  - "The following code example demonstrates how to use the Validate method. This code example is part of a larger example provided for the <xref:System.Configuration.PositiveTimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.PositiveTimeSpanValidator#4](~/add/codesnippet/csharp/m-system.configuration.p_0_1.cs)]\n [!code-vb[System.Configuration.PositiveTimeSpanValidator#4](~/add/codesnippet/visualbasic/m-system.configuration.p_0_1.vb)]"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "Verdien for et objekt."
  overload: System.Configuration.PositiveTimeSpanValidator.Validate*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>value</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>value</code>kan ikke løses som et positivt <xref:System.TimeSpan> verdi."
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.PositiveTimeSpanValidator.#ctor
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: PositiveTimeSpanValidator()
  nameWithType: PositiveTimeSpanValidator.PositiveTimeSpanValidator()
  fullName: System.Configuration.PositiveTimeSpanValidator.PositiveTimeSpanValidator()
- uid: System.Configuration.PositiveTimeSpanValidator.CanValidate(System.Type)
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: PositiveTimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.PositiveTimeSpanValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.PositiveTimeSpanValidator.Validate(System.Object)
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: PositiveTimeSpanValidator.Validate(Object)
  fullName: System.Configuration.PositiveTimeSpanValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.PositiveTimeSpanValidator.#ctor*
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: PositiveTimeSpanValidator
  nameWithType: PositiveTimeSpanValidator.PositiveTimeSpanValidator
- uid: System.Configuration.PositiveTimeSpanValidator.CanValidate*
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: CanValidate
  nameWithType: PositiveTimeSpanValidator.CanValidate
- uid: System.Configuration.PositiveTimeSpanValidator.Validate*
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: Validate
  nameWithType: PositiveTimeSpanValidator.Validate
