### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanValidatorAttribute
  id: TimeSpanValidatorAttribute
  children:
  - System.Configuration.TimeSpanValidatorAttribute.#ctor
  - System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  - System.Configuration.TimeSpanValidatorAttribute.MaxValue
  - System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  - System.Configuration.TimeSpanValidatorAttribute.MinValue
  - System.Configuration.TimeSpanValidatorAttribute.MinValueString
  - System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  - System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  - System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: TimeSpanValidatorAttribute
  nameWithType: TimeSpanValidatorAttribute
  fullName: System.Configuration.TimeSpanValidatorAttribute
  type: Class
  summary: "Angir at .NET Framework for å utføre nå på en konfigurasjonsegenskapen deklarativt. Denne klassen kan ikke arves."
  remarks: "Du kan bruke attributtet TimeSpanValidatorAttribute som overflate en konfigurasjonsegenskapen. Dette er for å be .NET Framework for å validere den ved hjelp av den <xref:System.Configuration.TimeSpanValidator>klasse og overføre den decorating parameterne.</xref:System.Configuration.TimeSpanValidator>       Du kan bruke TimeSpanValidatorAttribute objekter bare egenskapstypene."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the TimeSpanValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/t-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/t-system.configuration.t_1_1.cs)]  \n  \n The following example is an excerpt of the configuration file that contains the custom section used by the previous sample.  \n  \n```  \n<configuration xmlns=\"http://schemas.microsoft.com/.NetConfiguration/v2.0\">  \n  <configSections>  \n    <section name=\"custom\" type=\"Microsoft.Samples.AspNet.Configuration.SampleSection, ConfigurationValidatorAttribute\" />  \n  </configSections>  \n  <custom fileName=\"NewFile.txt\" maxSize=\"1000\" maxAttempts=\"101\" maxUsers=\"2500\" maxIdleTime=\"00:15:00\" />  \n</configuration>  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class TimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanValidatorAttribute()
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.TimeSpanValidatorAttribute&quot;> </xref> klasse."
  remarks: "Du bruker denne konstruktøren i attributed modellen for å sikre at verditypen tilordnet relaterte-egenskapen er en <xref:System.TimeSpan>objektet.</xref:System.TimeSpan>"
  example:
  - "The following example shows how to use the <xref:System.Configuration.StringValidatorAttribute.%23ctor%2A> constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#12](~/add/codesnippet/visualbasic/m-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#12](~/add/codesnippet/csharp/m-system.configuration.t_0_1.cs)]"
  syntax:
    content: public TimeSpanValidatorAttribute ();
    parameters: []
  overload: System.Configuration.TimeSpanValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
  fullName: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Henter eller angir en verdi som angir om å inkludere eller ekskludere heltall i området som er angitt av <> </> *> og <> </> *>."
  remarks: "Området er inclusive av den <xref:System.Configuration.TimeSpanValidatorAttribute.MinValueString%2A>og <xref:System.Configuration.TimeSpanValidatorAttribute.MaxValueString%2A>Egenskaper.</xref:System.Configuration.TimeSpanValidatorAttribute.MaxValueString%2A> </xref:System.Configuration.TimeSpanValidatorAttribute.MinValueString%2A> Når egenskapen ExcludeRange er `false`, de tillatte verdiene er utenfor området."
  example:
  - "The following example shows how to use the ExcludeRange property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/p-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/p-system.configuration.t_0_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis verdien må utelates; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standard <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Henter absolutt maksimalt <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  remarks: "Dette er den absolutte største tillatte verdien av .NET Framework. Verdien som er definert av den <xref:System.TimeSpan>felt.</xref:System.TimeSpan>"
  syntax:
    content: public TimeSpan MaxValue { get; }
    return:
      type: System.TimeSpan
      description: "Maksimalt tillatt størrelse <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MaxValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  id: MaxValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Henter eller angir den relative maksimalt <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  remarks: "Dette er relativ maksimumsverdien som er angitt av brukeren."
  example:
  - "The following example shows how to use the MaxValueString property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/p-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/p-system.configuration.t_1_1.cs)]"
  syntax:
    content: public string MaxValueString { get; set; }
    return:
      type: System.String
      description: "Maksimalt tillatt størrelse <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MaxValueString*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Den valgte verdien representerer mindre enn <xref:System.Configuration.TimeSpanValidatorAttribute.MinValue*>.</xref:System.Configuration.TimeSpanValidatorAttribute.MinValue*>"
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Henter absolutt minste <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  remarks: "Dette er den absolutte minste tillatte verdien av .NET Framework. Verdien som er definert av den <xref:System.TimeSpan>felt.</xref:System.TimeSpan>"
  syntax:
    content: public TimeSpan MinValue { get; }
    return:
      type: System.TimeSpan
      description: "Minste tillatte <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MinValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  id: MinValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Henter eller angir den relative minst <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  remarks: "Dette er relativ minimumsverdien som er angitt av brukeren."
  example:
  - "The following example shows how to use the MinValueString property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/p-system.configuration.t_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/p-system.configuration.t_2_1.cs)]"
  syntax:
    content: public string MinValueString { get; set; }
    return:
      type: System.String
      description: "Minste tillatte <xref:System.TimeSpan>verdi.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MinValueString*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Den valgte verdien representerer flere <xref:System.Configuration.TimeSpanValidatorAttribute.MaxValue*>.</xref:System.Configuration.TimeSpanValidatorAttribute.MaxValue*>"
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  id: TimeSpanMaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanMaxValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Henter den absolutte største tillatte verdien."
  remarks: "Strengen som inneholder den maksimale tillatte verdien for tidsintervallet."
  example:
  - "The following example shows how to use the TimeSpanMaxValue field.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#10](~/add/codesnippet/visualbasic/f-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#10](~/add/codesnippet/csharp/f-system.configuration.t_0_1.cs)]"
  syntax:
    content: public const string TimeSpanMaxValue;
    return:
      type: System.String
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  id: TimeSpanMinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanMinValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Henter den absolutte minste tillatte verdien."
  remarks: "Strengen som inneholder den minste tillatte verdien for tidsintervallet."
  example:
  - "The following example shows how to use the TimeSpanMinValue field.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#11](~/add/codesnippet/visualbasic/f-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#11](~/add/codesnippet/csharp/f-system.configuration.t_1_1.cs)]"
  syntax:
    content: public const string TimeSpanMinValue;
    return:
      type: System.String
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Henter en forekomst av den <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> klasse."
  remarks: "Du kan bruke egenskapen ValidatorInstance til å utføre strengen ved å kalle den <xref:System.Configuration.TimeSpanValidator.Validate%2A>metoden.</xref:System.Configuration.TimeSpanValidator.Validate%2A>"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Den <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> validerer forekomst."
  overload: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanValidatorAttribute()
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
  fullName: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValue
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanMaxValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanMinValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanValidatorAttribute
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
