### YamlMime:ManagedReference
items:
- uid: System.Configuration.StringValidator
  id: StringValidator
  children:
  - System.Configuration.StringValidator.#ctor(System.Int32)
  - System.Configuration.StringValidator.#ctor(System.Int32,System.Int32)
  - System.Configuration.StringValidator.#ctor(System.Int32,System.Int32,System.String)
  - System.Configuration.StringValidator.CanValidate(System.Type)
  - System.Configuration.StringValidator.Validate(System.Object)
  langs:
  - csharp
  name: StringValidator
  nameWithType: StringValidator
  fullName: System.Configuration.StringValidator
  type: Class
  summary: "Gir validering av en streng."
  remarks: "Klassen StringValidator brukes til å sikre at en streng som oppfyller bestemte kriterier. Kriteriet for validering etableres når en forekomst av klassen StringValidator er opprettet. Det er tre konstruktøren overbelastninger for StringValidator-klassen. Den <xref:System.Configuration.StringValidator.%23ctor%28System.Int32%29?displayProperty=fullName>konstruktør med én parameter bekrefter minste akseptable lengden på strengen valideres.</xref:System.Configuration.StringValidator.%23ctor%28System.Int32%29?displayProperty=fullName> Den <xref:System.Configuration.StringValidator.%23ctor%28System.Int32%2CSystem.Int32%29?displayProperty=fullName>konstruktør med to parametere sikrer at strengen som godkjennes følger en minimums- og en maksimal lengde.</xref:System.Configuration.StringValidator.%23ctor%28System.Int32%2CSystem.Int32%29?displayProperty=fullName> Den <xref:System.Configuration.StringValidator.%23ctor%28System.Int32%2CSystem.Int32%2CSystem.String%29?displayProperty=fullName>konstruktør med tre parametere kontrollerer i minimums- og maksimumslengde verdiene i en streng som godkjennes, i tillegg til om bestemte tegn er til stede i strengen valideres.</xref:System.Configuration.StringValidator.%23ctor%28System.Int32%2CSystem.Int32%2CSystem.String%29?displayProperty=fullName>       Den <xref:System.Configuration.StringValidator.CanValidate%2A>metoden bestemmer om objekttypen valideres samsvarer med den forventede typen.</xref:System.Configuration.StringValidator.CanValidate%2A> Objektet valideres sendes som en parameter for den <xref:System.Configuration.StringValidator.Validate%2A>metoden.</xref:System.Configuration.StringValidator.Validate%2A>"
  example:
  - "The following example demonstrates how to use the StringValidator type.  \n  \n [!code-cs[System.Configuration.StringValidator#1](~/add/codesnippet/csharp/t-system.configuration.s_0_1.cs)]\n [!code-vb[System.Configuration.StringValidator#1](~/add/codesnippet/visualbasic/t-system.configuration.s_0_1.vb)]"
  syntax:
    content: 'public class StringValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.StringValidator.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: System.Configuration.StringValidator
  langs:
  - csharp
  name: StringValidator(Int32)
  nameWithType: StringValidator.StringValidator(Int32)
  fullName: System.Configuration.StringValidator.StringValidator(Int32)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> klasse, basert på den angitte parameter."
  remarks: "Konstruktøren StringValidator bekrefter minste akseptable lengden på strengen valideres."
  syntax:
    content: public StringValidator (int minLength);
    parameters:
    - id: minLength
      type: System.Int32
      description: "Et heltall som angir minimumslengden for strengverdien."
  overload: System.Configuration.StringValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidator.#ctor(System.Int32,System.Int32)
  id: '#ctor(System.Int32,System.Int32)'
  parent: System.Configuration.StringValidator
  langs:
  - csharp
  name: StringValidator(Int32,Int32)
  nameWithType: StringValidator.StringValidator(Int32,Int32)
  fullName: System.Configuration.StringValidator.StringValidator(Int32,Int32)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> klasse, basert på angitte parametere."
  remarks: "Denne konstruktøren StringValidator sikrer at strengen som godkjennes følger en minimums- og en maksimumslengde."
  syntax:
    content: public StringValidator (int minLength, int maxLength);
    parameters:
    - id: minLength
      type: System.Int32
      description: "Et heltall som angir minimumslengden for strengverdien."
    - id: maxLength
      type: System.Int32
      description: "Et heltall som angir den maksimale lengden på strengverdien."
  overload: System.Configuration.StringValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidator.#ctor(System.Int32,System.Int32,System.String)
  id: '#ctor(System.Int32,System.Int32,System.String)'
  parent: System.Configuration.StringValidator
  langs:
  - csharp
  name: StringValidator(Int32,Int32,String)
  nameWithType: StringValidator.StringValidator(Int32,Int32,String)
  fullName: System.Configuration.StringValidator.StringValidator(Int32,Int32,String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> klasse, basert på angitte parametere."
  remarks: "Denne konstruktøren StringValidator sikrer at strengen valideres følger en minimums- og en maksimal lengde, og også sikrer at utelukkes bestemte tegn i strengen."
  example:
  - "The following example demonstrates how to use this StringValidator constructor. This code example is part of a larger example provided for the <xref:System.Configuration.StringValidator> class.  \n  \n [!code-cs[System.Configuration.StringValidator#2](~/add/codesnippet/csharp/53dd41c3-e827-4f95-a9a0-_1.cs)]\n [!code-vb[System.Configuration.StringValidator#2](~/add/codesnippet/visualbasic/53dd41c3-e827-4f95-a9a0-_1.vb)]"
  syntax:
    content: public StringValidator (int minLength, int maxLength, string invalidCharacters);
    parameters:
    - id: minLength
      type: System.Int32
      description: "Et heltall som angir minimumslengden for strengverdien."
    - id: maxLength
      type: System.Int32
      description: "Et heltall som angir den maksimale lengden på strengverdien."
    - id: invalidCharacters
      type: System.String
      description: "En streng som representerer ugyldige tegn."
  overload: System.Configuration.StringValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.StringValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: StringValidator.CanValidate(Type)
  fullName: System.Configuration.StringValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Bestemmer om et objekt kan valideres basert på typen."
  remarks: ''
  example:
  - "The following example demonstrates how to use the CanValidate method. This code example is part of a larger example provided for the <xref:System.Configuration.StringValidator> class.  \n  \n [!code-cs[System.Configuration.StringValidator#3](~/add/codesnippet/csharp/m-system.configuration.s_7_1.cs)]\n [!code-vb[System.Configuration.StringValidator#3](~/add/codesnippet/visualbasic/m-system.configuration.s_7_1.vb)]"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Objekttypen."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis den <code> type </code> parameteren samsvarer med en streng; ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.StringValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.StringValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: StringValidator.Validate(Object)
  fullName: System.Configuration.StringValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Bestemmer om verdien av et objekt er ugyldig."
  remarks: "Den <xref:System.Configuration.StringValidator>klassen inneholder vilkårene som er nødvendig for å validere en strengobjektet.</xref:System.Configuration.StringValidator> Kriteriet opprettes når en forekomst av den <xref:System.Configuration.StringValidator>klassen er opprettet.</xref:System.Configuration.StringValidator> Objektet for å validere sendes som en parameter for metoden Valider."
  example:
  - "The following example demonstrates how to use the Validate method. This code example is part of a larger example provided for the <xref:System.Configuration.StringValidator> class.  \n  \n [!code-cs[System.Configuration.StringValidator#4](~/add/codesnippet/csharp/m-system.configuration.s_1_1.cs)]\n [!code-vb[System.Configuration.StringValidator#4](~/add/codesnippet/visualbasic/m-system.configuration.s_1_1.vb)]"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "Verdien for objektet."
  overload: System.Configuration.StringValidator.Validate*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>value</code> is less than <code>minValue</code> or greater than <code>maxValue</code> as defined in the constructor.  \n  \n \\- or -  \n  \n <code>value</code> contains invalid characters."
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.StringValidator.#ctor(System.Int32)
  parent: System.Configuration.StringValidator
  isExternal: false
  name: StringValidator(Int32)
  nameWithType: StringValidator.StringValidator(Int32)
  fullName: System.Configuration.StringValidator.StringValidator(Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.StringValidator.#ctor(System.Int32,System.Int32)
  parent: System.Configuration.StringValidator
  isExternal: false
  name: StringValidator(Int32,Int32)
  nameWithType: StringValidator.StringValidator(Int32,Int32)
  fullName: System.Configuration.StringValidator.StringValidator(Int32,Int32)
- uid: System.Configuration.StringValidator.#ctor(System.Int32,System.Int32,System.String)
  parent: System.Configuration.StringValidator
  isExternal: false
  name: StringValidator(Int32,Int32,String)
  nameWithType: StringValidator.StringValidator(Int32,Int32,String)
  fullName: System.Configuration.StringValidator.StringValidator(Int32,Int32,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.StringValidator.CanValidate(System.Type)
  parent: System.Configuration.StringValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: StringValidator.CanValidate(Type)
  fullName: System.Configuration.StringValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.StringValidator.Validate(System.Object)
  parent: System.Configuration.StringValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: StringValidator.Validate(Object)
  fullName: System.Configuration.StringValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.StringValidator.#ctor*
  parent: System.Configuration.StringValidator
  isExternal: false
  name: StringValidator
  nameWithType: StringValidator.StringValidator
- uid: System.Configuration.StringValidator.CanValidate*
  parent: System.Configuration.StringValidator
  isExternal: false
  name: CanValidate
  nameWithType: StringValidator.CanValidate
- uid: System.Configuration.StringValidator.Validate*
  parent: System.Configuration.StringValidator
  isExternal: false
  name: Validate
  nameWithType: StringValidator.Validate
