### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  id: PeerApplicationRegistrationType
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  langs:
  - csharp
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  type: Enum
  summary: "Angir hvilken type registrering for å utføre for en <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> eller <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerObject&quot;> </xref> registrering."
  remarks: "Registrerer en <xref:System.Net.PeerToPeer.Collaboration.PeerApplication>gjør det mulig å motta <xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>invitasjonen forespørsler.</xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration> </xref:System.Net.PeerToPeer.Collaboration.PeerApplication> Tjenesten eller programmet som utfører registreringen må ha tillatelse til å gjøre dette, fordi det krever tilgang til den <xref:System.Net.PeerToPeer.Collaboration.ContactManager>og andre ressurser som brukere, programmer og tjenester på den eksterne maskinen.</xref:System.Net.PeerToPeer.Collaboration.ContactManager>"
  syntax:
    content: public enum PeerApplicationRegistrationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  id: AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Den <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> eller <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerObject&quot;> </xref> registreres for alle noder på verten for programmet"
  syntax:
    content: AllUsers
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  id: CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Programmet eller objekt registreres bare for brukeren som er knyttet til kall node"
  syntax:
    content: CurrentUser
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
