### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventHandler
  id: SettingChangingEventHandler
  langs:
  - csharp
  name: SettingChangingEventHandler
  nameWithType: SettingChangingEventHandler
  fullName: System.Configuration.SettingChangingEventHandler
  type: Delegate
  summary: "Representerer metoden som håndterer den <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingChanging&quot;> </xref> hendelsen."
  remarks: "Den <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>inntreffer før verdien for egenskapen en program-innstillingene er endret, vanligvis via et kall til den <xref:System.Configuration.ApplicationSettingsBase.Item%2A>metoden.</xref:System.Configuration.ApplicationSettingsBase.Item%2A> </xref:System.Configuration.ApplicationSettingsBase.SettingChanging> <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>kan avbrytes via <xref:System.Configuration.SettingChangingEventArgs>hendelsen data klasse.</xref:System.Configuration.SettingChangingEventArgs></xref:System.Configuration.ApplicationSettingsBase.SettingChanging>"
  syntax:
    content: public delegate void SettingChangingEventHandler(object sender, SettingChangingEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
