### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlXmlReaderSettings
  id: XamlXmlReaderSettings
  children:
  - System.Xaml.XamlXmlReaderSettings.#ctor
  - System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  - System.Xaml.XamlXmlReaderSettings.CloseInput
  - System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  - System.Xaml.XamlXmlReaderSettings.XmlLang
  - System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  langs:
  - csharp
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings
  fullName: System.Xaml.XamlXmlReaderSettings
  type: Class
  summary: "Angir behandlingen av regler eller innstillingene for den <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> XAML leseren implementering."
  syntax:
    content: 'public class XamlXmlReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XamlXmlReaderSettings()
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings()
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> klasse."
  syntax:
    content: public XamlXmlReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlXmlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  id: '#ctor(System.Xaml.XamlXmlReaderSettings)'
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XamlXmlReaderSettings(XamlXmlReaderSettings)
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> klassen ved å kopiere innstillinger fra en eksisterende <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> objektet."
  syntax:
    content: public XamlXmlReaderSettings (System.Xaml.XamlXmlReaderSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlXmlReaderSettings
      description: "Den eksisterende <xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;> </xref> objektet du vil kopiere."
  overload: System.Xaml.XamlXmlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput
  id: CloseInput
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
  fullName: System.Xaml.XamlXmlReaderSettings.CloseInput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Henter eller angir en verdi som angir om den underliggende dataflyt eller tekst leseren, må lukkes når det <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> er lukket."
  syntax:
    content: public bool CloseInput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis det underliggende dataflyten eller leseren må lukkes når det <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> er lukket; ellers, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Standard <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlReaderSettings.CloseInput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  id: SkipXmlCompatibilityProcessing
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  fullName: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Henter eller angir en verdi som bestemmer om leseren må være forskjellig fra standard <xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> virkemåte for hvordan markup kompatibilitet innhold behandles."
  remarks: "Standard behandler virkemåte for XML-markup kompatibilitet i <xref:System.Xaml.XamlXmlReader>er som <xref:System.Xaml.XamlXmlReader>som er oppgitt for initialisering, er omsluttet av en opprettet internt helper klasse.</xref:System.Xaml.XamlXmlReader> </xref:System.Xaml.XamlXmlReader> Denne hjelperklasse leser koden kompatibilitet noder separat og skriver inn i noder basert på markup kompatibilitet av skjema-kontekst.       Foreslått scenarier for sette SkipXmlCompatibilityProcessing til `true` er:-du vil beholde markup kompatibilitet innhold i primær XAML dataflyten.      -Du har allerede behandlet markup kompatibilitetsnivå fordi du bruker en leser som kan behandle markup kompatibilitet innhold internt.      -Du velger å ignorere XML-kompatibilitet konvensjoner i XAML leseren implementeringen din grunner av ytelse."
  syntax:
    content: public bool SkipXmlCompatibilityProcessing { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis den første leseren brukes direkte, som betyr at XML-kompatibilitet kode behandles som en del av den primære dataflyten og regnes ikke kompatibilitetsnivået. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Hvis det brukes standard virkemåte, som behandler XML-kompatibilitet separat. Standard <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang
  id: XmlLang
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
  fullName: System.Xaml.XamlXmlReaderSettings.XmlLang
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Henter eller angir verdien som leseren kan hever for språkinnstilling til skrivere skrive <xref uid=&quot;langword_csharp_xml:lang&quot; name=&quot;xml:lang&quot; href=&quot;&quot;> </xref> attributter i noder."
  remarks: "Oppkalleren er ansvarlig for å sørge for at strengen du oppgi er riktig for `xml:lang` bruk."
  syntax:
    content: public string XmlLang { get; set; }
    return:
      type: System.String
      description: "Strengen som skal brukes for mulige <xref uid=&quot;langword_csharp_xml:lang&quot; name=&quot;xml:lang&quot; href=&quot;&quot;> </xref> utdata som er basert på leseren."
  overload: System.Xaml.XamlXmlReaderSettings.XmlLang*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  id: XmlSpacePreserve
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
  fullName: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Henter eller angir en verdi som bestemmer om XAML leseren instruerer eventuelle XAML forfattere å skrive <xref uid=&quot;langword_csharp_xml:space&quot; name=&quot;xml:space&quot; href=&quot;&quot;> </xref> attributter i noder. Eventuelt denne virkemåten er sendes denne informasjonen gjennom delte XAML skjemaet kontekst."
  remarks: "XML-mellomrom konsepter er robuste nok til å bruke XAML og ignoreres vanligvis XAML lesere."
  syntax:
    content: public bool XmlSpacePreserve { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis forfattere som behandler XAML noden dataflyten kan skrive `xml:space=&quot;preserve&quot;` i utdataene. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> Hvis <xref uid=&quot;langword_csharp_xml:space&quot; name=&quot;xml:space&quot; href=&quot;&quot;> </xref> attributter kan ikke skrive i nodene."
  overload: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.#ctor
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings()
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings()
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings()
- uid: System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings(XamlXmlReaderSettings)
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
- uid: System.Xaml.XamlXmlReaderSettings
  parent: System.Xaml
  isExternal: false
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings
  fullName: System.Xaml.XamlXmlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
  fullName: System.Xaml.XamlXmlReaderSettings.CloseInput
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  fullName: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
  fullName: System.Xaml.XamlXmlReaderSettings.XmlLang
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
  fullName: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
- uid: System.Xaml.XamlXmlReaderSettings.#ctor*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
