### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingJsonSerializationSection
  id: ScriptingJsonSerializationSection
  children:
  - System.Web.Configuration.ScriptingJsonSerializationSection.#ctor
  - System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  - System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  - System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  - System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  langs:
  - csharp
  name: ScriptingJsonSerializationSection
  nameWithType: ScriptingJsonSerializationSection
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection
  type: Class
  summary: "Representerer en <xref uid=&quot;langword_csharp_jsonSerialization&quot; name=&quot;jsonSerialization&quot; href=&quot;&quot;> </xref> konfigurasjonsdelen i den <xref uid=&quot;langword_csharp_scripting&quot; name=&quot;scripting&quot; href=&quot;&quot;> </xref> elementet i konfigurasjonsfilen. Denne klassen kan ikke arves."
  remarks: "Klassen ScriptingJsonSerializationSection gjør det mulig å programmatisk tilgang til og endre den `jsonSerialization` konfigurasjonsdelen for bruker AJAX-funksjonalitet i ASP.NET-elementet.       Bruk denne til å angi serialisering og deserialization verdiene for AJAX-aktiverte programmer."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for properties of the ScriptingJsonSerializationSection class.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <jsonSerialization maxJsonLength=\"1000\" />  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example demonstrates how to access ScriptingJsonSerializationSection programmatically.  \n  \n [!code-cs[System.Web.Configuration#3](~/add/codesnippet/csharp/t-system.web.configurati_75_1.cs)]\n [!code-vb[System.Web.Configuration#3](~/add/codesnippet/visualbasic/t-system.web.configurati_75_1.vb)]"
  syntax:
    content: 'public sealed class ScriptingJsonSerializationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: ScriptingJsonSerializationSection()
  nameWithType: ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.ScriptingJsonSerializationSection&quot;> </xref> klasse."
  syntax:
    content: public ScriptingJsonSerializationSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  id: Converters
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: Converters
  nameWithType: ScriptingJsonSerializationSection.Converters
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Henter en <xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;> </xref> objekt som inneholder en samling av <xref href=&quot;System.Web.Configuration.Converter&quot;> </xref> objekter."
  syntax:
    content: public System.Web.Configuration.ConvertersCollection Converters { get; }
    return:
      type: System.Web.Configuration.ConvertersCollection
      description: "A <xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.Converters*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  id: MaxJsonLength
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: MaxJsonLength
  nameWithType: ScriptingJsonSerializationSection.MaxJsonLength
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Henter eller angir den maksimale lengden som er godkjent av den <xref href=&quot;System.Web.Script.Serialization.JavaScriptSerializer&quot;> </xref> objekt for JavaScript objektet notasjon (JSON) strenger."
  remarks: "Verdien for egenskapen MaxJsonLength gjelder bare for den interne <xref:System.Web.Script.Serialization.JavaScriptSerializer>-forekomst som brukes av asynkron kommunikasjonslaget for å aktivere Web services-metoder.</xref:System.Web.Script.Serialization.JavaScriptSerializer>"
  syntax:
    content: public int MaxJsonLength { get; set; }
    return:
      type: System.Int32
      description: "Et heltall som representerer den maksimale lengden for JSON strenger. Standard er 102400 tegn."
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingJsonSerializationSection.Properties
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  id: RecursionLimit
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: RecursionLimit
  nameWithType: ScriptingJsonSerializationSection.RecursionLimit
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Henter eller angir grensen for å sette en betingelse antallet nivåer som objektet til å behandle."
  remarks: "Egenskapen RecursionLimit refererer til maksimalt hierarkinivået et objekt som <xref:System.Web.Script.Serialization.JavaScriptSerializer>behandler under deserialisering av en streng som JavaScript objektet notasjon (JSON) eller når serialisering av et objekt.</xref:System.Web.Script.Serialization.JavaScriptSerializer>       Verdien for RecursionLimit gjelder bare for den interne <xref:System.Web.Script.Serialization.JavaScriptSerializer>-forekomst som brukes av asynkron kommunikasjonslaget for å aktivere Web services-metoder.</xref:System.Web.Script.Serialization.JavaScriptSerializer>"
  syntax:
    content: public int RecursionLimit { get; set; }
    return:
      type: System.Int32
      description: "Antall nivåer for objektet. Standarden er 100."
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Egenskapen settes til en verdi som er mindre enn&1;."
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: ScriptingJsonSerializationSection()
  nameWithType: ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Converters
  nameWithType: ScriptingJsonSerializationSection.Converters
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
- uid: System.Web.Configuration.ConvertersCollection
  parent: System.Web.Configuration
  isExternal: false
  name: ConvertersCollection
  nameWithType: ConvertersCollection
  fullName: System.Web.Configuration.ConvertersCollection
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: MaxJsonLength
  nameWithType: ScriptingJsonSerializationSection.MaxJsonLength
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingJsonSerializationSection.Properties
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: RecursionLimit
  nameWithType: ScriptingJsonSerializationSection.RecursionLimit
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: ScriptingJsonSerializationSection
  nameWithType: ScriptingJsonSerializationSection.ScriptingJsonSerializationSection
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Converters*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Converters
  nameWithType: ScriptingJsonSerializationSection.Converters
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: MaxJsonLength
  nameWithType: ScriptingJsonSerializationSection.MaxJsonLength
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Properties*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingJsonSerializationSection.Properties
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: RecursionLimit
  nameWithType: ScriptingJsonSerializationSection.RecursionLimit
