### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.InternalConfigEventHandler
  id: InternalConfigEventHandler
  langs:
  - csharp
  name: InternalConfigEventHandler
  nameWithType: InternalConfigEventHandler
  fullName: System.Configuration.Internal.InternalConfigEventHandler
  type: Delegate
  summary: "Definerer en klasse som brukes av .NET Framework-infrastruktur for å støtte Konfigurasjonshendelser."
  syntax:
    content: public delegate void InternalConfigEventHandler(object sender, InternalConfigEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
