### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.CertificateReferenceElement
  id: CertificateReferenceElement
  children:
  - System.ServiceModel.Configuration.CertificateReferenceElement.#ctor
  - System.ServiceModel.Configuration.CertificateReferenceElement.FindValue
  - System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded
  - System.ServiceModel.Configuration.CertificateReferenceElement.Properties
  - System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation
  - System.ServiceModel.Configuration.CertificateReferenceElement.StoreName
  - System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType
  langs:
  - csharp
  name: CertificateReferenceElement
  nameWithType: CertificateReferenceElement
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement
  type: Class
  summary: "Representerer konfigurasjonsinnstillingene for validering av et X.509-sertifikat. Denne klassen kan ikke arves."
  syntax:
    content: 'public sealed class CertificateReferenceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: CertificateReferenceElement()
  nameWithType: CertificateReferenceElement.CertificateReferenceElement()
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.CertificateReferenceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.CertificateReferenceElement&quot;> </xref> klasse."
  syntax:
    content: public CertificateReferenceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: FindValue
  nameWithType: CertificateReferenceElement.FindValue
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en streng som angir verdien til å søke etter i X.509 sertifikatlageret."
  remarks: "Typen som finnes i denne egenskapen må oppfylle kravene til den angitte <xref:System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType%2A>verdi.</xref:System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType%2A> Standarden er en tom streng."
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "Verdien til å søke etter i X.509 sertifikatlageret."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded
  id: IsChainIncluded
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: IsChainIncluded
  nameWithType: CertificateReferenceElement.IsChainIncluded
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en boolsk verdi som angir om valideringen gjøres ved hjelp av en sertifikatkjede."
  syntax:
    content: public bool IsChainIncluded { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis en sertifikatkjede brukes i validering; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: Properties
  nameWithType: CertificateReferenceElement.Properties
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: CertificateReferenceElement.StoreLocation
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en verdi som angir plasseringen av sertifikatlageret klienten kan bruke til å validere serversertifikatet."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "En <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref> som angir plasseringen til sertifikatlageret klienten kan bruke til å validere serversertifikatet. Standardverdien er <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: StoreName
  nameWithType: CertificateReferenceElement.StoreName
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir navnet på X.509 sertifikatlageret til å åpne."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "En <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref> som inneholder navnet på X.509 sertifikatlageret til å åpne."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: CertificateReferenceElement.X509FindType
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir typen X.509 søk kjøres."
  remarks: "Hvilken <xref:System.ServiceModel.Configuration.CertificateReferenceElement.FindValue%2A>må oppfylle kravene for denne egenskapen.</xref:System.ServiceModel.Configuration.CertificateReferenceElement.FindValue%2A>"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "En <xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref> som inneholder typen X.509 søk kjøres."
  overload: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.#ctor
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: CertificateReferenceElement()
  nameWithType: CertificateReferenceElement.CertificateReferenceElement()
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.CertificateReferenceElement()
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: FindValue
  nameWithType: CertificateReferenceElement.FindValue
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: IsChainIncluded
  nameWithType: CertificateReferenceElement.IsChainIncluded
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.Properties
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: Properties
  nameWithType: CertificateReferenceElement.Properties
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: StoreLocation
  nameWithType: CertificateReferenceElement.StoreLocation
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: StoreName
  nameWithType: CertificateReferenceElement.StoreName
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: X509FindType
  nameWithType: CertificateReferenceElement.X509FindType
  fullName: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.#ctor*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: CertificateReferenceElement
  nameWithType: CertificateReferenceElement.CertificateReferenceElement
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.FindValue*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: FindValue
  nameWithType: CertificateReferenceElement.FindValue
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.IsChainIncluded*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: IsChainIncluded
  nameWithType: CertificateReferenceElement.IsChainIncluded
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.Properties*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: Properties
  nameWithType: CertificateReferenceElement.Properties
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreLocation*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: StoreLocation
  nameWithType: CertificateReferenceElement.StoreLocation
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.StoreName*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: StoreName
  nameWithType: CertificateReferenceElement.StoreName
- uid: System.ServiceModel.Configuration.CertificateReferenceElement.X509FindType*
  parent: System.ServiceModel.Configuration.CertificateReferenceElement
  isExternal: false
  name: X509FindType
  nameWithType: CertificateReferenceElement.X509FindType
