### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  id: MsmqIntegrationSecurity
  children:
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  - System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  langs:
  - csharp
  name: MsmqIntegrationSecurity
  nameWithType: MsmqIntegrationSecurity
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  type: Class
  summary: "Klassen MsmqIntegrationSecurity innkapsler transport sikkerhetsinnstillingene for Message Queuing (MSMQ) integration kanal."
  remarks: "Message Queuing-integrering kanalen aktiverer [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] programmer for å kommunisere med eksisterende Message Queuing-programmer."
  syntax:
    content: public sealed class MsmqIntegrationSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: MsmqIntegrationSecurity()
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Initialiserer en ny forekomst av <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity&quot;> </xref>."
  syntax:
    content: public MsmqIntegrationSecurity ();
    parameters: []
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  id: Mode
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Henter eller angir den <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref> som er knyttet til Message Queuing (MSMQ) integration kanal."
  remarks: '<xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>er en opplisting som inneholder følgende verdier: <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>og <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> </xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode></xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> Standardverdien er <xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>'
  syntax:
    content: public System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
      description: "Den <xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref> som er knyttet til kanalen for Message Queuing-integrering."
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  id: Transport
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.MsmqIntegration
  summary: "Henter den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> som er knyttet til Message Queuing (MSMQ) integration kanal."
  remarks: "<xref:System.ServiceModel.MsmqTransportSecurity>innkapsler sikkerhetsinnstillingene for Message Queuing-integrering transport.</xref:System.ServiceModel.MsmqTransportSecurity> Innstillingene er den samme for Message Queuing-integrering og transport i kø. <xref:System.ServiceModel.MsmqTransportSecurity>lar deg angi godkjenningsmodus, krypteringsalgoritmen, sikre nummeralgoritme og beskyttelsesnivået.</xref:System.ServiceModel.MsmqTransportSecurity>"
  syntax:
    content: public System.ServiceModel.MsmqTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.MsmqTransportSecurity
      description: "Den <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> som er knyttet til kanalen for Message Queuing-integrering."
  overload: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: MsmqIntegrationSecurity()
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity()
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.MsmqIntegrationSecurity()
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
  parent: System.ServiceModel.MsmqIntegration
  isExternal: false
  name: MsmqIntegrationSecurityMode
  nameWithType: MsmqIntegrationSecurityMode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.#ctor*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: MsmqIntegrationSecurity
  nameWithType: MsmqIntegrationSecurity.MsmqIntegrationSecurity
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Mode*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurity.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity.Transport*
  parent: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurity
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurity.Transport
