### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SerializationMode
  id: SerializationMode
  children:
  - System.Web.Configuration.SerializationMode.Binary
  - System.Web.Configuration.SerializationMode.ProviderSpecific
  - System.Web.Configuration.SerializationMode.String
  - System.Web.Configuration.SerializationMode.Xml
  langs:
  - csharp
  name: SerializationMode
  nameWithType: SerializationMode
  fullName: System.Web.Configuration.SerializationMode
  type: Enum
  summary: "Bestemmer serialisering metoden som brukes en <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objektet."
  remarks: "Den <xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A>-egenskapen til det <xref:System.Web.Configuration.ProfilePropertySettings>objektet kontrollerer serialiseringsmodus for egenskapsinnstillingen enkelt profil.</xref:System.Web.Configuration.ProfilePropertySettings> </xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A>"
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#17](~/add/codesnippet/csharp/t-system.web.configurati_92_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#17](~/add/codesnippet/visualbasic/t-system.web.configurati_92_1.vb)]"
  syntax:
    content: public enum SerializationMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.Binary
  id: Binary
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: Binary
  nameWithType: SerializationMode.Binary
  fullName: System.Web.Configuration.SerializationMode.Binary
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Den <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objektet serialiseres med binær Serialiseringsfeil."
  syntax:
    content: Binary
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.ProviderSpecific
  id: ProviderSpecific
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: ProviderSpecific
  nameWithType: SerializationMode.ProviderSpecific
  fullName: System.Web.Configuration.SerializationMode.ProviderSpecific
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Leverandøren har implisitt kunnskap om typen og er ansvarlig for å bestemme hvordan du serialisere den <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objektet i datakilden."
  syntax:
    content: ProviderSpecific
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.String
  id: String
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: String
  nameWithType: SerializationMode.String
  fullName: System.Web.Configuration.SerializationMode.String
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Den <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> objektet er serialisert til en enkelt streng."
  syntax:
    content: String
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.Xml
  id: Xml
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: Xml
  nameWithType: SerializationMode.Xml
  fullName: System.Web.Configuration.SerializationMode.Xml
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Profilen <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> serialiseres som XML ved hjelp av XML-serialisering."
  syntax:
    content: Xml
    return:
      type: System.Web.Configuration.SerializationMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.SerializationMode.Binary
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: Binary
  nameWithType: SerializationMode.Binary
  fullName: System.Web.Configuration.SerializationMode.Binary
- uid: System.Web.Configuration.SerializationMode
  parent: System.Web.Configuration
  isExternal: false
  name: SerializationMode
  nameWithType: SerializationMode
  fullName: System.Web.Configuration.SerializationMode
- uid: System.Web.Configuration.SerializationMode.ProviderSpecific
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: ProviderSpecific
  nameWithType: SerializationMode.ProviderSpecific
  fullName: System.Web.Configuration.SerializationMode.ProviderSpecific
- uid: System.Web.Configuration.SerializationMode.String
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: String
  nameWithType: SerializationMode.String
  fullName: System.Web.Configuration.SerializationMode.String
- uid: System.Web.Configuration.SerializationMode.Xml
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: Xml
  nameWithType: SerializationMode.Xml
  fullName: System.Web.Configuration.SerializationMode.Xml
