### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlSchemaContextSettings
  id: XamlSchemaContextSettings
  children:
  - System.Xaml.XamlSchemaContextSettings.#ctor
  - System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  - System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  - System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  langs:
  - csharp
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings
  fullName: System.Xaml.XamlSchemaContextSettings
  type: Class
  summary: "Gir valgfrie innstillinger for en <xref href=&quot;System.Xaml.XamlSchemaContext&quot;> </xref>."
  syntax:
    content: public class XamlSchemaContextSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: XamlSchemaContextSettings()
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings()
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> klasse."
  syntax:
    content: public XamlSchemaContextSettings ();
    parameters: []
  overload: System.Xaml.XamlSchemaContextSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  id: '#ctor(System.Xaml.XamlSchemaContextSettings)'
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: XamlSchemaContextSettings(XamlSchemaContextSettings)
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> klassen ved å kopiere verdiene i en eksisterende <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref> forekomsten."
  syntax:
    content: public XamlSchemaContextSettings (System.Xaml.XamlSchemaContextSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlSchemaContextSettings
      description: "En eksisterende <xref href=&quot;System.Xaml.XamlSchemaContextSettings&quot;> </xref>."
  overload: System.Xaml.XamlSchemaContextSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  id: FullyQualifyAssemblyNamesInClrNamespaces
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  fullName: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Henter eller angir en verdi som angir om et XAML-skjema og konteksten bruke fullstendige samlingsnavn i verdiene som returneres av oppslaget API."
  remarks: "Verdien for denne egenskapen påvirker strenger som returneres av <xref:System.Xaml.XamlSchemaContext.GetAllXamlNamespaces%2A>i konteksten konstruert XML-skjema.</xref:System.Xaml.XamlSchemaContext.GetAllXamlNamespaces%2A> Hvis <xref:System.Xaml.XamlSchemaContext.FullyQualifyAssemblyNamesInClrNamespaces%2A>er `true`, samlingen-delen av rapporter tilsvarer <xref:System.Reflection.Assembly.FullName%2A?displayProperty=fullName>.</xref:System.Reflection.Assembly.FullName%2A?displayProperty=fullName> </xref:System.Xaml.XamlSchemaContext.FullyQualifyAssemblyNamesInClrNamespaces%2A>"
  syntax:
    content: public bool FullyQualifyAssemblyNamesInClrNamespaces { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis et XAML-skjema og konteksten bruker fullstendige samlingsnavn i verdiene som returneres av oppslaget APIer; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  id: SupportMarkupExtensionsWithDuplicateArity
  parent: System.Xaml.XamlSchemaContextSettings
  langs:
  - csharp
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  fullName: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Henter eller angir en verdi som angir om en XAML skjemaet kontekst tillater markup utvidelser som har to konstruktører med samme aritet (antall Inndataparametere)."
  remarks: "Fra en <xref:System.Xaml.XamlSchemaContext>, du kan ikke lese innstillingene for direkte.</xref:System.Xaml.XamlSchemaContext> I stedet du mottar verdier fra bestemte skrivebeskyttede egenskaper, for eksempel <xref:System.Xaml.XamlSchemaContext.SupportMarkupExtensionsWithDuplicateArity%2A>, hvilken rapport basert på innstillinger-verdier.</xref:System.Xaml.XamlSchemaContext.SupportMarkupExtensionsWithDuplicateArity%2A>"
  syntax:
    content: public bool SupportMarkupExtensionsWithDuplicateArity { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis skjemaet konteksten tillater markup utvidelser som har identiske aritet; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlSchemaContextSettings.#ctor
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings()
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings()
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings()
- uid: System.Xaml.XamlSchemaContextSettings.#ctor(System.Xaml.XamlSchemaContextSettings)
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings(XamlSchemaContextSettings)
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
  fullName: System.Xaml.XamlSchemaContextSettings.XamlSchemaContextSettings(XamlSchemaContextSettings)
- uid: System.Xaml.XamlSchemaContextSettings
  parent: System.Xaml
  isExternal: false
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings
  fullName: System.Xaml.XamlSchemaContextSettings
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
  fullName: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
  fullName: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
- uid: System.Xaml.XamlSchemaContextSettings.#ctor*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: XamlSchemaContextSettings
  nameWithType: XamlSchemaContextSettings.XamlSchemaContextSettings
- uid: System.Xaml.XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: FullyQualifyAssemblyNamesInClrNamespaces
  nameWithType: XamlSchemaContextSettings.FullyQualifyAssemblyNamesInClrNamespaces
- uid: System.Xaml.XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity*
  parent: System.Xaml.XamlSchemaContextSettings
  isExternal: false
  name: SupportMarkupExtensionsWithDuplicateArity
  nameWithType: XamlSchemaContextSettings.SupportMarkupExtensionsWithDuplicateArity
