### YamlMime:ManagedReference
items:
- uid: System.Configuration.DefaultSettingValueAttribute
  id: DefaultSettingValueAttribute
  children:
  - System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  - System.Configuration.DefaultSettingValueAttribute.Value
  langs:
  - csharp
  name: DefaultSettingValueAttribute
  nameWithType: DefaultSettingValueAttribute
  fullName: System.Configuration.DefaultSettingValueAttribute
  type: Class
  summary: "Angir verdien for egenskapen en program-innstillingene."
  remarks: "> [!IMPORTANT]> DefaultSettingValueAttribute kan bare brukes på individuelle innstillinger; Det er ugyldig for å bruke dette attributtet til en klasse for hele programmet.       Forskjellige innstillinger leverandører kan ha forskjellige krav eller begrensningene ved bruk av DefaultSettingValueAttribute. For eksempel den <xref:System.Configuration.LocalFileSettingsProvider>krever ikke dette attributtet, og overstyrer verdien som er angitt av dette attributtet hvis det ikke er noen verdier, standard eller endret av brukeren, finnes allerede i datalageret.</xref:System.Configuration.LocalFileSettingsProvider>       DefaultSettingValueAttribute krever at standardverdien kan representeres som en streng. Resultatet kan ikke innstillinger ved hjelp av XML-serialisering ha en angitt standardverdi, ved hjelp av dette attributtet. Noen leverandører kan velge å støtte flere serialisering skjemaene som kan angis på kompileringstidspunktet i <xref:System.Configuration.SettingsSerializeAsAttribute>.</xref:System.Configuration.SettingsSerializeAsAttribute>      > [!CAUTION] > Standardverdier som er angitt av dette attributtet er lagret som ren tekst i de resulterende kompilerte .exe- eller DLL-filen. Disse standardverdiene er derfor arvbart usikker."
  example:
  - "The following code example demonstrates the use of the DefaultSettingValueAttribute applied to three of the four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The first three of these form properties have default values associated with them.  \n  \n The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.d_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.d_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class DefaultSettingValueAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.DefaultSettingValueAttribute
  langs:
  - csharp
  name: DefaultSettingValueAttribute(String)
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  fullName: System.Configuration.DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en forekomst av den <xref href=&quot;System.Configuration.DefaultSettingValueAttribute&quot;> </xref> klasse."
  remarks: "Den angitte strengen må være en verdi som er kompatibel med den tilgjengelige serialisering mekanismen som er forbundet med egenskapstypen. For eksempel hvis egenskapen er av typen <xref:System.Drawing.Color>, og deretter en `value` av `&quot;Azure&quot;` er gyldige.</xref:System.Drawing.Color>      > [!CAUTION] > Standardverdier som er angitt av dette attributtet er lagret som ren tekst i de resulterende kompilerte .exe- eller DLL-filen. Disse standardverdiene er derfor arvbart usikker."
  syntax:
    content: public DefaultSettingValueAttribute (string value);
    parameters:
    - id: value
      type: System.String
      description: "En <xref:System.String>som representerer verdien for egenskapen.</xref:System.String>"
  overload: System.Configuration.DefaultSettingValueAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultSettingValueAttribute.Value
  id: Value
  parent: System.Configuration.DefaultSettingValueAttribute
  langs:
  - csharp
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
  fullName: System.Configuration.DefaultSettingValueAttribute.Value
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Henter standardverdien for egenskapen programmet innstillinger."
  remarks: "Egenskapen Value er angitt i den <xref:System.Configuration.DefaultSettingValueAttribute.%23ctor%2A>konstruktør.</xref:System.Configuration.DefaultSettingValueAttribute.%23ctor%2A>       Angi leverandører støtter flere serialisering skjemaene som kan angis med <xref:System.Configuration.SettingsSerializeAsAttribute>.</xref:System.Configuration.SettingsSerializeAsAttribute>"
  syntax:
    content: public string Value { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som representerer verdien for egenskapen.</xref:System.String>"
  overload: System.Configuration.DefaultSettingValueAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: DefaultSettingValueAttribute(String)
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  fullName: System.Configuration.DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.DefaultSettingValueAttribute.Value
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
  fullName: System.Configuration.DefaultSettingValueAttribute.Value
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor*
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: DefaultSettingValueAttribute
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute
- uid: System.Configuration.DefaultSettingValueAttribute.Value*
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
