### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventHandler
  id: SettingsLoadedEventHandler
  langs:
  - csharp
  name: SettingsLoadedEventHandler
  nameWithType: SettingsLoadedEventHandler
  fullName: System.Configuration.SettingsLoadedEventHandler
  type: Delegate
  summary: "Representerer metoden som håndterer den <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsLoaded&quot;> </xref> hendelsen."
  remarks: "Den <xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>hendelsen oppstår når innstillingene er hentet fra en leverandør.</xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded> Denne hendelsen starter én gang for hver leverandøren."
  syntax:
    content: public delegate void SettingsLoadedEventHandler(object sender, SettingsLoadedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
