### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CheckForUpdateCompletedEventHandler
  id: CheckForUpdateCompletedEventHandler
  langs:
  - csharp
  name: CheckForUpdateCompletedEventHandler
  nameWithType: CheckForUpdateCompletedEventHandler
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventHandler
  type: Delegate
  summary: "Representerer metoden som håndterer den <xref href=&quot;System.Deployment.Application.ApplicationDeployment.CheckForUpdateCompleted&quot;> </xref> hendelse for en <xref href=&quot;System.Deployment.Application.ApplicationDeployment&quot;> </xref>."
  remarks: 'Når du oppretter en CheckForUpdateCompletedEventHandler representant, må du identifisere metoden som håndterer hendelsen. Hvis du vil knytte hendelsen til hendelsesbehandlingen, må du legge til en forekomst av representanten i hendelsen. Hendelsesbehandlingen kalles når det oppstår hendelsen, med mindre du fjerner representanten. Du finner mer informasjon om hendelsesbehandlingen representanter [NIB: hendelser og representanter](http://msdn.microsoft.com/en-us/d98fd58b-fa4f-4598-8378-addf4355a115).'
  syntax:
    content: public delegate void CheckForUpdateCompletedEventHandler(object sender, CheckForUpdateCompletedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
