### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TicketCompatibilityMode
  id: TicketCompatibilityMode
  children:
  - System.Web.Configuration.TicketCompatibilityMode.Framework20
  - System.Web.Configuration.TicketCompatibilityMode.Framework40
  langs:
  - csharp
  name: TicketCompatibilityMode
  nameWithType: TicketCompatibilityMode
  fullName: System.Web.Configuration.TicketCompatibilityMode
  type: Enum
  summary: "Angir om Coordinated Universal Time (UTC) eller lokal tid for billett utløpsdatoen for skjemagodkjenning."
  remarks: "Billett utløpsdatoen for ASP.NET skjemagodkjenning kan lagres ved hjelp av Coordinated Universal Time (UTC) eller den lokale tidssonen. For kompatibilitet mellom programmer, og for kompatibilitet mellom ulike versjoner av .NET Framework, tidspunktet for utløp billett kan angis ved hjelp av `ticketCompatilityMode` -attributtet for elementet. Standardverdien for den `ticketCompatibilityMode` attributtet er Framework20."
  example:
  - "The following example configures the forms authentication ticket expiration date as UTC time.  \n  \n```  \n<system.web>  \n  <authentication mode=\"Forms\">   \n    <forms ticketCompatilityMode=\"Framework40\">  \n    </forms>  \n  </authentication>  \n</system.web>  \n```"
  syntax:
    content: public enum TicketCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework20
  id: Framework20
  parent: System.Web.Configuration.TicketCompatibilityMode
  langs:
  - csharp
  name: Framework20
  nameWithType: TicketCompatibilityMode.Framework20
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework20
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Angir at billett utløpsdatoen er lagret i lokal tid. Dette er standardverdien."
  syntax:
    content: Framework20
    return:
      type: System.Web.Configuration.TicketCompatibilityMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework40
  id: Framework40
  parent: System.Web.Configuration.TicketCompatibilityMode
  langs:
  - csharp
  name: Framework40
  nameWithType: TicketCompatibilityMode.Framework40
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework40
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Angir at billett utløpsdatoen er lagret som UTC."
  syntax:
    content: Framework40
    return:
      type: System.Web.Configuration.TicketCompatibilityMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework20
  parent: System.Web.Configuration.TicketCompatibilityMode
  isExternal: false
  name: Framework20
  nameWithType: TicketCompatibilityMode.Framework20
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework20
- uid: System.Web.Configuration.TicketCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: TicketCompatibilityMode
  nameWithType: TicketCompatibilityMode
  fullName: System.Web.Configuration.TicketCompatibilityMode
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework40
  parent: System.Web.Configuration.TicketCompatibilityMode
  isExternal: false
  name: Framework40
  nameWithType: TicketCompatibilityMode.Framework40
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework40
