### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.HttpWebRequestElement
  id: HttpWebRequestElement
  children:
  - System.Net.Configuration.HttpWebRequestElement.#ctor
  - System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  - System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  - System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  - System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  - System.Net.Configuration.HttpWebRequestElement.Properties
  - System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  langs:
  - csharp
  name: HttpWebRequestElement
  nameWithType: HttpWebRequestElement
  fullName: System.Net.Configuration.HttpWebRequestElement
  type: Class
  summary: "Representerer den maksimale lengden for hodene. Denne klassen kan ikke arves."
  remarks: "This class corresponds to the `maximumResponseHeadersLength` attribute of the [\\&lt;httpWebRequest\\&gt; Element (Network Settings)](../Topic/%3ChttpWebRequest%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n The information in this class applies to responses to requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class HttpWebRequestElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: HttpWebRequestElement()
  nameWithType: HttpWebRequestElement.HttpWebRequestElement()
  fullName: System.Net.Configuration.HttpWebRequestElement.HttpWebRequestElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Net.Configuration.HttpWebRequestElement&quot;> </xref> klasse."
  remarks: "Denne konstruktøren legger til en <xref:System.Configuration.ConfigurationProperty>objektet som representerer den <xref:System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength%2A>til den <xref:System.Configuration.ConfigurationElement.Properties%2A>samlingen.</xref:System.Configuration.ConfigurationElement.Properties%2A> </xref:System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength%2A> </xref:System.Configuration.ConfigurationProperty>"
  syntax:
    content: public HttpWebRequestElement ();
    parameters: []
  overload: System.Net.Configuration.HttpWebRequestElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  id: MaximumErrorResponseLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Henter eller angir den maksimale tillatte lengden på et svar på en feil."
  syntax:
    content: public int MaximumErrorResponseLength { get; set; }
    return:
      type: System.Int32
      description: "En 32-biters heltall som inneholder den maksimale lengden i kilobyte (1024 byte) på feilmeldingssvaret med fortegn. Standardverdien er 64."
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  id: MaximumResponseHeadersLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Henter eller angir den maksimale tillatte lengden på svarhoder."
  remarks: "Lengden måles i kilobyte (1024 byte), og den omfatter statuslinjen svar og svar-hodene samt alle ekstra kontrolltegn mottatt som en del av HTTP-protokollen.       Verdien-1 betyr ingen grense er pålagt svarhoder; verdien 0 betyr at alle forespørsler mislykkes."
  syntax:
    content: public int MaximumResponseHeadersLength { get; set; }
    return:
      type: System.Int32
      description: "En 32-biters heltall som inneholder den maksimale lengden i kilobyte (1024 byte) på svarhoder med fortegn. Standardverdien er 64."
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  id: MaximumUnauthorizedUploadLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Henter eller angir den maksimale lengden på en opplasting som svar på en uautorisert feilkode."
  syntax:
    content: public int MaximumUnauthorizedUploadLength { get; set; }
    return:
      type: System.Int32
      description: "En 32-biters heltall med fortegn som inneholder den maksimale lengden (i flere enheter 1,024 byte) på en opplasting som svar på en uautorisert feilkode. Verdien -1 angir at ingen størrelsesgrensen vil være pålagt opplasting. Angivelse av MaximumUnauthorizedUploadLength-egenskapen til en annen verdi sender bare forespørselens brødtekst Hvis det er mindre enn antall byte som er angitt. Slik at du vil angi verdien 1 for å sende forespørselen meldingsteksten bare hvis det er mindre enn 1,024 byte.       Standardverdien for denne egenskapen er -1."
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  id: PostDeserialize
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: HttpWebRequestElement.PostDeserialize()
  fullName: System.Net.Configuration.HttpWebRequestElement.PostDeserialize()
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Net.Configuration.HttpWebRequestElement.PostDeserialize*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.Properties
  id: Properties
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
  fullName: System.Net.Configuration.HttpWebRequestElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Net.Configuration.HttpWebRequestElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  id: UseUnsafeHeaderParsing
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
  fullName: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Angi denne egenskapen ignoreres valideringsfeil som oppstår under analyse av HTTP."
  remarks: "Når denne egenskapen er satt til `false`, følgende valideringer er utført under HTTP-analyse:-Bruk CRLF i slutten av linjen kode, ved hjelp av Vognretur eller Linjeskift alene er ikke tillatt.      -Hode navn kan ikke ha mellomrom.      -Hvis det finnes flere status linjer, behandles alle ekstra status linjer som misformet topptekst navn/verdi-par.      -Statuslinjen må ha en beskrivelse av status, i tillegg til en statuskode.      -Navn kan ikke inneholder ikke-ASCII-tegn. Denne valideringen utføres om denne egenskapen er satt til `true` eller `false`.       Når et brudd på oppstår, et <xref:System.Net.WebException>unntak med status settes til <xref:System.Net.WebExceptionStatus>.</xref:System.Net.WebExceptionStatus> </xref:System.Net.WebException> Hvis den `UseUnsafeHeaderParsing` er satt til `true`, valideringsfeil ignoreres.       Når egenskapen settes `true` har innvirkning på sikkerheten, og bør bare gjøres hvis bakoverkompatibilitet med en server kreves."
  syntax:
    content: public bool UseUnsafeHeaderParsing { get; set; }
    return:
      type: System.Boolean
      description: "Boolsk verdi som angir om denne egenskapen er angitt."
  overload: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: HttpWebRequestElement()
  nameWithType: HttpWebRequestElement.HttpWebRequestElement()
  fullName: System.Net.Configuration.HttpWebRequestElement.HttpWebRequestElement()
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: PostDeserialize()
  nameWithType: HttpWebRequestElement.PostDeserialize()
  fullName: System.Net.Configuration.HttpWebRequestElement.PostDeserialize()
- uid: System.Net.Configuration.HttpWebRequestElement.Properties
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
  fullName: System.Net.Configuration.HttpWebRequestElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
  fullName: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: HttpWebRequestElement
  nameWithType: HttpWebRequestElement.HttpWebRequestElement
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: PostDeserialize
  nameWithType: HttpWebRequestElement.PostDeserialize
- uid: System.Net.Configuration.HttpWebRequestElement.Properties*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
