### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressState
  id: DeploymentProgressState
  children:
  - System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  - System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  - System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  langs:
  - csharp
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
  type: Enum
  summary: "Angir gjeldende trinn i en [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] Last ned operasjonen."
  remarks: "DeploymentProgressState er sendt av way av den <xref:System.Deployment.Application.DownloadProgressChangedEventArgs.State%2A>medlem av <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs>, som brukes av den <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, og <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>hendelser.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> </xref:System.Deployment.Application.DeploymentProgressChangedEventArgs> </xref:System.Deployment.Application.DownloadProgressChangedEventArgs.State%2A> Bruk medlemmene i denne opplistingen til å finne ut hvilken del av den [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] distribusjon er allerede lastet ned til den lokale maskinen."
  example:
  - "The following code example installs the latest [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] application update asynchronously.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/t-system.deployment.appl_0_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: public enum DeploymentProgressState
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  id: DownloadingApplicationFiles
  parent: System.Deployment.Application.DeploymentProgressState
  langs:
  - csharp
  name: DownloadingApplicationFiles
  nameWithType: DeploymentProgressState.DownloadingApplicationFiles
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  type: Field
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: '[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]laster ned DLL-fil- og datafiler som består av programmet.'
  syntax:
    content: DownloadingApplicationFiles
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  id: DownloadingApplicationInformation
  parent: System.Deployment.Application.DeploymentProgressState
  langs:
  - csharp
  name: DownloadingApplicationInformation
  nameWithType: DeploymentProgressState.DownloadingApplicationInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  type: Field
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: '[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]laster ned programmanifestet.'
  syntax:
    content: DownloadingApplicationInformation
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  id: DownloadingDeploymentInformation
  parent: System.Deployment.Application.DeploymentProgressState
  langs:
  - csharp
  name: DownloadingDeploymentInformation
  nameWithType: DeploymentProgressState.DownloadingDeploymentInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  type: Field
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: '[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]laster ned distribusjon manifestet.'
  syntax:
    content: DownloadingDeploymentInformation
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  parent: System.Deployment.Application.DeploymentProgressState
  isExternal: false
  name: DownloadingApplicationFiles
  nameWithType: DeploymentProgressState.DownloadingApplicationFiles
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  parent: System.Deployment.Application.DeploymentProgressState
  isExternal: false
  name: DownloadingApplicationInformation
  nameWithType: DeploymentProgressState.DownloadingApplicationInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  parent: System.Deployment.Application.DeploymentProgressState
  isExternal: false
  name: DownloadingDeploymentInformation
  nameWithType: DeploymentProgressState.DownloadingDeploymentInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
