### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ConnectionManagementElement
  id: ConnectionManagementElement
  children:
  - System.Net.Configuration.ConnectionManagementElement.#ctor
  - System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  - System.Net.Configuration.ConnectionManagementElement.Address
  - System.Net.Configuration.ConnectionManagementElement.MaxConnection
  - System.Net.Configuration.ConnectionManagementElement.Properties
  langs:
  - csharp
  name: ConnectionManagementElement
  nameWithType: ConnectionManagementElement
  fullName: System.Net.Configuration.ConnectionManagementElement
  type: Class
  summary: "Representerer maksimalt antall tilkoblinger til en ekstern datamaskin. Denne klassen kan ikke arves."
  remarks: "This class corresponds to the [\\&lt;add\\&gt; Element for connectionManagement (Network Settings)](../Topic/%3Cadd%3E%20Element%20for%20connectionManagement%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify the maximum number of simultaneous connections to a remote computer.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ConnectionManagementElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: ConnectionManagementElement()
  nameWithType: ConnectionManagementElement.ConnectionManagementElement()
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Net.Configuration.ConnectionManagementElement&quot;> </xref> klasse."
  syntax:
    content: public ConnectionManagementElement ();
    parameters: []
  overload: System.Net.Configuration.ConnectionManagementElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  id: '#ctor(System.String,System.Int32)'
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: ConnectionManagementElement(String,Int32)
  nameWithType: ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Net.Configuration.ConnectionManagementElement&quot;> </xref> klassen med den angitte adressen og tilkoblingsinformasjonen grensen."
  remarks: "Denne konstruktøren angir den <xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>egenskapen `address` og <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>egenskapen `maxConnection`.</xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A> </xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>"
  syntax:
    content: public ConnectionManagementElement (string address, int maxConnection);
    parameters:
    - id: address
      type: System.String
      description: "En streng som identifiserer adressen til en ekstern datamaskin."
    - id: maxConnection
      type: System.Int32
      description: "Et heltall som angir maksimalt antall tilkoblinger til `address` fra den lokale datamaskinen."
  overload: System.Net.Configuration.ConnectionManagementElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.Address
  id: Address
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Henter eller angir adressen for eksterne datamaskiner."
  remarks: "Du kan angi denne egenskapen med en stjerne (*) til å angi standardantall tilkoblinger for uspesifisert datamaskiner.       Denne egenskapen identifiserer én eller flere eksterne datamaskiner og <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>egenskapen angir hvor mange samtidige tilkoblinger som tillates mellom den lokale datamaskinen og eksterne datamaskiner.</xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>"
  syntax:
    content: public string Address { get; set; }
    return:
      type: System.String
      description: "En streng som inneholder et vanlig uttrykk som beskriver en IP-adresse eller DNS-navn."
  overload: System.Net.Configuration.ConnectionManagementElement.Address*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  id: MaxConnection
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Henter eller angir maksimalt antall tilkoblinger som kan gjøres til en ekstern datamaskin."
  remarks: "Egenskapen angir hvor mange samtidige tilkoblinger som tillates mellom den lokale datamaskinen og den eksterne datamaskinen. Den eksterne datamaskinen er angitt med den <xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>egenskapen.</xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>       Egenskapen MaxConnection er per <xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName>.</xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName> Hvis et program ikke endres <xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName>enn standardinnstillingen deretter MaxConnection egenskapen gjelder for hele programdomenet.</xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName> Hvis bare en enkelt programdomenet kjøres i programmet, er egenskapsinnstillingen MaxConnection generelle."
  syntax:
    content: public int MaxConnection { get; set; }
    return:
      type: System.Int32
      description: "Et heltall som angir maksimalt antall tilkoblinger."
  overload: System.Net.Configuration.ConnectionManagementElement.MaxConnection*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.Properties
  id: Properties
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Net.Configuration.ConnectionManagementElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement()
  nameWithType: ConnectionManagementElement.ConnectionManagementElement()
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement()
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement(String,Int32)
  nameWithType: ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement(String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.Configuration.ConnectionManagementElement.Address
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
- uid: System.Net.Configuration.ConnectionManagementElement.Properties
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement
  nameWithType: ConnectionManagementElement.ConnectionManagementElement
- uid: System.Net.Configuration.ConnectionManagementElement.Address*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Address
  nameWithType: ConnectionManagementElement.Address
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
- uid: System.Net.Configuration.ConnectionManagementElement.Properties*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
