### YamlMime:ManagedReference
items:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  id: ITransformerConfigurationControl
  children:
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  langs:
  - csharp
  name: ITransformerConfigurationControl
  nameWithType: ITransformerConfigurationControl
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  type: Interface
  summary: "Definerer kontrakten implementerer en kontroll som konfigurasjonskontroll for transformeringen i en webdeler-tilkobling."
  remarks: "En konfigurasjonskontroll kan vises når en transformering krever en bruker til å konfigurere den. Konfigurasjonskontrollen gir brukergrensesnittet (UI) som tillater at brukeren velger hvilke verdier gjøres om. Den gjengis i en Tilkoblingssone. Den <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>metoden returnerer en konfigurasjonskontroll.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>       Du kan overstyre den <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A>metoden når transformeringen krever et tilpasset brukergrensesnitt.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A> Konfigurasjonskontrollen må implementere grensesnittet ITransformerConfigurationControl som inneholder den <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled>og <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded>hendelser.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded> </xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled> Disse hendelser inntreffer når en kontroll transformeringen ikke har konfigurert eller er konfigurert på riktig måte, henholdsvis."
  syntax:
    content: public interface ITransformerConfigurationControl
  implements: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  id: Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Forekommer når transformeringen konfigurasjon ikke er fullført."
  remarks: "Webdeler kontrollen som implementerer <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>forårsaket hendelsen når en transformeringen-konfigurasjon ikke er fullført, fordi brukeren avbrøt konfigurasjonen eller fordi konfigurasjonen ikke kan utføres.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Cancelled;
    return:
      type: System.EventHandler
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  id: Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Forekommer når Transformeringskonfigurasjonen er fullført."
  remarks: "Webdeler kontrollen som implementerer <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>forårsaket hendelsen når en konfigurasjon for transformeringen er fullført.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Succeeded;
    return:
      type: System.EventHandler
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
- uid: System.EventHandler
  parent: System
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: System.EventHandler
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
