### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement
  id: UserPrincipalNameElement
  children:
  - System.ServiceModel.Configuration.UserPrincipalNameElement.#ctor
  - System.ServiceModel.Configuration.UserPrincipalNameElement.Properties
  - System.ServiceModel.Configuration.UserPrincipalNameElement.Value
  langs:
  - csharp
  name: UserPrincipalNameElement
  nameWithType: UserPrincipalNameElement
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement
  type: Class
  summary: "Representerer en konfigurasjonselementet som angir et hovednavn for bruker. Denne klassen kan arves."
  remarks: "Et hovednavn for bruker er navnet p책loggingstype for en bruker p책 et nettverk. Brukerhovednavnet best책r av objektet brukernavnet som brukes i Active Directory, etterfulgt av symbolet (@) og deretter vanligvis DNS overordnet domene. Jeff i Fabrikam.com domenetre kan for eksempel ha brukerhovednavnet [ jeff@fabrikam.com ](mailto:jeffsmith@fabrikam.com)."
  syntax:
    content: 'public sealed class UserPrincipalNameElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  langs:
  - csharp
  name: UserPrincipalNameElement()
  nameWithType: UserPrincipalNameElement.UserPrincipalNameElement()
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.UserPrincipalNameElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.UserPrincipalNameElement&quot;> </xref> klasse."
  syntax:
    content: public UserPrincipalNameElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.UserPrincipalNameElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  langs:
  - csharp
  name: Properties
  nameWithType: UserPrincipalNameElement.Properties
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Value
  id: Value
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  langs:
  - csharp
  name: Value
  nameWithType: UserPrincipalNameElement.Value
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.Value
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir verdien som er angitt for denne konfigurasjonselementet."
  syntax:
    content: public string Value { get; set; }
    return:
      type: System.String
      description: "En tekststreng som angir et brukerkontonavn (noen ganger kalles p책loggingsnavn for bruker) og et domenenavn som identifiserer domenet som brukerkontoen er plassert."
  overload: System.ServiceModel.Configuration.UserPrincipalNameElement.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.#ctor
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: UserPrincipalNameElement()
  nameWithType: UserPrincipalNameElement.UserPrincipalNameElement()
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.UserPrincipalNameElement()
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: Properties
  nameWithType: UserPrincipalNameElement.Properties
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Value
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: Value
  nameWithType: UserPrincipalNameElement.Value
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.Value
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.#ctor*
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: UserPrincipalNameElement
  nameWithType: UserPrincipalNameElement.UserPrincipalNameElement
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties*
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: Properties
  nameWithType: UserPrincipalNameElement.Properties
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Value*
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: Value
  nameWithType: UserPrincipalNameElement.Value
