### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventArgs
  id: SettingChangingEventArgs
  children:
  - System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  - System.Configuration.SettingChangingEventArgs.NewValue
  - System.Configuration.SettingChangingEventArgs.SettingClass
  - System.Configuration.SettingChangingEventArgs.SettingKey
  - System.Configuration.SettingChangingEventArgs.SettingName
  langs:
  - csharp
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs
  fullName: System.Configuration.SettingChangingEventArgs
  type: Class
  summary: "Gir dataene for den <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingChanging&quot;> </xref> hendelsen."
  remarks: "Klassen SettingChangingEventArgs gir dataene for den <xref:System.Configuration.ApplicationSettingsBase.SettingChanging>hendelse som signaliserer at verdien for egenskapen en program-innstillingene er ferd med å endre.</xref:System.Configuration.ApplicationSettingsBase.SettingChanging> Den vanligste formen for denne hendelsen, er det `get` aksessor <xref:System.Configuration.ApplicationSettingsBase.Item%2A>metoden i <xref:System.Configuration.ApplicationSettingsBase>klasse.</xref:System.Configuration.ApplicationSettingsBase> </xref:System.Configuration.ApplicationSettingsBase.Item%2A>       Fordi SettingChangingEventArgs er avledet fra <xref:System.ComponentModel.CancelEventArgs>, behandlingsprogrammet har du muligheten til å avbryte Skriveoperasjonen.</xref:System.ComponentModel.CancelEventArgs>"
  syntax:
    content: 'public class SettingChangingEventArgs : System.ComponentModel.CancelEventArgs'
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  id: '#ctor(System.String,System.String,System.String,System.Object,System.Boolean)'
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en forekomst av den <xref href=&quot;System.Configuration.SettingChangingEventArgs&quot;> </xref> klasse."
  remarks: "Konstruktøren SettingChangingEventArgs tilordner bare verdier for parameterne til de tilsvarende egenskapene i <xref:System.Configuration.SettingChangingEventArgs>klasse.</xref:System.Configuration.SettingChangingEventArgs>"
  syntax:
    content: public SettingChangingEventArgs (string settingName, string settingClass, string settingKey, object newValue, bool cancel);
    parameters:
    - id: settingName
      type: System.String
      description: "En <xref:System.String>som inneholder navnet på applikasjonsinnstilling.</xref:System.String>"
    - id: settingClass
      type: System.String
      description: "En <xref:System.String>som inneholder en beskrivelse av innstillingen.</xref:System.String> Ofte er denne parameteren satt til navnet på programmet innstillinger."
    - id: settingKey
      type: System.String
      description: "En <xref:System.String>som inneholder programmet innstillinger-nøkkelen.</xref:System.String>"
    - id: newValue
      type: System.Object
      description: "En <xref:System.Object>som inneholder den nye verdien som skal tilordnes til egenskapen programmet innstillinger.</xref:System.Object>"
    - id: cancel
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>å avbryte hendelsen; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.SettingChangingEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  id: NewValue
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Henter den nye verdien som ble tilordnet til egenskapen programmet innstillinger."
  remarks: "Den faktiske typen NewValue-egenskapen må være kompatibel med egenskapen innstillinger angis. Det er tilgjengelig via <xref:System.Configuration.SettingsProperty.PropertyType%2A>egenskapen for <xref:System.Configuration.SettingsProperty>klassen.</xref:System.Configuration.SettingsProperty> </xref:System.Configuration.SettingsProperty.PropertyType%2A>"
  syntax:
    content: public object NewValue { get; }
    return:
      type: System.Object
      description: "En <xref:System.Object>som inneholder den nye verdien som skal tilordnes til egenskapen programmet innstillinger.</xref:System.Object>"
  overload: System.Configuration.SettingChangingEventArgs.NewValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  id: SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Henter programmet innstillinger egenskapskategori."
  remarks: "Alle programinnstillinger hører til applikasjonen innstillinger for gruppe. Gruppenavnet kan angis eksplisitt av decorating klassen med a <xref:System.Configuration.SettingsGroupNameAttribute>Hvis ikke, er en generert med navnet på innstillinger-wrapperen som klassen.</xref:System.Configuration.SettingsGroupNameAttribute>"
  syntax:
    content: public string SettingClass { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som inneholder en beskrivelse av innstillingen.</xref:System.String> Vanligvis er denne parameteren satt til navnet på programmet innstillinger."
  overload: System.Configuration.SettingChangingEventArgs.SettingClass*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  id: SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Henter programmet innstillinger-nøkkelen som er forbundet med egenskapen."
  remarks: "Klasse hver innstillinger-wrapperen som er hentet fra <xref:System.Configuration.ApplicationSettingsBase>, har en tilknyttet innstillinger nøkkel, som er en streng som bidrar til å oppheve tvetydigheten ulike forekomster av den samme wrapperen i et enkelt program.</xref:System.Configuration.ApplicationSettingsBase> Siden hver wrapperklasse definerer et sett med egenskaper som representerer programinnstillinger, bidrar innstillinger-nøkkelen på samme måte til å oppheve tvetydigheten bruken."
  syntax:
    content: public string SettingKey { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som inneholder programmet innstillinger-nøkkelen.</xref:System.String>"
  overload: System.Configuration.SettingChangingEventArgs.SettingKey*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  id: SettingName
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Henter navnet på applikasjonsinnstilling som er knyttet til programmet innstillinger-egenskap."
  remarks: "Vanligvis klassen innstillinger wrapperen som er avledet fra <xref:System.Configuration.ApplicationSettingsBase>, vil bli bygd opp slik at navnet på egenskapen programmet innstillingene skal være den samme som den tilknyttede applikasjonsinnstilling.</xref:System.Configuration.ApplicationSettingsBase>"
  syntax:
    content: public string SettingName { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som inneholder navnet på applikasjonsinnstilling.</xref:System.String>"
  overload: System.Configuration.SettingChangingEventArgs.SettingName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
- uid: System.Configuration.SettingChangingEventArgs.#ctor*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs
- uid: System.Configuration.SettingChangingEventArgs.NewValue*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
