### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.ReceiveSettings
  id: ReceiveSettings
  children:
  - System.ServiceModel.Activities.ReceiveSettings.#ctor
  - System.ServiceModel.Activities.ReceiveSettings.Action
  - System.ServiceModel.Activities.ReceiveSettings.CanCreateInstance
  - System.ServiceModel.Activities.ReceiveSettings.OwnerDisplayName
  langs:
  - csharp
  name: ReceiveSettings
  nameWithType: ReceiveSettings
  fullName: System.ServiceModel.Activities.ReceiveSettings
  type: Class
  summary: "Representerer innstillingene for en aktivitet som mottar en melding."
  syntax:
    content: public sealed class ReceiveSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ReceiveSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.ReceiveSettings
  langs:
  - csharp
  name: ReceiveSettings()
  nameWithType: ReceiveSettings.ReceiveSettings()
  fullName: System.ServiceModel.Activities.ReceiveSettings.ReceiveSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Activities.ReceiveSettings&quot;> </xref> klasse."
  syntax:
    content: public ReceiveSettings ();
    parameters: []
  overload: System.ServiceModel.Activities.ReceiveSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ReceiveSettings.Action
  id: Action
  parent: System.ServiceModel.Activities.ReceiveSettings
  langs:
  - csharp
  name: Action
  nameWithType: ReceiveSettings.Action
  fullName: System.ServiceModel.Activities.ReceiveSettings.Action
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Henter eller angir verdien for den handlingen meldingshodet."
  syntax:
    content: public string Action { get; set; }
    return:
      type: System.String
      description: "Handlingen URI for meldingen."
  overload: System.ServiceModel.Activities.ReceiveSettings.Action*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ReceiveSettings.CanCreateInstance
  id: CanCreateInstance
  parent: System.ServiceModel.Activities.ReceiveSettings
  langs:
  - csharp
  name: CanCreateInstance
  nameWithType: ReceiveSettings.CanCreateInstance
  fullName: System.ServiceModel.Activities.ReceiveSettings.CanCreateInstance
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Henter eller angir en verdi som angir om det er opprettet en ny arbeidsflytforekomst for å behandle meldingen om meldingen ikke koordinere til en eksisterende arbeidsflytforekomst."
  syntax:
    content: public bool CanCreateInstance { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis du har opprettet en ny arbeidsflytforekomst for å behandle meldingen. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Activities.ReceiveSettings.CanCreateInstance*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ReceiveSettings.OwnerDisplayName
  id: OwnerDisplayName
  parent: System.ServiceModel.Activities.ReceiveSettings
  langs:
  - csharp
  name: OwnerDisplayName
  nameWithType: ReceiveSettings.OwnerDisplayName
  fullName: System.ServiceModel.Activities.ReceiveSettings.OwnerDisplayName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Henter eller angir visningsnavnet for eieren."
  syntax:
    content: public string OwnerDisplayName { get; set; }
    return:
      type: System.String
      description: "Visningsnavnet for eieren."
  overload: System.ServiceModel.Activities.ReceiveSettings.OwnerDisplayName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Activities.ReceiveSettings.#ctor
  parent: System.ServiceModel.Activities.ReceiveSettings
  isExternal: false
  name: ReceiveSettings()
  nameWithType: ReceiveSettings.ReceiveSettings()
  fullName: System.ServiceModel.Activities.ReceiveSettings.ReceiveSettings()
- uid: System.ServiceModel.Activities.ReceiveSettings.Action
  parent: System.ServiceModel.Activities.ReceiveSettings
  isExternal: false
  name: Action
  nameWithType: ReceiveSettings.Action
  fullName: System.ServiceModel.Activities.ReceiveSettings.Action
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.ReceiveSettings.CanCreateInstance
  parent: System.ServiceModel.Activities.ReceiveSettings
  isExternal: false
  name: CanCreateInstance
  nameWithType: ReceiveSettings.CanCreateInstance
  fullName: System.ServiceModel.Activities.ReceiveSettings.CanCreateInstance
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Activities.ReceiveSettings.OwnerDisplayName
  parent: System.ServiceModel.Activities.ReceiveSettings
  isExternal: false
  name: OwnerDisplayName
  nameWithType: ReceiveSettings.OwnerDisplayName
  fullName: System.ServiceModel.Activities.ReceiveSettings.OwnerDisplayName
- uid: System.ServiceModel.Activities.ReceiveSettings.#ctor*
  parent: System.ServiceModel.Activities.ReceiveSettings
  isExternal: false
  name: ReceiveSettings
  nameWithType: ReceiveSettings.ReceiveSettings
- uid: System.ServiceModel.Activities.ReceiveSettings.Action*
  parent: System.ServiceModel.Activities.ReceiveSettings
  isExternal: false
  name: Action
  nameWithType: ReceiveSettings.Action
- uid: System.ServiceModel.Activities.ReceiveSettings.CanCreateInstance*
  parent: System.ServiceModel.Activities.ReceiveSettings
  isExternal: false
  name: CanCreateInstance
  nameWithType: ReceiveSettings.CanCreateInstance
- uid: System.ServiceModel.Activities.ReceiveSettings.OwnerDisplayName*
  parent: System.ServiceModel.Activities.ReceiveSettings
  isExternal: false
  name: OwnerDisplayName
  nameWithType: ReceiveSettings.OwnerDisplayName
