### YamlMime:ManagedReference
items:
- uid: System.Diagnostics.DiagnosticsConfigurationHandler
  id: DiagnosticsConfigurationHandler
  children:
  - System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  - System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: DiagnosticsConfigurationHandler
  nameWithType: DiagnosticsConfigurationHandler
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler
  type: Class
  summary: "Behandler diagnose-delen av konfigurasjonsfiler."
  remarks: "Metoden DiagnosticsConfigurationHandler er et behandlingsprogram for delen som deltar i løsing av konfigurasjonsinnstillingene i den [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) delen av konfigurasjonsfiler."
  syntax:
    content: >-
      [System.Obsolete("This class has been deprecated.  http://go.microsoft.com/fwlink/?linkid=14202")]

      public class DiagnosticsConfigurationHandler : System.Configuration.IConfigurationSectionHandler
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  langs:
  - csharp
  name: DiagnosticsConfigurationHandler()
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Diagnostics
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Diagnostics.DiagnosticsConfigurationHandler&quot;> </xref> klasse."
  syntax:
    content: public DiagnosticsConfigurationHandler ();
    parameters: []
  overload: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Diagnostics
  summary: "Analyserer konfigurasjonsinnstillingene for den [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) delen av konfigurasjonsfiler."
  remarks: "Create-metoden fyller ut en <xref:System.Collections.Hashtable>med verdier som er hentet fra den [ \\&lt;system.diagnostics\\&gt;](../Topic/%3Csystem.diagnostics%3E%20Element.md) delen av konfigurasjonsfilen, og returnerer hash.</xref:System.Collections.Hashtable>"
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Objektet arvet fra overordnet bane"
    - id: configContext
      type: System.Object
      description: "Reservert. Brukes i ASP.NET for å formidle den virtuelle banen til konfigurasjonen evaluering."
    - id: section
      type: System.Xml.XmlNode
      description: "XML-rotnoden i delen til å håndtere."
    return:
      type: System.Object
      description: "En ny konfigurasjonsobjektet, i form av en <xref href=&quot;System.Collections.Hashtable&quot;> </xref>."
  overload: System.Diagnostics.DiagnosticsConfigurationHandler.Create*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Finner ikke bytter.       - eller - Deklarer ikke ble funnet.       - eller - sporing ble ikke funnet.       - eller - ytelsestellere ble ikke funnet."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: DiagnosticsConfigurationHandler()
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor*
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: DiagnosticsConfigurationHandler
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create*
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: DiagnosticsConfigurationHandler.Create
