### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  id: HttpCapabilitiesDefaultProvider
  children:
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor(System.Web.Configuration.HttpCapabilitiesDefaultProvider)
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency(System.String)
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList(System.Collections.ArrayList)
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(System.Web.HttpRequest)
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  langs:
  - csharp
  name: HttpCapabilitiesDefaultProvider
  nameWithType: HttpCapabilitiesDefaultProvider
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  type: Class
  summary: "Standard-utvidelsen for den <xref href=&quot;System.Web.Configuration.HttpCapabilitiesProvider&quot;> </xref> klasse som er inkludert i ASP.NET."
  syntax:
    content: 'public class HttpCapabilitiesDefaultProvider : System.Web.Configuration.HttpCapabilitiesProvider'
  inheritance:
  - System.Object
  - System.Web.Configuration.HttpCapabilitiesProvider
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: HttpCapabilitiesDefaultProvider()
  nameWithType: HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider()
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.HttpCapabilitiesDefaultProvider&quot;> </xref> klasse."
  syntax:
    content: public HttpCapabilitiesDefaultProvider ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor(System.Web.Configuration.HttpCapabilitiesDefaultProvider)
  id: '#ctor(System.Web.Configuration.HttpCapabilitiesDefaultProvider)'
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
  nameWithType: HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.HttpCapabilitiesDefaultProvider&quot;> </xref> klassen med verdier til den angitte forekomsten."
  syntax:
    content: public HttpCapabilitiesDefaultProvider (System.Web.Configuration.HttpCapabilitiesDefaultProvider parent);
    parameters:
    - id: parent
      type: System.Web.Configuration.HttpCapabilitiesDefaultProvider
      description: "Den <xref href=&quot;System.Web.Configuration.HttpCapabilitiesDefaultProvider&quot;> </xref> -forekomst for bruk for å initialisere en ny forekomst."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency(System.String)
  id: AddDependency(System.String)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: AddDependency(String)
  nameWithType: HttpCapabilitiesDefaultProvider.AddDependency(String)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency(String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Legger til en HTTP-forespørselen streng skal brukes til å analysere browser capability-informasjon."
  remarks: "Denne metoden legger til i samlingen som er opprettet ved hjelp av `use` underordnet element av den `browserCaps` element i Web.config-filen."
  syntax:
    content: public void AddDependency (string variable);
    parameters:
    - id: variable
      type: System.String
      description: "Strengen som skal brukes til å analysere browser capability-informasjon."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList(System.Collections.ArrayList)
  id: AddRuleList(System.Collections.ArrayList)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: AddRuleList(ArrayList)
  nameWithType: HttpCapabilitiesDefaultProvider.AddRuleList(ArrayList)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList(ArrayList)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Legger til en søkestreng som endrer en definisjon for nettleseren."
  remarks: "Denne metoden legger til i samlingen som er opprettet ved hjelp av `filter` underordnet element av den `browserCaps` element i Web.config-filen."
  syntax:
    content: public virtual void AddRuleList (System.Collections.ArrayList ruleList);
    parameters:
    - id: ruleList
      type: System.Collections.ArrayList
      description: "Søkestrengen som endrer en definisjon for nettleseren."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime
  id: CacheTime
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: CacheTime
  nameWithType: HttpCapabilitiesDefaultProvider.CacheTime
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir hvor lang tid i sekunder å beholde den <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> objektet i hurtigbufferen."
  syntax:
    content: public TimeSpan CacheTime { get; set; }
    return:
      type: System.TimeSpan
      description: "Hvor lang tid i sekunder å beholde den <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> objektet i hurtigbufferen."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(System.Web.HttpRequest)
  id: GetBrowserCapabilities(System.Web.HttpRequest)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: GetBrowserCapabilities(HttpRequest)
  nameWithType: HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(HttpRequest)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(HttpRequest)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter den <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> objekt for den angitte <xref href=&quot;System.Web.HttpRequest&quot;> </xref> objektet."
  syntax:
    content: public override System.Web.HttpBrowserCapabilities GetBrowserCapabilities (System.Web.HttpRequest request);
    parameters:
    - id: request
      type: System.Web.HttpRequest
      description: "Den <xref href=&quot;System.Web.HttpRequest&quot;> </xref> objektet."
    return:
      type: System.Web.HttpBrowserCapabilities
      description: "Den <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> objekt den <xref href=&quot;System.Web.HttpRequest&quot;> </xref> objektet som ble sendt."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType
  id: ResultType
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: ResultType
  nameWithType: HttpCapabilitiesDefaultProvider.ResultType
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir typen klassen som brukes til å inneholde resultater fra analyse av <xref uid=&quot;langword_csharp_browserCap&quot; name=&quot;browserCap&quot; href=&quot;&quot;> </xref> element i Web.config-filen."
  remarks: "Denne egenskapen samsvarer med den `result` underordnet element av den `browserCaps` element i Web.config-filen."
  syntax:
    content: public Type ResultType { get; set; }
    return:
      type: System.Type
      description: "Hva slags klassen som brukes til å inneholde resultater fra analyse av <xref uid=&quot;langword_csharp_browserCaps&quot; name=&quot;browserCaps&quot; href=&quot;&quot;> </xref> element i Web.config-filen."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  id: UserAgentCacheKeyLength
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: UserAgentCacheKeyLength
  nameWithType: HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir antall tegn fra brukeren agent strengen som skal brukes for bufring av det <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> objektet."
  syntax:
    content: public int UserAgentCacheKeyLength { get; set; }
    return:
      type: System.Int32
      description: "Antallet tegn fra den angitte brukerlisten agent strengen som skal brukes for bufring av det <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> objektet."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.HttpCapabilitiesProvider
  isExternal: false
  name: System.Web.Configuration.HttpCapabilitiesProvider
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: HttpCapabilitiesDefaultProvider()
  nameWithType: HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider()
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider()
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor(System.Web.Configuration.HttpCapabilitiesDefaultProvider)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
  nameWithType: HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  parent: System.Web.Configuration
  isExternal: false
  name: HttpCapabilitiesDefaultProvider
  nameWithType: HttpCapabilitiesDefaultProvider
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency(System.String)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: AddDependency(String)
  nameWithType: HttpCapabilitiesDefaultProvider.AddDependency(String)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList(System.Collections.ArrayList)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: AddRuleList(ArrayList)
  nameWithType: HttpCapabilitiesDefaultProvider.AddRuleList(ArrayList)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList(ArrayList)
- uid: System.Collections.ArrayList
  parent: System.Collections
  isExternal: false
  name: ArrayList
  nameWithType: ArrayList
  fullName: System.Collections.ArrayList
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: CacheTime
  nameWithType: HttpCapabilitiesDefaultProvider.CacheTime
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(System.Web.HttpRequest)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: GetBrowserCapabilities(HttpRequest)
  nameWithType: HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(HttpRequest)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(HttpRequest)
- uid: System.Web.HttpBrowserCapabilities
  parent: System.Web
  isExternal: false
  name: HttpBrowserCapabilities
  nameWithType: HttpBrowserCapabilities
  fullName: System.Web.HttpBrowserCapabilities
- uid: System.Web.HttpRequest
  parent: System.Web
  isExternal: false
  name: HttpRequest
  nameWithType: HttpRequest
  fullName: System.Web.HttpRequest
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: ResultType
  nameWithType: HttpCapabilitiesDefaultProvider.ResultType
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: UserAgentCacheKeyLength
  nameWithType: HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: HttpCapabilitiesDefaultProvider
  nameWithType: HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: AddDependency
  nameWithType: HttpCapabilitiesDefaultProvider.AddDependency
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: AddRuleList
  nameWithType: HttpCapabilitiesDefaultProvider.AddRuleList
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: CacheTime
  nameWithType: HttpCapabilitiesDefaultProvider.CacheTime
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: GetBrowserCapabilities
  nameWithType: HttpCapabilitiesDefaultProvider.GetBrowserCapabilities
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: ResultType
  nameWithType: HttpCapabilitiesDefaultProvider.ResultType
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: UserAgentCacheKeyLength
  nameWithType: HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
