### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement
  id: ServiceBehaviorElement
  children:
  - System.ServiceModel.Configuration.ServiceBehaviorElement.#ctor
  - System.ServiceModel.Configuration.ServiceBehaviorElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ServiceBehaviorElement.Add(System.ServiceModel.Configuration.BehaviorExtensionElement)
  - System.ServiceModel.Configuration.ServiceBehaviorElement.CanAdd(System.ServiceModel.Configuration.BehaviorExtensionElement)
  - System.ServiceModel.Configuration.ServiceBehaviorElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  langs:
  - csharp
  name: ServiceBehaviorElement
  nameWithType: ServiceBehaviorElement
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement
  type: Class
  summary: "Representerer en konfigurasjonselementet som inneholder en liste over tjenesten virkemåter som brukes på alle [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] tjenester på maskinen."
  syntax:
    content: 'public class ServiceBehaviorElement : System.ServiceModel.Configuration.NamedServiceModelExtensionCollectionElement<System.ServiceModel.Configuration.BehaviorExtensionElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1
  - System.ServiceModel.Configuration.NamedServiceModelExtensionCollectionElement`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.ServiceModel.Configuration.NamedServiceModelExtensionCollectionElement`1.Name
  - System.ServiceModel.Configuration.NamedServiceModelExtensionCollectionElement`1.Properties
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.Add(`0)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.CanAdd(`0)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.Clear
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.Contains(`0)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.ContainsKey(System.String)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.ContainsKey(System.Type)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.CopyTo(`0[],System.Int32)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.Count
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.GetEnumerator
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.Item(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.Item(System.Type)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.Remove(`0)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.ResetModified
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.SetIsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.SetReadOnly
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.System#Collections#Generic#ICollection{TServiceModelExtensionElement}#IsReadOnly
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.System#Collections#IEnumerable#GetEnumerator
  - System.ServiceModel.Configuration.ServiceModelExtensionCollectionElement`1.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  langs:
  - csharp
  name: ServiceBehaviorElement()
  nameWithType: ServiceBehaviorElement.ServiceBehaviorElement()
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement.ServiceBehaviorElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.ServiceBehaviorElement&quot;> </xref> klasse."
  syntax:
    content: public ServiceBehaviorElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceBehaviorElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  langs:
  - csharp
  name: ServiceBehaviorElement(String)
  nameWithType: ServiceBehaviorElement.ServiceBehaviorElement(String)
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement.ServiceBehaviorElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.ServiceBehaviorElement&quot;> </xref> klassen med det angitte navnet."
  syntax:
    content: public ServiceBehaviorElement (string name);
    parameters:
    - id: name
      type: System.String
      description: "Et unikt navn for elementet virkemåte."
  overload: System.ServiceModel.Configuration.ServiceBehaviorElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.Add(System.ServiceModel.Configuration.BehaviorExtensionElement)
  id: Add(System.ServiceModel.Configuration.BehaviorExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  langs:
  - csharp
  name: Add(BehaviorExtensionElement)
  nameWithType: ServiceBehaviorElement.Add(BehaviorExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement.Add(BehaviorExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Legger til et nytt virkemåte-element i denne delen."
  syntax:
    content: public override void Add (System.ServiceModel.Configuration.BehaviorExtensionElement element);
    parameters:
    - id: element
      type: System.ServiceModel.Configuration.BehaviorExtensionElement
      description: "En <xref href=&quot;System.ServiceModel.Configuration.BehaviorExtensionElement&quot;> </xref> som skal legges til."
  overload: System.ServiceModel.Configuration.ServiceBehaviorElement.Add*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Typen som er angitt av <code> element </code> er ugyldig."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.CanAdd(System.ServiceModel.Configuration.BehaviorExtensionElement)
  id: CanAdd(System.ServiceModel.Configuration.BehaviorExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  langs:
  - csharp
  name: CanAdd(BehaviorExtensionElement)
  nameWithType: ServiceBehaviorElement.CanAdd(BehaviorExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement.CanAdd(BehaviorExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Legger til et nytt virkemåte-element i denne delen, og returnerer en verdi som angir om operasjonen er fullført."
  syntax:
    content: public override bool CanAdd (System.ServiceModel.Configuration.BehaviorExtensionElement element);
    parameters:
    - id: element
      type: System.ServiceModel.Configuration.BehaviorExtensionElement
      description: "En <xref href=&quot;System.ServiceModel.Configuration.BehaviorExtensionElement&quot;> </xref> som skal legges til."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis operasjonen er fullført. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.ServiceBehaviorElement.CanAdd*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Typen som er angitt av <code> element </code> er ugyldig."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: ServiceBehaviorElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Leser XML fra konfigurasjonsfilen."
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "En <xref:System.Xml.XmlReader>som leser fra konfigurasjonsfilen.</xref:System.Xml.XmlReader>"
    - id: serializeCollectionKey
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>til å serialisere bare samlingen Nøkkelegenskapene; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.ServiceBehaviorElement.DeserializeElement*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.NamedServiceModelExtensionCollectionElement`1
  isExternal: false
  name: System.ServiceModel.Configuration.NamedServiceModelExtensionCollectionElement<System.ServiceModel.Configuration.BehaviorExtensionElement>
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  isExternal: false
  name: ServiceBehaviorElement()
  nameWithType: ServiceBehaviorElement.ServiceBehaviorElement()
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement.ServiceBehaviorElement()
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  isExternal: false
  name: ServiceBehaviorElement(String)
  nameWithType: ServiceBehaviorElement.ServiceBehaviorElement(String)
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement.ServiceBehaviorElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.Add(System.ServiceModel.Configuration.BehaviorExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  isExternal: false
  name: Add(BehaviorExtensionElement)
  nameWithType: ServiceBehaviorElement.Add(BehaviorExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement.Add(BehaviorExtensionElement)
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: BehaviorExtensionElement
  nameWithType: BehaviorExtensionElement
  fullName: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.CanAdd(System.ServiceModel.Configuration.BehaviorExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  isExternal: false
  name: CanAdd(BehaviorExtensionElement)
  nameWithType: ServiceBehaviorElement.CanAdd(BehaviorExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement.CanAdd(BehaviorExtensionElement)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: ServiceBehaviorElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElement.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  isExternal: false
  name: ServiceBehaviorElement
  nameWithType: ServiceBehaviorElement.ServiceBehaviorElement
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.Add*
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  isExternal: false
  name: Add
  nameWithType: ServiceBehaviorElement.Add
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.CanAdd*
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  isExternal: false
  name: CanAdd
  nameWithType: ServiceBehaviorElement.CanAdd
- uid: System.ServiceModel.Configuration.ServiceBehaviorElement.DeserializeElement*
  parent: System.ServiceModel.Configuration.ServiceBehaviorElement
  isExternal: false
  name: DeserializeElement
  nameWithType: ServiceBehaviorElement.DeserializeElement
