### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  id: XmlFormatExtensionPrefixAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute
  nameWithType: XmlFormatExtensionPrefixAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  type: Class
  summary: "Angir XML-navneområde og XML-navneområdeprefikset skal brukes for en beskrivelse format-utvidelsen i en beskrivelse av tjenesten. Denne klassen kan ikke arves."
  remarks: "En beskrivelse format utvidelsen utvider hvordan en tjenestebeskrivelsen genereres for en XML-webtjeneste opprettet ved hjelp av ASP.NET. Nærmere bestemt en beskrivelse format utvidelsen legger til XML-elementer i tjenestebeskrivelsen. Dette er nyttig når en SOAP-filtype er bygd til å kjøre på både klienten og serveren side av en XML-webtjeneste som du vil ha informasjon om SOAP-utvidelser ikke er plassert i tjenestebeskrivelsen. Hvis du legger til informasjon om SOAP-filtypen tjenestebeskrivelsen, kan en klient tolke den må kjøres bestemt SOAP-filtype. Et eksempel på en SOAP-filtype som må kjøre på både klienten og serveren er en kryptering SOAP-filtypen. Hvis en kryptering SOAP-utvidelse kjører på bare-serveren, og den krypterer returverdier før du sender dem tilbake til klienten, må klienten SOAP-utvidelsen for å dekryptere SOAP-meldingen. Ellers kan ikke klienten behandle returverdien.       Gjør følgende for å bygge en beskrivelse format utvidelsen: 1.  Bygg en klasse som er avledet fra <xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.</xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>      2.  Bruk en <xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>for klassen og angi filtype som den beskrivelse format utvidelsen skal kjøres.</xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>      3.  Du kan også bruke en <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute>for klassen, og angi et medlem i klassen som fungerer som et nytt utvidelsespunkt.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute>      4.  Angi XML-navneområdeprefikset for å tilknyttes XML-elementer som genereres av format-utvidelsen for beskrivelse eventuelt legge en XmlFormatExtensionPrefixAttribute for klassen.      5.  Konfigurer service beskrivelse format utvidelsen skal kunne kjøre i det `serviceDescriptionFormatExtensionTypes` delen av konfigurasjonsfilen."
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_2_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_2_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=true)]

      public sealed class XmlFormatExtensionPrefixAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute()
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute&quot;> </xref> klasse."
  syntax:
    content: public XmlFormatExtensionPrefixAttribute ();
    parameters: []
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute(String,String)
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute&quot;> </xref> klasse, angi XML-navneområde og XML-navneområdeprefikset for filtypen tjenesten beskrivelse format."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/31a2fbe2-95e2-473f-8282-_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/31a2fbe2-95e2-473f-8282-_1.vb)]
  syntax:
    content: public XmlFormatExtensionPrefixAttribute (string prefix, string ns);
    parameters:
    - id: prefix
      type: System.String
      description: "XML-navneområdeprefikset som er tilknyttet filtypen tjenesten beskrivelse format."
    - id: ns
      type: System.String
      description: "XML-navneområde som er tilknyttet filtypen tjenesten beskrivelse format."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  id: Namespace
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Henter eller angir XML-navneområde som er tilknyttet filtypen tjenesten beskrivelse format."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/p-system.web.services.co_4_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/p-system.web.services.co_4_1.vb)]
  syntax:
    content: public string Namespace { get; set; }
    return:
      type: System.String
      description: "XML-navneområde som er tilknyttet filtypen tjenesten beskrivelse format."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  id: Prefix
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Henter eller angir XML-navneområdeprefikset som er tilknyttet filtypen tjenesten beskrivelse format."
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/p-system.web.services.co_0_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/p-system.web.services.co_0_1.vb)]
  syntax:
    content: public string Prefix { get; set; }
    return:
      type: System.String
      description: "XML-navneområdeprefikset som er tilknyttet filtypen tjenesten beskrivelse format."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute()
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute(String,String)
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
