### YamlMime:ManagedReference
items:
- uid: System.Configuration.DefaultValidator
  id: DefaultValidator
  children:
  - System.Configuration.DefaultValidator.#ctor
  - System.Configuration.DefaultValidator.CanValidate(System.Type)
  - System.Configuration.DefaultValidator.Validate(System.Object)
  langs:
  - csharp
  name: DefaultValidator
  nameWithType: DefaultValidator
  fullName: System.Configuration.DefaultValidator
  type: Class
  summary: "Gir validering av et objekt. Denne klassen kan ikke arves."
  syntax:
    content: 'public sealed class DefaultValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.DefaultValidator.#ctor
  id: '#ctor'
  parent: System.Configuration.DefaultValidator
  langs:
  - csharp
  name: DefaultValidator()
  nameWithType: DefaultValidator.DefaultValidator()
  fullName: System.Configuration.DefaultValidator.DefaultValidator()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.DefaultValidator&quot;> </xref> klasse."
  syntax:
    content: public DefaultValidator ();
    parameters: []
  overload: System.Configuration.DefaultValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.DefaultValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: DefaultValidator.CanValidate(Type)
  fullName: System.Configuration.DefaultValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Bestemmer om et objekt kan valideres, basert på typen."
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Objekttypen."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>for alle typer valideres."
  overload: System.Configuration.DefaultValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.DefaultValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: DefaultValidator.Validate(Object)
  fullName: System.Configuration.DefaultValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Bestemmer om verdien av et objekt er ugyldig."
  remarks: "Metoden Valider validerer et objekt med en verdi."
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "Verdien for objektet."
  overload: System.Configuration.DefaultValidator.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.DefaultValidator.#ctor
  parent: System.Configuration.DefaultValidator
  isExternal: false
  name: DefaultValidator()
  nameWithType: DefaultValidator.DefaultValidator()
  fullName: System.Configuration.DefaultValidator.DefaultValidator()
- uid: System.Configuration.DefaultValidator.CanValidate(System.Type)
  parent: System.Configuration.DefaultValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: DefaultValidator.CanValidate(Type)
  fullName: System.Configuration.DefaultValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.DefaultValidator.Validate(System.Object)
  parent: System.Configuration.DefaultValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: DefaultValidator.Validate(Object)
  fullName: System.Configuration.DefaultValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.DefaultValidator.#ctor*
  parent: System.Configuration.DefaultValidator
  isExternal: false
  name: DefaultValidator
  nameWithType: DefaultValidator.DefaultValidator
- uid: System.Configuration.DefaultValidator.CanValidate*
  parent: System.Configuration.DefaultValidator
  isExternal: false
  name: CanValidate
  nameWithType: DefaultValidator.CanValidate
- uid: System.Configuration.DefaultValidator.Validate*
  parent: System.Configuration.DefaultValidator
  isExternal: false
  name: Validate
  nameWithType: DefaultValidator.Validate
