### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  id: ICustomIdentityConfiguration
  children:
  - System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  langs:
  - csharp
  name: ICustomIdentityConfiguration
  nameWithType: ICustomIdentityConfiguration
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  type: Interface
  summary: "Definerer metoder som gjør at en klassen for å laste inn egendefinert konfigurasjon."
  remarks: "Klasser som implementerer grensesnittet ICustomIdentityConfiguration kan laste inn egendefinert konfigurasjon fra XML.       Flere Windows Identity Foundation (WIF) klassene implementere grensesnittet ICustomIdentityConfiguration for å gi muligheten til å definere egendefinert konfigurasjon av avledede klasser fra en konfigurasjonsfil. Mange av WIF klassene angi en base implementering av denne metoden Angi standardkonfigurasjonen for objektene de representerer."
  syntax:
    content: public interface ICustomIdentityConfiguration
  implements: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  id: LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  langs:
  - csharp
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Laster inn egendefinert konfigurasjon fra XML. Overstyre denne metoden for å angi egendefinerte håndtering av konfigurasjonen elementer."
  remarks: "Metoden LoadCustomConfiguration kalles av konfigurasjonen-infrastruktur. Når denne metoden kalles, den `nodelist` parameteren inneholder på øverste nivå underordnede elementer for det overordnede elementet som konfigurerer objektklasse i konfigurasjonsfilen. For eksempel en klasse som er hentet fra <xref:System.IdentityModel.Tokens.IssuerNameRegistry>, får de underordnede elementene for den [ \\&lt; issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) element som er sendt av `nodelist` parameteren.</xref:System.IdentityModel.Tokens.IssuerNameRegistry> Den `nodelist` består av bare <xref:System.Xml.XmlElement>objekter.</xref:System.Xml.XmlElement> Hvert enkelt av disse kan ha attributter og underordnede elementer avhengig configuration-skjemaet som er definert for klassen som konfigureres."
  syntax:
    content: public void LoadCustomConfiguration (System.Xml.XmlNodeList nodeList);
    parameters:
    - id: nodeList
      type: System.Xml.XmlNodeList
      description: "XML-nodene som inneholder egendefinert konfigurasjon. Hver node i listen er av typen <xref href=&quot;System.Xml.XmlElement&quot;> </xref>."
  overload: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration
