### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  id: BaseAddressPrefixFilterElement
  children:
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  - System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement
  nameWithType: BaseAddressPrefixFilterElement
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  type: Class
  summary: "Representerer en konfigurasjonselementet som angir en gjennom filter, som gir en metode for å velge riktig IIS bindingene når vert for en [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] programmet i IIS. Denne klassen kan ikke arves."
  remarks: "En prefikset filter leverandør en mekanisme for en tjeneste skal bindes til en bestemt URI. Det mulig å være vert for flere programmer med forskjellige base adresser for den samme planen i samme område.       IIS-nettsteder er beholdere for virtuelle programmer som inneholder virtuelle mapper. Programmet i et område får gjennom én eller flere IIS-binding. IIS-bindinger gir to informasjonselementer: Bindingsprotokollen og bindingsinformasjonen. Bindingen protocol (for eksempel HTTP) definerer skjemaet der kommunikasjon skjer, og bindingsinformasjonen (for eksempel IP-adresse, Port, vertshodeadministrerte) inneholder data som brukes til å få tilgang til området.       IIS støtter angir flere IIS-bindinger per område, som fører til at flere base adresser per skjema. Etter en [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] vertsbaserte under et område-tjenesten kan bare én basisadressen per skjema-bindingen, kan du bruke funksjonen prefikset filter for å velge Obligatorisk basisadressen til vertsbaserte tjenesten.  Innkommende base adressene, angitt av IIS, er filtrert på grunnlag valgfritt prefiks listefilteret.       For eksempel området ditt kan inneholde følgende base adressene ```   http://testl.fabrikam.com/Service.svc   http://test2.fabrikam.com/Service.svc   ``` du kan bruke følgende konfigurasjonsfil til å angi et prefiks filter på appdomain-nivå.      ```   <system.serviceModel>     <serviceHostingEnvironment>        <baseAddressPrefixFilters>           <add prefix=”net.tcp://test1.fabrikam.com:8000”/>           <add prefix=”http://test2.fabrikam.com:9000”/>       </baseAddressPrefixFilters>     </serviceHostingEnvironment>   </system.serviceModel>   ```I dette eksemplet `net.tcp://test1.fabrikam.com:8000` og `http://test2.fabrikam.com:9000` er bare base-adresser for de respektive skjemaene som er tillatt som skal sendes via.       Som standard når prefiks ikke er angitt, skal alle adresser sendes. Angir prefikset fører bare samsvarende basisadressen for fargevalg som skal sendes via.      > [!NOTE] > Filteret støtter ikke noen jokertegn. I tillegg baseAddresses angitt av IIS kan ha adresser som er bundet til andre skjemaene finnes ikke i den `baseAddressPrefixFilters` listen. Disse adressene blir ikke filtrert ut."
  syntax:
    content: 'public sealed class BaseAddressPrefixFilterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement()
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.BaseAddressPrefixFilterElement&quot;> </xref> klasse."
  syntax:
    content: public BaseAddressPrefixFilterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  id: '#ctor(System.Uri)'
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: BaseAddressPrefixFilterElement(Uri)
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.BaseAddressPrefixFilterElement&quot;> </xref> klassen med en bestemt URI."
  syntax:
    content: public BaseAddressPrefixFilterElement (Uri prefix);
    parameters:
    - id: prefix
      type: System.Uri
      description: "Et filter som fører til at tjenesten ikke lytte på alle URI-adresser som begynner med denne bestemte prefiks."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  id: Prefix
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir en prefikset som skal brukes til å samsvare med en del av en basisadressen."
  syntax:
    content: public Uri Prefix { get; set; }
    return:
      type: System.Uri
      description: "URIEN som brukes til å samsvare med en del av en basisadressen."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  langs:
  - csharp
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement()
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement()
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor(System.Uri)
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement(Uri)
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement(Uri)
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
  fullName: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.#ctor*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: BaseAddressPrefixFilterElement
  nameWithType: BaseAddressPrefixFilterElement.BaseAddressPrefixFilterElement
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Prefix*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Prefix
  nameWithType: BaseAddressPrefixFilterElement.Prefix
- uid: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement.Properties*
  parent: System.ServiceModel.Configuration.BaseAddressPrefixFilterElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressPrefixFilterElement.Properties
