### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSaveMode
  id: ConfigurationSaveMode
  children:
  - System.Configuration.ConfigurationSaveMode.Full
  - System.Configuration.ConfigurationSaveMode.Minimal
  - System.Configuration.ConfigurationSaveMode.Modified
  langs:
  - csharp
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
  type: Enum
  summary: "Bestemmer hvilke egenskaper som er skrevet til en konfigurasjonsfil."
  remarks: "ConfigurationSaveMode opplistingsverdiene identifiserer hvilke egenskaper som er skrevet til en konfigurasjonsfil ved kall av <xref:System.Configuration.Configuration.Save%2A>og <xref:System.Configuration.Configuration.SaveAs%2A>metoder.</xref:System.Configuration.Configuration.SaveAs%2A> </xref:System.Configuration.Configuration.Save%2A>"
  syntax:
    content: public enum ConfigurationSaveMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Full
  id: Full
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Full
  nameWithType: ConfigurationSaveMode.Full
  fullName: System.Configuration.ConfigurationSaveMode.Full
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gjør alle egenskaper for å skrive til konfigurasjonsfilen. Dette er nyttig vanligvis til å opprette informasjon konfigurasjonsfiler eller flytting verdier fra en maskin til en annen."
  syntax:
    content: Full
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Minimal
  id: Minimal
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Minimal
  nameWithType: ConfigurationSaveMode.Minimal
  fullName: System.Configuration.ConfigurationSaveMode.Minimal
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gjør bare egenskaper som er forskjellig fra arvede verdier skrives i konfigurasjonsfilen."
  syntax:
    content: Minimal
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Modified
  id: Modified
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Modified
  nameWithType: ConfigurationSaveMode.Modified
  fullName: System.Configuration.ConfigurationSaveMode.Modified
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Årsaker endres bare egenskaper skrives til konfigurasjonsfilen, selv om verdien er lik verdien arvet."
  syntax:
    content: Modified
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationSaveMode.Full
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Full
  nameWithType: ConfigurationSaveMode.Full
  fullName: System.Configuration.ConfigurationSaveMode.Full
- uid: System.Configuration.ConfigurationSaveMode
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
- uid: System.Configuration.ConfigurationSaveMode.Minimal
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Minimal
  nameWithType: ConfigurationSaveMode.Minimal
  fullName: System.Configuration.ConfigurationSaveMode.Minimal
- uid: System.Configuration.ConfigurationSaveMode.Modified
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Modified
  nameWithType: ConfigurationSaveMode.Modified
  fullName: System.Configuration.ConfigurationSaveMode.Modified
