### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier
  id: IApplicationIdentifier
  children:
  - System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  langs:
  - csharp
  name: IApplicationIdentifier
  nameWithType: IApplicationIdentifier
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier
  type: Interface
  summary: "Definerer en ID for programdomener en hurtigbuffer implementering kan bruke til å kommunisere med en vertsmiljøet."
  remarks: "En [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] vertsmiljøet som ASP.NET kan bruke grensesnittet IApplicationIdentifier til å definere strenger som identifiserer individuelle programdomener. Vertsmiljøet implementerer grensesnittet IApplicationIdentifier. Dette grensesnittet deretter er tilgjengelig for <xref:System.Runtime.Caching.ObjectCache>implementeringer via den <xref:System.Runtime.Caching.ObjectCache.Host%2A>egenskapen.</xref:System.Runtime.Caching.ObjectCache.Host%2A> </xref:System.Runtime.Caching.ObjectCache>       En hurtigbuffer implementering bruker denne referansen til å hente en identifikator for programdomenet. I ASP.NET Bruk hurtigbufferen implementeringer programidentifikatoren ikke konstruere identifikatorer for hurtigbufferen ytelsestellere. Dette gir navn for ytelse tellerforekomster som kan skilles mellom programdomener når flere programdomener kjører."
  syntax:
    content: public interface IApplicationIdentifier
  implements: []
  platform:
  - net462
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  id: GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  langs:
  - csharp
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
  type: Method
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Hosting
  summary: "Henter en identifikator for et programdomene."
  remarks: "Metoden GetApplicationId implementeres vanligvis av en [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] vertsmiljøet for å lage et program-ID for en <xref:System.Runtime.Caching.ObjectCache>implementering.</xref:System.Runtime.Caching.ObjectCache> En <xref:System.Runtime.Caching.ObjectCache>implementering bruker denne informasjonen til å identifisere programdomenet som kjører.</xref:System.Runtime.Caching.ObjectCache>       For eksempel i ASP.NET bruker hurtigbufferen en program-ID ikke konstruere identifikatorer for hurtigbufferen ytelsestellere. Hurtigbufferen kaller metoden GetApplicationId som implementeres av vertsmiljøet og verten returnerer IDen. Dette gir navn for ytelse tellerforekomster som kan skilles mellom programdomener når flere programdomener kjører."
  syntax:
    content: public string GetApplicationId ();
    parameters: []
    return:
      type: System.String
      description: "En unik ID for gjeldende programdomenet."
  overload: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId
  nameWithType: IApplicationIdentifier.GetApplicationId
