### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  id: ServiceModelActivationSectionGroup
  children:
  - System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.#ctor
  - System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics
  - System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  - System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe
  - System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp
  langs:
  - csharp
  name: ServiceModelActivationSectionGroup
  nameWithType: ServiceModelActivationSectionGroup
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  type: Class
  summary: "Inneholder konfigurasjonsdelen for SMSvcHost.exe-verktøyet. Denne klassen kan arves."
  remarks: "Denne klassen innkapsler de ulike konfigurasjon elementene for SMSvcHost.exe-verktøyet. Spesielt, representerer den elementene i konfigurasjonen som kan konfigureres i filen SMSvcHost.exe.config."
  syntax:
    content: 'public sealed class ServiceModelActivationSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  langs:
  - csharp
  name: ServiceModelActivationSectionGroup()
  nameWithType: ServiceModelActivationSectionGroup.ServiceModelActivationSectionGroup()
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.ServiceModelActivationSectionGroup()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup&quot;> </xref> klasse."
  syntax:
    content: public ServiceModelActivationSectionGroup ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics
  id: Diagnostics
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  langs:
  - csharp
  name: Diagnostics
  nameWithType: ServiceModelActivationSectionGroup.Diagnostics
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Henter diagnosen konfigurasjonsdelen."
  syntax:
    content: public System.ServiceModel.Activation.Configuration.DiagnosticSection Diagnostics { get; }
    return:
      type: System.ServiceModel.Activation.Configuration.DiagnosticSection
      description: "En <xref href=&quot;System.ServiceModel.Activation.Configuration.DiagnosticSection&quot;> </xref> forekomsten som inneholder diagnostikk konfigurasjonsdelen."
  overload: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  id: GetSectionGroup(System.Configuration.Configuration)
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  langs:
  - csharp
  name: GetSectionGroup(Configuration)
  nameWithType: ServiceModelActivationSectionGroup.GetSectionGroup(Configuration)
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup(Configuration)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Henter den <xref uid=&quot;langword_csharp_System.ServiceModel.Activation&quot; name=&quot;System.ServiceModel.Activation&quot; href=&quot;&quot;> </xref> delen konfigurasjonsgruppen fra den angitte konfigurasjonsfilen."
  remarks: "Du kan bruke denne metoden til å trekke ut konfigurasjonsinnstillingene for aktivering fra en konfigurasjonsfil."
  syntax:
    content: public static System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup GetSectionGroup (System.Configuration.Configuration config);
    parameters:
    - id: config
      type: System.Configuration.Configuration
      description: "En <xref href=&quot;System.Configuration.Configuration&quot;> </xref> som representerer en konfigurasjonsfil."
    return:
      type: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
      description: "En <xref href=&quot;System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup&quot;> </xref> som representerer den <xref uid=&quot;langword_csharp_System.ServiceModel.Activation&quot; name=&quot;System.ServiceModel.Activation&quot; href=&quot;&quot;> </xref> innstillingene i konfigurasjonsfilen."
  overload: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe
  id: NetPipe
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  langs:
  - csharp
  name: NetPipe
  nameWithType: ServiceModelActivationSectionGroup.NetPipe
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Henter konfigurasjonsinnstillingene for NetPipeActivator deling av tjenesten."
  syntax:
    content: public System.ServiceModel.Activation.Configuration.NetPipeSection NetPipe { get; }
    return:
      type: System.ServiceModel.Activation.Configuration.NetPipeSection
      description: "En <xref href=&quot;System.ServiceModel.Activation.Configuration.NetPipeSection&quot;> </xref> som inneholder konfigurasjonsinnstillingene for NetPipeActivator deling av tjenesten."
  overload: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp
  id: NetTcp
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  langs:
  - csharp
  name: NetTcp
  nameWithType: ServiceModelActivationSectionGroup.NetTcp
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Henter konfigurasjonsinnstillingene for NetTcpPortSharing deling av tjenesten."
  syntax:
    content: public System.ServiceModel.Activation.Configuration.NetTcpSection NetTcp { get; }
    return:
      type: System.ServiceModel.Activation.Configuration.NetTcpSection
      description: "En <xref href=&quot;System.ServiceModel.Activation.Configuration.NetTcpSection&quot;> </xref> som inneholder konfigurasjonsinnstillingene for NetTcpPortSharing deling av tjenesten."
  overload: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.#ctor
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: ServiceModelActivationSectionGroup()
  nameWithType: ServiceModelActivationSectionGroup.ServiceModelActivationSectionGroup()
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.ServiceModelActivationSectionGroup()
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: Diagnostics
  nameWithType: ServiceModelActivationSectionGroup.Diagnostics
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: DiagnosticSection
  nameWithType: DiagnosticSection
  fullName: System.ServiceModel.Activation.Configuration.DiagnosticSection
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: GetSectionGroup(Configuration)
  nameWithType: ServiceModelActivationSectionGroup.GetSectionGroup(Configuration)
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup(Configuration)
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: ServiceModelActivationSectionGroup
  nameWithType: ServiceModelActivationSectionGroup
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: NetPipe
  nameWithType: ServiceModelActivationSectionGroup.NetPipe
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: NetPipeSection
  nameWithType: NetPipeSection
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: NetTcp
  nameWithType: ServiceModelActivationSectionGroup.NetTcp
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: NetTcpSection
  nameWithType: NetTcpSection
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.#ctor*
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: ServiceModelActivationSectionGroup
  nameWithType: ServiceModelActivationSectionGroup.ServiceModelActivationSectionGroup
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics*
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: Diagnostics
  nameWithType: ServiceModelActivationSectionGroup.Diagnostics
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup*
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: GetSectionGroup
  nameWithType: ServiceModelActivationSectionGroup.GetSectionGroup
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe*
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: NetPipe
  nameWithType: ServiceModelActivationSectionGroup.NetPipe
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp*
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: NetTcp
  nameWithType: ServiceModelActivationSectionGroup.NetTcp
