### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  id: MessageSecurityOverMsmqElement
  children:
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  langs:
  - csharp
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  type: Class
  summary: "Gjør det mulig å angi egenskapene for sikkerhet på radnivå meldingen på den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> binding."
  syntax:
    content: 'public sealed class MessageSecurityOverMsmqElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: MessageSecurityOverMsmqElement()
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.MessageSecurityOverMsmqElement&quot;> </xref> klasse."
  syntax:
    content: public MessageSecurityOverMsmqElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Angir algoritmen suite som er brukt for sikkerhetsmeldinger på SOAP-nivå."
  remarks: "<xref:System.ServiceModel.Security.SecurityAlgorithmSuite>definerer en rekke algoritmer, for eksempel adresser sammendragsgodkjenning, KeyWrap, signatur, kryptering og KeyDerivation.</xref:System.ServiceModel.Security.SecurityAlgorithmSuite> Denne egenskapen er mest relevante når du arbeider med en plattform som bruker et sett med algoritmer som er forskjellig fra standard. Du bør være klar over sterke og svake sider i de relevante algoritmene når du gjør endringer i denne egenskapen."
  syntax:
    content: public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: "Den <xref href=&quot;System.ServiceModel.Security.SecurityAlgorithmSuite&quot;> </xref> innstillingen for meldinger som sendes via den <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> binding."
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter eller angir den <xref:System.ServiceModel.MessageCredentialType>sikkerhetsinnstillinger for meldinger som sendes via MSMQ-transport.</xref:System.ServiceModel.MessageCredentialType>"
  remarks: "Denne egenskapen kan settes til én av følgende verdier: – Ingen: Dette tillater at tjenesten samvirker med anonyme klienter. Verken tjenesten eller klienten krever legitimasjon.      – Windows: Dette gjør det mulig for SOAP-utvekslinger er godkjent forbindelse med en Windows-legitimasjon. Dette utfører alltid Kerberos-godkjenning.      -UserName: Dette kan tjenesten krever som klienten godkjennes ved hjelp av legitimasjon brukernavn. Denne legitimasjonen må angis ved hjelp av <xref:System.ServiceModel.Description.ClientCredentials>klasse.</xref:System.ServiceModel.Description.ClientCredentials>          > [!NOTE]      >   [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] støtter ikke sender et passord ufullstendig eller avledes nøkler ved hjelp av passord og bruk av slike nøkler for sikkerhet for melding. Som en [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] fremtvinger i exchange er sikret ved UserName-legitimasjoner. Denne modusen krever at Tjenestesertifikatet angis på klientsiden ved hjelp av ClientCredential virkemåte og serviceCertificate.      -Sertifikatet: Dette kan tjenesten krever som klienten godkjenning med et sertifikat. Legitimasjonen for klienten i dette tilfellet må angis ved hjelp av <xref:System.ServiceModel.Description.ClientCredentials>klasse eller ClientCredentials virkemåte.</xref:System.ServiceModel.Description.ClientCredentials> Tjenesten legitimasjonen i dette tilfellet må angis ved hjelp av <xref:System.ServiceModel.Description.ClientCredentials>klasse eller ClientCredentials virkemåte ved å angi serviceCertificate.</xref:System.ServiceModel.Description.ClientCredentials>      -CardSpace: Dette, kan tjenesten krever som klienten godkjennes ved hjelp av en [!INCLUDE[infocard1](~/add/includes/infocard1-md.md)]. ServiceCertiifcate må klargjøres i ClientCredential virkemåte.       Sertifikatet legitimasjonen for den `MessageSecurityOverMsmq` gjelder bare når sikkerhetsmodusen er satt til `Both` eller `Message`."
  syntax:
    content: public System.ServiceModel.MessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.MessageCredentialType
      description: "Den <xref:System.ServiceModel.MessageCredentialType>sikkerhetsinnstillinger for meldinger som sendes via MSMQ-transport.</xref:System.ServiceModel.MessageCredentialType>"
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: MessageSecurityOverMsmqElement()
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
- uid: System.ServiceModel.MessageCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: MessageCredentialType
  nameWithType: MessageCredentialType
  fullName: System.ServiceModel.MessageCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
