### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MembershipSection
  id: MembershipSection
  children:
  - System.Web.Configuration.MembershipSection.#ctor
  - System.Web.Configuration.MembershipSection.DefaultProvider
  - System.Web.Configuration.MembershipSection.HashAlgorithmType
  - System.Web.Configuration.MembershipSection.Properties
  - System.Web.Configuration.MembershipSection.Providers
  - System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  langs:
  - csharp
  name: MembershipSection
  nameWithType: MembershipSection
  fullName: System.Web.Configuration.MembershipSection
  type: Class
  summary: "Definerer konfigurasjonsinnstillinger for å støtte infrastrukturen for å konfigurere og administrere medlemskap detaljer. Denne klassen kan ikke arves."
  remarks: "Klassen MembershipSection gjør det mulig å programmatisk tilgang til og endre den `membership` delen i en konfigurasjonsfil."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `membership` section, which can also be accessed as members of the MembershipSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `membership` section.  \n  \n```  \n<system.web>  \n  <membership   \n    defaultProvider=\"AspNetSqlMembershipProvider\"  \n    userIsOnlineTimeWindow=\"15\">  \n    <providers>  \n      <add   \n        name=\" AspNetSqlMembershipProvider\"  \n        type=\"System.Web.Security.SqlMembershipProvider, System.Web,   \n          Version=2.0.3600.0, Culture=neutral,   \n          PublicKeyToken=b03f5f7f11d50a3a\"  \n        connectionStringName=\"LocalSqlServer\"  \n        passwordAttemptThreshold=\"5\"  \n        passwordAttemptWindow=\"10\"  \n        enablePasswordRetrieval=\"false\"  \n        enablePasswordReset=\"true\"  \n        requiresQuestionAndAnswer=\"true\"  \n        applicationName=\"/\"  \n        requiresUniqueEmail=\"false\"  \n        passwordFormat=\"Hashed\"  \n        description=\"Stores and retrieves membership data from   \n          the local Microsoft SQL Server database.\"  \n      />  \n    </providers>  \n  </membership>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the MembershipSection class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#1](~/add/codesnippet/csharp/t-system.web.configurati_44_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_44_1.vb)]"
  syntax:
    content: 'public sealed class MembershipSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: MembershipSection()
  nameWithType: MembershipSection.MembershipSection()
  fullName: System.Web.Configuration.MembershipSection.MembershipSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.MembershipSection&quot;> </xref> klasse."
  remarks: "Konstruktøren MembershipSection skal ikke brukes direkte fra koden. Kalles av ASP.NET Konfigurasjonssystemet. Du hente en forekomst av den <xref:System.Web.Configuration.MembershipSection>klassen ved hjelp av den <xref:System.Configuration.Configuration.GetSection%2A>metoden.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.MembershipSection>"
  syntax:
    content: public MembershipSection ();
    parameters: []
  overload: System.Web.Configuration.MembershipSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.DefaultProvider
  id: DefaultProvider
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: MembershipSection.DefaultProvider
  fullName: System.Web.Configuration.MembershipSection.DefaultProvider
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir navnet på standardleverandøren som brukes til å behandle roller."
  remarks: "DefaultProvider må samsvare med en navngitt verdi i den `providers` spørsmål for den `membership` delen av konfigurasjonsfilen. En tom streng (`&quot;&quot;`) er ikke en gyldig verdi for egenskapen DefaultProvider."
  example:
  - "The following code example demonstrates how to use the DefaultProvider property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#2](~/add/codesnippet/csharp/p-system.web.configurati_239_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_239_1.vb)]"
  syntax:
    content: public string DefaultProvider { get; set; }
    return:
      type: System.String
      description: "Navnet på en leverandør i <xref:System.Web.Configuration.MembershipSection.Providers*>.</xref:System.Web.Configuration.MembershipSection.Providers*> Standard <xref uid=&quot;langword_csharp_AspNetSqlRoleProvider&quot; name=&quot;AspNetSqlRoleProvider&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.MembershipSection.DefaultProvider*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.HashAlgorithmType
  id: HashAlgorithmType
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: HashAlgorithmType
  nameWithType: MembershipSection.HashAlgorithmType
  fullName: System.Web.Configuration.MembershipSection.HashAlgorithmType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir krypteringstypen som brukes for i sensitiv medlemskapsinformasjon."
  remarks: "Ved kjøretid, medlemskapssystemet binding til riktig hash-algoritmetypen, og deretter bruker denne typen under kryptering av informasjon om gruppemedlemskap. Hvis egenskapen HashAlgorithmType ikke er angitt, standard medlemskapssystemet <xref:System.Web.Configuration.MachineKeySection.Validation%2A>egenskapen i <xref:System.Web.Configuration.MachineKeySection>klasse.</xref:System.Web.Configuration.MachineKeySection> </xref:System.Web.Configuration.MachineKeySection.Validation%2A>"
  example:
  - "The following code example demonstrates how to use the HashAlgorithmType property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#3](~/add/codesnippet/csharp/p-system.web.configurati_135_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_135_1.vb)]"
  syntax:
    content: public string HashAlgorithmType { get; set; }
    return:
      type: System.String
      description: "Hva slags kryptering brukes til å kryptere sensitive medlemskapsinformasjon."
  overload: System.Web.Configuration.MembershipSection.HashAlgorithmType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.Properties
  id: Properties
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: Properties
  nameWithType: MembershipSection.Properties
  fullName: System.Web.Configuration.MembershipSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Web.Configuration.MembershipSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.Providers
  id: Providers
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: Providers
  nameWithType: MembershipSection.Providers
  fullName: System.Web.Configuration.MembershipSection.Providers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter en <xref href=&quot;System.Configuration.ProviderSettingsCollection&quot;> </xref> objekt av <xref href=&quot;System.Configuration.ProviderSettings&quot;> </xref> objekter."
  remarks: "Medlemskap leverandører er komponenter som gir tilgang til medlemskap for et område. Du kan angi medlemskap leverandører i den `providers` spørsmål for den `membership` delen av konfigurasjonsfilen.       Den <xref:System.Web.Configuration.MembershipSection.DefaultProvider%2A>egenskapen inneholder navnet på leverandøren som brukes som standard.</xref:System.Web.Configuration.MembershipSection.DefaultProvider%2A>"
  example:
  - "The following code example demonstrates how to use the Providers property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#5](~/add/codesnippet/csharp/p-system.web.configurati_90_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#5](~/add/codesnippet/visualbasic/p-system.web.configurati_90_1.vb)]"
  syntax:
    content: public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: "En <xref href=&quot;System.Configuration.ProviderSettingsCollection&quot;> </xref> som inneholder leverandørens innstillinger er definert i den <xref uid=&quot;langword_csharp_providers&quot; name=&quot;providers&quot; href=&quot;&quot;> </xref> spørsmål for den <xref uid=&quot;langword_csharp_membership&quot; name=&quot;membership&quot; href=&quot;&quot;> </xref> delen av konfigurasjonsfilen."
  overload: System.Web.Configuration.MembershipSection.Providers*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  id: UserIsOnlineTimeWindow
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: UserIsOnlineTimeWindow
  nameWithType: MembershipSection.UserIsOnlineTimeWindow
  fullName: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir hvor lang tid i minutter, før en bruker er ikke lenger være tilkoblet."
  remarks: "Verdien for egenskapen UserIsOnlineTimeWindow beregnes ved å sammenligne gjeldende klokkeslett minus UserIsOnlineTimeWindow-egenskapen med den <xref:System.Web.Security.MembershipUser.LastActivityDate%2A>verdien for brukeren.</xref:System.Web.Security.MembershipUser.LastActivityDate%2A>"
  example:
  - "The following code example demonstrates how to use the UserIsOnlineTimeWindow property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#4](~/add/codesnippet/csharp/p-system.web.configurati_39_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#4](~/add/codesnippet/visualbasic/p-system.web.configurati_39_1.vb)]"
  syntax:
    content: public TimeSpan UserIsOnlineTimeWindow { get; set; }
    return:
      type: System.TimeSpan
      description: "En lang tid i minutter."
  overload: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.MembershipSection.#ctor
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: MembershipSection()
  nameWithType: MembershipSection.MembershipSection()
  fullName: System.Web.Configuration.MembershipSection.MembershipSection()
- uid: System.Web.Configuration.MembershipSection.DefaultProvider
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: DefaultProvider
  nameWithType: MembershipSection.DefaultProvider
  fullName: System.Web.Configuration.MembershipSection.DefaultProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.MembershipSection.HashAlgorithmType
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: HashAlgorithmType
  nameWithType: MembershipSection.HashAlgorithmType
  fullName: System.Web.Configuration.MembershipSection.HashAlgorithmType
- uid: System.Web.Configuration.MembershipSection.Properties
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Properties
  nameWithType: MembershipSection.Properties
  fullName: System.Web.Configuration.MembershipSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.MembershipSection.Providers
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Providers
  nameWithType: MembershipSection.Providers
  fullName: System.Web.Configuration.MembershipSection.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: UserIsOnlineTimeWindow
  nameWithType: MembershipSection.UserIsOnlineTimeWindow
  fullName: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Web.Configuration.MembershipSection.#ctor*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: MembershipSection
  nameWithType: MembershipSection.MembershipSection
- uid: System.Web.Configuration.MembershipSection.DefaultProvider*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: DefaultProvider
  nameWithType: MembershipSection.DefaultProvider
- uid: System.Web.Configuration.MembershipSection.HashAlgorithmType*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: HashAlgorithmType
  nameWithType: MembershipSection.HashAlgorithmType
- uid: System.Web.Configuration.MembershipSection.Properties*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Properties
  nameWithType: MembershipSection.Properties
- uid: System.Web.Configuration.MembershipSection.Providers*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Providers
  nameWithType: MembershipSection.Providers
- uid: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: UserIsOnlineTimeWindow
  nameWithType: MembershipSection.UserIsOnlineTimeWindow
