### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  id: MachineKeyCompatibilityMode
  children:
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  langs:
  - csharp
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
  type: Enum
  summary: "Angir hvilken kryptering kan brukes."
  remarks: "Du kan bruke verdiene MachineKeyCompatibilityMode når du angir den <xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>egenskapen.</xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>"
  syntax:
    content: public enum MachineKeyCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  id: Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Bruk metodene krypteringsnøkkelen som ble implementert i .NET Framework-versjoner eldre enn versjon 2.0 Service Pack 2. Initialisering av vektorer (IV-er) som brukes for alle krypteringsoperasjoner bortsett fra for å lagre krypterte passord i Medlemsdatabase for ASP.NET."
  syntax:
    content: Framework20SP1
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  id: Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Bruk sterkere kryptering metodene som er tilgjengelige i .NET Framework, versjon 2.0 SP2 eller senere. Initialisering av vektorer (IV-er) som brukes for alle krypteringsoperasjoner."
  syntax:
    content: Framework20SP2
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  id: Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Bruk kryptering metodene som er tilgjengelig i versjon av .NET Framework 4.5 eller senere. Sammenlignet med kryptering metodene som brukes for Framework20SP1 og Framework20SP2, chiffrert tekst som genereres av de kryptografiske for standard er litt mindre og mer motstandsdyktige mot bestemte klasser av teoretiske angrep. De også integrere med [!INCLUDE[win8](~/add/includes/ajax-current-ext-md.md)] mappebehandling for å hente nødvendige krypteringsnøklene. Dette alternativet også mulig å angi egendefinerte kryptografisk for ved å skrive en klasse som er avledet fra <xref href=&quot;System.Security.Cryptography.DataProtector&quot;> </xref> og angi klassenavnet i den &lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt; egenskapen.       Følgende konfigurasjonskrav gjelder for dette alternativet: 1. Hvis den &lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt; egenskapen har en verdi av &lt;xref:System.Web.Configuration.MachineKeySection.ApplicationName%2A?displayProperty=fullName&gt; egenskapen må også ha en verdi.       2. Den &lt;xref:System.Web.Configuration.MachineKeySection.Validation%2A?displayProperty=fullName&gt; attributtet må angi en systemdefinerte validering algoritme (for eksempel MD5, SHA1, HMACSHA256, HMACSHA384 eller HMACSHA512) eller en egendefinert validering algoritme i en klasse som er avledet fra den <xref href=&quot;System.Security.Cryptography.KeyedHashAlgorithm&quot;> </xref> klasse. Verdiene AES og 3DES er ikke validering algoritmer.       Når du angir dette alternativet, skjemaer godkjenningsbilletter er alltid både kryptert og signert, uavhengig av den angitte verdien for den &lt;xref:System.Web.Configuration.FormsAuthenticationConfiguration.Protection%2A?displayProperty=fullName&gt; egenskapen. Vis tilstand er begge kryptert og signert Hvis en side <> </> *> egenskapen <code> true </code> eller <> </> *> egenskapen er <xref:System.Web.UI.ViewStateEncryptionMode.Always>.</xref:System.Web.UI.ViewStateEncryptionMode.Always>"
  syntax:
    content: Framework45
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
