### YamlMime:ManagedReference
items:
- uid: System.Windows.Forms.LayoutSettings
  id: LayoutSettings
  children:
  - System.Windows.Forms.LayoutSettings.#ctor
  - System.Windows.Forms.LayoutSettings.LayoutEngine
  langs:
  - csharp
  name: LayoutSettings
  nameWithType: LayoutSettings
  fullName: System.Windows.Forms.LayoutSettings
  type: Class
  summary: "Inneholder en basisklasse for innsamling av oppsettet skjemaet Egenskaper."
  remarks: "Klassen LayoutSettings er basisklasse for typene som samler de ulike egenskapene som er felles på et bestemt bruker brukergrensesnittet (UI) oppsettet oppsett, for eksempel <xref:System.Windows.Forms.TableLayoutSettings>og <xref:System.Windows.Forms.FlowLayoutSettings>.</xref:System.Windows.Forms.FlowLayoutSettings> </xref:System.Windows.Forms.TableLayoutSettings>"
  example:
  - "The following example shows how to initialize a <xref:System.Windows.Forms.TableLayoutSettings> object for a <xref:System.Windows.Forms.TableLayoutPanel> control. For a full code listing, see [How to: Implement a Custom ToolStripRenderer](~/add/includes/ajax-current-ext-md.md).  \n  \n [!code-vb[System.Windows.Forms.ToolStrip.GridStrip#2](~/add/codesnippet/visualbasic/t-system.windows.forms.l_8_1.vb)]\n [!code-cs[System.Windows.Forms.ToolStrip.GridStrip#2](~/add/codesnippet/csharp/t-system.windows.forms.l_8_1.cs)]"
  syntax:
    content: public abstract class LayoutSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Forms.LayoutSettings.#ctor
  id: '#ctor'
  parent: System.Windows.Forms.LayoutSettings
  langs:
  - csharp
  name: LayoutSettings()
  nameWithType: LayoutSettings.LayoutSettings()
  fullName: System.Windows.Forms.LayoutSettings.LayoutSettings()
  type: Constructor
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Windows.Forms.LayoutSettings&quot;> </xref> klasse."
  syntax:
    content: protected LayoutSettings ();
    parameters: []
  overload: System.Windows.Forms.LayoutSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Forms.LayoutSettings.LayoutEngine
  id: LayoutEngine
  parent: System.Windows.Forms.LayoutSettings
  langs:
  - csharp
  name: LayoutEngine
  nameWithType: LayoutSettings.LayoutEngine
  fullName: System.Windows.Forms.LayoutSettings.LayoutEngine
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Henter den gjeldende tabell oppsettet motoren."
  remarks: 'Den <xref:System.Windows.Forms.TableLayoutSettings.LayoutEngine%2A>egenskapen brukes vanligvis i to kontekster: beholderen som bruker et oppsettet oppsett og underordnede kontroll av beholderen oppsettet skjemaet brukes.</xref:System.Windows.Forms.TableLayoutSettings.LayoutEngine%2A>'
  syntax:
    content: public virtual System.Windows.Forms.Layout.LayoutEngine LayoutEngine { get; }
    return:
      type: System.Windows.Forms.Layout.LayoutEngine
      description: "Den <xref href=&quot;System.Windows.Forms.Layout.LayoutEngine&quot;> </xref> i bruk."
  overload: System.Windows.Forms.LayoutSettings.LayoutEngine*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Windows.Forms.LayoutSettings.#ctor
  parent: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: LayoutSettings()
  nameWithType: LayoutSettings.LayoutSettings()
  fullName: System.Windows.Forms.LayoutSettings.LayoutSettings()
- uid: System.Windows.Forms.LayoutSettings.LayoutEngine
  parent: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: LayoutEngine
  nameWithType: LayoutSettings.LayoutEngine
  fullName: System.Windows.Forms.LayoutSettings.LayoutEngine
- uid: System.Windows.Forms.Layout.LayoutEngine
  parent: System.Windows.Forms.Layout
  isExternal: false
  name: LayoutEngine
  nameWithType: LayoutEngine
  fullName: System.Windows.Forms.Layout.LayoutEngine
- uid: System.Windows.Forms.LayoutSettings.#ctor*
  parent: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: LayoutSettings
  nameWithType: LayoutSettings.LayoutSettings
- uid: System.Windows.Forms.LayoutSettings.LayoutEngine*
  parent: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: LayoutEngine
  nameWithType: LayoutSettings.LayoutEngine
