### YamlMime:ManagedReference
items:
- uid: System.EnvironmentVariableTarget
  id: EnvironmentVariableTarget
  children:
  - System.EnvironmentVariableTarget.Machine
  - System.EnvironmentVariableTarget.Process
  - System.EnvironmentVariableTarget.User
  langs:
  - csharp
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
  type: Enum
  summary: "Angir plasseringen der en miljøvariabel som er lagret eller hente i et sett eller get-operasjon."
  remarks: "Opplistingen EnvironmentVariableTarget brukes av bestemte overlastingene av den <xref:System.Environment.SetEnvironmentVariable%2A>, <xref:System.Environment.GetEnvironmentVariable%2A>, og <xref:System.Environment.GetEnvironmentVariables%2A>metoder for å angi plassering eller mål, der navnet og verdien for en miljøvariabel som er lagret eller hentes.</xref:System.Environment.GetEnvironmentVariables%2A> </xref:System.Environment.GetEnvironmentVariable%2A> </xref:System.Environment.SetEnvironmentVariable%2A>       Målet kan være en av tre steder: miljøblokken knyttet til den gjeldende prosessen, Windows operativsystemet registernøkkelen reservert for miljøvariabler som er knyttet til den gjeldende brukeren eller registernøkkelen som er reservert for miljøvariabler som er knyttet til alle brukere på den lokale maskinen."
  example:
  - "The following code example demonstrates the EnvironmentVariableTarget enumeration in methods that create, modify, and delete environment variables.  \n  \n [!code-cpp[environment.getsetenvar#1](~/add/codesnippet/cpp/t-system.environmentvari_1.cpp)]\n [!code-vb[environment.getsetenvar#1](~/add/codesnippet/visualbasic/t-system.environmentvari_1.vb)]\n [!code-cs[environment.getsetenvar#1](~/add/codesnippet/csharp/t-system.environmentvari_1.cs)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentVariableTarget
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.Machine
  id: Machine
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "Miljøvariabelen lagret eller hentet fra den <xref uid=&quot;langword_csharp_HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; name=&quot;HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; href=&quot;&quot;> </xref> nøkkel i operativsystemet Windows-registret."
  remarks: "Når en bruker oppretter miljøvariabelen i set-operasjon, lagrer operativsystemet miljøvariabelen i registeret, men ikke i den gjeldende prosessen. Hvis en bruker på den lokale maskinen starter en ny prosess, kopierer operativsystemet miljøvariabelen fra registret til denne prosessen.       Når du avslutter prosessen ødelegger operativsystemet miljøvariabelen som pågår. Imidlertid vedvarer miljøvariabelen i registeret før en bruker, fjernes den programmatisk eller ved hjelp av et verktøy for operativsystemet."
  syntax:
    content: Machine
    return:
      type: System.EnvironmentVariableTarget
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.Process
  id: Process
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "Miljøvariabelen lagret eller hentet fra miljøblokken knyttet til gjeldende prosessen."
  remarks: "Brukeren oppretter miljøvariabelen i set-operasjon.       Når du avslutter prosessen ødelegger operativsystemet miljøvariabelen som pågår."
  syntax:
    content: Process
    return:
      type: System.EnvironmentVariableTarget
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.User
  id: User
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "Miljøvariabelen lagret eller hentet fra den <xref uid=&quot;langword_csharp_HKEY_CURRENT_USER\\Environment&quot; name=&quot;HKEY_CURRENT_USER\\Environment&quot; href=&quot;&quot;> </xref> nøkkel i operativsystemet Windows-registret."
  remarks: "Når brukeren oppretter miljøvariabelen i set-operasjon, lagrer operativsystemet miljøvariabelen i registeret, men ikke i den gjeldende prosessen. Hvis brukeren starter en ny prosess, kopierer operativsystemet miljøvariabelen fra registret til denne prosessen.       Når du avslutter prosessen ødelegger operativsystemet miljøvariabelen som pågår. Imidlertid vedvarer miljøvariabelen i registeret før brukeren fjerner programmatisk eller ved hjelp av et verktøy for operativsystemet."
  syntax:
    content: User
    return:
      type: System.EnvironmentVariableTarget
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.EnvironmentVariableTarget.Machine
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
- uid: System.EnvironmentVariableTarget
  parent: System
  isExternal: false
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
- uid: System.EnvironmentVariableTarget.Process
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
- uid: System.EnvironmentVariableTarget.User
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
