### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFrameworks
  id: CompatibleFrameworks
  children:
  - System.Deployment.Application.CompatibleFrameworks.Frameworks
  - System.Deployment.Application.CompatibleFrameworks.SupportUrl
  langs:
  - csharp
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworks
  type: Class
  summary: "Gir informasjon om versjoner av .NET Framework dette programmet kan installere og kjøre."
  syntax:
    content: public class CompatibleFrameworks
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworks.Frameworks
  id: Frameworks
  parent: System.Deployment.Application.CompatibleFrameworks
  langs:
  - csharp
  name: Frameworks
  nameWithType: CompatibleFrameworks.Frameworks
  fullName: System.Deployment.Application.CompatibleFrameworks.Frameworks
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter en liste over .NET Framework-versjonene dette programmet kan installere og kjøre."
  syntax:
    content: public System.Collections.Generic.IList<System.Deployment.Application.CompatibleFramework> Frameworks { get; }
    return:
      type: System.Collections.Generic.IList{System.Deployment.Application.CompatibleFramework}
      description: "En liste over <xref href=&quot;System.Deployment.Application.CompatibleFramework&quot;> </xref> objekter som angir .NET Framework-versjonene dette programmet kan installere og kjøre."
  overload: System.Deployment.Application.CompatibleFrameworks.Frameworks*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworks.SupportUrl
  id: SupportUrl
  parent: System.Deployment.Application.CompatibleFrameworks
  langs:
  - csharp
  name: SupportUrl
  nameWithType: CompatibleFrameworks.SupportUrl
  fullName: System.Deployment.Application.CompatibleFrameworks.SupportUrl
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Henter en <xref:System.Uri>som gir brukeren instruksjonene for å installere en versjon av .NET Framework dette programmet kan installere og kjøre.</xref:System.Uri>"
  remarks: "Egenskapen SupportUrl inneholder <xref:System.Uri>som kan vises i den `SupportUrl` attributt i den [ \\&lt; compatibleFrameworks\\&gt; Elementet](../Topic/%3CcompatibleFrameworks%3E%20Element%20\\(ClickOnce%20Deployment\\).md).</xref:System.Uri>"
  syntax:
    content: public Uri SupportUrl { get; }
    return:
      type: System.Uri
      description: "En <xref:System.Uri>som gir brukeren instruksjonene for å installere en versjon av .NET Framework dette programmet kan installere og kjøre.</xref:System.Uri>"
  overload: System.Deployment.Application.CompatibleFrameworks.SupportUrl*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Application.CompatibleFrameworks.Frameworks
  parent: System.Deployment.Application.CompatibleFrameworks
  isExternal: false
  name: Frameworks
  nameWithType: CompatibleFrameworks.Frameworks
  fullName: System.Deployment.Application.CompatibleFrameworks.Frameworks
- uid: System.Collections.Generic.IList{System.Deployment.Application.CompatibleFramework}
  parent: System.Collections.Generic
  isExternal: true
  name: IList<CompatibleFramework>
  nameWithType: IList<CompatibleFramework>
  fullName: System.Collections.Generic.IList<System.Deployment.Application.CompatibleFramework>
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: IList<System.Deployment.Application.CompatibleFramework>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Deployment.Application.CompatibleFramework
    name: CompatibleFramework
    nameWithType: CompatibleFramework
    fullName: CompatibleFramework
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Deployment.Application.CompatibleFrameworks.SupportUrl
  parent: System.Deployment.Application.CompatibleFrameworks
  isExternal: false
  name: SupportUrl
  nameWithType: CompatibleFrameworks.SupportUrl
  fullName: System.Deployment.Application.CompatibleFrameworks.SupportUrl
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Deployment.Application.CompatibleFrameworks.Frameworks*
  parent: System.Deployment.Application.CompatibleFrameworks
  isExternal: false
  name: Frameworks
  nameWithType: CompatibleFrameworks.Frameworks
- uid: System.Deployment.Application.CompatibleFrameworks.SupportUrl*
  parent: System.Deployment.Application.CompatibleFrameworks
  isExternal: false
  name: SupportUrl
  nameWithType: CompatibleFrameworks.SupportUrl
