### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSerializeAsAttribute
  id: SettingsSerializeAsAttribute
  children:
  - System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  - System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  langs:
  - csharp
  name: SettingsSerializeAsAttribute
  nameWithType: SettingsSerializeAsAttribute
  fullName: System.Configuration.SettingsSerializeAsAttribute
  type: Class
  summary: "Angir serialisering mekanisme som skal bruke innstillinger for leverandøren. Denne klassen kan ikke arves."
  remarks: "For Innstillingsleverandør støtter ofte mer enn én av .NET Framework standard serialisering skjemaene. Disse skjemaene er beskrevet av det <xref:System.Configuration.SettingsSerializeAs>opplisting med ren tekst, XML og binær Serialiseringsfeil.</xref:System.Configuration.SettingsSerializeAs> En leverandør støtter i tillegg eventuelt en egendefinert serialisering-skjemaet.       Med SettingsSerializeAsAttribute, kan du angi hvilken serialisering mekanisme som skal brukes for en gitt applikasjon klasse eller en egenskap. Dette attributtet anses som en forespørsel til leverandøren av innstillinger. Det kan bli ignorert eller føre til en feil hvis leverandøren eller individuelle egenskapstypen ikke støtter det angitte serialisering-skjemaet. Hvis dette attributtet ikke finnes, gir leverandøren vanligvis en serialisering standardmekanismen, vanligvis ren tekst.       Selv om innstillingene-leverandøren kan gir mulighet for å endre dynamisk serialisering mekanisme under kjøring, er dette ikke en vanlig egenskap."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsSerializeAsAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  id: '#ctor(System.Configuration.SettingsSerializeAs)'
  parent: System.Configuration.SettingsSerializeAsAttribute
  langs:
  - csharp
  name: SettingsSerializeAsAttribute(SettingsSerializeAs)
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  fullName: System.Configuration.SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en forekomst av den <xref href=&quot;System.Configuration.SettingsSerializeAsAttribute&quot;> </xref> klasse."
  remarks: "Hvis innstillingene-leverandør eller en type egenskapen som skal konverteres ikke støtter serialisering-skjemaet som er angitt av den `serializeAs` parameteren operasjonen har én av følgende resultat:-innstillinger-leverandøren kan Ignorer attributtet og bruke det standard serialisering skjemaet.      Prosess-serialisering kan mislykkes uten svar. Egenskapen for programmet innstillingene vil ikke opprettholdt.      -Kan oppstå et unntak under serialisering."
  syntax:
    content: public SettingsSerializeAsAttribute (System.Configuration.SettingsSerializeAs serializeAs);
    parameters:
    - id: serializeAs
      type: System.Configuration.SettingsSerializeAs
      description: "En <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> listes opp verdi som angir serialisering-skjemaet."
  overload: System.Configuration.SettingsSerializeAsAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  id: SerializeAs
  parent: System.Configuration.SettingsSerializeAsAttribute
  langs:
  - csharp
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
  fullName: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Henter den <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> opplistingsverdi som angir serialisering-skjemaet."
  remarks: "Denne egenskapen er angitt i den <xref:System.Configuration.SettingsSerializeAsAttribute.%23ctor%2A>konstruktør.</xref:System.Configuration.SettingsSerializeAsAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SettingsSerializeAs SerializeAs { get; }
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "En <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> listes opp verdi som angir serialisering-skjemaet."
  overload: System.Configuration.SettingsSerializeAsAttribute.SerializeAs*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SettingsSerializeAsAttribute(SettingsSerializeAs)
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  fullName: System.Configuration.SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
- uid: System.Configuration.SettingsSerializeAs
  parent: System.Configuration
  isExternal: false
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
  fullName: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor*
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SettingsSerializeAsAttribute
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs*
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
