### YamlMime:ManagedReference
items:
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute
  id: NoSettingsVersionUpgradeAttribute
  children:
  - System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute
  type: Class
  summary: "Angir at en Innstillingsleverandør av bør deaktivere logic som henter aktiveres når en applikasjon oppgradering er registrert. Denne klassen kan ikke arves."
  remarks: "Hvis du vil opprette en fullstendig program Innstillingsleverandør som støtter programmet versjonskontroll leverandøren må implementere den <xref:System.Configuration.IApplicationSettingsProvider>grensesnittet.</xref:System.Configuration.IApplicationSettingsProvider> Én av medlemmer i dette grensesnittet i <xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A>,-metoden til å varsle leverandøren at en ny versjon av programmet er installert.</xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A> Svar er leverandøren forventet å utføre en handling, vanligvis overfører forbi applikasjonsinnstillingene.       NoSettingsVersionUpgradeAttribute informerer leverandøren for å undertrykke oppgradering logikken knyttet til gjeldende innstillinger for klassen. Verdien for den forrige versjonen av denne egenskapsgruppen bør derfor ikke bli overført til den nye installasjonen.      > [!NOTE] > Dette attributtet kan bare brukes på enkelt program-innstillinger."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class NoSettingsVersionUpgradeAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.NoSettingsVersionUpgradeAttribute&quot;> </xref> klasse."
  remarks: "Dette er levert av kompilatoren Standardkonstruktøren for <xref:System.Configuration.NoSettingsVersionUpgradeAttribute>klasse.</xref:System.Configuration.NoSettingsVersionUpgradeAttribute>"
  syntax:
    content: public NoSettingsVersionUpgradeAttribute ();
    parameters: []
  overload: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute
