### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupDescriptionAttribute
  id: SettingsGroupDescriptionAttribute
  children:
  - System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute
  fullName: System.Configuration.SettingsGroupDescriptionAttribute
  type: Class
  summary: "Inneholder en streng som beskriver en programproxygruppen for innstillinger for egenskapen. Denne klassen kan arves."
  remarks: "En applikasjon innstillinger klasse som er avledet fra <xref:System.Configuration.ApplicationSettingsBase>, definerer én eller flere egenskaper som hører til samme programproxygruppen for egenskapen.</xref:System.Configuration.ApplicationSettingsBase> SettingsGroupDescriptionAttribute er et valgfritt attributt som du kan bruke til å angi beskrivende tekst for en innstillinger egenskapsgruppe. Denne teksten skal hjelpe både utformingen verktøy og administrasjonsverktøy for kjøring i identifiserer og som beskriver gruppen tilknyttede egenskapen.      > [!NOTE] > Dette attributtet kan bare brukes på wrapper klassen nivå."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupDescriptionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.SettingsGroupDescriptionAttribute&quot;> </xref> klasse."
  remarks: "Selv om teoretiske maksimumslengden på den `description` parameteren er begrenset av øvre grense i en <xref:System.Int32>, praktisk begrenser henhold brukbarheten og kvoten begrensningene av leverandøren innstillinger blir mye mindre.</xref:System.Int32>"
  syntax:
    content: public SettingsGroupDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: "En <xref:System.String>som inneholder den beskrivende teksten for innstillinger programproxygruppen.</xref:System.String>"
  overload: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Beskrivende tekst for programproxygruppen for innstillinger egenskaper."
  remarks: "Beskrivelse egenskapsverdien er angitt i den <xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A>konstruktør.</xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A>"
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "En <xref:System.String>som inneholder den beskrivende teksten for innstillinger programproxygruppen.</xref:System.String>"
  overload: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
