### YamlMime:ManagedReference
items:
- uid: System.Configuration.IgnoreSectionHandler
  id: IgnoreSectionHandler
  children:
  - System.Configuration.IgnoreSectionHandler.#ctor
  - System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: IgnoreSectionHandler
  nameWithType: IgnoreSectionHandler
  fullName: System.Configuration.IgnoreSectionHandler
  type: Class
  summary: "Inneholder en definisjon for eldre delen-behandlingsprogram for konfigurasjonsdeler ikke er behandlet av det <xref href=&quot;System.Configuration&quot;> </xref> typer."
  remarks: "Konfigurasjonssystemet fullstendig analyserer konfigurasjonsfiler for å innhente informasjon om konfigurasjon og oppstår unntak når det oppstår konfigurasjonsdeler som ikke har en tilsvarende oppføring i den `configSections` delen.       For disse delene ble ikke håndtert av den <xref:System.Configuration>typer, den nye wrapper typen <xref:System.Configuration.IgnoreSection>er angitt.</xref:System.Configuration.IgnoreSection> </xref:System.Configuration> Dette er å hindre at konfigurasjonsfilen – analyse av unntak.       Eldre formålene finnes også i IgnoreSectionHandler."
  syntax:
    content: 'public class IgnoreSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.IgnoreSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.IgnoreSectionHandler
  langs:
  - csharp
  name: IgnoreSectionHandler()
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler()
  fullName: System.Configuration.IgnoreSectionHandler.IgnoreSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.IgnoreSectionHandler&quot;> </xref> klasse."
  syntax:
    content: public IgnoreSectionHandler ();
    parameters: []
  overload: System.Configuration.IgnoreSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IgnoreSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: IgnoreSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IgnoreSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Oppretter en ny konfigurasjon-behandling og legger angitte konfigurasjonsobjektet i delen behandlingsprogrammet-samlingen."
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Konfigurasjonsinnstillingene i en tilsvarende overordnet konfigurasjonsdelen."
    - id: configContext
      type: System.Object
      description: "Den virtuelle banen som beregner i konfigurasjonsdelen konfigurasjonsverdier. Vanligvis denne parameteren er reservert og <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
    - id: section
      type: System.Xml.XmlNode
      description: "En <xref href=&quot;System.Xml.XmlNode&quot;> </xref> som inneholder konfigurasjonsinformasjonen som skal behandles. Gir direkte tilgang til XML-innholdet i konfigurasjonsdelen."
    return:
      type: System.Object
      description: "Opprettet behandlingsprogram konfigurasjonsobjektet."
  overload: System.Configuration.IgnoreSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.IgnoreSectionHandler.#ctor
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: IgnoreSectionHandler()
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler()
  fullName: System.Configuration.IgnoreSectionHandler.IgnoreSectionHandler()
- uid: System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: IgnoreSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IgnoreSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.IgnoreSectionHandler.#ctor*
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: IgnoreSectionHandler
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler
- uid: System.Configuration.IgnoreSectionHandler.Create*
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: Create
  nameWithType: IgnoreSectionHandler.Create
