### YamlMime:ManagedReference
items:
- uid: System.AddIn.Hosting.AddInEnvironment
  id: AddInEnvironment
  children:
  - System.AddIn.Hosting.AddInEnvironment.#ctor(System.AppDomain)
  - System.AddIn.Hosting.AddInEnvironment.Process
  langs:
  - csharp
  name: AddInEnvironment
  nameWithType: AddInEnvironment
  fullName: System.AddIn.Hosting.AddInEnvironment
  type: Class
  summary: "Gir tilgang til programdomenet og prosessen med et tillegg."
  remarks: "Bruk denne klassen å laste inn tillegg i en ønsket miljøet ditt, som kan være én av følgende:-en eksisterende programdomenet som du har den <xref:System.AppDomain>objektet.</xref:System.AppDomain>      – En programdomenet som ble generert automatisk for å aktivere en tilleggsprogrammet.      – En eksisterende ekstern prosess.       For å få AddInEnvironment-objekt for et tillegg, sendes det tillegget programdomenet til AddInEnvironment klassen konstruktøren. Du kan også bruke den <xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>for den <xref:System.AddIn.Hosting.AddInController>klassen for å hente den tillegget AddInEnvironment objektet.</xref:System.AddIn.Hosting.AddInController> </xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>       Når du skaffer deg AddInEnvironment-objekt, kan du gjøre følgende:-sendes AddInEnvironment objektet til den riktige <xref:System.AddIn.Hosting.AddInToken.Activate%2A>metoden overbelastning.</xref:System.AddIn.Hosting.AddInToken.Activate%2A> Tillegget aktiveres i programdomenet og prosessen som representeres av AddInEnvironment-objektet.      -Bruk av <xref:System.AddIn.Hosting.AddInEnvironment.Process%2A>til å hente en <xref:System.AddIn.Hosting.AddInProcess>objektet.</xref:System.AddIn.Hosting.AddInProcess> </xref:System.AddIn.Hosting.AddInEnvironment.Process%2A> Sende objektet til den riktige <xref:System.AddIn.Hosting.AddInToken.Activate%2A>metoden overbelastning.</xref:System.AddIn.Hosting.AddInToken.Activate%2A> Tillegget aktiveres i prosessen som representeres av den <xref:System.AddIn.Hosting.AddInProcess>objekt, men i en ny programdomenet.</xref:System.AddIn.Hosting.AddInProcess>"
  syntax:
    content: public sealed class AddInEnvironment
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.AddIn.Hosting.AddInEnvironment.#ctor(System.AppDomain)
  id: '#ctor(System.AppDomain)'
  parent: System.AddIn.Hosting.AddInEnvironment
  langs:
  - csharp
  name: AddInEnvironment(AppDomain)
  nameWithType: AddInEnvironment.AddInEnvironment(AppDomain)
  fullName: System.AddIn.Hosting.AddInEnvironment.AddInEnvironment(AppDomain)
  type: Constructor
  assemblies:
  - System.AddIn
  namespace: System.AddIn.Hosting
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.AddIn.Hosting.AddInEnvironment&quot;> </xref> klasse."
  remarks: "Hvis du har tilgang til programdomenet som inneholder tillegget må, kan du bruke denne konstruktøren ikke hente tillegget <xref:System.AddIn.Hosting.AddInEnvironment>objektet.</xref:System.AddIn.Hosting.AddInEnvironment> Ellers kan du bruke den <xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>for den <xref:System.AddIn.Hosting.AddInController>klassen for å hente den <xref:System.AddIn.Hosting.AddInEnvironment>objektet.</xref:System.AddIn.Hosting.AddInEnvironment> </xref:System.AddIn.Hosting.AddInController> </xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>"
  syntax:
    content: public AddInEnvironment (AppDomain appDomain);
    parameters:
    - id: appDomain
      type: System.AppDomain
      description: "Programdomenet som inneholder tilleggsprogrammet."
  overload: System.AddIn.Hosting.AddInEnvironment.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>appDomain</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Security.SecurityException
    commentId: T:System.Security.SecurityException
    description: "Fullstendig klarering tillatelse er etterspørsel etter. En oppringer i kallet kjeden har ikke tilstrekkelige rettigheter."
  platform:
  - net462
- uid: System.AddIn.Hosting.AddInEnvironment.Process
  id: Process
  parent: System.AddIn.Hosting.AddInEnvironment
  langs:
  - csharp
  name: Process
  nameWithType: AddInEnvironment.Process
  fullName: System.AddIn.Hosting.AddInEnvironment.Process
  type: Property
  assemblies:
  - System.AddIn
  namespace: System.AddIn.Hosting
  summary: "Henter den <xref href=&quot;System.AddIn.Hosting.AddInProcess&quot;> </xref> objektet som representerer prosessen som tillegget kjører."
  remarks: "Du kan bruke denne egenskapen til å aktivere flere tillegg i den samme prosessen, men i forskjellige domener.       Sende det <xref:System.AddIn.Hosting.AddInProcess>objektet innhentet med denne egenskapen til det aktuelle <xref:System.AddIn.Hosting.AddInToken.Activate%2A>metoden overbelastning.</xref:System.AddIn.Hosting.AddInToken.Activate%2A> </xref:System.AddIn.Hosting.AddInProcess>       Hvis du vil aktivere dem. i det samme domenet i en ekstern prosess må du sende den <xref:System.AddIn.Hosting.AddInEnvironment>objekt direkte til det <xref:System.AddIn.Hosting.AddInToken.Activate%60%601%28System.AddIn.Hosting.AddInEnvironment%29?displayProperty=fullName>metoden overbelastning.</xref:System.AddIn.Hosting.AddInToken.Activate%60%601%28System.AddIn.Hosting.AddInEnvironment%29?displayProperty=fullName> </xref:System.AddIn.Hosting.AddInEnvironment>"
  syntax:
    content: public System.AddIn.Hosting.AddInProcess Process { get; }
    return:
      type: System.AddIn.Hosting.AddInProcess
      description: "Prosessen som tillegget kjører."
  overload: System.AddIn.Hosting.AddInEnvironment.Process*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Security.SecurityException
  isExternal: true
  name: System.Security.SecurityException
- uid: System.AddIn.Hosting.AddInEnvironment.#ctor(System.AppDomain)
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: AddInEnvironment(AppDomain)
  nameWithType: AddInEnvironment.AddInEnvironment(AppDomain)
  fullName: System.AddIn.Hosting.AddInEnvironment.AddInEnvironment(AppDomain)
- uid: System.AppDomain
  parent: System
  isExternal: false
  name: AppDomain
  nameWithType: AppDomain
  fullName: System.AppDomain
- uid: System.AddIn.Hosting.AddInEnvironment.Process
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: Process
  nameWithType: AddInEnvironment.Process
  fullName: System.AddIn.Hosting.AddInEnvironment.Process
- uid: System.AddIn.Hosting.AddInProcess
  parent: System.AddIn.Hosting
  isExternal: false
  name: AddInProcess
  nameWithType: AddInProcess
  fullName: System.AddIn.Hosting.AddInProcess
- uid: System.AddIn.Hosting.AddInEnvironment.#ctor*
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: AddInEnvironment
  nameWithType: AddInEnvironment.AddInEnvironment
- uid: System.AddIn.Hosting.AddInEnvironment.Process*
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: Process
  nameWithType: AddInEnvironment.Process
