### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.IServerWebConfig
  id: IServerWebConfig
  children:
  - System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: IServerWebConfig
  nameWithType: IServerWebConfig
  fullName: System.EnterpriseServices.Internal.IServerWebConfig
  type: Interface
  summary: "Oppretter en Web.config-filen for en SOAP-aktiverte COM +-programmet og legger til komponenten oppføringer i filen for COM-grensesnitt som publiseres i applikasjonen."
  remarks: "Grensesnittet IServerWebConfig implementeres bare ved den <xref:System.EnterpriseServices.Internal.ServerWebConfig>klasse og brukes bare i .NET Framework-infrastruktur.</xref:System.EnterpriseServices.Internal.ServerWebConfig> I stedet for implementerer dette grensesnittet eller starte et IServerWebConfig grensesnittet objekt, bruker du <xref:System.EnterpriseServices.Internal.Publish>klasse som implementerer den <xref:System.EnterpriseServices.Internal.IComSoapPublisher>grensesnittet.</xref:System.EnterpriseServices.Internal.IComSoapPublisher> </xref:System.EnterpriseServices.Internal.Publish>       IServerWebConfig er brukt internt av .NET Framework. Du trenger ikke å bruke den direkte i koden."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("6261e4b5-572a-4142-a2f9-1fe1a0c97097")]

      public interface IServerWebConfig
  implements: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Legger til XML-elementer i Web.config-filen for et COM-grensesnitt som er publisert i SOAP-aktiverte COM +-programmet."
  remarks: "Se den <xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A>metode for implementeringsdetaljene.</xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A> Men du trenger ikke å kalle `AddElement` metoden direkte."
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string Mode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Banen for den eksisterende Web.config-filen."
    - id: AssemblyName
      type: System.String
      description: "Navnet på samlingen som inneholder typen som legges til."
    - id: TypeName
      type: System.String
      description: "Navnet på typen som legges til."
    - id: ProgId
      type: System.String
      description: "Program-IDen for typen som legges til."
    - id: Mode
      type: System.String
      description: "En strengkonstant som tilsvarer navnet på et medlem fra den <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> opplisting som angir hvordan et kjent objekt er aktivert."
    - id: Error
      type: System.String
      description: "Du kan skrive en feilmelding som en streng."
  overload: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Oppretter en Web.config-filen for en SOAP-aktiverte COM +-programmet slik at filen er klar til å ha XML-elementer som er lagt til for COM-grensesnitt publiseres."
  remarks: "Se den <xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A>metode for implementeringsdetaljene.</xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A> Men du trenger ikke å kalle `Create` direkte."
  syntax:
    content: public void Create (string FilePath, string FileRootName, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "Mappen der du vil opprette konfigurasjonsfil."
    - id: FileRootName
      type: System.String
      description: "Strengverdien som filtypen config kan legges til (for eksempel Web for Web.config)."
    - id: Error
      type: System.String
      description: "Du kan skrive en feilmelding som en streng."
  overload: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: IServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create
  nameWithType: IServerWebConfig.Create
