### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.EndpointCollectionElement
  id: EndpointCollectionElement
  children:
  - System.ServiceModel.Configuration.EndpointCollectionElement.#ctor
  - System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints
  - System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey(System.String)
  - System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  - System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType
  - System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement
  - System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  langs:
  - csharp
  name: EndpointCollectionElement
  nameWithType: EndpointCollectionElement
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement
  type: Class
  summary: "Behandler en samling av tjenesten endepunkt i en konfigurasjonsfil."
  syntax:
    content: 'public abstract class EndpointCollectionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: EndpointCollectionElement()
  nameWithType: EndpointCollectionElement.EndpointCollectionElement()
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Oppretter en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.EndpointCollectionElement&quot;> </xref> klasse."
  syntax:
    content: protected EndpointCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints
  id: ConfiguredEndpoints
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: ConfiguredEndpoints
  nameWithType: EndpointCollectionElement.ConfiguredEndpoints
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Når implementert i en avledet klasse, inneholder en skrivebeskyttet samling <xref href=&quot;System.ServiceModel.Configuration.StandardEndpointElement&quot;> </xref> egenskaper og metoder."
  syntax:
    content: public abstract System.Collections.ObjectModel.ReadOnlyCollection<System.ServiceModel.Configuration.StandardEndpointElement> ConfiguredEndpoints { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.ServiceModel.Configuration.StandardEndpointElement}
      description: "En skrivebeskyttet samling <xref href=&quot;System.ServiceModel.Configuration.StandardEndpointElement&quot;> </xref> egenskaper og metoder."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey(System.String)
  id: ContainsKey(System.String)
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: ContainsKey(String)
  nameWithType: EndpointCollectionElement.ContainsKey(String)
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey(String)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Bestemmer om tjenesteelementet i en konfigurasjonsfilen inneholder et endpoint-element med samme navn som den angitte strengen."
  syntax:
    content: public abstract bool ContainsKey (string name);
    parameters:
    - id: name
      type: System.String
      description: "Navnet på nøkkel i en nøkkel/verdi-par som representerer en endpoint elementnavnet og verdien."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis den angitte strengen inneholder et angitt elementnavn. Ellers<xref uid=&quot;langword_csharp_false.&quot; name=&quot;false.&quot; href=&quot;&quot;></xref>"
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  id: EndpointName
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: EndpointName
  nameWithType: EndpointCollectionElement.EndpointName
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Når implementert i en avledet klasse, henter verdien for name-attributtet for et tjenesten endpoint-element."
  syntax:
    content: public string EndpointName { get; }
    return:
      type: System.String
      description: "Verdien for attributtet name i en service endpoint-elementet."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType
  id: EndpointType
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: EndpointType
  nameWithType: EndpointCollectionElement.EndpointType
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter typen serviceendepunktet når implementert i en avledet klasse."
  syntax:
    content: public abstract Type EndpointType { get; }
    return:
      type: System.Type
      description: "Et sluttpunkt tjenestetypen."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement
  id: GetDefaultStandardEndpointElement
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: GetDefaultStandardEndpointElement()
  nameWithType: EndpointCollectionElement.GetDefaultStandardEndpointElement()
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Når implementert i en avledet klasse, tilbakestiller <xref href=&quot;System.ServiceModel.Configuration.StandardEndpointElement&quot;> </xref>."
  syntax:
    content: protected abstract System.ServiceModel.Configuration.StandardEndpointElement GetDefaultStandardEndpointElement ();
    parameters: []
    return:
      type: System.ServiceModel.Configuration.StandardEndpointElement
      description: "Et tjenesten standard endpoint modellelement."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  id: TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: TryAdd(String,ServiceEndpoint,Configuration)
  nameWithType: EndpointCollectionElement.TryAdd(String,ServiceEndpoint,Configuration)
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd(String,ServiceEndpoint,Configuration)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Når implementert i en avledet klasse, legger du til det angitte endepunktet i samlingen av tjenesten endepunkt i en konfigurasjonsfil."
  syntax:
    content: protected abstract bool TryAdd (string name, System.ServiceModel.Description.ServiceEndpoint endpoint, System.Configuration.Configuration config);
    parameters:
    - id: name
      type: System.String
      description: "Navnet på endepunktet for tjenesten som inneholder endpoint-samlingen."
    - id: endpoint
      type: System.ServiceModel.Description.ServiceEndpoint
      description: "Elementet tjenesten endepunkt som skal legges til i samlingen."
    - id: config
      type: System.Configuration.Configuration
      description: "Konfigurasjonsfilen som mottar serviceendepunktet."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis endepunktet er lagt til i samlingen i konfigurasjonsfilen; Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointCollectionElement()
  nameWithType: EndpointCollectionElement.EndpointCollectionElement()
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointCollectionElement()
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: ConfiguredEndpoints
  nameWithType: EndpointCollectionElement.ConfiguredEndpoints
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.ServiceModel.Configuration.StandardEndpointElement}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<StandardEndpointElement>
  nameWithType: ReadOnlyCollection<StandardEndpointElement>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.ServiceModel.Configuration.StandardEndpointElement>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.ServiceModel.Configuration.StandardEndpointElement>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Configuration.StandardEndpointElement
    name: StandardEndpointElement
    nameWithType: StandardEndpointElement
    fullName: StandardEndpointElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey(System.String)
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: ContainsKey(String)
  nameWithType: EndpointCollectionElement.ContainsKey(String)
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointName
  nameWithType: EndpointCollectionElement.EndpointName
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointType
  nameWithType: EndpointCollectionElement.EndpointType
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: GetDefaultStandardEndpointElement()
  nameWithType: EndpointCollectionElement.GetDefaultStandardEndpointElement()
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement()
- uid: System.ServiceModel.Configuration.StandardEndpointElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardEndpointElement
  nameWithType: StandardEndpointElement
  fullName: System.ServiceModel.Configuration.StandardEndpointElement
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: TryAdd(String,ServiceEndpoint,Configuration)
  nameWithType: EndpointCollectionElement.TryAdd(String,ServiceEndpoint,Configuration)
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd(String,ServiceEndpoint,Configuration)
- uid: System.ServiceModel.Description.ServiceEndpoint
  parent: System.ServiceModel.Description
  isExternal: true
  name: ServiceEndpoint
  nameWithType: ServiceEndpoint
  fullName: System.ServiceModel.Description.ServiceEndpoint
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointCollectionElement
  nameWithType: EndpointCollectionElement.EndpointCollectionElement
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: ConfiguredEndpoints
  nameWithType: EndpointCollectionElement.ConfiguredEndpoints
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: ContainsKey
  nameWithType: EndpointCollectionElement.ContainsKey
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointName
  nameWithType: EndpointCollectionElement.EndpointName
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointType
  nameWithType: EndpointCollectionElement.EndpointType
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: GetDefaultStandardEndpointElement
  nameWithType: EndpointCollectionElement.GetDefaultStandardEndpointElement
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: TryAdd
  nameWithType: EndpointCollectionElement.TryAdd
