### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  id: AssemblyVersionCompatibility
  children:
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  langs:
  - csharp
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
  type: Enum
  summary: "Definerer forskjellige typer versjonskompatibiliteten for samlingen. Denne funksjonen er ikke tilgjengelig i versjon 1.0 av .NET Framework."
  remarks: "`AssemblyVersionCompatibility`definerer kompatibilitet av en samling med andre versjoner av samme samling, som angir om den ikke kan kjøre side-ved-side med andre versjoner (for eksempel på grunn av konflikter over en driver).       Hvis ingen kompatibilitet er angitt, er kompatibel med side-ved-side i alle omfang i en samling.       En samling kan ikke være mer spesifikke med hensyn til nøyaktig som tidligere versjoner det ikke er kompatibel med side-ved-side med. Derfor hvis den `AssemblyVersionCompatibility` er angitt, betyr det samlingen er ikke side-ved-side med alle vet versjoner. Hvis ikke angitt, kommer den side-ved-side med alle kjente versjoner."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum AssemblyVersionCompatibility
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  id: SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameDomain
  nameWithType: AssemblyVersionCompatibility.SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Samlingen kan ikke utføre med andre versjoner hvis de kjører i samme programdomene."
  syntax:
    content: SameDomain
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  id: SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameMachine
  nameWithType: AssemblyVersionCompatibility.SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Samlingen kan ikke utføre med andre versjoner hvis de kjører på samme maskin."
  syntax:
    content: SameMachine
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  id: SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameProcess
  nameWithType: AssemblyVersionCompatibility.SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Samlingen kan ikke utføre med andre versjoner hvis de kjører i den samme prosessen."
  syntax:
    content: SameProcess
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameDomain
  nameWithType: AssemblyVersionCompatibility.SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameMachine
  nameWithType: AssemblyVersionCompatibility.SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameProcess
  nameWithType: AssemblyVersionCompatibility.SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
