### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComContractsSection
  id: ComContractsSection
  children:
  - System.ServiceModel.Configuration.ComContractsSection.#ctor
  - System.ServiceModel.Configuration.ComContractsSection.ComContracts
  - System.ServiceModel.Configuration.ComContractsSection.Properties
  langs:
  - csharp
  name: ComContractsSection
  nameWithType: ComContractsSection
  fullName: System.ServiceModel.Configuration.ComContractsSection
  type: Class
  summary: "Representerer en konfigurasjonsdel som inneholder elementer for å angi navnet på navneområde og kontrakten for en COM +-integrering kontrakt. Denne klassen kan ikke arves."
  remarks: "COM +-integrering servicekontraktene er for øyeblikket begrenset til &quot;http://tempuri.org&quot;-navneområdet, og navnet på servicekontrakten er avledet fra støttet COM-grensesnitt. Du kan imidlertid angi alternativer ved å bruke den `comContracts` delen i konfigurasjonsfilen. Du kan for eksempel bruke følgende konfigurasjon til å angi navnet på navneområde og kontrakten for en servicekontrakt [!code-cs [XpsCreate #XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent) ] når tjenesten er initialisert, brukes de angitte navnene på navneområder og kontrakten genererte tjenesten beskrivelse.       Når denne delen er tom, bruker initialisering av tjenesten et navneområde og kontrakten standardnavn hentet fra IDen for støttet COM-grensesnitt."
  syntax:
    content: 'public sealed class ComContractsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: ComContractsSection()
  nameWithType: ComContractsSection.ComContractsSection()
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContractsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ServiceModel.Configuration.ComContractsSection&quot;> </xref> klasse."
  syntax:
    content: public ComContractsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComContractsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  id: ComContracts
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Henter alle COM +-integrering servicekontraktene angitt under."
  syntax:
    content: public System.ServiceModel.Configuration.ComContractElementCollection ComContracts { get; }
    return:
      type: System.ServiceModel.Configuration.ComContractElementCollection
      description: "En <xref href=&quot;System.ServiceModel.Configuration.ComContractElementCollection&quot;> </xref> som inneholder alle COM +-integrering servicekontraktene angitt under."
  overload: System.ServiceModel.Configuration.ComContractsSection.ComContracts*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ComContractsSection.Properties
  fullName: System.ServiceModel.Configuration.ComContractsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.ServiceModel.Configuration.ComContractsSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContractsSection()
  nameWithType: ComContractsSection.ComContractsSection()
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContractsSection()
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContracts
- uid: System.ServiceModel.Configuration.ComContractElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ComContractElementCollection
  nameWithType: ComContractElementCollection
  fullName: System.ServiceModel.Configuration.ComContractElementCollection
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: Properties
  nameWithType: ComContractsSection.Properties
  fullName: System.ServiceModel.Configuration.ComContractsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContractsSection
  nameWithType: ComContractsSection.ComContractsSection
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: Properties
  nameWithType: ComContractsSection.Properties
