### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebPartsSection
  id: WebPartsSection
  children:
  - System.Web.Configuration.WebPartsSection.#ctor
  - System.Web.Configuration.WebPartsSection.EnableExport
  - System.Web.Configuration.WebPartsSection.GetRuntimeObject
  - System.Web.Configuration.WebPartsSection.Personalization
  - System.Web.Configuration.WebPartsSection.Properties
  - System.Web.Configuration.WebPartsSection.Transformers
  langs:
  - csharp
  name: WebPartsSection
  nameWithType: WebPartsSection
  fullName: System.Web.Configuration.WebPartsSection
  type: Class
  summary: "Gir programmatisk tilgang til den <xref uid=&quot;langword_csharp_webParts&quot; name=&quot;webParts&quot; href=&quot;&quot;> </xref> konfigurasjonsdelen filen. Denne klassen kan ikke arves."
  remarks: "Den `webParts` filen konfigurasjonsdelen kan du angi en leverandør av webdeler personlige data, angi tilpassing autorisering og Legg til egendefinert klasser utvide den <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer>klasse for bruk av webdeler tilkoblinger.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer>"
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `webParts` section, which can also be accessed as members of the WebPartsSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `webParts` section.  \n  \n```  \n<system.web>  \n  <webParts>  \n    <personalization  \n      defaultProvider=\" AspNetSqlPersonalizationProvider \">  \n        <!—- Providers may only be defined at the   \n            application level -->  \n      <providers>  \n        <add name=\"AspNetSqlPersonalizationProvider\"  \ntype=\"System.Web.UI.WebControls.WebParts.SqlPersonalizationProvider\"  \n        connectionStringName=\"LocalSqlServer\"  \n        applicationName=\"/\" />        \n      </providers>  \n      <authorization>  \n        <deny users=\"*\" verbs=\"enterSharedScope\" />  \n        <allow users=\"Admin\" verbs=\"modifyState\" />  \n      </authorization>  \n    </personalization>  \n    <transformers>  \n      <add name=\"RowToFieldTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToFieldTransformer\" />  \n      <add name=\"RowToFilterTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToFilterTransformer\" />  \n      <add name=\"RowToParametersTransformer\"  \ntype=\"System.Web.UI.WebControls.WebParts.RowToParametersTransformer\" />  \n    </transformers>  \n  </webParts>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the WebPartsSection class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#1](~/add/codesnippet/csharp/t-system.web.configurati_23_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_23_1.vb)]"
  syntax:
    content: 'public sealed class WebPartsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: WebPartsSection()
  nameWithType: WebPartsSection.WebPartsSection()
  fullName: System.Web.Configuration.WebPartsSection.WebPartsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Web.Configuration.WebPartsSection&quot;> </xref> klasse med standardinnstillinger."
  remarks: "Konstruktøren WebPartsSection skal ikke brukes direkte fra koden. Kalles av ASP.NET Konfigurasjonssystemet. Du hente en forekomst av den <xref:System.Web.Configuration.WebPartsSection>klassen ved hjelp av den <xref:System.Configuration.Configuration.GetSection%2A>metoden.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.WebPartsSection>       Denne konstruktøren skal ikke brukes direkte fra koden. Kalles av ASP.NET Konfigurasjonssystemet.       Tabellen nedenfor viser standardinnstillingene som brukes til denne konstruktøren.      | Angi | Standardverdien |   |-------------|-------------------|   | <xref:System.Web.Configuration.WebPartsSection.Personalization%2A>| Et tomt <xref:System.Web.Configuration.WebPartsPersonalization>-objekt. |   | <xref:System.Web.Configuration.WebPartsSection.Transformers%2A>| En <xref:System.Web.Configuration.TransformerInfoCollection>samling som inneholder en standard <xref:System.Web.Configuration.TransformerInfo>objektet. |</xref:System.Web.Configuration.TransformerInfo> </xref:System.Web.Configuration.TransformerInfoCollection> </xref:System.Web.Configuration.WebPartsSection.Transformers%2A> </xref:System.Web.Configuration.WebPartsPersonalization> </xref:System.Web.Configuration.WebPartsSection.Personalization%2A>"
  syntax:
    content: public WebPartsSection ();
    parameters: []
  overload: System.Web.Configuration.WebPartsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.EnableExport
  id: EnableExport
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: EnableExport
  nameWithType: WebPartsSection.EnableExport
  fullName: System.Web.Configuration.WebPartsSection.EnableExport
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter eller angir en verdi som angir om du vil aktivere eksport av kontrolldata til en beskrivelse XML-fil."
  syntax:
    content: public bool EnableExport { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>aktivere eksport av kontrolldata beskrivelse en XML-fil. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.WebPartsSection.EnableExport*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.GetRuntimeObject
  id: GetRuntimeObject
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: GetRuntimeObject()
  nameWithType: WebPartsSection.GetRuntimeObject()
  fullName: System.Web.Configuration.WebPartsSection.GetRuntimeObject()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override object GetRuntimeObject ();
    parameters: []
    return:
      type: System.Object
      description: "Som skal legges til."
  overload: System.Web.Configuration.WebPartsSection.GetRuntimeObject*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.Personalization
  id: Personalization
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: Personalization
  nameWithType: WebPartsSection.Personalization
  fullName: System.Web.Configuration.WebPartsSection.Personalization
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter en <xref href=&quot;System.Web.Configuration.WebPartsPersonalization&quot;> </xref> objektet som lar deg angi leverandør av personlige data i webdeler og angi webdeler tilpassing autorisering."
  remarks: ''
  example:
  - "The following code example shows how to use the Personalization property.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#3](~/add/codesnippet/csharp/p-system.web.configurati_218_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_218_1.vb)]"
  syntax:
    content: public System.Web.Configuration.WebPartsPersonalization Personalization { get; }
    return:
      type: System.Web.Configuration.WebPartsPersonalization
      description: "En <xref href=&quot;System.Web.Configuration.WebPartsPersonalization&quot;> </xref> objektet som lar deg angi leverandør av personlige data og angi tilpassing autorisering."
  overload: System.Web.Configuration.WebPartsSection.Personalization*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.Properties
  id: Properties
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: Properties
  nameWithType: WebPartsSection.Properties
  fullName: System.Web.Configuration.WebPartsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Som skal legges til."
  overload: System.Web.Configuration.WebPartsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsSection.Transformers
  id: Transformers
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: Transformers
  nameWithType: WebPartsSection.Transformers
  fullName: System.Web.Configuration.WebPartsSection.Transformers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Henter en samling av <xref href=&quot;System.Web.Configuration.TransformerInfo&quot;> </xref> objekter."
  remarks: "<xref:System.Web.Configuration.TransformerInfo>objekter angi egendefinerte klasser utvide den <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer>klasse for bruk av webdelen tilkoblinger for ASP.NET-applikasjoner som er berørt av konfigurasjonsfilen.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer></xref:System.Web.Configuration.TransformerInfo> Disse klassene transformeringen fungere som broer mellom tilkoblede webdeler, oversette data mellom webdeler med inkompatible tilkoblingen punkt."
  example:
  - "The following code example shows how to use the Transformers property.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#2](~/add/codesnippet/csharp/p-system.web.configurati_303_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_303_1.vb)]"
  syntax:
    content: public System.Web.Configuration.TransformerInfoCollection Transformers { get; }
    return:
      type: System.Web.Configuration.TransformerInfoCollection
      description: "En <xref href=&quot;System.Web.Configuration.TransformerInfoCollection&quot;> </xref> samling <xref href=&quot;System.Web.Configuration.TransformerInfo&quot;> </xref> objekter."
  overload: System.Web.Configuration.WebPartsSection.Transformers*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.WebPartsSection.#ctor
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: WebPartsSection()
  nameWithType: WebPartsSection.WebPartsSection()
  fullName: System.Web.Configuration.WebPartsSection.WebPartsSection()
- uid: System.Web.Configuration.WebPartsSection.EnableExport
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: EnableExport
  nameWithType: WebPartsSection.EnableExport
  fullName: System.Web.Configuration.WebPartsSection.EnableExport
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.WebPartsSection.GetRuntimeObject
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: GetRuntimeObject()
  nameWithType: WebPartsSection.GetRuntimeObject()
  fullName: System.Web.Configuration.WebPartsSection.GetRuntimeObject()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.WebPartsSection.Personalization
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Personalization
  nameWithType: WebPartsSection.Personalization
  fullName: System.Web.Configuration.WebPartsSection.Personalization
- uid: System.Web.Configuration.WebPartsPersonalization
  parent: System.Web.Configuration
  isExternal: false
  name: WebPartsPersonalization
  nameWithType: WebPartsPersonalization
  fullName: System.Web.Configuration.WebPartsPersonalization
- uid: System.Web.Configuration.WebPartsSection.Properties
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Properties
  nameWithType: WebPartsSection.Properties
  fullName: System.Web.Configuration.WebPartsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.WebPartsSection.Transformers
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Transformers
  nameWithType: WebPartsSection.Transformers
  fullName: System.Web.Configuration.WebPartsSection.Transformers
- uid: System.Web.Configuration.TransformerInfoCollection
  parent: System.Web.Configuration
  isExternal: false
  name: TransformerInfoCollection
  nameWithType: TransformerInfoCollection
  fullName: System.Web.Configuration.TransformerInfoCollection
- uid: System.Web.Configuration.WebPartsSection.#ctor*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: WebPartsSection
  nameWithType: WebPartsSection.WebPartsSection
- uid: System.Web.Configuration.WebPartsSection.EnableExport*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: EnableExport
  nameWithType: WebPartsSection.EnableExport
- uid: System.Web.Configuration.WebPartsSection.GetRuntimeObject*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: GetRuntimeObject
  nameWithType: WebPartsSection.GetRuntimeObject
- uid: System.Web.Configuration.WebPartsSection.Personalization*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Personalization
  nameWithType: WebPartsSection.Personalization
- uid: System.Web.Configuration.WebPartsSection.Properties*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Properties
  nameWithType: WebPartsSection.Properties
- uid: System.Web.Configuration.WebPartsSection.Transformers*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Transformers
  nameWithType: WebPartsSection.Transformers
