### YamlMime:ManagedReference
items:
- uid: System.ComponentModel.SettingsBindableAttribute
  id: SettingsBindableAttribute
  children:
  - System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  - System.ComponentModel.SettingsBindableAttribute.Bindable
  - System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  - System.ComponentModel.SettingsBindableAttribute.GetHashCode
  - System.ComponentModel.SettingsBindableAttribute.No
  - System.ComponentModel.SettingsBindableAttribute.Yes
  langs:
  - csharp
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute
  fullName: System.ComponentModel.SettingsBindableAttribute
  type: Class
  summary: "Angir når en komponent-egenskapen kan være bundet til en applikasjonsinnstilling."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsBindableAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: SettingsBindableAttribute(Boolean)
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  fullName: System.ComponentModel.SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.ComponentModel.SettingsBindableAttribute&quot;> </xref> klasse."
  syntax:
    content: public SettingsBindableAttribute (bool bindable);
    parameters:
    - id: bindable
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Angi at en egenskap er nødvendig å binde innstillinger. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ComponentModel.SettingsBindableAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable
  id: Bindable
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
  fullName: System.ComponentModel.SettingsBindableAttribute.Bindable
  type: Property
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Henter en verdi som angir om det er nødvendig å binde innstillinger som en egenskap."
  syntax:
    content: public bool Bindable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis egenskapen er riktige å binde innstillinger. Ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ComponentModel.SettingsBindableAttribute.Bindable*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: SettingsBindableAttribute.Equals(Object)
  fullName: System.ComponentModel.SettingsBindableAttribute.Equals(Object)
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Returnerer en verdi som angir om denne forekomsten er likt det angitte objektet."
  syntax:
    content: public override bool Equals (object obj);
    parameters:
    - id: obj
      type: System.Object
      description: "En <xref:System.Object>skal sammenlignes med denne forekomsten eller en nullreferanse (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> i Visual Basic).</xref:System.Object>"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Hvis <code> obj </code> er lik typen og verdien for denne forekomsten; ellers <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ComponentModel.SettingsBindableAttribute.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode
  id: GetHashCode
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: SettingsBindableAttribute.GetHashCode()
  fullName: System.ComponentModel.SettingsBindableAttribute.GetHashCode()
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Returnerer hashkoden for denne forekomsten."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "En 32-biters heltall med fortegn hash-kode."
  overload: System.ComponentModel.SettingsBindableAttribute.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.No
  id: No
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: No
  nameWithType: SettingsBindableAttribute.No
  fullName: System.ComponentModel.SettingsBindableAttribute.No
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Angir at en egenskap ikke nødvendig å binde innstillinger som."
  syntax:
    content: public static readonly System.ComponentModel.SettingsBindableAttribute No;
    return:
      type: System.ComponentModel.SettingsBindableAttribute
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.SettingsBindableAttribute.Yes
  id: Yes
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Yes
  nameWithType: SettingsBindableAttribute.Yes
  fullName: System.ComponentModel.SettingsBindableAttribute.Yes
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Angir at det er nødvendig å binde innstillinger som en egenskap."
  syntax:
    content: public static readonly System.ComponentModel.SettingsBindableAttribute Yes;
    return:
      type: System.ComponentModel.SettingsBindableAttribute
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: SettingsBindableAttribute(Boolean)
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  fullName: System.ComponentModel.SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
  fullName: System.ComponentModel.SettingsBindableAttribute.Bindable
- uid: System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Equals(Object)
  nameWithType: SettingsBindableAttribute.Equals(Object)
  fullName: System.ComponentModel.SettingsBindableAttribute.Equals(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: GetHashCode()
  nameWithType: SettingsBindableAttribute.GetHashCode()
  fullName: System.ComponentModel.SettingsBindableAttribute.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ComponentModel.SettingsBindableAttribute.No
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: No
  nameWithType: SettingsBindableAttribute.No
  fullName: System.ComponentModel.SettingsBindableAttribute.No
- uid: System.ComponentModel.SettingsBindableAttribute
  parent: System.ComponentModel
  isExternal: false
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute
  fullName: System.ComponentModel.SettingsBindableAttribute
- uid: System.ComponentModel.SettingsBindableAttribute.Yes
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Yes
  nameWithType: SettingsBindableAttribute.Yes
  fullName: System.ComponentModel.SettingsBindableAttribute.Yes
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
- uid: System.ComponentModel.SettingsBindableAttribute.Equals*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Equals
  nameWithType: SettingsBindableAttribute.Equals
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: GetHashCode
  nameWithType: SettingsBindableAttribute.GetHashCode
