### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.BuildEngine.BuildSettings
  id: BuildSettings
  children:
  - Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  - Microsoft.Build.BuildEngine.BuildSettings.None
  langs:
  - csharp
  name: BuildSettings
  nameWithType: BuildSettings
  fullName: Microsoft.Build.BuildEngine.BuildSettings
  type: Enum
  summary: "Angir innstillingene for en kompilering."
  syntax:
    content: >-
      [System.Flags]

      public enum BuildSettings
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  id: DoNotResetPreviouslyBuiltTargets
  parent: Microsoft.Build.BuildEngine.BuildSettings
  langs:
  - csharp
  name: DoNotResetPreviouslyBuiltTargets
  nameWithType: BuildSettings.DoNotResetPreviouslyBuiltTargets
  fullName: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Angir at ingen viktige eksterne tilstanden er endret, og ingen tidligere bygd mål skal bygges."
  syntax:
    content: DoNotResetPreviouslyBuiltTargets
    return:
      type: Microsoft.Build.BuildEngine.BuildSettings
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.BuildEngine.BuildSettings.None
  id: None
  parent: Microsoft.Build.BuildEngine.BuildSettings
  langs:
  - csharp
  name: None
  nameWithType: BuildSettings.None
  fullName: Microsoft.Build.BuildEngine.BuildSettings.None
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Angir at byggingen kjører normalt."
  syntax:
    content: None
    return:
      type: Microsoft.Build.BuildEngine.BuildSettings
      description: "Som skal legges til."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  parent: Microsoft.Build.BuildEngine.BuildSettings
  isExternal: false
  name: DoNotResetPreviouslyBuiltTargets
  nameWithType: BuildSettings.DoNotResetPreviouslyBuiltTargets
  fullName: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
- uid: Microsoft.Build.BuildEngine.BuildSettings
  parent: Microsoft.Build.BuildEngine
  isExternal: false
  name: BuildSettings
  nameWithType: BuildSettings
  fullName: Microsoft.Build.BuildEngine.BuildSettings
- uid: Microsoft.Build.BuildEngine.BuildSettings.None
  parent: Microsoft.Build.BuildEngine.BuildSettings
  isExternal: false
  name: None
  nameWithType: BuildSettings.None
  fullName: Microsoft.Build.BuildEngine.BuildSettings.None
